Refactory headings to improve accessibility
minvws/nl-covid19-data-dashboard pull request #1040
Opened 2020-11-30 09:28 UTC by VWSCoronaDashboard1

## Summary

- Place correctly ordered H1, H2, H3, etc headings on the page
- Only place content area in the <main/> element
- Remove headings from menu's
- Add skiplink to footer menu
- Add extra text to main content heading (H1) only 'visible' to screenreaders

## Motivation

Improve accessibility

## Detailed design

The ContentHeader component now renders the category as an H1 element and the title as an H2.
An extra property called 'ariaCategory' was added which is an additional text that is added to the H1, but is hidden from view so only screenreaders will pick it up. This is to prevent the H1 to be the same for pages that belong to the same category.
A visually impaired user will, for example, read 'Besmettingen - Positieve testen', while regular users will only see 'Besmettingen' as the page header. (The second part is obvious for those users from the sidebar menu).
The sidebar has all of the heading elements removed and is partly refactored to styled components.

## Drawbacks

n/a

## Alternatives

n/a

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-11-30 10:14 UTC, VWSCoronaDashboard8 approved these changes
Cleans up nicely 💯  A few small remarks

2020-11-30 10:14 UTC, VWSCoronaDashboard8 commented on src/components-styled/anchor-tile.tsx
> +const StyledAnchorTile = styled(Tile)<{ shadow: boolean }>((x) =>
I would give this a simpler name like Container or Main. The component itself is not an AnchorTile, but only a part of it.

2020-11-30 10:14 UTC, VWSCoronaDashboard8 commented on src/components-styled/aside/category.tsx
> +    mb: 3,
I suspect it would be better to manage this margin in the parent where the component is used.

2020-11-30 10:14 UTC, VWSCoronaDashboard8 commented on src/components-styled/aside/title-with-icon.tsx
> +      mb={-2}
Maybe add a comment about this "hack". Why it is required / how we can improve on this

2020-11-30 10:14 UTC, VWSCoronaDashboard8 commented on src/components-styled/content-header/index.tsx
> +    left: '-10000px',
Is placing it way out of screen really necessary? Would a `display: hidden` work as well maybe?

2020-11-30 10:14 UTC, VWSCoronaDashboard8 commented on src/locale/en.json
> +    "footernav": "Go directly to the footer navigation"
These two could use a _ separator since they are not single words. My spell checker will complain about these things.

2020-11-30 10:14 UTC, VWSCoronaDashboard8 commented on src/scss/fonts.scss
> -
💯

2020-11-30 10:17 UTC, VWSCoronaDashboard1 commented on src/components-styled/aside/category.tsx
> +    mb: 3,
Interesting. Because these are the styles I took from the Heading component. Does that mean the margins ought to be removed from those as well?

2020-11-30 10:18 UTC, VWSCoronaDashboard1 commented on src/components-styled/content-header/index.tsx
> +    left: '-10000px',
No

2020-11-30 10:31 UTC, VWSCoronaDashboard1 commented on src/components-styled/content-header/index.tsx
> +    left: '-10000px',
https://webaim.org/techniques/css/invisiblecontent/

2020-11-30 10:55 UTC, VWSCoronaDashboard1 commented on src/components-styled/aside/category.tsx
> +    mb: 3,
For this case I removed the margins and added them to the parent. But the question concerning the headings still stands I suppose.

2020-11-30 12:36 UTC, VWSCoronaDashboard8 approved these changes

2020-11-30 13:16 UTC, VWSCoronaDashboard10 reviewed
lot of work 👍

2020-11-30 13:16 UTC, VWSCoronaDashboard10 commented on src/components-styled/content-header/index.tsx
> +          {Boolean(ariaCategory) && (
```suggestion
          {ariaCategory && (
```

2020-11-30 13:16 UTC, VWSCoronaDashboard10 commented on src/components-styled/heading-with-icon.tsx
> +  headingLevel?: 1 | 2 | 3 | 4 | 5;
You can import the type `HeadingLevel` for this

2020-11-30 13:16 UTC, VWSCoronaDashboard10 commented on src/components/layout/MunicipalityLayout.tsx
> +                              <span className="metric-wrapper">
did you forget to remove this or has this not yet been transformed to a styled component?

2020-11-30 13:16 UTC, VWSCoronaDashboard10 commented on src/components/layout/index.tsx
> +          >
```suggestion
          <div
            css={css({
              fontSize: 5,
              lineHeight: 0,
              mb: 0,
              mt: 4,
              fontWeight: 'bold',
            })}
          >
```

2020-11-30 13:16 UTC, VWSCoronaDashboard10 commented on src/components/layout/index.tsx
> +          >
Or maybe something like this is also good enough? `<Heading level={1} as='div' ...`

2020-12-01 08:47 UTC, VWSCoronaDashboard1 commented on src/components/layout/MunicipalityLayout.tsx
> +                              <span className="metric-wrapper">
this hasn't been refactored to a SC.

2020-12-01 09:03 UTC, VWSCoronaDashboard10 commented on src/components-styled/aside/title-with-icon.tsx
> +    </Box>
@VWSCoronaDashboard8 @VWSCoronaDashboard1 @VWSCoronaDashboard4 what is your opinion about the above?

2020-12-01 09:17 UTC, VWSCoronaDashboard1 commented on src/components-styled/aside/title-with-icon.tsx
> +    </Box>
I use Box because it's the base component and has some default properties. If we don't use Box here, then I don't understand why we have the Box component in the first place...

2020-12-01 09:30 UTC, VWSCoronaDashboard4 requested changes

2020-12-01 09:30 UTC, VWSCoronaDashboard4 commented on src/components-styled/content-header/index.tsx
> +          {ariaCategory && <AriaInlineText> - {ariaCategory}</AriaInlineText>}
What is the idea behind the naming of this? We're not using aria-attributes here?

2020-12-01 09:30 UTC, VWSCoronaDashboard4 commented on src/components/layout/SafetyRegionLayout.tsx
> +              aria-label="metrieken per categorie keuze"
this should be in the translation files

2020-12-01 09:30 UTC, VWSCoronaDashboard4 commented on src/components/layout/SafetyRegionLayout.tsx
> +                          <span className="metric-wrapper">
You're touching a lot of the sidebar, but this `<span>` persists; maybe move it to a styled component as well? It should in any case become a block level element some time, since the Metric components contain block level elements.

2020-12-01 09:30 UTC, VWSCoronaDashboard4 commented on src/components/layout/index.tsx
> +                  aria-label="pagina keuze"
move this text to the translation files

2020-12-01 09:30 UTC, VWSCoronaDashboard4 commented on src/components/layout/MunicipalityLayout.tsx
> +              aria-label="metrieken per categorie keuze"
this should be in the translation files

2020-12-01 09:30 UTC, VWSCoronaDashboard4 commented on src/components/layout/index.tsx
> +          aria-label="landelijk regio gemeente keuze"
:arrow_right: translation file

2020-12-01 09:31 UTC, VWSCoronaDashboard4 commented on src/components/layout/SafetyRegionLayout.tsx
> +                          <span className="metric-wrapper">
If this is outside the scope of this PR : fine :-)

2020-12-01 09:38 UTC, VWSCoronaDashboard1 commented on src/components/layout/SafetyRegionLayout.tsx
> +                          <span className="metric-wrapper">
yea, I left some bits for the actual aside refactor ;)

2020-12-01 09:38 UTC, VWSCoronaDashboard1 commented on src/components-styled/content-header/index.tsx
> +          {ariaCategory && <AriaInlineText> - {ariaCategory}</AriaInlineText>}
the idea is that this part is only readable by a screenreader (as described in the summary)

2020-12-01 11:01 UTC, merged