Create elderly at home regional page
minvws/nl-covid19-data-dashboard pull request #1058
Opened 2020-12-01 15:58 UTC by VWSCoronaDashboard10

## Summary
Create the "elderly at home" regional page.

2020-12-01 16:41 UTC, VWSCoronaDashboard1 approved these changes

2020-12-02 07:20 UTC, VWSCoronaDashboard8 approved these changes

2020-12-02 07:20 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/thuiswonende-ouderen.tsx
> +const text = siteText.thuiswonende_ouderen;
I don't know if it's feasible to re-use the complete nl structure here. I think in a lot of cases the vr and gm pages have their own separate copy. So it might be worth duplicating and prefixing it with vr_ to scope it. I think we should probably discuss this in the team. If we always want to separate text like this I would opt to start prefixing the nl stuff with nl_ too.

2020-12-02 07:20 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/thuiswonende-ouderen.tsx
> +        category={siteText.nationaal_layout.headings.kwetsbare_groepen}
this is not part of the national layout but maybe that's ok. Just a misleading scope name maybe

2020-12-02 07:51 UTC, VWSCoronaDashboard10 commented on src/pages/veiligheidsregio/[code]/thuiswonende-ouderen.tsx
> +const text = siteText.thuiswonende_ouderen;
There are no differences when looking at the design, that's why I opted for using a single structure. We can duplicate it the moment it becomes necessary.

2020-12-02 07:53 UTC, VWSCoronaDashboard10 commented on src/pages/veiligheidsregio/[code]/thuiswonende-ouderen.tsx
> +        category={siteText.nationaal_layout.headings.kwetsbare_groepen}
whoops, no good catch, need to change this.

2020-12-02 08:10 UTC, VWSCoronaDashboard4 requested changes

2020-12-02 08:10 UTC, VWSCoronaDashboard4 commented on src/pages/veiligheidsregio/[code]/thuiswonende-ouderen.tsx
> +        title={text.section_positive_tested.title}
Titles for other metrics include the safety region name as part of the title

2020-12-02 09:33 UTC, VWSCoronaDashboard4 approved these changes

2020-12-02 10:27 UTC, merged