Topic/infected age groups keyboard
minvws/nl-covid19-data-dashboard pull request #1073
Opened 2020-12-04 14:30 UTC by VWSCoronaDashboard4

## Summary

Adds keyboard navigation and a11y support for the infected people age demographic.

## Detailed design

* Added a separate file to calculate the coordinates used by the chart. The chart file now basically contains the buildup of the SVG using those coordinates.
* The coordinates are calculated and memorized by the main `age-demographic` component.
* The coordinates are used in a new `useTooltip` hook. That hook returns the event handlers and the read only state.
* These event handlers are passed on to the chart.
* A new Tooltip component uses the state to render the correct contents on the provided coordinates.
* `aria-live` attributes are tweaked to pick up the changes in the tooltip.
* Added generic help text for barcharts to help discover the keyboard navigation.

2020-12-04 15:55 UTC, VWSCoronaDashboard1 approved these changes
Excellent!

2020-12-04 15:55 UTC, VWSCoronaDashboard1 commented on src/components-styled/tooltip.tsx
> +    // The new index overfloews from zero to the last and vice versa
```suggestion
    // The new index overflows from zero to the last and vice versa
```

2020-12-04 15:55 UTC, VWSCoronaDashboard1 commented on src/components-styled/tooltip.tsx
> +  // This timeout smoothens the display of the tooltip for mouse users
```suggestion
  // This timeout smooths the display of the tooltip for mouse users
```

2020-12-04 15:55 UTC, VWSCoronaDashboard1 commented on src/domain/infected-people/age-demographic/age-demographic.tsx
> +  // Calculate graph's coordinates based on the data, the component width and eher we are on a small screen or not.
```suggestion
  // Calculate graph's coordinates based on the data, the component width and whether we are on a small screen or not.
```

2020-12-07 08:00 UTC, VWSCoronaDashboard4 commented on src/components-styled/tooltip.tsx
> +  // This timeout smoothens the display of the tooltip for mouse users
Smoothens is a word ;-)

2020-12-07 12:02 UTC, VWSCoronaDashboard10 reviewed
My first thought is that it looks quite complex, I guess it's hard to wrap my head around all the calculations in the coordinates getter (and everything related to those calculations), but I guess that if it works it's good for now.  Couple of questions though, and I think I spotted a bug :-)

2020-12-07 12:35 UTC, VWSCoronaDashboard1 commented on src/components-styled/tooltip.tsx
> +  // This timeout smoothens the display of the tooltip for mouse users
haha, ok, ignore then ;)

2020-12-07 13:23 UTC, VWSCoronaDashboard8 requested changes

2020-12-07 13:23 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic-chart.tsx
> +            onMouseMove={(event) => openTooltip(event, d)}
I agree, if you go for a generic shorthand name use `x` for anything else use a readable name.

2020-12-07 13:23 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  numTicks: number;
Reading this I wonder what ticks have to do with coordinates, or what it means in general

2020-12-07 13:23 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  infectedPercentageScale: ValueOf<ScaleTypeToD3Scale<any, any, any>>;
So AgeDemographicCoordinates is tied to the infected people metric? Are you sure this kind of coupling is necessary?

2020-12-07 13:23 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  getTooltipCoordinates: GetTooltipCoordinates<NationalInfectedAgeGroupsValue>;
Same here, I wonder why the tooltip coordinates have to care about the type of metric...

2020-12-07 13:23 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  };
It is surprising to see margin settings on a component interface. Maybe they can be handled by a parent/wrapping element in the composition?

But I have to admit at this point I have no idea what the component is doing, so you can ignore my comment if it seems essential to the inner workings

2020-12-07 13:23 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +    return bStart - aStart;
Sorting works directly on strings too 
```suggestion
    return bStart.localeCompare(aStart);
```

2020-12-07 13:23 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  const createPoint = (scale: any, accessor: any) => (
Or, write a comment about why you need this escape hatch

2020-12-07 13:23 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  };
I have a bad feeling about this long and specific interface, but I think this is something to revisit later. We don't have proper abstractions or visx yet, and it will be hard to define them correctly in the beginning.

2020-12-07 14:02 UTC, VWSCoronaDashboard4 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  };
This is not a CSS margin, its a margin inside the drawn graphic.

2020-12-07 14:04 UTC, VWSCoronaDashboard4 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  getTooltipCoordinates: GetTooltipCoordinates<NationalInfectedAgeGroupsValue>;
It was a choice between providing the proper type for the value (and using a generic like this), or providing an `any` on all of the places this is processed.

2020-12-07 14:07 UTC, VWSCoronaDashboard4 commented on src/domain/infected-people/age-demographic/age-demographic-tooltip-content.tsx
> +  }
No, I'll add a comment about this. The aria-live attribute would spell out every new display (additions), instead of only the last one (changes).

2020-12-07 14:30 UTC, VWSCoronaDashboard4 commented on src/domain/infected-people/age-demographic/age-demographic-coordinates.ts
> +  const createPoint = (scale: any, accessor: any) => (
I'll add a comment.

2020-12-07 17:01 UTC, VWSCoronaDashboard8 approved these changes

2020-12-08 09:54 UTC, VWSCoronaDashboard4 commented on src/domain/infected-people/age-demographic/age-demographic.tsx
> +            setParentWidth(parent.width);
I've added a comment in the code to clarify this a bit; I don't get an error and it's because of how the `ParentWidth` component handles this callback.

For now I suggest to leave this, as it does not give any troubles/errors. In theory it can be torn apart, resulting in more complex code / nesting of components.

2020-12-08 12:27 UTC, merged