chore: visx linechart
minvws/nl-covid19-data-dashboard pull request #1093
Opened 2020-12-08 14:35 UTC by VWSCoronaDashboard13

## Summary

Brief explanation of the feature, and describe how other developers can test and see your implementation.

## Motivation

Why are we doing this? What use cases does it support? What is the expected
outcome?

Please focus on explaining the motivation so that if this PR is not accepted,
the motivation could be used to develop alternative solutions. In other words,
enumerate the constraints you are trying to solve without coupling them too
closely to the solution you have in mind.

## Detailed design

This is the bulk of the PR. Explain the design in enough detail for somebody
familiar with the project to understand, and for somebody familiar with the
front-end to implement. This should get into specifics and corner-cases,
and include examples of how the feature is used. Any new terminology should be
defined here.

## Drawbacks

Why should we _not_ do this? Please consider:

- implementation cost, both in term of code size and complexity
- maintenance cost, how complex is the solution and how prone to change is it?
- integration of this feature with other existing and planned features

There are tradeoffs to choosing any path. Attempt to identify them here.

## Alternatives

What other designs have been considered? What is the impact of not doing this?

## Unresolved questions

Optional, but suggested for bigger features. What parts of the design are still
TBD or not implemented? How will you deal with that in the future?

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-12-08 14:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=1093) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=1093) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=1093) it.</sub>

2020-12-09 19:25 UTC, VWSCoronaDashboard commented
> The new chart accepts a formatting function for the tooltip, however the existing functions utilize features of highcharts to, for example, make some text bold. Now that we have more flexibility in regards to the content of our tooltips, how do we want to handle formatting them?

I would assume it can handle composition now. We're not using Highcharts anymore.

```
          <Tooltip>
            <div>
              <strong>x:</strong> 10}
            </div>
            <div>
              <strong>y:</strong> 20}
            </div>
          </Tooltip>
```

2020-12-09 19:26 UTC, VWSCoronaDashboard commented
> I'm not sure how this performs in terms of accessibility

That's not a drawback. I'll move it to unresolved questions. As long as it doesn't perform worse than Highcharts it's not a blocker.

2020-12-09 19:32 UTC, VWSCoronaDashboard commented
I've pushed a few commits that should solve some of the TS errors.
There's one big one left, and I know where to start solving it but I don't have the time and focus to solve it. 

The issue:

In `src/components/custom-line-chart/index.tsx` we have this type. I've naively made it myself when building the PoC instead of re-using one that already existed.

```tsx
export type ThresholdProps = {
  values: any[];
  width: number;
  height?: number;
  timeframe?: TimeframeOption;
  signaalwaarde?: number;
  formatTooltip: any;
  formatYAxis: any;
  showFill: boolean;
  valueAnnotation?: string;
};
```

I think you should be using the interface (including generics for the values) from `src/components/lineChart/index.tsx`

```tsx
export interface LineChartProps<T> {
  values: T[];
  signaalwaarde?: number;
  timeframe?: TimeframeOption;
  formatTooltip?: (value: T) => string;
  formatYAxis?: (y: number) => string;
  showFill?: boolean;
  valueAnnotation?: string;
}
```

I've solved the tooltip TypeScript errors by importing the Tooltip hook types from `@visx/tooltip/lib/hooks/useTooltip` and extending it with our `Value` type.

2020-12-15 14:05 UTC, VWSCoronaDashboard8 requested changes

2020-12-15 14:05 UTC, VWSCoronaDashboard8 commented on src/components/custom-line-chart/chart/trends.tsx
> +  const onPointerMove = useCallback(
Similar to my comment earlier about event handlers this should probably be called `handlePointerMove` because it's an event handling function.

2020-12-15 14:05 UTC, VWSCoronaDashboard8 commented on src/components/custom-line-chart/chart/trends.tsx
> +  handleHover: any;
```suggestion
  onHover: any;
```

Apart from any not being specific enough, the name can be improved like I mentioned earlier

2020-12-15 14:05 UTC, VWSCoronaDashboard8 commented on src/components/custom-line-chart/chart/trends.tsx
> +        onMouseMove={onPointerMove}
See this is already not very nice to read and something like this is a little clearer I think:

```suggestion
        onMouseMove={handlePointerMove}
```

2020-12-15 14:40 UTC, VWSCoronaDashboard13 commented on src/components/custom-line-chart/chart/tooltip.tsx
> +          transition: 'left 0.075s, top 0.075s',
yeah, I thought about moving it, but decided it made more sense to keep it with the dynamic styles it's associated with

2020-12-15 14:41 UTC, VWSCoronaDashboard13 commented on src/components/custom-line-chart/chart/trends.tsx
> +export const trendTypes = {
ahh this is perfect! good to know about the enum thing

2020-12-15 14:55 UTC, VWSCoronaDashboard13 commented on src/components/custom-line-chart/chart/index.tsx
> +      return +date - +d0.date > +d1.date - +date ? d1 : d0;
Just learned this from Jan: The sort function requires numbers so the + sign converts the dates to numbers

2020-12-15 15:10 UTC, VWSCoronaDashboard13 commented on src/components/custom-line-chart/chart/index.tsx
> +      return +date - +d0.date > +d1.date - +date ? d1 : d0;
The sort function requires numbers so the + sign converts the dates to numbers

2020-12-15 15:13 UTC, VWSCoronaDashboard4 reviewed
Looking good, some nitpicks

2020-12-15 15:13 UTC, VWSCoronaDashboard4 commented on src/components-styled/line-chart-tile.tsx
> +              <CustomLineChart
Is it possible to rename these to eg `LineChart` and `LineChartProps` before merging?

2020-12-15 15:13 UTC, VWSCoronaDashboard4 commented on src/components/custom-line-chart/index.tsx
> +function calculateYMax(values: Value[], signaalwaarde = -Infinity) {
This method is also present in `src/components/lineChart/index.tsx` ; maybe just 1 of them is needed?

2020-12-15 15:13 UTC, VWSCoronaDashboard4 commented on src/components/custom-line-chart/index.tsx
> +      ? { value: signaalwaarde, label: 'Signaalwaarde' }
Label value is hardcoded?

2020-12-15 15:57 UTC, VWSCoronaDashboard13 commented on src/components-styled/line-chart-tile.tsx
> +              <CustomLineChart
done 👍

2020-12-15 15:59 UTC, VWSCoronaDashboard13 commented on src/components/custom-line-chart/index.tsx
> +      ? { value: signaalwaarde, label: 'Signaalwaarde' }
should I be using this? `text.common.barScale.signaalwaarde` from `import text from '~/locale/index';`

2020-12-15 16:03 UTC, VWSCoronaDashboard13 commented on src/components/custom-line-chart/index.tsx
> +function calculateYMax(values: Value[], signaalwaarde = -Infinity) {
I've left it in this file and removed it from the other so that we don't have to move them if we decide to remove that file

2020-12-15 16:44 UTC, VWSCoronaDashboard13 commented on src/components/custom-line-chart/index.tsx
> +function calculateYMax(values: Value[], signaalwaarde = -Infinity) {
Ahh actually they are using different value types, so I'm going to leave it for now

2020-12-15 16:49 UTC, VWSCoronaDashboard13 commented on src/components-styled/line-chart-tile.tsx
> +} from '~/components/custom-line-chart/index';
yes! I organized them 👍

2020-12-16 10:28 UTC, VWSCoronaDashboard8 requested changes
This is just a reminder that I've reviewed it thus far, but we can improve on the unknown/any types still

2020-12-20 12:29 UTC, VWSCoronaDashboard commented on src/components/custom-line-chart/chart/trends.tsx
> +          x={(d: any) => x(d.date)}
Made d a Datapoint type.

2020-12-20 12:30 UTC, VWSCoronaDashboard commented on src/components/custom-line-chart/index.tsx
> +      ? { value: signaalwaarde, label: 'Signaalwaarde' }
Solved this.

2020-12-20 12:42 UTC, VWSCoronaDashboard commented on src/components/custom-line-chart/index.tsx
> +function calculateYMax(values: Value[], signaalwaarde = -Infinity) {
As soon as everything is moved to the new line chart, we'll remove the old folder and see which types need to remain or not ;).

2020-12-22 12:13 UTC, VWSCoronaDashboard8 approved these changes

2020-12-22 20:05 UTC, merged