Clean up a lot of styles
minvws/nl-covid19-data-dashboard pull request #1182
Opened 2020-12-15 12:33 UTC by VWSCoronaDashboard10

## Summary

- Removed a lot of scss files
- Changed a lot of spacing from component-outside margins to container-component children-spacing

Note that some diffs are so large that github decides to collapse them 🤷

2020-12-15 13:02 UTC, VWSCoronaDashboard4 requested changes
Nice cleanup!

2020-12-15 13:16 UTC, VWSCoronaDashboard10 commented on src/components-styled/aside/menu.tsx
> +    display: 'block',
I guess because of it being rendered as a  child of an `anchor`-element, but if there are block-level children it doesn't really matter I guess .. I'll change it to a div.

2020-12-15 13:21 UTC, VWSCoronaDashboard10 commented on src/domain/site/site-content.tsx
> +    boxShadow: `0 -1px 1px 0 #e5e5e5, 0 1px 1px 0 #e5e5e5, 0 2px 2px 0 #e5e5e5,
good catch, it already exists

2020-12-15 13:23 UTC, VWSCoronaDashboard10 commented on src/pages/gemeente/[code]/positief-geteste-mensen.tsx
>        <SEOHead
I must say that I totally agree, just getting tired of visiting these 1000 files again 😓

2020-12-15 13:30 UTC, VWSCoronaDashboard8 approved these changes

2020-12-15 13:30 UTC, VWSCoronaDashboard8 commented on src/domain/site/site-content.tsx
> +import css from '@styled-system/css';
I would suggest to call it domain/app, as the term "website" seems a little dated. Also, I'm not sure if this qualifies as a domain since it can encapsulate anything. Maybe it's about time to have some discussion to see what domains we can identify, and how we want to structure these folders.

2020-12-15 13:30 UTC, VWSCoronaDashboard8 commented on src/domain/site/site-content.tsx
> +interface SiteContentProps {
Then this could be called AppContent

2020-12-15 13:30 UTC, VWSCoronaDashboard8 commented on src/utils/use-is-mounted-ref.ts
> +import { useEffect, useRef, useState } from 'react';
nit; since these contain two different functions you might as well make the filename a little more generic like `utils/is-mounted`

2020-12-15 17:04 UTC, VWSCoronaDashboard10 commented on src/domain/site/site-content.tsx
> +import css from '@styled-system/css';
Yep I also don't like the domain "site" or "app". I'll move it to the styled-components directory and probably put them alltogether in a subdirectory.

2020-12-18 11:42 UTC, VWSCoronaDashboard1 approved these changes

2020-12-18 11:42 UTC, VWSCoronaDashboard1 commented on src/components-styled/aside/menu.tsx
> +}
No criticism, just curious: why is this preferable to using a styled ul directly?

2020-12-18 11:42 UTC, VWSCoronaDashboard1 commented on src/components-styled/select.tsx
> +        value={value || ''}
```suggestion
        value={value ?? ''}
```
In theory, when the value is 0, this would otherwise be set to '' (edge case, I know)

2020-12-18 11:42 UTC, VWSCoronaDashboard1 commented on src/components/choropleth/municipality-navigation-map.tsx
> +        fill="#01689b"
Do these need to be in the theme, or are they so specific to just this use that this doesn't make sense?

2020-12-18 11:42 UTC, VWSCoronaDashboard1 commented on src/pages/_app.tsx
> -
this is added somewhere else?

2020-12-18 11:58 UTC, VWSCoronaDashboard10 commented on src/pages/_app.tsx
> -
yes, nextjs provides a bunch of polyfilles for IE11

2020-12-18 12:03 UTC, VWSCoronaDashboard10 commented on src/components-styled/aside/menu.tsx
> +}
I haven't thought about it actually ..

2020-12-18 12:54 UTC, VWSCoronaDashboard4 commented on src/pages/_app.tsx
> -
Have you verified it is working? When adding this, it was assumed NextJS would provide this properly, while it did not...

2020-12-18 12:55 UTC, VWSCoronaDashboard10 commented on src/pages/_app.tsx
> -
of course 💪

2020-12-18 12:56 UTC, VWSCoronaDashboard4 commented on src/components-styled/layout/app-content.tsx
> +    display: ['block', null, null, 'flex'],
maybe use the utility you created to write this as media query object? `{ _: null, lg: 'flex' }`

2020-12-18 13:00 UTC, VWSCoronaDashboard4 approved these changes

2020-12-18 13:33 UTC, VWSCoronaDashboard8 approved these changes

2020-12-18 13:33 UTC, VWSCoronaDashboard8 commented on src/components-styled/layout/app-content.tsx
> +  renderSidebar: React.ReactNode;
I'm surprised by this interface. I would expect renderSidebar to be a function, or the prop be called something like `sidebarComponent`

2020-12-18 13:33 UTC, VWSCoronaDashboard8 commented on src/components-styled/layout/app-content.tsx
> +  renderSearch?: React.ReactNode;
Similar comment here

2020-12-18 13:33 UTC, VWSCoronaDashboard8 commented on src/domain/layout/municipality-layout.tsx
> +        renderSidebar={
```suggestion
        sidebarComponent={
```

2020-12-18 13:33 UTC, VWSCoronaDashboard8 commented on src/domain/layout/municipality-layout.tsx
> +        renderSearch={<MunicipalityComboBox />}
```suggestion
        searchComponent={<MunicipalityComboBox />}
```

2020-12-18 13:46 UTC, VWSCoronaDashboard10 commented on src/components-styled/layout/app-content.tsx
> +  renderSidebar: React.ReactNode;
I'm also surprised, fixed it :-)

2020-12-18 13:48 UTC, merged