Feature/vaccinatie page
minvws/nl-covid19-data-dashboard pull request #1335
Opened 2021-01-05 13:20 UTC by VWSCoronaDashboard14

## Summary

Added the temporary vaccination page where it includes only 4 KPI's that has to be updated from the locale. Also in the layout on the left, it has to be updated manually.

Todo: In the national-layout.tsx fix a typescript error on the data attribute of the SidebarMetric component. 

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-01-05 13:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=1335) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=1335) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=1335) it.</sub>

2021-01-05 14:52 UTC, VWSCoronaDashboard requested changes
There's too much settings and content put into Lokalise with this PR for comfort. We have a CMS and should start using it now. I'll come up with a plan later to see how we can do that.

2021-01-05 14:56 UTC, VWSCoronaDashboard commented on packages/app/src/domain/layout/national-layout.tsx
> +                    // @ts-ignore
Why is this ignored?

2021-01-06 08:58 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/layout/national-layout.tsx
> +                    // @ts-ignore
The typescript pattern that the Sidebarmetric requires doesn't match what I try to add from the localize (I only need 2 keys). I couldn't find a solution for this other than temporarily ignoring it for this page.  How can I prevent this?

2021-01-06 09:55 UTC, VWSCoronaDashboard4 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +      {' '}
Not sure why this space is so important? :-)

2021-01-06 11:02 UTC, VWSCoronaDashboard4 approved these changes

2021-01-06 11:10 UTC, VWSCoronaDashboard8 approved these changes

2021-01-06 11:10 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/en.json
> +      "difference": "Do not edit this text, this is a temporary workaround",
nit; maybe "Do not remove this key. It is required as a temporary workaround" would be a little clearer. Because it is at the top of the data structure one might interpret it as if you're not allowed to edit this section.

2021-01-06 11:10 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/nl.json
> +      "difference": "Do not edit this text, this is a temporary workaround",
Same comment here of course

2021-01-06 13:49 UTC, VWSCoronaDashboard10 commented
This branch won't build locally on my environment. Can you validate it builds correctly at yours @VWSCoronaDashboard14 before going to develop?

2021-01-19 10:12 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/deceased/deceased-monitor-section.tsx
> +        <Box pl="56px">
This pl thing looks very odd. Maybe add a comment to explain why this can't be themed or otherwise made to appear logical

2021-01-19 11:23 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/deceased/deceased-monitor-section.tsx
> +        <Box pl="56px">
Relevant: https://github.com/minvws/nl-covid19-data-dashboard/pull/1349

2021-01-19 14:07 UTC, VWSCoronaDashboard10 requested changes

2021-01-19 14:31 UTC, VWSCoronaDashboard10 approved these changes

2021-01-19 15:18 UTC, VWSCoronaDashboard8 approved these changes

2021-01-19 15:18 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/nl.json
> +          "total_vaccinated": "2187",
Our metric properties all start with the subject. So maybe you can still change that here.

2021-01-25 12:05 UTC, merged