added bold text to line graphs
minvws/nl-covid19-data-dashboard pull request #1342
Opened 2021-01-05 15:07 UTC by VWSCoronaDashboard14

## Summary

Wrapped the date (dates) in bold tags in the line graph tooltip.

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-01-05 15:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=1342) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=1342) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=1342) it.</sub>

2021-01-05 15:12 UTC, VWSCoronaDashboard requested changes

2021-01-05 15:12 UTC, VWSCoronaDashboard commented on packages/app/src/components-styled/line-chart/index.tsx
> +        <b>{formatDateFromMilliseconds(value.__date.getTime())}: </b>
The text is not of special importance, and it's not a bring-to-attention type of element. MDN advices to use css to make this bold with font-weight attributes.

Does

```
import { Text } from '~/components-styled/typography';
<Text fontWeight="bold">
```

do what you want here?

2021-01-05 15:12 UTC, VWSCoronaDashboard commented on packages/app/src/components-styled/line-chart/index.tsx
> +        <b>
Same here, do not use `<b>`

2021-01-05 15:29 UTC, VWSCoronaDashboard1 approved these changes

2021-01-06 09:54 UTC, VWSCoronaDashboard8 reviewed
Before the `<strong>` tag was used to indicate bold text in tooltips. I don't know if that is better but maybe check if it renders the same as the other bold text in tooltips.

Also, in this repo we try to keep the convention to start commit messages with a capital letter and a present-tense verb, for example "Add bold text..."

2021-01-06 13:13 UTC, VWSCoronaDashboard approved these changes

2021-01-06 13:25 UTC, merged