Move cypress into a separate package of the monorepo
minvws/nl-covid19-data-dashboard pull request #1369
Opened 2021-01-07 11:46 UTC by VWSCoronaDashboard1

## Summary

As the title states

## Motivation

This will PR will hopefully streamline the build process a little bit:
During the build step of the application, the Cypress dependencies would be installed as well, while these aren't needed.
Then in the next step where the Cypress tests are built, all of the app's dependencies would be installed as well, adding unnecessary time to the build.
By moving Cypress into its own package these superfluous installs will be prevented.

## Detailed design

Not much to explain. All of the Cypress test files have been moved to packages/cypress. The cypress dependencies (well, just one really) have been removed from the app's package.json and added to the cypress/package.json.

## Drawbacks

n/a

## Alternatives

n/a

## Unresolved questions

After this PR is merged there will need to be made some changes to the yaml file on gitlab. Specifically, this block:
```
script:
    - echo -e "Cloning '${BRANCH_NAME}' from ${ORIGIN_REPO}"
    - git clone --depth 1 -b ${BRANCH_NAME} https://${ORIGIN_REPO} mirror
    - cd mirror/packages/app/
    - mkdir -p public/json
    - cp -r ../../../files_from_blobstorage/* public/json/ 
    - yarn && yarn cy:ci --env host=${HOSTNAME_NL},port=80
  artifacts:
    when: on_failure
    paths:
      - /builds/vws/cdb/frontend-development-deployment/mirror/packages/app/cypress/screenshots/*
      - /builds/vws/cdb/frontend-development-deployment/mirror/packages/app/cypress/videos/*
```

Will need to be re-written to this:
```
script:
    - echo -e "Cloning '${BRANCH_NAME}' from ${ORIGIN_REPO}"
    - git clone --depth 1 -b ${BRANCH_NAME} https://${ORIGIN_REPO} mirror
    - cd mirror/packages/app/
    - mkdir -p public/json
    - cp -r ../../../files_from_blobstorage/* public/json/ 
    - cd mirror/packages/cypress/
    - yarn && yarn cy:ci --env host=${HOSTNAME_NL},port=80
  artifacts:
    when: on_failure
    paths:
      - /builds/vws/cdb/frontend-development-deployment/mirror/packages/cypress/screenshots/*
      - /builds/vws/cdb/frontend-development-deployment/mirror/packages/cypress/videos/*

```

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-01-07 12:17 UTC, VWSCoronaDashboard4 approved these changes

2021-01-11 11:49 UTC, VWSCoronaDashboard8 requested changes

2021-01-11 11:49 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/aspect-ratio.tsx
> +  dataCy?: string;
nit; I don't like this name since it is unclear and strictly tied to Cypress (our app code should be impartial to what e2e testing library is being used). I'd rather use a more readable generic name in our app code like `testingHandle` or `testingLabel`, but maybe that's a discussion we should have in-person to we if we can agree.

2021-01-11 11:49 UTC, VWSCoronaDashboard8 commented on packages/cypress/integration/gemeente/positief-geteste-mensen.spec.ts
> +import { MunicipalContext } from '@/integration/types';
Why are you using `@` here?

2021-01-11 11:49 UTC, VWSCoronaDashboard8 commented on packages/cypress/package.json
> +    "compile": "echo 'No compiler configured for @corona-dashboard/cypress'",
I think these two can easily be defined and are valuable since we don't want to deploy / merge code with broken testing code.

2021-01-11 11:49 UTC, VWSCoronaDashboard8 commented on packages/cypress/tsconfig.json
> +      "@/*": ["/*"]
I think this adds unnecessary confusion.

Packages can import from other packages explicitly using the workspace package name. I think `~/` should only mean "local (package) src directory" in every package.

I will look up how this was done in my other monorepo project...

2021-01-11 12:22 UTC, VWSCoronaDashboard1 commented on packages/cypress/integration/gemeente/positief-geteste-mensen.spec.ts
> +import { MunicipalContext } from '@/integration/types';
because there are two different aliases, one for testing code and one that points to the app sources (I use a little bit of shared code there, most important is the `data.d.ts` file, but I also use some of the util functions)

2021-01-11 12:23 UTC, VWSCoronaDashboard1 commented on packages/cypress/tsconfig.json
> +      "@/*": ["/*"]
Please do, I'd be interested to see how it's supposed to be done. IMHO, the two separate aliases were clear enough, but if there's a better solution I'm all ears.

2021-01-11 12:54 UTC, VWSCoronaDashboard1 commented on packages/cypress/package.json
> +    "compile": "echo 'No compiler configured for @corona-dashboard/cypress'",
You're absolutely right, this is fixed now

2021-01-11 13:06 UTC, VWSCoronaDashboard1 commented on packages/app/src/components-styled/aspect-ratio.tsx
> +  dataCy?: string;
With that in mind, I've renamed the package from cypress to e2e, as well as the commands from `cy:open` to `e2e` and `cy:ci` to `e2e:ci`

2021-01-18 17:23 UTC, merged