Support for aria-labelby on graphs
minvws/nl-covid19-data-dashboard pull request #1407
Opened 2021-01-12 10:06 UTC by VWSCoronaDashboard14

### Working

Give the option to pass a description or an ariaDescription property to a graph. 
It will link up the description or the hidden ariaDescription with the SVG by using the `aria-labelledby` by creating an unique ID to link them.

I've only added in the localize keys that didn't have a description shown right now.

### Could be improved
Right now I'm getting the data from the locale by using:
`const accessibilityGraphs = siteText.accessibility_grafieken as any;`
I've tried some things but couldn't get around some typescript warnings, and had to fix it with `as any` for now.

2021-01-13 09:27 UTC, VWSCoronaDashboard8 requested changes

2021-01-13 09:27 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/nl.json
> +    },
I see no good reason to scope these things per nl/vr/gm really. They seem to be generic descriptions that seem to be constant across the charts in different scopes

2021-01-13 10:04 UTC, VWSCoronaDashboard14 commented on packages/app/src/locale/nl.json
> +    },
This was specifically asked to order them like this.

2021-01-13 10:11 UTC, VWSCoronaDashboard14 reviewed
Removed unused useRef commit should be "Introduced uniqueID hook, removed any type, added assert, updated const names to be more declarative".

2021-01-13 10:32 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/nl.json
> +    },
@VWSCoronaDashboard14 asked by who?

2021-01-13 10:41 UTC, VWSCoronaDashboard8 approved these changes

2021-01-13 10:41 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/choropleth.tsx
> +  const clipPathId = useRef(uniqueId());
The useRef can be removed here.

2021-01-13 10:41 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/gemeente/[code]/rioolwater.tsx
> +const accessibilityGraphsDescriptions = siteText.accessibility.grafieken;
nit; `graphDescriptions` or even `descriptions` as a variable name would have been clear enough within this scope I think

2021-01-13 10:41 UTC, VWSCoronaDashboard8 commented on packages/app/src/utils/useUniqueId.ts
> +// Create a unique identifier
nit; I think the comment doesn't add much value. The code and hook name speak for themselves I think.

2021-01-15 12:26 UTC, VWSCoronaDashboard1 approved these changes

2021-01-15 13:29 UTC, VWSCoronaDashboard4 approved these changes

2021-01-18 09:44 UTC, merged