Show just the one line if only one installation exists in the sewerwater chart
minvws/nl-covid19-data-dashboard pull request #1418
Opened 2021-01-12 16:10 UTC by VWSCoronaDashboard1

## Summary

As the title states

## Motivation

Change request

## Detailed design

n/a

## Drawbacks

n/a

## Alternatives

n/a

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-01-13 07:53 UTC, VWSCoronaDashboard8 approved these changes

2021-01-13 07:53 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/lineChart/hooks/useSewerWaterChartOptions.ts
> +    );
I think this is much simpler:

```
const installationNames = uniq(filteredScatterPlotValues.map(x => x.rwzi_awzi_name))
```

uniq is a lodash function

2021-01-13 08:26 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/lineChart/hooks/useSewerWaterChartOptions.ts
> +    );
Done

2021-01-14 11:45 UTC, VWSCoronaDashboard10 requested changes

2021-01-14 11:45 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/gemeente/[code]/rioolwater.tsx
> +
I don't really get this change:
- The expression `sewerStationNames.length > 1` is not that hard to calculate, why the move to a useMemo-hook?
- I don't think we should mutate state during the render of a component. Mutation can happen within callbacks or an effect-hook.

2021-01-14 11:51 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/gemeente/[code]/rioolwater.tsx
> +
I guess what you actually want is something like this:

```diff
- const [selectedInstallation, setSelectedInstallation] = useState<string>();
+ const [selectedInstallation, setSelectedInstallation] = useState<string>(sewerStationNames.length === 1 ? sewerStationNames[0] : undefined);

2021-01-14 11:52 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/gemeente/[code]/rioolwater.tsx
> +
which would still be buggy the moment `data` is becoming dynamic (that would require an effect which runs when `sewerStationNames` mutates). But it is not, and we're on page-level, so I think it's safe enough.

2021-01-14 12:43 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/gemeente/[code]/rioolwater.tsx
> +
Fixed

2021-01-14 12:51 UTC, merged