Export images from Sanity and resize them locally
minvws/nl-covid19-data-dashboard pull request #1434
Opened 2021-01-13 13:53 UTC by VWSCoronaDashboard

## Summary

This PR adds scripts to automatically [download images from Sanity](https://www.sanity.io/docs/migrating-data#1-export) to the filesystem and resize them with [Sharp](https://sharp.pixelplumbing.com/).

It adds:

1. A `yarn image:download` command
2. A `yarn image:resize` command
3. A 'yarn image' command that calls download and resize sequentially through [npm-run-all](https://www.npmjs.com/package/npm-run-all)

## Motivation

In our CMS, content managers can upload images. Due to security and technical availability concerns, we want to serve these images from our own server behind Akamai. 

We also want to resize/optimize these images automatically, because serving original images will lead to very high bandwidth.

## Detailed design

**Image downloading**

First, I `rm -rf` all folders containing the raw export, original sanity images and resized images. 

We call `sanity dataset export development|production export` from the CMS folder. We do this through a little bash script that also unzips the file and moves the assets to `packages/app/public/sanity/`

**Image resizing**

Since Next.js choose Sharp for image resizing, I made the same choice. We could have chosen ImageMagick too, but Sharp is easier to install through NPM and seems to be faster and actively maintained.

We loop over all the files in `packages/app/public/sanity/`. For every file we find, we loop over the sizes array and write new files to the filesystem.

```js

// These are the sizes we want to resize our original images to
const sizes = [320, 640, 768, 1024, 1280, 1536, 2048];

// looping over files here, and for every file we do this
const ext = path.extname(file);
const filename = path
  .basename(file)
  .split(".")
  .slice(0, -1)
  .join(".");
console.log(`Now resizing: ${file}`);

sizes.forEach((size) => {
  const output = `../app/public/sanity/${filename}-${size}${ext}`;
  sharp(file)
    .resize({ width: size, withoutEnlargement: true })
    .toFile(output);
});
```

## Drawbacks

Not a drawback, but something I wanted to flag for you to review:

I originally wanted to put the scripts in `packages/cli`. However, it was easier to call the scripts directly in `packages/cms` for 2 reasons:

1. We already have the required packages installed there
2. We already have the required environment variables for authentication to Sanity configured through dotfiles. This is useful for local development.

## Alternatives

- On development servers we can talk directly to Sanity CDN. There's no need to download the assets and resize them. I still need to implement this.

- `next/image` would serve this out of the box, but it's not compatible with static exports. We would need to start running the production server on a Node environment.

## Unresolved questions

Things we still need to implement while this PR is already being reviewed:

- [ ] Calling Sanity CDN in development and local environments from the front-end.
- [ ] Call the resize and download commands in the production pipeline

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/app/.gitignore
> +public/sanity
nit; for the outside world it doesn't matter what cms we use, so I think it would make sense to give this a more generic name so it doesn't become part of urls. And in theory a cms could change as well.

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/.gitignore
> +production.tar.gz
```suggestion
*.tar.gz
```

I think that works as well

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/package.json
> +    "images:download": "bash scripts/images.sh",
If `scripts/images` is mainly for download, then I would call it download. Or call one file `images-download.sh` and the other `images-resize.sh`

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/images.sh
> +mkdir ../../../app/public/sanity
Is this relative to CWD or file location? I suspect the former, which could be problematic with these paths. 

A solution could be to pass in the path via a command line argument

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/images.sh
> +# Start with a clean slate
I would place a hashbang here to indicate what to run it with then you don't have to specify bash in the calling of the script.

I think the correct way would be: `#!/usr/bin/env bash`, which makes the OS find bash no matter where it is installed.

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/resize.js
> +const sharp = require("sharp");
I would prefer to keep all sources Typescipt. You can execute it with ts-node.

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/resize.js
> +const walk = function (dir, done) {
nit; Prefer (named) function declarations over function expression

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/resize.js
> +    (function next() {
Why are you using an IIFE here? I'm guessing you copy-pasted this since it looks also like ES5 code with the vars and such ;)

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/resize.js
> +});
I would suggest something like `mew` for managing your command line arguments

2021-01-13 15:35 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/resize.js
> +walk(walkPath, function (error) {
An error callback function is quite ancient NodeJs style. We can use promises and possibly async/await.

2021-01-13 16:19 UTC, VWSCoronaDashboard7 commented on packages/app/.gitignore
> +public/sanity
Agree on the above!

2021-01-14 08:49 UTC, VWSCoronaDashboard commented on packages/app/.gitignore
> +public/sanity
Agreed. I changed it to be `public/cms` to at least indicate where it's coming from.

2021-01-14 08:53 UTC, VWSCoronaDashboard commented on packages/cms/package.json
> +    "images:download": "bash scripts/images.sh",
Thanks, I did exactly that.

2021-01-14 08:54 UTC, VWSCoronaDashboard commented on packages/cms/scripts/images.sh
> +mkdir ../../../app/public/sanity
Yes, this is all relative to CWD, which is pretty annoying.

2021-01-14 08:55 UTC, VWSCoronaDashboard commented on packages/cms/scripts/images.sh
> +# Start with a clean slate
Done!

2021-01-14 08:58 UTC, VWSCoronaDashboard commented on packages/cms/scripts/resize.js
> +const sharp = require("sharp");
Done!

2021-01-14 08:59 UTC, VWSCoronaDashboard commented on packages/cms/scripts/resize.js
> +const walk = function (dir, done) {
Agree, and fixed.

2021-01-14 08:59 UTC, VWSCoronaDashboard commented on packages/cms/scripts/resize.js
> +    (function next() {
Oh this is definitely copy-pasted! 🥇

2021-01-14 09:01 UTC, VWSCoronaDashboard commented on packages/cms/scripts/resize.js
> +walk(walkPath, function (error) {
I copy pasted ancient Nodejs stuff. Do you want me to rewrite this to modern JS or are you happy to leave it as-is?

2021-01-14 09:03 UTC, VWSCoronaDashboard commented on packages/cms/.gitignore
> +production.tar.gz
I think this has been resolved in the branch already.

2021-01-14 09:12 UTC, VWSCoronaDashboard commented on packages/cms/scripts/resize.js
> +});
You know what, I simply removed this block of code completely. I don't think we'll miss it.

2021-01-14 11:58 UTC, VWSCoronaDashboard1 commented on packages/cms/scripts/resize.js
> +walk(walkPath, function (error) {
> I copy pasted ancient Nodejs stuff. Do you want me to rewrite this to modern JS or are you happy to leave it as-is?

That's a silly question to ask to @VWSCoronaDashboard8 ;)

2021-01-14 12:04 UTC, VWSCoronaDashboard1 commented on packages/cms/scripts/images-resize.ts
> +            const output = `../app/public/cms/${filename}-${size}${ext}`;
I see this path sprinkled around the codebase quite a bit. Maybe it's an idea to stick this in a config object that you can import in all the appropriate places.

2021-01-14 14:37 UTC, VWSCoronaDashboard commented on packages/cms/scripts/images-resize.ts
> +            const output = `../app/public/cms/${filename}-${size}${ext}`;
Eh, it's not worth the effort. All the instances are different.

I did however add a config.js object so I only declare the sizes array in one place!

2021-01-15 14:34 UTC, VWSCoronaDashboard1 approved these changes

2021-01-19 10:40 UTC, VWSCoronaDashboard8 requested changes

2021-01-19 10:40 UTC, VWSCoronaDashboard8 commented on packages/app/src/utils/findClosestSize.ts
> +const config = require('~/config.js');
Why is the config a js file? And I think you can then still use a normal import statement

2021-01-19 10:40 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/images-download.sh
> +mv * ../../../app/public/cms
Fine for now but I think it makes sense to just rewrite this in TS later so that it can be more understandable and robust. Where we can use __dirname and other techniques that everyone is familiar with.

Then execute that script with `ts-node`

2021-01-19 10:40 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/images-resize.ts
> +const config = require("../../app/src/config.js");
A package should not have direct imports from other packages like this. It kind of defeats the idea of a monorepo. 

You can now place this in common maybe.

2021-01-19 10:41 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/resize.js
> +walk(walkPath, function (error) {
Well I am fine with simply having a cleanup / convert round at the end of this sprint, so doing it in a separate PR.

2021-01-19 19:23 UTC, VWSCoronaDashboard commented on packages/app/src/utils/findClosestSize.ts
> +const config = require('~/config.js');
Guess it should be TS? 👍 
I'll try the import.

2021-01-19 19:24 UTC, VWSCoronaDashboard commented on packages/cms/scripts/images-resize.ts
> +const config = require("../../app/src/config.js");
Good one. I'll try rewriting this.

2021-01-25 11:49 UTC, VWSCoronaDashboard1 approved these changes

2021-01-25 11:49 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/over.tsx
> +"imageContent": *[_type == 'imagePipelineTest'][0]{
This reeks of test code, are we sure we want this merged?

2021-01-25 11:52 UTC, VWSCoronaDashboard commented on packages/app/src/pages/over.tsx
> +"imageContent": *[_type == 'imagePipelineTest'][0]{
Good one. I can remove it and add code to the article pages to test out the image pipeline.

2021-01-25 12:21 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/image.tsx
> +  const filename = src.split('.')[0];
```
const [filename, extension] = src.split('.')
```

2021-01-25 12:21 UTC, VWSCoronaDashboard4 commented on packages/cms/scripts/images-resize.ts
> +// These are the sizes we want to resize our original images to
This comment and other comments in this file do not make much sense. Perhaps have a closer look at the comments and add some that clarify what is going on, where needed?

2021-01-25 12:29 UTC, VWSCoronaDashboard8 requested changes

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/image.tsx
> +  const extension = src.split('.')[1];
```suggestion
  const [filename, extension] = src.split('.');
```

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/image.tsx
> +  const url = `/cms${filename}-${findClosestSize(width)}.${extension}`;
Looks like you are attaching the word `cms` to the `filename`. Why not put a dash in between?

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/image.tsx
> +  const url = `/cms${filename}-${findClosestSize(width)}.${extension}`;
If filename includes a leading slash then it's technically not a filename, but I would be ok with adding a comment to inform the reader.

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/over.tsx
> +import { SanityImageProps } from '~/types/cms.d.ts';
nit; The ts part will be resolved just like other ts files.

```suggestion
import { SanityImageProps } from '~/types/cms.d';
```

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/over.tsx
> +              src={`/${coverImage.assetId}.${coverImage.extension}`}
If the leading slash in my previous comment is coming from here, I suggest to remove it here and add it in the other place. To me that makes more sense and is clear to the user. It's uncommon anyway to start a path with / unless you mean the unix root.

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/utils/findClosestSize.ts
> +export function findClosestSize(width: number) {
This function looks like quite specific domain logic and not really a utility belt function in that sense. I would move it to the cms folder, maybe inside a `logic` subfolder or `logic.ts` file. Not sure if you were there when we discussed file structure on Friday. That was about components but I think a similar way of thinking can be applied here.

Also I think the function would be a little better if you passed in sizes as the first argument. Then it's immediately clear what it does from the calling context, and you also don't need the comment.

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/utils/imageLoader.ts
> +  const extension = src.split('.')[1];
Same suggestion as previously

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/cms/scripts/images-resize.ts
> +import { sizes } from '@corona-dashboard/common/src/config';
If config is something to be imported from common, then the common package should export it. It's not ok for one package to directly import source files from another package. The public facing files of common live in `dist` and are exposed via the package definitions. 

You probably just need to add the config to the exports list in src/index.ts

```suggestion
import { sizes } from '@corona-dashboard/common';
```

2021-01-25 12:29 UTC, VWSCoronaDashboard8 commented on packages/common/src/config.ts
> +export const sizes = [320, 640, 768, 1024, 1280, 1536, 2048];
Since `common` and `config` don't have a clear context, I think it makes sense to be a little more specific here and call them `imagesSizes` or `resizeImageSizes` even.

2021-01-25 12:42 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/over.tsx
> +import { SanityImageProps } from '~/types/cms.d.ts';
You can leave me `.d` part as well

2021-01-26 15:56 UTC, VWSCoronaDashboard commented on packages/common/src/config.ts
> +export const sizes = [320, 640, 768, 1024, 1280, 1536, 2048];
Sounds good to me!

2021-01-26 15:58 UTC, VWSCoronaDashboard commented on packages/app/src/components-styled/image.tsx
> +  const url = `/cms${filename}-${findClosestSize(width)}.${extension}`;
Yup, it's because of a trailing slash. I'll add some comments here.

2021-01-26 16:00 UTC, VWSCoronaDashboard commented on packages/app/src/pages/weekberichten/index.tsx
> +import { getLayoutWithMetadata } from '~/domain/layout/layout';
I don't know why this file is here or what it's for. It must've happened when we change bases?

2021-01-26 16:04 UTC, VWSCoronaDashboard commented on packages/app/src/utils/findClosestSize.ts
> +export function findClosestSize(width: number) {
I agree with your second point and have changed the code to reflect that. 👍 

I disagree with your first point, as the utility function is closely coupled to the front-end application.

2021-01-26 16:10 UTC, VWSCoronaDashboard commented on packages/cms/scripts/images-resize.ts
> +// These are the sizes we want to resize our original images to
I've added the source of the code as a comment and explained it's unoptimized, but working code.

2021-01-26 19:54 UTC, VWSCoronaDashboard8 approved these changes

2021-01-26 21:16 UTC, VWSCoronaDashboard1 approved these changes

2021-01-26 21:16 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/weekberichten/index.tsx
> +import { getLayoutWithMetadata } from '~/domain/layout/layout';
I deleted this file, so it looks like a faulty merge. You can remove it as well.

2021-01-27 10:59 UTC, merged