Add CoronaMelder app chema
minvws/nl-covid19-data-dashboard pull request #1440
Opened 2021-01-13 15:56 UTC by VWSCoronaDashboard14

Schema for the CornaMelder app including:
Warnings daily
Total downloads
Warnings daily difference compared to the day before.

2021-01-14 07:50 UTC, VWSCoronaDashboard8 requested changes

2021-01-14 07:50 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/__difference.json
> +    "behavior_app__warning_daily": {
This app is unrelated to the other behavior research so I would not choose to name it like this. If the thing is known  as the Corona App then I suggest you call it that `corona_app.`

2021-01-14 07:50 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/behavior_app.json
> +{
Rename also this file or course

2021-01-14 07:50 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/behavior_app.json
> +  "title": "national_behavior_app",
The file used to be called national. You can start prefixing with nl_ now. The others are on the backlog for renaming. This title is used to generate the Typescript type names.

2021-01-14 07:50 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/behavior_app.json
> +        "warning_daily": {
Not sure what is most consistent with the other schemas but I would name these either in plural (downloads_ and warnings_) or past-tense (downloaded_, warned_)

2021-01-15 13:31 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/corona_app.json
> +  "title": "nl_corona_app",
Other schema's use `national` as prefix, not `nl`:

```suggestion
  "title": "national_corona_app",
```

2021-01-18 16:29 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/corona_app.json
> +  "title": "nl_corona_app",
@VWSCoronaDashboard4 The plan was to start using nl/vr/gm as the new prefix, because the file names have changed from national to nl. Only I didn't find time yet to change all of the titles. The newer schema's use the nl_ prefix

2021-01-18 16:29 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/corona_app.json
> +      "title": "national_corona_app_value",
So this one should start with nl_ too

2021-01-18 16:30 UTC, VWSCoronaDashboard8 approved these changes

2021-01-18 16:33 UTC, VWSCoronaDashboard8 commented
@VWSCoronaDashboard14 A schema for a new feature is usually merged together with the implementation of that feature in UI code. So this PR should merge into a base branch, or be marked as being a base branch itself on which the other tasks can build.

2021-02-08 13:31 UTC, closed without merging