Topic/actueel artikelen
minvws/nl-covid19-data-dashboard pull request #1454
Opened 2021-01-14 09:11 UTC by VWSCoronaDashboard4

## Summary

Adds Articles structure to the CMS + basic routing and interfaces for the frontend.

## Detailed design

* Adds schemes in CMS, including types to combine images/graphs in rich text.
* Rich text is limited for now, removing options for H1, H4-H6 and other elements we don't want to use there.
* Basic TS Interfaces to work with the Articles, with Todos added to add more specifics later on.
* Basic routing: `/artikelen` and `/artikelen/[slug]`

# Left for a separate PR

* Validation of uniqueness of the slugs
* More detailed TypeScript interfaces

2021-01-14 09:39 UTC, VWSCoronaDashboard1 approved these changes

2021-01-14 09:39 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/artikelen/[slug].tsx
> +}
I'm guessing this will need to be changed according to the changes made by @VWSCoronaDashboard10 concerning the data loading?

2021-01-14 09:39 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/artikelen/index.tsx
> +  const lastGenerated = JSON.parse(fileContents).last_generated;
There's a handy little util for this:
https://github.com/minvws/nl-covid19-data-dashboard/blob/topic/actueel-artikelen/packages/app/src/static-props/utils/load-json-from-data-file.ts

2021-01-14 09:39 UTC, VWSCoronaDashboard1 commented on packages/cms/schemas/documents/artikel.js
> +    },
Doesn't the preview also need an image?

2021-01-14 09:40 UTC, VWSCoronaDashboard4 commented on packages/app/src/pages/artikelen/[slug].tsx
> +}
Yes!

2021-01-14 09:47 UTC, VWSCoronaDashboard4 commented on packages/cms/schemas/documents/artikel.js
> +    },
This is the preview in the CMS, not in the frontend.

2021-01-14 09:48 UTC, VWSCoronaDashboard1 commented on packages/cms/schemas/documents/artikel.js
> +    },
Aha, makes sense then!

2021-01-14 10:13 UTC, VWSCoronaDashboard8 commented on packages/cms/schemas/locale/locale-rich-content-block.js
> +  title: "Locale Rich Content Block",
Other titles seem to be in Dutch, and apart from that I wonder what a locale rich content block means. Maybe add a comment to explain. I see it also can include chart configs?

2021-01-14 10:13 UTC, VWSCoronaDashboard8 commented on packages/cms/schemas/objects/line-chart.js
> +export default {
Maybe add a comment to explain what this is for. A line chart config with metric name and property doesn't appear to be quite enough to instantiate an actual line chart.

2021-01-14 10:13 UTC, VWSCoronaDashboard8 commented on packages/cms/schemas/schema.js
>      //documents
I prefer to use block comments for actual comments, so they are more visible and also distinguishable from stuff that is just commented out.

2021-01-14 10:22 UTC, VWSCoronaDashboard1 commented on packages/cms/schemas/locale/locale-rich-content-block.js
> +  title: "Locale Rich Content Block",
Perhaps `localizedRichContentBlock` makes more sense?

2021-01-14 12:55 UTC, VWSCoronaDashboard commented
Generic feedback without looking at your code:

1. Good call to put metadata content in a fieldset. I've got an open-graph model defined already, so we can use that one for metadata. I think we should check if we can make this UI better by adding the sanity-tabs plugin!

2. I'm missing alt text on the image. We need to add those.

3. I simultaneously love and worry about the "lijngrafiek" in content blocks. 

It's impressive that it can work like this, and I believe the authoring flow would be nice. However, because we repeat it for the english version it almost feels like we're opening up the editor too much.

Maybe a better approach is to use document level translations for artikelen, and keep using field level translations for other documents. Of course that introduces the new problem that you need to re-enter your slug and images for translated posts, which is also less than ideal.

Another thing is that it relies on front-end specific knowledge to couple the charts. Maybe we can improve that too. I can imagine that we keep a collection of links between the CMS and front-end ourselves as a collection of tiles/charts in the CMS and let the content manager choose one from a predefined list?

2021-01-14 13:06 UTC, VWSCoronaDashboard4 commented on packages/app/src/types/cms.d.ts
> +    current: string;
This is the default sanity slug object, since in the sanity schema we use the build in slug component.

2021-01-14 13:09 UTC, VWSCoronaDashboard4 commented on packages/cms/schemas/objects/line-chart.js
> +export default {
I'll add a Todo. This will indeed need to be extended in a separate PR.

2021-01-14 13:15 UTC, VWSCoronaDashboard4 commented on packages/cms/schemas/locale/locale-rich-content-block.js
> +  title: "Locale Rich Content Block",
This is perhaps food for a different/broader discussion.

The `title` is merely what is displayed in the CMS, I'll tweak that a bit.

The `name` is how it is referred to within other blocks/schema's. There this camelcasing is used. It is the structure that supports one locale (either EN or NL in this case). See the other files in this directory.

2021-01-14 13:16 UTC, VWSCoronaDashboard4 commented on packages/app/src/types/cms.d.ts
> +  _type: 'lineChart';
All other CMS types are following the camelCase structure so far.

2021-01-14 13:17 UTC, VWSCoronaDashboard4 commented on packages/app/src/types/cms.d.ts
> +  intro: Block | null;
It's a sanity `Block` type

2021-01-14 13:28 UTC, VWSCoronaDashboard reviewed
Lot's of small comments and questions. No real blockers, especially if we agree that this needs more refinement afterwards on develop or actueel-base. Also, no real approval because this isn't _done_-done.

Happy to see this!

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/app/src/pages/artikelen/[slug].tsx
> +  );
Does the UI copy still need markdown parsing? If things are right, all rich text now comes from the CMS and is parsed by the Sanity Block component.

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/app/src/pages/artikelen/[slug].tsx
> +`;
nit: To reduce bandwidth we could look into specifying all fields up front, which means you don't get the fields that you don't need. Should save a few bytes.

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/app/src/pages/artikelen/[slug].tsx
> +const metadata = {
Fine with todo's, but make sure to write them down in the topic/actueel-base PR.

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/app/src/types/cms.d.ts
> +    current: string;
This is how Sanity stores data that's of a `slug` type:

```
{
  "_type": "slug",
  "current": "this-is-the-title"
}
```

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/app/src/types/cms.d.ts
> +}
These are hard to type. We'll need to spend more time figuring out how to deal with dynamic block content.

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/cms/schemas/locale/locale-rich-content-block.js
> +  title: "Locale Rich Content Block",
The other block is also localized, and also has rich content. This one has reduced formatting options and adds new allowed types.

You might need to call this for what it is, a Block for rticles.

`articleBlock`?

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/cms/schemas/locale/locale-rich-content-block.js
> +        ],
This is great for SEO! 👏

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/cms/schemas/objects/line-chart.js
> +export default {
It's also not _really_ a linechart. It serves as a connection between front-end values and the CMS.

This is probably one of the more difficult models for the CMS. Let's take the time to get it right, even if it means launching without charts initially?

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/cms/schemas/objects/line-chart.js
> +  ],
Technically, this makes sense... I'll give you that.

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/cms/schemas/documents/artikel.js
> +    },
You actually can add the image in the preview too. It will help recognize articles when listing them. I'm voting that we should add this.

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/cms/schemas/locale/locale-rich-content-block.js
> +  title: "Locale Rich Content Block",
I don't think this block should ever be used outside of articles though. That's why I suggest you name it in reference to that.

You can also move the file to be part of a `articles` schema folder. Co-locate those things to make it clear they are related.

2021-01-14 13:28 UTC, VWSCoronaDashboard commented on packages/app/src/pages/artikelen/index.tsx
> +  const articlesData = await getPreviewClient().fetch(articlesQuery);
You should not use previewClient here. I'm seeing both the original article and a draft on this page.

2021-01-14 14:43 UTC, VWSCoronaDashboard commented on packages/app/src/pages/artikelen/[slug].tsx
> +  const articles = localize(articlesData, [targetLanguage, 'nl']);
In return you get localized data. Localize takes a look at your targetLanguage and returns only the fields that are either .en or .nl.

2021-01-14 14:47 UTC, VWSCoronaDashboard requested changes

2021-01-14 14:47 UTC, VWSCoronaDashboard commented on packages/app/src/pages/artikelen/[slug].tsx
> +  const articlesData = await getPreviewClient().fetch(articlesQuery);
Do not use the preview client.

2021-01-14 14:57 UTC, VWSCoronaDashboard10 approved these changes
Couple of small comments 👍

2021-01-14 14:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/artikelen/[slug].tsx
> +const ArticleDetail: FCWithLayout<ArticleDetailProps> = (props) => {
You can infer the props from the getInitialProps:

```suggestion
const ArticleDetail: FCWithLayout<typeof getStaticProps> = (props) => {
```

2021-01-14 14:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/artikelen/[slug].tsx
> +  description: 'TODO',
```suggestion
  title: '@TODO',
  description: '@TODO',
```
makes it easier to find them :-)

2021-01-14 14:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/artikelen/index.tsx
> +        <div key={`article-${article.slug.current}`}>
```suggestion
        <div key={article.slug.current}>
```

2021-01-14 14:57 UTC, VWSCoronaDashboard10 commented on packages/cms/schemas/documents/artikel.js
> +  name: "artikel",
Not sure what the `name` property is meant for, but we might want them to be English?

2021-01-14 14:57 UTC, VWSCoronaDashboard10 commented on packages/cms/schemas/documents/artikel.js
> +  name: "artikel",
Looks like a lot of other `name` properties in this file are English

2021-01-14 14:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/static-props/get-data.ts
> +        ? queryOrQueryGetter.call({}, context)
Why not simply `queryOrQueryGetter(context)`?

2021-01-15 07:32 UTC, VWSCoronaDashboard4 commented on packages/cms/schemas/documents/artikel.js
> +    },
I'd agree we can add this. I'd opt to do that in a separate PR, to also scope what it should/shouldn't do layout wise.

2021-01-15 10:38 UTC, VWSCoronaDashboard approved these changes

2021-01-15 10:41 UTC, merged