Reduce amount of ticks on age demographic graph on smaller screens
minvws/nl-covid19-data-dashboard pull request #1465
Opened 2021-01-14 14:31 UTC by VWSCoronaDashboard14

Reduce amount of ticks on age demographic graph on smaller screens

2021-01-14 14:42 UTC, VWSCoronaDashboard commented on packages/app/src/domain/infected-people/age-demographic/age-demographic-chart.tsx
> +    const numTicksOnBreakpoint = breakpoints.xs ? numTicks : 2;
```suggestion
    const { xs } = useBreakpoints();
    const numTicksOnBreakpoint = xs ? numTicks : 2;
```

2021-01-14 14:42 UTC, VWSCoronaDashboard approved these changes

2021-01-14 15:55 UTC, VWSCoronaDashboard1 approved these changes

2021-01-15 13:15 UTC, VWSCoronaDashboard4 requested changes

2021-01-15 13:15 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/infected-people/age-demographic/age-demographic-chart.tsx
> +    const numTicksOnBreakpoint = xs ? numTicks : 2;
You get `numTicks` via `coordinates` which is calculated in the file `age-demographic-coordinates`. It is crucial to keep thiese calculations in that file for performance and tidyness. Other parts of the graph also refer to these coordinates (eg the tooltip), so if these are not in sync things might break.

2021-01-18 10:06 UTC, VWSCoronaDashboard4 approved these changes

2021-01-18 10:28 UTC, merged