Risk level indicator for VR
minvws/nl-covid19-data-dashboard pull request #1496
Opened 2021-01-18 09:18 UTC by VWSCoronaDashboard14

New risk level indicator for the safety region and municipality actueel page.

I'm not totally satisfied with how the typescript is currently implemented.

2021-01-18 10:23 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/risk-level-indicator.tsx
> +        {description} <br />
Split this into two Text: `<Text>
        {description}</Text>
<Text> ....`

2021-01-18 10:23 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/risk-level-indicator.tsx
> +        <StyledSpan>
Since this is only used in this file: perhaps name it a bit better? eg 
```suggestion
        <EscalationLevelTitle>
```

2021-01-18 10:24 UTC, VWSCoronaDashboard8 requested changes

2021-01-18 10:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/assets/stopwatch.svg
> +<svg focusable="false" width="31" height="32" viewBox="0 0 31 32" fill="none" xmlns="http://www.w3.org/2000/svg">
I believe all of our SVGs lately got an extra property to make them non-focusable for accessibility reasons

2021-01-18 10:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/risk-level-indicator.tsx
> +  href: string;
nit; Maybe consider naming this linkHref, to group it with linkTitle, or create a `link: { href, title}` property where both are combined

2021-01-18 10:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/risk-level-indicator.tsx
> +  assert(filteredEscalationLevel, 'Could not find an escalation level');
It helps of you make the error more informative by logging what level value could not be found.

2021-01-18 10:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/en.json
> +  "risoconiveau_maatregelen": {
Typo. I would strongly advise you to install a spell checker in your IDE. I use Code Spell Checker in VSCode for both English and Dutch.

2021-01-18 10:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/nl.json
> +  "risoconiveau_maatregelen": {
Same here

2021-01-18 10:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/actueel.tsx
> +    typeof router.query.code === 'string' ? router.query.code : undefined;
I think you might as well use router.query.code directly. I don't really see a point in more defensive programming since you already have an assert below.

2021-01-18 10:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/actueel.tsx
> +  assert(filteredRegion, 'Could not find a region code');
Similar as before, extend the message to include information about what value couldn't be found.

2021-01-18 10:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/actueel.tsx
> +  const riskLevelText = siteText.risoconiveau_maatregelen;
If you're working with one source of text, simply `text` is sufficient in this scope. I will make the code below more clean I think.

2021-01-18 11:25 UTC, VWSCoronaDashboard14 commented on packages/app/src/pages/veiligheidsregio/[code]/actueel.tsx
> +  const riskLevelText = siteText.risoconiveau_maatregelen;
There are 3 different root keys coming from localized, that it might be better to separate them maybe?

2021-01-18 13:21 UTC, VWSCoronaDashboard4 approved these changes

2021-01-19 07:06 UTC, VWSCoronaDashboard8 approved these changes
👍

2021-01-19 09:31 UTC, merged