Add editorial tile to actueel page
minvws/nl-covid19-data-dashboard pull request #1578
Opened 2021-01-24 15:11 UTC by VWSCoronaDashboard1

## Summary

This adds a tile to the actueel page that displays the latest editorial and one highlighted article teaser.

## Motivation

Feature request

## Detailed design

A new schema for editorials was added. Right now this is still a verbatim copy of the articles schema (as is the editorialdetail component). But since these editorials are supposed to differ from regular articles they're modeled separately since they're subject to change.
A page schema for actueel was added that allowed content management to choose the highlighted article.
A placeholder page for the editorial page was added, since no design for this exists yet.

## Drawbacks

n/a

## Alternatives

n/a

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-01-24 16:51 UTC, 0x80 approved these changes

2021-01-24 16:51 UTC, 0x80 commented on packages/cms/resolve-document-actions.js
> +} from 'part:@sanity/base/document-actions';
What is this weird looking import doing?

2021-01-24 16:51 UTC, 0x80 commented on packages/cms/schemas/documents/editorial.js
> +import { ARTICLE_FIELDS } from './fields/ARTICLE_FIELDS';
I don't see a need to have the filename match the variable casing. We agreed to make all files kebab-case so these ones can be that too.

2021-01-24 16:51 UTC, 0x80 commented on packages/cms/schemas/schema.js
> +// routekaart en maatregelen
Looks like some things can be cleaned up

2021-01-25 10:44 UTC, VWSCoronaDashboard4 requested changes

2021-01-25 10:44 UTC, VWSCoronaDashboard4 commented on packages/app/src/utils/formatDate.ts
> +import '@formatjs/intl-datetimeformat/polyfill';
Revert this please, see the comment above it. This will cause IE11 to break the app

2021-01-25 10:44 UTC, VWSCoronaDashboard4 commented on packages/app/src/utils/formatDate.ts
> +export function formatSanityDate(
Sanity is the name of the source, not the name of the date format. Perhaps adjust the name to match what the format is?

2021-01-25 10:44 UTC, VWSCoronaDashboard4 commented on packages/cms/schemas/documents/editorial.js
> +  fields: [].concat(ARTICLE_FIELDS),
Wouldn't it be handier to just have two separate configs? Then you can safely remove an item from one, or add one to the other, without messing anything up.

2021-01-25 10:49 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/formatDate.ts
> +import '@formatjs/intl-datetimeformat/polyfill';
Oh damn, my formatter automatically changes this...

2021-01-25 10:50 UTC, VWSCoronaDashboard1 commented on packages/cms/schemas/documents/editorial.js
> +  fields: [].concat(ARTICLE_FIELDS),
No, in this case, I'm using composition exactly because these types of content shared these fields. In the future, there will be different flavors as well, such as blogposts, etc.

2021-01-25 10:52 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/formatDate.ts
> +export function formatSanityDate(
True, but I reckoned that within our domain the sanity source implies that it's a string-based date...

2021-01-25 10:57 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/formatDate.ts
> +export function formatSanityDate(
I've renamed it to `formatDateFromString`

2021-01-25 10:58 UTC, merged