Update sitemap grid and arrow from quicklinks
minvws/nl-covid19-data-dashboard pull request #1698
Opened 2021-01-28 14:43 UTC by VWSCoronaDashboard14

On medium screen size, the sitemap goes to a 4 and 2 column layout. 
Fixed an issue where a long word Is on the mini-trend-tile component and the arrow breaks on a certain point to the next line. Solved it by positioning an arrow that belongs to a single word title absolute right from it.

2021-01-28 15:32 UTC, VWSCoronaDashboard4 approved these changes

2021-01-28 15:48 UTC, merged

2021-01-28 15:50 UTC, VWSCoronaDashboard8 requested changes

2021-01-28 15:50 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/link-with-icon.tsx
> +  singleWord?: boolean;
This is not a good name for a boolean, since its content is not a word. We prefix all booleans with is/has/can/should etc.

2021-01-28 15:50 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/link-with-icon.tsx
> +  const singleWord = splittedString.length === 1;
same here

2021-01-28 15:50 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/link-with-icon.tsx
> +        {iconPlacement == 'right' && !headingLink && (
In JS you always use `===` for comparison unless you want to allow implicit casting to happen but that is considered bad practice. In this case it can't hurt, but it's easier to just never use `==` at all.

2021-01-28 15:50 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/link-with-icon.tsx
>    const splittedString = children.split(' ');
I think you can simply call this `words` it would make the code a little more terse.

2021-01-28 15:50 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/link-with-icon.tsx
> +      <span css={css({ svg: { height: '11px', width: '13px', mx: '3px' } })}>
This looks a bit nasty since we don't rely on CSS selectors normally with styled components/system. Can we not control width and height via props on the Icon component?

2021-01-28 15:50 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/topical/data-sitemap.tsx
> +          flexDirection="row"
row is the default flex direction so I think this is redundant

2021-01-28 15:50 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/topical/data-sitemap.tsx
> +    },
What is this for? Is it for setting a margin some of the LinkBox elements? If so, this margin can also be set via props since the LinkBox components are not instantiated programatically I think?

If true, you don't actually need the LinkBox component because the other css properties can also be set as props on Box directly. But yeah that might be a little verbose, unless you create a LinkBox from Box by setting defaultProps and thus create it once. I don't mind much, just some ideas.

2021-01-29 09:27 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/topical/data-sitemap.tsx
> +    },
Totally agree, it both does the job but I think your proposal is more in line with the standard we use across the dashboard.