Use webpack plugin to import specific locale
minvws/nl-covid19-data-dashboard pull request #1717
Opened 2021-01-29 10:54 UTC by VWSCoronaDashboard

## Summary

I saw un the bundle analyzer that we bundle both languages. This PR makes it so we only ship one.

## Motivation

Reduce bundle size.

## Detailed design

There's 2 things you need to check when reviewing:

- I've used webpacks NormalModuleReplacementPlugin to import a specific language file.
- I added a new TS file that mimicks the "normal" import, so it exposes the correct types.
- We only expose the type from the NL file. Never the EN file. As they should be 100% the same I don't think it's a problem.

2021-01-29 10:58 UTC, VWSCoronaDashboard1 reviewed
So, this solution is great for bundle size. Yet, it also removes the compile-time check for missing keys between nl.json and en.json.
In the original file this union `TALLLanguages = TNLLocale | TENLocale` would ensure that all keys are present in both files.

2021-01-29 11:37 UTC, VWSCoronaDashboard7 commented
> So, this solution is great for bundle size. Yet, it also removes the compile-time check for missing keys between nl.json and en.json.
> In the original file this union `TALLLanguages = TNLLocale | TENLocale` would ensure that all keys are present in both files.

If we want to reduce the bundle-size and have this check, that type-enforced check could be replaced by a custom schema validator since the locale files are also just a json file with some structure. Of course this is some more effort than that union approach. No sure if there are other trade-offs involved.

2021-01-29 11:40 UTC, VWSCoronaDashboard1 commented
> If we want to reduce the bundle-size and have this check, that type-enforced check could be replaced by a custom schema validator since the locale files are also just a json file with some structure. Of course this is some more effort than that union approach. No sure if there are other trade-offs involved.

It would actually be possible to generate a json schema @build time from the nl.json file and use that schema to validate the en.json. That would probably be the fastest way of performing this check.

2021-01-29 11:43 UTC, VWSCoronaDashboard1 commented
> It would actually be possible to generate a json schema @ build-time from the nl.json file and use that schema to validate the en.json. That would probably be the fastest way of performing this check.

Come to think of it, this would probably be a much simpler approach since we only want to compare the structure:
https://www.npmjs.com/package/json-diff

2021-01-29 13:02 UTC, VWSCoronaDashboard1 approved these changes

2021-01-29 13:57 UTC, VWSCoronaDashboard4 commented on packages/app/src/locale/APP_TARGET.ts
> +import localefile from './nl.json';
```suggestion
import locale from './nl.json';
```

2021-01-29 13:57 UTC, VWSCoronaDashboard4 commented on packages/cli/src/validator/validate-locales.ts
> +  obj1: Record<string, unknown>,
Can we perhaps get rid of the `unknown`?

```suggestion
  obj1: Record<string, LocaleValue>,
```

if you define `type LocaleValue = string | Record<string, LocaleValue>;` or something similar.

2021-01-29 13:58 UTC, VWSCoronaDashboard4 approved these changes

2021-01-29 13:58 UTC, VWSCoronaDashboard4 commented on package.json
> +      "pre-commit": "yarn workspace @corona-dashboard/app lint-staged && yarn workspace @corona-dashboard/cli validate-locales",
For future improvement: a way to run these async to speed up dev time.

2021-02-01 09:35 UTC, VWSCoronaDashboard8 requested changes

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/next.config.js
> +    // e.g. ~/src/locale/APP_TARGET.json becomes ~/src/locale/nl.json
nit; I prefer to stick to jsdoc style comment starting with `/**` and ending with `*/` It makes it easier to re-format and add lines. Also I feel it makes the comments stand out better and distinguish themselves from commented-out code chunks.

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/APP_TARGET.ts
> +// This file just exports the type from the NL file so all types still work.
Same comment here. BTW the VSCode extension "rewrap" helps with this kind of thing

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/APP_TARGET.ts
> +// This file is meant to trick TypeScript.
I don't see much value in naming this file upper-case since it's not a constant and I don't know what the meaning would be.

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/index.ts
> +export type TALLLanguages = TLocale;
Maybe for later, but now that we have one type, we can remove TALLLanguages and just to a find/replace with TLocale. In that sense you might as well name it Locale since we stopped prefixing types with T or I.

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validator/validate-locales.ts
> +import en from '../../../app/src/locale/en.json';
One package should not import files from another package directly so this not quite ok. But then again app is not set up to be a shared module, so I'll guess I can just ignore this for now.

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validator/validate-locales.ts
> +  obj1: Record<string, unknown>,
I don't know if there are still arrays in the locale file, but then they would have to be included as well I guess...

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validator/validate-locales.ts
> +    []
If you type the second argument you don't have to type the function arguments. The object type is already known from objects.

```suggestion
  const allKeys: string[] = objects.reduce(
    (keys, object) => keys.concat(Object.keys(object)),
    [] as string[]
```

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validator/validate-locales.ts
> +  const union = new Set(allKeys);
You could have used a Set in the reduce straight away.

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validator/validate-locales.ts
> +if (objectsHaveSameKeys(nl, en)) {
This `objectsHaveSameKeys` function seems to only check the top-level keys, so I doubt if this validation is useful. I think you better compile a list of strings where each nested property is listed `some.nested.property` and then compare those lists. This would require a recursive function.

2021-02-01 09:35 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validator/validate-locales.ts
> +if (objectsHaveSameKeys(nl, en)) {
Maybe you can get around this by doing a jsonDiff straight-away and then look at the output to see if the diff is only values or also differences in key (add/remove). I suspect the diff format will tell you that.

2021-02-11 09:28 UTC, VWSCoronaDashboard commented on packages/app/src/locale/APP_TARGET.ts
> +// This file is meant to trick TypeScript.
It is a constant, look at the Webpack config. Or at least it should look like a constant and be recognisable as one even if it's technically not true.

2021-02-11 09:29 UTC, VWSCoronaDashboard commented on packages/cli/src/validator/validate-locales.ts
> +import en from '../../../app/src/locale/en.json';
Updated this!

2021-02-11 09:38 UTC, VWSCoronaDashboard commented on packages/cli/src/validator/validate-locales.ts
> +if (objectsHaveSameKeys(nl, en)) {
Done exactly that now. Json-diff is the single source of truth for equality. I also don't think this check is as important really, we're better off building in fallbacks in the front-end and checking for empty values in the CMS or Lokalise.

2021-02-11 09:43 UTC, VWSCoronaDashboard1 approved these changes

2021-02-11 10:15 UTC, VWSCoronaDashboard8 approved these changes

2021-02-11 10:15 UTC, VWSCoronaDashboard8 commented on packages/app/next.config.js
> +        /(.*)APP_TARGET(\.*)/,
nit; I wonder why you choose to call it "app target" and not just "locale" or something. I associate target with compile target/platform, and the name locale would have been clear to me.

2021-02-11 10:15 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/APP_TARGET.ts
> +export default locale;
Is it necessary to use a default export? We choose to avoid it in other places.

2021-02-11 10:15 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/index.ts
> +export type TALLLanguages = TLocale;
I would suggest doing a find/replace on `TALLLanguages` and name `TLocale` simply `Locale` while you're at it

2021-02-11 10:15 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validate-schema/validate-locales.ts
> +import en from '@corona-dashboard/app/src/locale/en.json';
I guess we could move this to the common package at some point. Together with the schema definitions.

2021-02-11 10:15 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validate-schema/validate-locales.ts
> +function objectsHaveSameKeys(
I find this function name a little odd, since it doesn't start with a verb. I suggest something like `matchObjectKeys` or `validateObjectKeysEquality`

2021-02-11 10:15 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validate-schema/validate-locales.ts
> +  // @ts-ignore
What are you trying to ignore here? Maybe you can solve it by casting the arguments to `diff`?

2021-02-11 10:15 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validate-schema/validate-locales.ts
> +    // which means if diff is truthy, we found differences and should throw an error
I'd suggest to combine this in to a single JSDoc style comment for readability.

2021-02-11 10:15 UTC, VWSCoronaDashboard8 commented on packages/cli/src/validate-schema/validate-locales.ts
> +      {},
It seems odd that you are passing something to diffString if the library doesn't accept it in its types. I think a comment would be useful here.

2021-02-11 11:11 UTC, VWSCoronaDashboard commented on package.json
> +      "pre-commit": "yarn workspace @corona-dashboard/app lint-staged && yarn workspace @corona-dashboard/cli validate-locales",
Afaik lokalize will not remove keys. But it doesn't matter, we've removed the custom validator and let TypeScript do an equality check again. If en !== nl it errors.

2021-02-11 11:12 UTC, VWSCoronaDashboard commented on packages/app/next.config.js
> +        /(.*)APP_TARGET(\.*)/,
If I remember correctly it's because I just followed the documentation blindly without thinking about the filename. Just wanted to have it working first. I can still rename this before I merge :).

2021-02-11 11:13 UTC, VWSCoronaDashboard commented on packages/app/src/locale/APP_TARGET.ts
> +export default locale;
That's a discussion for another PR or ticket 👍  (but I agree with you)

2021-02-11 11:18 UTC, VWSCoronaDashboard commented on packages/app/next.config.js
> +        /(.*)APP_TARGET(\.*)/,
Renamed it to APP_LOCALE. It's clear what it means and I like that it's an easy, explicit selector. Don't want to get it confused with other files called locale.

2021-02-11 11:18 UTC, merged

2021-02-11 11:19 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/APP_TARGET.ts
> +export type ENLocale = typeof en;
I'm not 100% sure if we reached consensus on this, but in most other places were are camel-casing acronyms just like normal words. I personally believe it's the only way to stay consistent with types and instances. For example `jsonParser` for instance and `JsonParser` for type/class. Otherwise, what are you are going to call them. jSONParser and JSONParser? or jsonParser and JSONParser? It just easier to think of them as regular words.

```suggestion
export type NlLocale = typeof nl;
export type EnLocale = typeof en;
```

2021-02-11 11:35 UTC, VWSCoronaDashboard commented on packages/app/src/locale/APP_TARGET.ts
> +export type ENLocale = typeof en;
I would go for camelCasing too. It's much easier to read.