Add article strips to all appropriate pages
minvws/nl-covid19-data-dashboard pull request #1754
Opened 2021-02-01 17:53 UTC by VWSCoronaDashboard1

## Summary

This PR adds a component that displays a number of article teasers to the following pages:
- behavior
- deceased
- hospital
- intensive care
- positive tests
- reproduction
- sewerwater
- vaccinations

They are added to national, safety regions and municipalities where appropriate.

## Motivation

Feature request

## Detailed design

In the CMS the following schemas have been added:
- behaviorPage
- deceasedPage
- hospitalPage
- intensiveCarePage
- positiveTestsPage
- reproductionPage
- sewerPage
- vaccinationsPage

All of the schemas now just have one fields which is called 'articles', which is a list of references to an Article document.
Per page schema the maximum of references in the list differ though, so that's why the fields aren't shared.

These schemas will be added to in later stages I'm sure. When a specialized schema is needed for safety regions and/or municipalities these can be added later and the queries can be combined in the static props phase.

To show the article teasers on the pages the `ArticleStrip` component was added, which is a simple list of clickable images and article titles.

CMS-wise, the desk-structure.js file has been cleaned up a little to prevent a lot of code duplication while creating the menu structure.

## Drawbacks

n/a
## Alternatives

n/a

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-02-02 16:03 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/landelijk/sterfte.tsx
> +  }>(createPageArticlesQuery('deceasedPage'))
I have the feeling that the `createGetContent` is not very scalable, we might want to discuss this during FE meeting.

2021-02-02 16:11 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/landelijk/sterfte.tsx
> +  }>(createPageArticlesQuery('deceasedPage'))
To be honest, I think it's fine. If `createGetContent `simply makes sure the query gets executed, then we can build all sorts of logic that assembles this query. But, yes, it's a good subject for discussion.

2021-02-02 16:12 UTC, VWSCoronaDashboard1 commented on packages/app/src/components-styled/article-strip.tsx
> +type ArticleStripItemProps = {
Oh, I've been using types exclusively haha

2021-02-02 16:24 UTC, VWSCoronaDashboard1 commented on packages/app/src/components-styled/article-strip.tsx
> +const ArticleStripItem = function (props: ArticleStripItemProps) {
I blame lack of sleep ;)

2021-02-02 20:58 UTC, VWSCoronaDashboard8 approved these changes

2021-02-02 20:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/article-strip.tsx
> +    <Tile css={css({ bg: 'lightBlue' })}>
nit; if tiles commonly need background colors I think it makes sense to support it as a prop (by including that part of styled system).

2021-02-02 20:58 UTC, VWSCoronaDashboard8 commented on packages/cms/desk-structure.js
> +// we expose through other sections in the CMStructureBuilder.
Looks like some accidental find/replace

2021-02-03 08:11 UTC, VWSCoronaDashboard4 requested changes

2021-02-03 08:11 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/article-strip.tsx
> +            width={122}
This should not be needed. You can pass the `122` as second argument to `getImageProps` and get the proper width and height props back

2021-02-03 08:11 UTC, VWSCoronaDashboard4 commented on packages/cms/schemas/documents/pages/hospital-page.js
> +      title: 'Uitgelichte artikelen',
Wouldn't it make sense to create an object/type for this? Now these identical properties are copied over. If we want to adjust these articles, we can do it in 1 spot in the CMS and in 1 spot in the App.

2021-02-03 08:11 UTC, VWSCoronaDashboard4 commented on packages/cms/schemas/documents/pages/positive-tests-page.js
> +export default {
Is this the positive test page on NL, VR or GM level? Or all?

2021-02-03 08:29 UTC, VWSCoronaDashboard1 commented on packages/cms/schemas/documents/pages/hospital-page.js
> +      title: 'Uitgelichte artikelen',
As stated in the PR description: "Per schema, the maximum of references in the list differs though, so that's why the fields aren't shared."
Because this deals with just one field, I don't really see how putting just the one field in a shared field helps us at this point. The field itself isn't really much subject to change.
We should avoid anything like inheritance in the schema's, that's an anti-pattern and discouraged by Sanity themselves.

2021-02-03 08:30 UTC, VWSCoronaDashboard1 commented on packages/cms/schemas/documents/pages/hospital-page.js
> +      title: 'Uitgelichte artikelen',
I think right now it seems like a lot of duplication since all the pages only share the article selection, but I think in the future they will become very much different from each other and this approach will make more sense.
Anyway, let's have that meeting ;)

2021-02-03 08:42 UTC, VWSCoronaDashboard1 commented on packages/cms/schemas/documents/pages/positive-tests-page.js
> +export default {
"When a specialized schema is needed for safety regions and/or municipalities these can be added later and the queries can be combined in the static props phase." hehehe.
These are global, indeed.

2021-02-03 09:24 UTC, merged