Add highlight path on safety region on choropleth
minvws/nl-covid19-data-dashboard pull request #1765
Opened 2021-02-02 13:03 UTC by VWSCoronaDashboard14

The choropleth supports now a safety-region highlight code
Create separation of the `StyledPath` and `StyledHoverPath` to make it easier to style them.
Introduced also a `riskLevelStyling` boolean to have separate styling for a municipality or a risk level choropleth

2021-02-02 13:15 UTC, VWSCoronaDashboard1 reviewed
I think in a meeting about this it was suggested that perhaps the same effect could be attained by changing the stroke width of the region feature (making the underlying feature's stroke very wide and dark) and displaying the hover feature on top of it (with a narrower stroke and lighter color).

Was this solution researched and later discarded because it didn't work?

While the solution in this PR works, it does add another set of features to the map, making it heavier on the DOM. While the region map isn't that huge, should the same feature be required for the municipal map in the future, the solution would no longer be practical since that would add another 350 features to the map.

2021-02-02 13:21 UTC, VWSCoronaDashboard1 approved these changes

2021-02-02 13:21 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/choropleth/safety-region-choropleth.tsx
> +  highlightCode?: string;
nit, the prop for the selected feature is called 'selected', perhaps name this one 'highlighted'.

2021-02-02 13:53 UTC, VWSCoronaDashboard8 requested changes

2021-02-02 13:53 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/choropleth.tsx
> +  highightCallback?: (
Typo => install a spell checker?

2021-02-02 13:53 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/choropleth.tsx
> +              render={highightCallback}
If this is a render callback I suggest you give it a name that indicates that. We do it in other places too afaik. I `renderHighlight` for example. The fact that it is a callback is already inherent to the type function, so it's not so valuable to use the word callback in the name.

2021-02-02 13:53 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/path.tsx
> +  d,
`d` is not a good name for a variable, since it doesn't tell you anything. Maybe `pathData` or something...

2021-02-02 13:53 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/path.tsx
> +    stroke: 'x.stroke',
This looks like a mistake. And if you observed things working with this, it might be redundant?

2021-02-02 13:53 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/safety-region-choropleth.tsx
> +  highlightCode?: string;
👍  It would be also be nice to rename selected to `selectedCode` while you're at it, since "selected" is not a clear variable name.

2021-02-02 13:53 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/safety-region-choropleth.tsx
> +  const highightCallback = useCallback(
More typo

2021-02-02 13:53 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/safety-region-choropleth.tsx
> +    riskLevelStyling = false,
This name doesn't indicate that it's a boolean

2021-02-02 14:03 UTC, VWSCoronaDashboard10 commented
> I think in a meeting about this it was suggested that perhaps the same effect could be attained by **changing the stroke width of the region feature** (making the underlying feature's stroke very wide and dark) and displaying the hover feature on top of it (with a narrower stroke and lighter color).

I think this won't work because other adjacent layers could be rendered on top of the selected feature which would result in odd missing borders on some places.

> While the solution in this PR works, it does add another set of features to the map, making it heavier on the DOM. While the region map isn't that huge, should the same feature be required for the municipal map in the future, the solution would no longer be practical since that would add another 350 features to the map.

I think the impact on the DOM is minimal because the callback returns `null` for features that don't match the highlighted feature, or am I wrong?

2021-02-02 14:25 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/choropleth.tsx
> +              render={highightCallback}
I agree, but currently all render callbacks of the choropleth component are currently named like this. It can be fixed with this PR, but I think it's also fine to do this in another PR

2021-02-02 14:25 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/path.tsx
> +  d,
Ah yes I agree .. I initially named it `d` on the original Path component to mimic the SVG path element [`d`-attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d), but it's of course nice to have a readable prop :p

2021-02-02 14:25 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/path.tsx
> +    transitionTimingFunction: 'ease-out',
I guess these are obsolete now, they were previously meant for the `:hover` styles but those have been moved to the StyledHoverPath component.

2021-02-02 14:25 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/safety-region-choropleth.tsx
> +        </>
I think the `key`-props can be moved to the fragment
```suggestion
        <Fragment key={vrcode}>
          <Path
            d={path}
            stroke="#fff"
            strokeWidth={8}
          />
          <Path
            d={path}
            stroke="#000"
            strokeWidth={2}
          />
        </Fragment>
```

2021-02-02 14:25 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/index.tsx
> +                      riskLevelStyling={true}
It looks like the risk level styling should be applied on the choropleths with the metricName `escalation_levels`, so I think we should be able to remove this boolean prop and instead do something like this inside the SafetyRegionChoropleth  function body:

```tsx
const riskLevelStyling = metricName === 'escalation_levels'

// or maybe a better name:
const isEscalationLevelTheme = metricName === 'escalation_levels'

2021-02-03 08:22 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/choropleth/choropleth.tsx
> +              render={highightCallback}
I'll do it in another pull-request after this today, to keep things separate.

2021-02-03 10:14 UTC, VWSCoronaDashboard4 approved these changes

2021-02-03 10:24 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/index.tsx
> +                      riskLevelStyling={true}
@VWSCoronaDashboard14 what do you think of this suggestion?

2021-02-03 10:27 UTC, VWSCoronaDashboard14 commented on packages/app/src/pages/index.tsx
> +                      riskLevelStyling={true}
That was honestly pretty smart, I've already changed it but didn't resolve the conversation yet.

2021-02-03 10:40 UTC, merged