Strip unnecessary NPM properties from package jsons
minvws/nl-covid19-data-dashboard pull request #1807
Opened 2021-02-04 08:52 UTC by VWSCoronaDashboard8

## Summary

* Set all packages to private, because we don't intend to publish them to NPM
* Remove version info since it doesn't have a real meaning without publishing
* Remove different licenses and only keep one declaration in the root package

The versions were often overlooked when making a new release, and updating them is cumbersome and error prone. I believe we better omit them completely.

2021-02-04 09:00 UTC, VWSCoronaDashboard4 requested changes

2021-02-04 09:00 UTC, VWSCoronaDashboard4 commented on packages/app/package.json
> -  "version": "2.14.3",
We need to make sure this version is not read out, before we can remove it.

2021-02-04 09:00 UTC, VWSCoronaDashboard4 commented on packages/cms/package.json
> -  "license": "UNLICENSED",
Shouldn't the `EUROPEAN UNION PUBLIC LICENCE v. 1.2` be copied over to all packages?

2021-02-04 09:07 UTC, VWSCoronaDashboard8 commented on packages/cms/package.json
> -  "license": "UNLICENSED",
Since the packages are not published I think it doesn't have a value. We mention it in the root package.

2021-02-04 09:09 UTC, VWSCoronaDashboard8 commented on packages/app/package.json
> -  "version": "2.14.3",
I'm assuming it will turn up as undefined or an empty string. We'll find out soon enough 🤠 But I'll notify our chef pipeline.

2021-02-04 09:10 UTC, VWSCoronaDashboard1 approved these changes

2021-02-04 09:10 UTC, VWSCoronaDashboard1 commented on packages/app/package.json
> -  "version": "2.14.3",
I don't think it's being extracted anywhere. The tag is set manually, so I am pretty sure this version is here just for decoration.

2021-02-04 12:31 UTC, VWSCoronaDashboard10 commented
Build is failing: https://github.com/minvws/nl-covid19-data-dashboard/pull/1807/checks?check_run_id=1829268978

2021-02-05 12:45 UTC, VWSCoronaDashboard4 approved these changes

2021-02-05 12:52 UTC, merged