Add vaccine availability and estimates schemas
minvws/nl-covid19-data-dashboard pull request #1840
Opened 2021-02-05 14:42 UTC by VWSCoronaDashboard1

## Summary

As the title states

## Motivation

These schemas are meant to feed this chart:
![image](https://user-images.githubusercontent.com/69849293/107047874-996b5380-67c8-11eb-970b-47d1d1ae817e.png)

The four datapoints added to the national schema are indicated in the screenshot to show which part of the graph they'll feed.

## Detailed design

n/a

## Drawbacks

n/a

## Alternatives

n/a

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-02-05 15:08 UTC, VWSCoronaDashboard8 requested changes

2021-02-05 15:08 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/vaccine_administered.json
> +        "date_unix"
Just checking; so this data will be reported daily?

2021-02-05 15:08 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  vaccine_administered_estimate?: NlVaccineAdministeredEstimate;
Looks like you forgot to add these in the "required" list in __index

2021-02-05 15:08 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  total?: number;
In the previous chart we would calculate the total. It was a different kind of total because it was per vaccine company so it spanned multiple time series items. I guess having the total supplied by backend is a good things here. But I wonder then why is it considered optional? I suspect you forgot to add it to the required list...

2021-02-05 15:08 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  total?: number;
Same for this one

2021-02-05 15:08 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  total?: number;
etc

2021-02-05 15:08 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  total?: number;
etc

2021-02-05 15:09 UTC, VWSCoronaDashboard1 commented on packages/app/schema/nl/vaccine_administered.json
> +        "date_unix"
that's a good question actually, I forgot to check. Thanks!

2021-02-05 15:10 UTC, VWSCoronaDashboard1 commented on packages/common/src/types/data.ts
> +  total?: number;
Indeed, this is definitely Friday afternoon work... Sorry...

2021-02-05 15:15 UTC, VWSCoronaDashboard1 commented on packages/app/schema/nl/vaccine_administered.json
> +        "date_unix"
Yea, just check the example, its definitely a week span... Fixed!

2021-02-08 10:54 UTC, VWSCoronaDashboard8 approved these changes

2021-02-08 10:54 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/__index.json
> +    "vaccine_availability_estimate",
I avoided the term "availability" before because it can be interpreted in different ways. Is it current stock, (estimated) delivery or a combination of both? If it's a combination of both, I don't have a better name for it. But if it's one of the other two I would not use this name.

2021-02-08 11:04 UTC, VWSCoronaDashboard1 commented on packages/app/schema/nl/__index.json
> +    "vaccine_availability_estimate",
That's a good question, I'll try to find out which one it is because I don't have an answer for that currently.

2021-02-08 15:54 UTC, VWSCoronaDashboard1 commented on packages/app/schema/nl/__index.json
> +    "vaccine_availability_estimate",
After some digging we found out that this is indeed NOT the availability, but the *delivery* instead.
So, they have been renamed to vaccine_delivery and vaccine_delivery_estimate

2021-02-22 09:02 UTC, closed without merging