Adds schemas for escalation levels
minvws/nl-covid19-data-dashboard pull request #1841
Opened 2021-02-05 14:54 UTC by VWSCoronaDashboard4

## Summary

Adds schemas for escalation levels

2021-02-05 15:18 UTC, VWSCoronaDashboard10 commented on packages/app/schema/vr/__index.json
> +      "$ref": "hospital_escalation_level.json"
These two KPI's will be rendered on the 'positief-geteste-mensen'- and 'ziekenhuis-opnames' pages, so what would you think of defining them in the `tested_overall` and `hospital_nice` schema's?

The fields could be named something like `infected_per_100k_moving_average` and `infected_per_100k_moving_average`.

The new escalation level page can simply grab these schema's to render the KPI's on that page.

2021-02-05 15:37 UTC, VWSCoronaDashboard4 commented on packages/app/schema/vr/__index.json
> +      "$ref": "hospital_escalation_level.json"
That does not combine well. Those are daily updates, these are weekly.

2021-02-05 15:42 UTC, VWSCoronaDashboard4 commented on packages/app/schema/vr/__index.json
> +      "$ref": "hospital_escalation_level.json"
The `_100k` and `_unix` are always at the end, since they tell something about the format; see the schemas/readme file.

2021-02-05 15:55 UTC, VWSCoronaDashboard10 commented on packages/app/schema/vr/__index.json
> +      "$ref": "hospital_escalation_level.json"
Aren't they also daily updated, but with a moving weekly average?. And it could of course be named `infected_moving_average_per_100k` :-)

2021-02-08 09:15 UTC, VWSCoronaDashboard8 requested changes

2021-02-08 09:15 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr/__index.json
> +      "$ref": "hospital_escalation_level.json"
I think the fact that this data is used to display an escalation level is not neccesarily interesting from a data definition standpoint. I would prefer to describe _what_ the data is and not _how_ it is used, because that might change in the future.

Also we need to think carefully if we want to keep the shape of this data compatible with the value/values/timestamps of what we already have for normal timeseries or if this is something fundamentally different. For example

```
"date_unix",
        "escalation_level",
        "valid_from_unix",
        "date_of_insertion_unix"
```
This `valid_from_unix` is not a timestamp we have in other time series and I wonder what it means in relation to `date_unix`. Also of escalation-level data is different from normal time series (for example we will never display older values) then it might be warranted to diverge from the value/values format.

Whatever we choose, I think it needs to be a conscious decision. I suggest we'll have a chat about this with devs.

2021-02-08 12:37 UTC, VWSCoronaDashboard1 approved these changes

2021-02-08 13:10 UTC, VWSCoronaDashboard8 requested changes

2021-02-08 13:10 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr/__index.json
> +    "tested_weekly",
Also, what type of "tested" is this? Might be worth using `tested_overall` or `tested_ggd` as a prefix, depending on the context. So then it could be `tested_overall_average` if it is about all reported tests including ggd.

2021-02-08 13:10 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr/escalation_level.json
> +        "escalation_level",
The context is already "escalation_level" so maybe just call this "level" to avoid confusion. I know this shape is the same as vr_collection.escalation_levels so I get why you might want to use that. But then again the metric property names don't fully match either.

2021-02-08 13:10 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr/hospital_weekly.json
> +        "admissions_per_1m": { "type": "integer" },
Are you sure this will not be a decimal value? Per 1M sounds like it might be a float

2021-02-08 13:59 UTC, VWSCoronaDashboard4 commented on packages/app/schema/vr/escalation_level.json
> +          "maximum": 4
This is not related to the metrics; this is just the escalation level (copied from the choropleth json to the VR json).

2021-02-08 13:59 UTC, VWSCoronaDashboard4 commented on packages/app/schema/vr/hospital_weekly.json
> +        "admissions_per_1m": { "type": "integer" },
Yes, this should be an integer.

2021-02-08 14:43 UTC, VWSCoronaDashboard8 approved these changes

2021-02-17 08:22 UTC, merged