Add CoronaMelder in compliance and support page
minvws/nl-covid19-data-dashboard pull request #1855
Opened 2021-02-08 13:18 UTC by VWSCoronaDashboard14

Merged the scheme from this [pull request](https://github.com/minvws/nl-covid19-data-dashboard/pull/1440) and added the CoronaMelder in the page.

2021-02-08 14:36 UTC, VWSCoronaDashboard4 commented on packages/app/src/pages/landelijk/gedrag.tsx
> +                  <Anchor>{corona_app.rapport.link.text}</Anchor>
This is now a `a` in an `a`?

2021-02-08 14:36 UTC, VWSCoronaDashboard4 commented on packages/app/src/pages/landelijk/gedrag.tsx
> +                  '& > span': { color: 'data.primary', fontWeight: 'bold' },
Maybe `replaceKpisInText` should be adjusted to work better with styled components; it now accepts a `className` property in the objects in the array you provide.

You can also opt to use `replaceComponentsInText`.

2021-02-08 14:36 UTC, VWSCoronaDashboard4 commented on packages/app/src/pages/landelijk/gedrag.tsx
> +              <IconContainer>
Or use the `LinkWithIcon` component?

2021-02-09 10:17 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/landelijk/gedrag.tsx
> +    width: '25px',
```suggestion
    height: 25,
    width: 25,
```

or maybe even this will work with styled-system:
```suggestion
    size: 25,
```

2021-02-09 11:13 UTC, VWSCoronaDashboard14 commented on packages/app/schema/nl/corona_app.json
> +        "downloaded_total": {
In the written text they referring to total downloads, so I assume it is that.

2021-02-10 10:28 UTC, VWSCoronaDashboard8 approved these changes

2021-02-10 10:28 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/en.json
> +      "description": "Introductietekst die aangeeft........",
I think we choose to use Dutch names for lokalize keys, but it's probably already mixed up in a lot of places so I don't think it matters much anymore.

2021-02-10 10:28 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/gedrag.tsx
> +  const { behavior } = data;
nit; I think for the code readability it makes more sense to create a `behaviorLastValue` constant, and then use data.behavior.values directly.

2021-02-17 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/en.json
> +    "waarschuwen": {
It seems weird to have a verb as a key. Should this be "waarschuwingen" maybe?

2021-02-17 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/nl.json
> +    "waarschuwen": {
Same here

2021-02-17 09:37 UTC, VWSCoronaDashboard8 requested changes

2021-02-17 09:37 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/gedrag.tsx
> +              start: behaviorLastValue.last_value.date_start_unix,
This seems wrong. `behaviorLastValue.last_value` then the first is not the lastValue

2021-02-17 10:06 UTC, VWSCoronaDashboard8 approved these changes

2021-02-17 10:22 UTC, merged