Add schema for vaccine KPI tiles
minvws/nl-covid19-data-dashboard pull request #1869
Opened 2021-02-09 10:59 UTC by VWSCoronaDashboard14

Add schema for vaccine KPI tiles for the calculated and reported doses.

2021-02-10 10:36 UTC, VWSCoronaDashboard8 requested changes

2021-02-10 10:36 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/__index.json
> +    "vaccine_dose"
This name is not clear to me. vaccine_dose could also be interpreted as vaccine_delivery since that is also about doses. And we already have schema's for vaccine_administered in this branch so I think this PR conflicts with that work.

https://github.com/minvws/nl-covid19-data-dashboard/pull/1840/files

2021-02-10 10:36 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/vaccine_dose.json
> +        },
calculated is not a clear term to me. Is it an estimate? 

Then I would suggest something like `estimate_total`, `estimate_ggd` etc.

2021-02-10 10:36 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/vaccine_dose.json
> +        "reported": {
If this is a total then I suggest to add the _total suffix for clarity.

2021-02-10 13:54 UTC, VWSCoronaDashboard8 requested changes

2021-02-10 13:54 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/vaccine_administered_per_authority.json
> +        }
I'm missing date timestamps here. The format is values/last_value so even though they are displayed in KPI tiles, I would expect data to be timestamped. Use date_start/end if data is spanning multiple days.

2021-02-12 10:08 UTC, VWSCoronaDashboard8 approved these changes

2021-02-12 10:08 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/vaccine_administered_total.json
> +        },
The context is already `_administered_total` so the total suffix is redundant here.

2021-02-12 10:08 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/__index.json
> +    "vaccine_administered_total"
Ooof I didn't realize the split approach was going to add this many schema's  👀  Now I feel things would have been better grouped by reporting source with possible null values to fill blanks. But whatever, I think we probably have more important things to focus on.

2021-02-16 16:20 UTC, VWSCoronaDashboard8 approved these changes

2021-02-16 16:31 UTC, 0x80 approved these changes

2021-02-16 16:31 UTC, 0x80 commented on packages/app/schema/nl/__index.json
> +    "vaccine_administered_general_practitioner",
We call this doctor for simplicity in other schema's. It's technically not the right word, but most people still refer to it by "doctor". And since you made the others plural I'd suggest using `_doctors`

2021-02-16 16:31 UTC, 0x80 commented on packages/app/schema/nl/vaccine_administered_general_practitioner.json
> +{
Same for these files / names of course.

2021-02-17 15:42 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/topical/topical-vaccine-tile.tsx
> +  // };
comment

2021-02-17 15:42 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/topical/topical-vaccine-tile.tsx
> +      </Text> */}
I think this can go?

2021-02-17 15:44 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/index.tsx
> +              />
nit; I think any number is usually about an amount, so it doesn't add much value to have that in the name.

2021-02-17 15:46 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +                      amount={
nit; Maybe call this `value` instead. It's a little more generic.

2021-02-17 15:48 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +  text: string;
Maybe you can be more specific about what type of text this is. Is it a description for example?

2021-02-19 09:34 UTC, merged