Add dynamic hidden accessibility text for metadata sources
minvws/nl-covid19-data-dashboard pull request #1884
Opened 2021-02-10 12:26 UTC by VWSCoronaDashboard14

Add accessibility text for screenreaders on the metadata links in tiles and content-headers.
It takes the title and adds before the link a hidden text that yields what the link contains.

The only drawback is that some titles are called "Verloop over tijd" which could be a little confusing.
I'm not sure the titles should be more descriptive and I need to take a second look and add the for example also the current page. Would love to know your opinion.

Tested it with Voiceover from Apple:
<img width="648" alt="Screenshot 2021-02-10 at 13 25 47" src="https://user-images.githubusercontent.com/76471292/107509953-934bed00-6ba3-11eb-9463-27037c99325e.png">

2021-02-10 13:05 UTC, VWSCoronaDashboard4 approved these changes

2021-02-10 13:46 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/chart-tile-container.tsx
> +  title: string;
wouldn't `subject` make more sense? We're giving it the title, but it's somehow the subject of what the link is about.

2021-02-10 13:46 UTC, VWSCoronaDashboard10 commented on packages/app/src/locale/nl.json
> +    "link_download": "Download de databron van \"{{title}}\" op",
For flexibility I think it's good to also make the source part of this string:

`"Bekijk de databron van \"{{subject}}\" op {{source}}"`

2021-02-10 17:43 UTC, VWSCoronaDashboard8 requested changes

2021-02-10 17:43 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/chart-tile-container.tsx
> +  title: string;
I agree that in this context subject might be more fitting. Of even something specific like screenReaderSubject if all we're going to be using this data for is the extra feature for screen readers. If this is passed as title you would expect it to be rendered as some sort of title.

In the case of ChartTileContainer it is not so bad, because in the parent tile the text is still used as a title, but later on you are passing it as "title" to Metadata, and that is really confusing because metadata doesn't have the concept of a title.

2021-02-10 17:43 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/chart-tile-container.tsx
> +          <Metadata {...metadata} title={title} />
...so here we should really find a better name.

2021-02-10 17:43 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/chart-tile-container.tsx
> +          <Metadata {...metadata} title={title} />
Also it looks like you are just passing title to ChartTileContainer to then pass it on the Metadata, but the props for metadata are already passed on. So I think you should be able to set the "title" data directly on the metadata prop.

2021-02-10 17:43 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/chart-tile.tsx
> +    <ChartTileContainer metadata={metadata} title={title}>
☝️ ...here is what I mean. If you inject the "title" (under a better name) in metadata, when it is passed on automatically to the internal metadata component.

2021-02-10 17:43 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/chart-tile-container.tsx
> +  title: string;
Maybe `accessibilitySubject` is also an option, since eventually the data ends up in `accessibilityText`

2021-02-10 17:43 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/content-header/metadata.tsx
> +  accessibilityText: string;
I wouldn't mind shortening with a11y, since accessibility is such an annoying word to write 😅

2021-02-11 10:00 UTC, VWSCoronaDashboard14 commented on packages/app/src/locale/nl.json
> +    "link_download": "Download de databron van \"{{title}}\" op",
We are using the source to display it on the screen. If I would do this it would read twice the source, or I need to disable the displayed one by wrapping it and add a `aria-hidden="true" ` not a fan of that.

2021-02-11 10:28 UTC, VWSCoronaDashboard8 approved these changes

2021-02-11 10:28 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/content-header/metadata.tsx
> +          { accessibilitySubject, source: 'test' }
nit;
```suggestion
          { subject: accessibilitySubject, source: 'test' }
```
Because within the context of lokalize I don't think it has value to have this variable name spelled out with accessibility. Subject is clear enough in that text.

2021-02-11 12:47 UTC, VWSCoronaDashboard8 approved these changes

2021-02-11 14:31 UTC, VWSCoronaDashboard7 commented
> The only drawback is that some titles are called "Verloop over tijd" which could be a little confusing. I'm not sure the titles should be more descriptive or I need to take a second look and add for example the current page. Would love to know your opinion.


The graphs should not be titled "Verloop over tijd" but the editorial team should make them more descriptive as far as I'm concerned. The title should stand on its own and not rely on other parts of the page to make sense. Also for accessibility reasons.

2021-02-11 15:12 UTC, merged