chore: Stop forwarding styled component props to dom elements in base components
minvws/nl-covid19-data-dashboard pull request #1929
Opened 2021-02-15 16:47 UTC by VWSCoronaDashboard13

## Summary

Uses the `shouldForwardProps` config provided by emotion to stop forwarding styled component props to dom elements when using "base" components.

## Motivation

Declutter dom elements. Styled component props won't be uselessly "forwarded" to the base elements; they'll just be applied via the classname. 

## Detailed design

Added `shouldForwardProps` config to exported reusable styled components that resided in their own file. This means this only applies to components that are built from these "base" components. 

```export const Box = styled.div.withConfig({
  shouldForwardProp: shouldForwardProp as any,
})<BoxProps>(```

Seems that there is a type mismatch somewhere, so the `shouldForwardProp` is assigned a type of `any` to bypass typescript errors. This isn't ideal, but I think the benefit outweighs the discomfort in this situation 😬

2021-02-15 17:05 UTC, VWSCoronaDashboard8 approved these changes

2021-02-16 07:08 UTC, VWSCoronaDashboard8 requested changes

2021-02-16 07:08 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/table.ts
> +import { StyledShouldForwardProp } from '~/utils/styledShouldForwardProp';
We write all file names in kebab-case. Also it seems like you are exporting the function starting with a capital letter as if it was a type, but it is used as a value here. So I think this should be 

```suggestion
import { styledShouldForwardProp } from '~/utils/styled-should-forward-prop';
```

2021-02-16 07:13 UTC, VWSCoronaDashboard8 commented on packages/app/src/utils/styledShouldForwardProp.ts
> +export const StyledShouldForwardProp = shouldForwardProp as StyledShouldForwardPropType;
What you are exporting is a (typed) value, not a type itself.

```suggestion
export const styledShouldForwardProp = shouldForwardProp as StyledShouldForwardPropType;
```

2021-02-16 07:13 UTC, VWSCoronaDashboard8 commented on packages/app/src/utils/styledShouldForwardProp.ts
> +type StyledShouldForwardPropType = (prop: string | number) => boolean;
Once you rename the exported function, this doesn't need the Type suffix. 

```suggestion
type StyledShouldForwardProp = (prop: string | number) => boolean;
```

2021-02-16 08:13 UTC, VWSCoronaDashboard13 commented on packages/app/src/components-styled/table.ts
> +import { StyledShouldForwardProp } from '~/utils/styledShouldForwardProp';
right, this makes sense. I just glanced a the other util files so I missed that there was a mix of casings. The requested updates have been made 👍

2021-02-16 08:14 UTC, VWSCoronaDashboard1 approved these changes

2021-02-16 08:16 UTC, VWSCoronaDashboard1 commented
The changes seem fine to me, but there are still a bunch of compile errors happening. So, run `yarn compile` in the project root and have a look at what's going wroing.

2021-02-16 08:27 UTC, VWSCoronaDashboard13 commented
> The changes seem fine to me, but there are still a bunch of compile errors happening. So, run `yarn compile` in the project root and have a look at what's going wroing.

Yeah, it looks like defining the StyledShouldForwardProp type is causing the compilation errors. I have a feeling trying to fix this probably isn't worth the effort and it would make sense to revert to casting to any?

2021-02-16 08:51 UTC, VWSCoronaDashboard1 commented
> > The changes seem fine to me, but there are still a bunch of compile errors happening. So, run `yarn compile` in the project root and have a look at what's going wroing.
> 
> Yeah, it looks like defining the StyledShouldForwardProp type is causing the compilation errors. I have a feeling trying to fix this probably isn't worth the effort and it would make sense to revert to casting to any?

if all else fails ;)

2021-02-16 09:26 UTC, VWSCoronaDashboard8 approved these changes

2021-02-16 09:52 UTC, merged