Update choropleth tooltips, reproduction svg and choropleth hover stroke
minvws/nl-covid19-data-dashboard pull request #1968
Opened 2021-02-17 14:39 UTC by VWSCoronaDashboard14

Add a subject to a tooltip on the choropleths
Added a marker left from the heading
Made the hover stroke white and added a bit more width
Updated the reproduction svg

**Example:**
<img width="293" alt="Screenshot 2021-02-17 at 15 37 55" src="https://user-images.githubusercontent.com/76471292/108219555-23ef7380-7136-11eb-8fcd-cd4e975cebf7.png">

2021-02-17 15:32 UTC, VWSCoronaDashboard1 approved these changes

2021-02-18 09:49 UTC, VWSCoronaDashboard approved these changes

2021-02-18 10:08 UTC, VWSCoronaDashboard8 approved these changes
I'm going to approve this, but there's lots of repetition in the code, so ideally this should be made DRY by using abstraction and reusable components.

2021-02-18 10:08 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/region/create-disability-infected-locations-regional-tooltip.tsx
> +    .slice(-1)[0];
After seeing this pattern /similar code repeated a third time I'm thinking it's time to create a function/abstraction for this. 

Something like: `getFilteredThresholdValues<T>(thresholdValues: T, filterBelow: number)`

2021-02-18 10:08 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/region/create-positive-tested-people-regional-tooltip.tsx
> +        />
This styling is also being repeated many times. I believe this warrants the creation of some simple reusable components, since this is currently far from DRY.

2021-02-19 11:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/tooltips/municipal/create-municipal-hospital-admissions-tooltip.tsx
> +        <span css={css({ fontWeight: 'bold' })}>
`<InlineText  fontWeight='bold'>`

2021-02-19 11:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/tooltips/municipal/create-positive-tested-people-municipal-tooltip.tsx
> +        <span css={css({ fontWeight: 'bold' })}>
same. here

2021-02-19 11:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/tooltips/region/create-disability-infected-locations-regional-tooltip.tsx
> +        <span css={css({ fontWeight: 'bold' })}>
and so on

2021-02-19 11:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/tooltips/region/create-sewer-regional-tooltip.tsx
> +        <Text m={0} mt={-1}>
a negative topmargin sounds like something is wrong with the layout .. has, by any chance, the tooltipSubject outside margins? Can't those be removed instead? (this is a prime example of why I'm not fond of outside margins)

2021-02-19 11:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/locale/nl.json
> +    "inwoners": "inwoners",
duplicate key, didn't TS/linter complain? (see the bottom of this block, line 648) Also: can't we use the `common.inwoners` instead of adding the `choropleth_tooltip.inhabitants` key?

2021-02-19 11:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/locale/nl.json
> +    "inhabitants": "inwoners",
this one I mean

2021-02-19 11:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/utils/getFilteredThresholdValues.ts
> +// by filtering out all the higher thresholds and then using the last key that still exists.
We ususally write comment blocks with the /** */ syntax
```suggestion
/**
 * Get all the thresholds and filter out the right color that needs to be rendered in the rectangle,
 * by filtering out all the higher thresholds and then using the last key that still exists.
 */
```

2021-02-19 11:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/utils/getFilteredThresholdValues.ts
> +    .slice(-1)[0];
might want to add a comment about what `slice(-1)[0]` does

2021-02-19 17:09 UTC, VWSCoronaDashboard8 requested changes

2021-02-19 17:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/region/create-positive-tested-people-regional-tooltip.tsx
> +        <span css={css({ fontWeight: 'bold' })}>
Same thing here with InlineText

2021-02-19 17:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/region/create-region-elderly-at-home-tooltip.tsx
> +          {formatNumber(100_000)}{' '}
I think this is easier readable if you format it in a single backtick string

2021-02-19 17:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/region/create-region-elderly-at-home-tooltip.tsx
> +        <span css={css({ fontWeight: 'bold' })}>
Inline text fontWeight

2021-02-19 17:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/region/create-region-hospital-admissions-tooltip.tsx
> +          <span css={css({ fontWeight: 'bold' })}>
etc...

2021-02-19 17:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/region/create-sewer-regional-tooltip.tsx
> +            })}`}
```suggestion
            {replaceVariablesInText(text.map_tooltip_value, {
              value: formatNumber(context.average),
            }}
```

2021-02-19 17:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/tooltipContent.tsx
> +const StyledTooltipContent = styled.div((x: any) =>
You should define the props/interface than you don't need any

```suggestion
const StyledTooltipContent = styled.div<{onClick?: ()=>void}>((x) =>
```

2021-02-19 17:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/tooltipSubject.tsx
> +}
Yes 🕺 so much better than before 👍

2021-02-19 17:09 UTC, VWSCoronaDashboard8 approved these changes

2021-02-19 17:11 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/choropleth/tooltips/tooltipContent.tsx
> +const StyledTooltipContent = styled.div((x: any) =>
Or even better do not pass the click handler to this component, as it doesn't care. Instead pass in a boolean or something `hasClickHandler` that you derive from it

2021-02-22 09:53 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/choropleth/tooltips/tooltipSubject.tsx
> +}
🎊

2021-02-22 10:00 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/tooltips/tooltipContent.tsx
> +const StyledTooltipContent = styled.div((x: any) =>
I'm wondering why the initial change from `styled.div((x) =>` to `styled.div((x; any) =>` was necessary at all, I'd think that `x` would infer the type coming from styled components (including the `onClick` type).

2021-02-22 10:01 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/choropleth/tooltips/tooltipSubject.tsx
> +import { ChoroplethThresholdsValue } from '@corona-dashboard/common';
we write filenames kebab-case: `tooltip-subject.tsx`

2021-02-24 08:16 UTC, merged