ci: Static site generation
minvws/nl-covid19-data-dashboard pull request #197
Opened 2020-08-28 11:28 UTC by VWSCoronaDashboard

## Summary

This PR showcases how we can use Next.js' getStaticProps to build our pages statically. 

## Motivation

This will increase (perceived) performance and reduce layout shifting. It also allows us to remove SWR from the packages as data will not have to be fetched client-side or invalidated.

## Detailed design

We use [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation). We are dependent on the pipeline to include the jsons on build-time to do this.

Ideally we run the schema validators on the JSONS before starting the build.

## Drawbacks

The only issue is that you have to rebuild your docker image whenever data updates, but this happens at most a couple of times a day. It's no real concern.

## Unresolved questions

Need to figure out how to apply types to this pattern.

2020-08-28 12:46 UTC, VWSCoronaDashboard1 requested changes

2020-08-28 12:46 UTC, VWSCoronaDashboard1 commented on src/pages/landelijk/besmettelijke-mensen.tsx
> +const InfectiousPeople: FCWithLayout = ({ data }) => {
```
interface IProps {
  data: National;
}

const InfectiousPeople: FCWithLayout<IProps> = ({ data }) => {
```

2020-08-28 12:46 UTC, VWSCoronaDashboard1 commented on src/pages/landelijk/besmettelijke-mensen.tsx
> +export const getStaticProps: GetStaticProps = async () => {
`export const getStaticProps: GetStaticProps<IProps> = async () => {`

2020-08-28 12:46 UTC, VWSCoronaDashboard1 commented on src/pages/landelijk/besmettelijke-mensen.tsx
> +  const jsonDirectory = path.join(process.cwd(), 'public/json');
path.join() takes any number of arguments. So this would work too:

`path.join(process.cwd(), 'public', 'json', 'NL.json');`

It would also ensure cross-platform path delimiters

2020-08-28 13:05 UTC, VWSCoronaDashboard1 approved these changes

2020-09-01 21:49 UTC, VWSCoronaDashboard commented on src/components/layout/NationalLayout.tsx
> +}
This type should be required for all pages that use <NationalLayout>. Did I implement that correctly?

2020-09-01 21:50 UTC, VWSCoronaDashboard commented on src/components/layout/index.tsx
> +  getLayout: (page: React.ReactNode, pageProps: any) => React.ReactNode;
In theory this can be any, but on NationalLayout it should always be this one:

```ts
interface PageProps {
  pageProps: {
    data: National;
  };
}
```

not sure how do type that out.

2020-09-01 21:51 UTC, VWSCoronaDashboard commented on src/components/tiles/regio/IntakeHospital.tsx
> +  data?: Regionaal;
The region page wrongly assumed that data can not be undefined. If data is undefined, it shows a loading state.

2020-09-01 21:51 UTC, VWSCoronaDashboard commented on src/pages/_app.tsx
> +      {getLayout(<Component {...pageProps} />, pageProps)}
This is the magic to get the data from getStaticProps in persistent layouts.

2020-09-01 21:54 UTC, VWSCoronaDashboard commented on src/pages/landelijk/besmettelijke-mensen.tsx
> +  return getNlData();
I'm amazed that this works, but it works! This keeps it semi-dry.

2020-09-01 21:56 UTC, VWSCoronaDashboard commented on src/pages/regio/[region].tsx
> +import fs from 'fs';
This whole file is basically a duplicate of `src/pages/regio/index.tsx` before I reduced it (the index file) to a simpler version that's an empty state with a search bar.

2020-09-01 21:56 UTC, VWSCoronaDashboard commented on src/pages/regio/[region].tsx
> +  };
This has changed to support dynamic routes instead of slugs. We might want to add redirects to the app for people who bookmarked the pages with query parameters?

2020-09-01 21:57 UTC, VWSCoronaDashboard commented on src/pages/regio/[region].tsx
> +  useEffect(focusFirstHeading, [data]);
This still works, even when it's as short as it is right now. It basically fires on page load.

2020-09-01 21:58 UTC, VWSCoronaDashboard commented on src/pages/regio/[region].tsx
> +  };
I still need to solve a bug where resetting the searchbar (which returns undefined) triggers a replace() but we should ignore that value.

2020-09-02 06:50 UTC, VWSCoronaDashboard1 commented on src/components/layout/NationalLayout.tsx
> +}
If it needs to be used by other pages, then definitely export the interface otherwise it can't be found.

2020-09-02 07:06 UTC, VWSCoronaDashboard1 approved these changes

2020-09-02 07:06 UTC, VWSCoronaDashboard1 commented on src/pages/_app.tsx
> +      {getLayout(<Component {...pageProps} />, pageProps)}
Just for completeness, I'd type the Component prop to FCWithLayout in the IProps interface on this page

2020-09-02 07:06 UTC, VWSCoronaDashboard1 commented on src/static-props/nl-data.ts
> +interface IProps {
```suggestion
export interface IProps {
```

2020-09-02 08:06 UTC, VWSCoronaDashboard3 requested changes
Overall looking good! But I have some concerns.

---

> I've changed the routing of the region pages

Please refrain from doing this. This is outside of the scope of this ticket and we are currently completely rebuilding /regio.

> No de-duping of data

This is indeed a big drawback. I’m sure webpack is smart enough to de-dupe imports. Are we sure this is the right approach over `import`?

> 

> I'm using fs and path because the official docs show that. I see we use require in other parts of the codebase to load JSON files in getStaticProps. Are there obvious downsides or upsides to either approach? Using require sounds simpler to me. I don't mind rewriting that logic to require if there's no downsides.

AFAIK, there are no downsides to `require`. Both fix directory slashes for different operating systems

> Do we want to keep SWR?

I don’t think we need it anymore.

2020-09-02 08:43 UTC, VWSCoronaDashboard commented
> Please refrain from doing this. This is outside of the scope of this ticket and we are currently completely rebuilding /regio.

This is unfortunately unavoidable if we want static pages. We can choose to wait with this improvement until things are more stable in the next release before committing to such a change?

> This is indeed a big drawback. I’m sure webpack is smart enough to de-dupe imports. Are we sure this is the right approach over import?

I have my doubts too :)

2020-09-07 14:42 UTC, closed without merging