Feature/gemeentes
minvws/nl-covid19-data-dashboard pull request #198
Opened 2020-08-28 13:35 UTC by VWSCoronaDashboard4

## Summary & Motivation

Adds data for municipalities to the region page.

## Detailed design

* A new map is added, it plots data based on the municipalities' geodata.
* A new mapping between municipalities / gemcode / vrcode is added to aid the select box.
* The region page is adjusted to toggle between Municipality / Safety region
* Extra (mostly duplicate, structure wise) tiles added
* Sewer tile for municipalities is adjusted to properly support zero, one or more RWZI locations.
* The select municipality component is adjusted to support two structures

2020-08-28 14:30 UTC, VWSCoronaDashboard1 requested changes

2020-08-28 14:30 UTC, VWSCoronaDashboard1 commented on src/components/mapChart/municipality.tsx
> +    <Fragment></Fragment>
You can just return null here, no need for an empty Fragment

2020-08-28 14:30 UTC, VWSCoronaDashboard1 commented on src/components/tiles/municipality/IntakeHospital.tsx
> +export const IntakeHospitalMunicipality: React.FC<IProps> = (props) => {
I think we've been moving away from using the React.FC interface in favor of just a function with a typed param.
I.e. function IntakeHospitalMunicipality(props: IProps)

2020-08-28 14:30 UTC, VWSCoronaDashboard1 commented on src/components/selectMunicipality/index.tsx
> +          regionType === 'safetyRegion' &&
I see a lot of conditional rendering in this component. Would it be a cleaner solution to perhaps split this up into two smaller components?

2020-08-28 14:30 UTC, VWSCoronaDashboard1 commented on src/components/tiles/municipality/IntakeHospital.tsx
> +          <>
This seems to have quite a bit of conditional rendering as well. Perhaps also a candidate to split up into smaller pieces?

2020-08-28 14:30 UTC, VWSCoronaDashboard1 commented on src/components/tiles/municipality/PositivelyTestedPeople.tsx
> +          <>
And another one that can perhaps be split up into smaller components.

2020-08-28 14:30 UTC, VWSCoronaDashboard1 commented on src/components/tiles/municipality/SewerWater.tsx
> +  }
This code could probably be refactored into a hook, and perhaps could use some useMemo() since there's quite a bit of data massaging going on

2020-08-28 14:30 UTC, VWSCoronaDashboard1 commented on src/pages/index.tsx
> +          }
Wasn't the parseInt logic added to the LastUpdated component, therefore data?.last_generated can just be set as the prop value?

2020-08-28 15:00 UTC, VWSCoronaDashboard4 commented on src/components/tiles/municipality/IntakeHospital.tsx
> +          <>
The intake hospital file is structurally equal to the one for safety regions. Optimizing it would be better suited for a separate task/PR.

2020-08-28 15:01 UTC, VWSCoronaDashboard4 commented on src/components/tiles/municipality/PositivelyTestedPeople.tsx
> +          <>
Same here; The positively tested people file is structurally equal to the one for safety regions. Optimizing it would be better suited for a separate task/PR.

2020-08-31 09:01 UTC, VWSCoronaDashboard3 requested changes

2020-08-31 11:43 UTC, merged