Remove margin-top and on paragraph elements
minvws/nl-covid19-data-dashboard pull request #2066
Opened 2021-02-23 15:21 UTC by VWSCoronaDashboard14

Globally remove all the margin-top from the paragraph tag, went through **all** the pages to spot some difference in the layout compared to the live version. Numerous small changes that were relying on the margin-top from the paragraph tag.

2021-02-23 15:30 UTC, VWSCoronaDashboard4 requested changes

2021-02-23 15:30 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/kpi-tile.tsx
> +          as="p"
I don't think this is right. Markdown will output `<p>` 's as well, so you'll get p's in p's.

2021-02-24 09:26 UTC, VWSCoronaDashboard10 commented on packages/app/src/style/global-style.tsx
> +}
I'd say that it can be applied to all elements (`*`), though not sure what others think of that..

2021-02-24 16:01 UTC, VWSCoronaDashboard8 approved these changes
You are setting a margin-bottom on a lof of components internally. While using margin-bottom is better then using margin-top, it is still bad practice to include an outside margin setting on a reusable component. 

The parent context should take care of spacing different elements. 

I'm going to approve this, but I feel in some instances you have moved the problem to a different location instead of making a structural fix.

2021-02-24 16:03 UTC, VWSCoronaDashboard8 commented on packages/app/src/style/global-style.tsx
> +}
I would be ok with that but let's not blow up the scope of this PR. I already feel that some instances here are just moving the problem, because of setting an outside margin on what should be a reusable component.

2021-03-02 08:58 UTC, VWSCoronaDashboard4 approved these changes

2021-03-02 09:13 UTC, merged