Add milestone vaccine page
minvws/nl-covid19-data-dashboard pull request #2090
Opened 2021-02-25 12:27 UTC by VWSCoronaDashboard14

Add milestones to vaccine 
WIP

2021-02-25 16:41 UTC, VWSCoronaDashboard4 reviewed
Some nitpicks :-)

Maybe some of the logic could be tidied up (in a different PR), but for now it's fine

2021-02-25 16:41 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/vaccine/milestones.tsx
> +interface MileProp {
```suggestion
interface MileProps {
```

2021-02-25 16:41 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/vaccine/milestones.tsx
> +interface ExpectProp {
```suggestion
interface ExpectProps {
```

2021-02-25 16:41 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    '&:hover': {
also add a `:focus` style

2021-02-25 16:41 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    backgroundColor: x.isLast ? '#fff' : 'header',
nit: there is a named color `white` in the theme too

2021-02-25 16:41 UTC, VWSCoronaDashboard4 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +    milestones: any;
`any`

2021-02-25 16:41 UTC, VWSCoronaDashboard4 commented on packages/app/src/queries/vaccine-page-query.ts
> +      "description": description.${targetLanguage},
nit: the indenting is a bit wonky here

2021-02-25 16:41 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/vaccine/milestones.tsx
> +  const [isExpanded, setIsExpanded] = useState(false);
perhaps have it expanded by default, and then with `useEffect` set it to false? that way with JS turned off all content is accessibile

2021-02-26 09:27 UTC, VWSCoronaDashboard10 approved these changes

2021-02-26 09:27 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    mb: 3,
You can remove this bottom margin and instead wrap all `UnorderedLists` in a Box component with the spacing prop.

The advantage is that there won't be any outside margin (currently the case due to your last list with bottom margin) and that it's not necessary to manually set margins on other components like the `Text` inbetween the lists.

2021-02-26 09:27 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    backgroundColor: x.isLast ? '#fff' : 'header',
nit on the nit: there's no color named `white` in our theme. Instead it will simply use the color-value 'white', just like it would work with `hotpink` ;-)

2021-02-26 09:27 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/objects/milestone.ts
> +      const {title, date} = selection
Do you happen to know the types of `title` and `date`? If so, can you please type them?
```suggestion
    prepare(selection: { title: string; date: ??? }) {
      const {title, date} = selection
```

2021-02-26 09:27 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +      "highlight": ${createPageArticlesQuery('vaccinationsPage')}
nice!

2021-02-26 09:35 UTC, VWSCoronaDashboard8 requested changes

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +interface MileProp {
MileProp?

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +interface ExpectProp {
"Conversation marked as resolved" maar ik zie nog geen code wijziging

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +interface MileStoneProps {
Milestone is 1 woord in het engels. Ik zou het component `MilestonesView` ofzo noemen, zodat je een `milestones` data field kunt hebben, want `mile` vind ik niet geschikt als naam.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +  expected: ExpectProp[];
Dit zijn geen props naar types die onderdeel zijn van je component props. Ze moeten dus geen Prop suffix hebben.  `mile` en `expect` vind ik geen geschikte namen. Een mile is iets anders, en expected is te vaag.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +  }
This wrapping function doesn't really serve a purpose and only obfuscates the code. You can use `() => setIsExpanded(true)` directly.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +      <Box maxWidth="maxWidthText" mb={2}>
maxWidth is set to a string here

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +      <UnorderedList>
No need to call this `UnorderedList` unless you have an `OrderedList` component in the same context and it has a meaning to the code. You can just call this `List` I think.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +        <ListItem isFirst={true}>
I think you should be able to target the first list item through normal CSS of the UnorderedList parent component.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +          <ListItemButton>
ListItemButton doesn't seem to be a button. It doesn't have a click handler and its children contain an actual button, so the name is confusing.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +                  {index !== miles.length - 1 ? (
You are repeating the same check 4 times here `index !== miles.length - 1 `.

Create a variable isLast so you only need to do it once. 

Also the property isLast on the individual components doesn't tell anything about what it does. Maybe you can name it after the effect it has on each of the components

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +                        {formatDate(new Date(mile.date))}
if mile.date is not a Date don't call it that. If it is a unix timestamp in milliseconds I'd prefer `date_ms`. If it comes directly from the backend it should be `date_unix` and be in seconds, but that would mean there is also a conversion bug here since `new Date()` expects milliseconds.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +const ListItem = styled.li<{ isLast?: boolean; isFirst?: boolean }>((x) =>
This looks messy with the isFirst boolean.

I think you better create two separate components if they are that far apart in styling. A `FirstItem` and a regular `Item` and switch between those in the parent context.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    paddingTop: x.isLast ? `${1.3 + 2}rem` : '',
I think this is the same as 3.3 rem? :)

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +      left: CIRCLE_SIZE / 2 - 1,
You keep repeating this `CIRCLE_SIZE / 2 - 1`. Better create a variable from it, so you only need to do this calculation once

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    minWidth: CIRCLE_SIZE,
I think if you set a width and height minwidth doesn't really have a function

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    left: '-2rem',
2rem and 4rem spacings are part of the theme. Try to use more theme spacing sizes because the CSS in these components seems to be pretty much completely detached from the theme, which increases technical dept.

2021-02-26 09:35 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/documents/pages/vaccinations-page.ts
> +      name: 'expected',
Expected is too vague. Since it is really 'expected milestones' why not call it that?  `expected_milestones`

2021-02-26 10:04 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/vaccine/milestones.tsx
> +                        {formatDate(new Date(mile.date))}
Sanity is giving me a string, I could also accept strings in the formatDate function or parse it to a new Date like here.

2021-02-26 10:29 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    minWidth: CIRCLE_SIZE,
I've set the min-width because when the screen gets smaller the circles got squashed by the flexbox, this prevents it.

2021-02-26 10:39 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +                        {formatDate(new Date(mile.date))}
OK then it's fine if it's an ISO date string. I was assuming this was a number.

2021-02-26 10:41 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +    minWidth: CIRCLE_SIZE,
I suspect you can also get the same result by setting flex shrink to 0, but this is fine then.

2021-02-26 10:44 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +        <ListItem isFirst={true}>
Later on I concluded that looking at the CSS it would be better to create separate components for first and other.

2021-02-26 10:45 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones.tsx
> +const ListItem = styled.li<{ isLast?: boolean; isFirst?: boolean }>((x) =>
correction; three different components. A fist, a last and a regular in-between styled version.

2021-02-26 12:04 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/vaccine/milestones.tsx
> +const ListItem = styled.li<{ isLast?: boolean; isFirst?: boolean }>((x) =>
@VWSCoronaDashboard8 Totally agree, gonna do that in a separate pull request. This code kinda grew along the way I was working on it.

2021-02-26 12:38 UTC, VWSCoronaDashboard8 approved these changes

2021-02-26 12:38 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones-view.tsx
> +type MilestonesType = {
No need to place a Type suffix on a type. The fact that it is declared as a type and starts with a capitol latter should be enough.

2021-02-26 12:38 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones-view.tsx
> +  expectedMilestones: ExpectedMilestonesType[];
```suggestion
  milestones: Milestones[];
  expectedMilestones: ExpectedMilestones[];
```

2021-02-26 12:38 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones-view.tsx
> +  const expandedHandler = () => setIsExpanded(true);
If you're not removing the wrapper function then maybe give it a name like a handler usually has with handle + an event type like `handleExpand`. Function names in general should start with a verb.

2021-02-26 12:38 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/milestones-view.tsx
> +        <Box as="ul" p={0} m={0} css={css({ listStyleType: 'none' })}>
Actually what you are rendering is more like an ordered list, since milestones are ordered in time. So to be semantically correct I think this should be `ol`

2021-02-28 19:13 UTC, closed without merging