Create the "tile"-like content header
minvws/nl-covid19-data-dashboard pull request #2138
Opened 2021-03-02 14:23 UTC by VWSCoronaDashboard10

## Summary

The vaccine progress content header will be rendered with a Tile layout, hence these changes.

![image](https://user-images.githubusercontent.com/73584448/109662095-f8737c80-7b6a-11eb-8abe-06abf337505c.png)

2021-03-02 16:12 UTC, VWSCoronaDashboard4 requested changes

2021-03-02 16:12 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/content-header/index.tsx
> +      <ContainerComponent>
This component becomes very generic / multi use with this change. Why not create a new component for the tile, and have a `h1` -less version of this component underneath?

The resulting code becomes harder for me to develop on without being afraid of breaking changes.

2021-03-02 16:19 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/content-header/index.tsx
> +      <ContainerComponent>
Ah yes, good idea. I'll pick that up tomorrow - thanks :-)

2021-03-03 09:49 UTC, VWSCoronaDashboard1 approved these changes

2021-03-03 10:49 UTC, VWSCoronaDashboard8 approved these changes

2021-03-03 15:31 UTC, closed without merging