Update line-chart chart axes with overflow visible
minvws/nl-covid19-data-dashboard pull request #2142
Opened 2021-03-02 16:27 UTC by VWSCoronaDashboard14

We could increase the padding to make more room for the chart-axes to avoid clipping, but I rather add an overflow visible.

![Screenshot 2021-03-02 at 17 26 56](https://user-images.githubusercontent.com/76471292/109680151-85730180-7b7c-11eb-92c3-17416d2c5a36.png)

2021-03-02 16:39 UTC, VWSCoronaDashboard1 approved these changes

2021-03-04 13:02 UTC, VWSCoronaDashboard8 requested changes
I don't think we should fix this by allowing the label to overflow. Was that requested specifically? We have padding props for the chart to allow for the labels on the y-axis to have more space. These paddings should be set so that the largest numbers align nicely with the content. If you allow overflow than the label it doesn't align anymore.

2021-03-05 12:23 UTC, VWSCoronaDashboard8 commented
I'm going to approve it anyway, since we could do both. Allow overflow for when paddings are not set correctly, and then adjust paddings if we notice the label overflowing.

2021-03-05 12:23 UTC, VWSCoronaDashboard8 approved these changes

2021-03-08 08:05 UTC, merged