Rendering fewer ticks on bar chart when width is less than 400px
minvws/nl-covid19-data-dashboard pull request #2158
Opened 2021-03-03 12:48 UTC by VWSCoronaDashboard13

## Summary

Rendering fewer ticks on the bar chart on mobile so there is no tick label overlap

## Detailed design

Conditionally setting the number of ticks in `generateBarChartCoordinates` based on the width

2021-03-03 12:57 UTC, VWSCoronaDashboard4 approved these changes

2021-03-03 13:03 UTC, VWSCoronaDashboard1 requested changes

2021-03-03 13:03 UTC, VWSCoronaDashboard1 commented on packages/app/src/components-styled/bar-chart/bar-chart-coordinates.ts
> +  const numTicks = width > 400 ? 10 : 6;
In this PR: https://github.com/minvws/nl-covid19-data-dashboard/pull/2154/files#diff-4af1f3aab2c05a3d786e2f4e6277c9acd28014b03cea47364c1fd97489f705ca
I've added the `useBreakpoints()` hook, its probably better to determine this tick number based on one of the breakpoints there in. In this case `breakpoints.xs`.

2021-03-05 12:54 UTC, VWSCoronaDashboard13 commented on packages/app/src/components-styled/bar-chart/bar-chart-coordinates.ts
> +  const numTicks = width > 400 ? 10 : 6;
Alright, I'll wait for that PR to get merged in before implementing this update

2021-03-05 12:57 UTC, VWSCoronaDashboard13 commented on packages/app/src/components-styled/bar-chart/bar-chart-coordinates.ts
> +  const numTicks = width > 400 ? 10 : 6;
Actually I just read another thread on slack discussing this issue where the consensus was to keep the existing implementation!

2021-03-05 12:59 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/bar-chart/bar-chart-coordinates.ts
> +  const numTicks = width > 400 ? 10 : 6;
Nope, your implementation is the correnct one indeed, we can merge this 👍

2021-03-05 13:00 UTC, VWSCoronaDashboard10 approved these changes

2021-03-05 13:01 UTC, merged