Add schema for risk levels for safety regions
minvws/nl-covid19-data-dashboard pull request #2226
Opened 2021-03-08 14:07 UTC by VWSCoronaDashboard14

Add the schema for the dynamic text in the safety regions' risk levels.
3 new keys added: 
`date_start_measurement`
`date_end_measurement`
`date_next_estimate`

2021-03-08 14:27 UTC, VWSCoronaDashboard1 requested changes

2021-03-08 14:27 UTC, VWSCoronaDashboard1 commented on packages/app/schema/vr/escalation_level.json
> +    "date_next_estimate": {
If the dates are unix timestamps, I believe the convention is to suffix them with `_unix`.

2021-03-09 14:56 UTC, VWSCoronaDashboard4 commented on packages/app/schema/vr/escalation_level.json
> +    "date_start_measurement_unix",
what's a measurement?

2021-03-09 15:19 UTC, VWSCoronaDashboard8 requested changes
I think we need to have a meeting to clear some things up and come up with good names, because this will get confusing

2021-03-10 10:09 UTC, VWSCoronaDashboard8 approved these changes

2021-03-10 16:42 UTC, VWSCoronaDashboard1 approved these changes

2021-03-16 14:25 UTC, merged