Schema for Vaccinated per age group
minvws/nl-covid19-data-dashboard pull request #2319
Opened 2021-03-17 09:32 UTC by VWSCoronaDashboard4

## Summary

Schema for Vaccinated per age group

The approach is equal to other age group schema's. Per age group there's the `age_group_range` with a total and percentage of the population.

There can be an `age_group_range` with value of eg `18+` to cover the total.

2021-03-17 10:32 UTC, VWSCoronaDashboard10 commented on packages/app/schema/nl/__index.json
> +    "vaccinated_per_age_group": {
Don't we use "vaccine_administered" instead of "vaccinated"? In that case I think this should be called `vaccine_administered_per_age_group`

2021-03-17 10:32 UTC, VWSCoronaDashboard10 commented on packages/app/schema/nl/vaccinated_per_age_group.json
> +        },
can these be of type integer?

2021-03-17 13:46 UTC, VWSCoronaDashboard8 requested changes

2021-03-17 13:46 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/__index.json
> +    "vaccinated_per_age_group": {
Yes, please use the same subject prefix as the others.

2021-03-17 13:46 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/vaccinated_per_age_group.json
> +        "coverage",
I think coverage is a little vague. I am assuming it's a percentage and it's the percentage fully vaccinated. So I would suggest to call it `fully_vaccinated_percentage`

2021-03-17 13:46 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/vaccinated_per_age_group.json
> +          "type": "number"
This should be integer I think

2021-03-18 10:18 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/__index.json
> +    "vaccinated_per_age_group": {
This is specifically about (partially) vaccinated people, not about administered doses.

2021-03-18 10:54 UTC, VWSCoronaDashboard10 commented on packages/app/schema/nl/__index.json
> +    "vaccinated_per_age_group": {
But doesn't 1 administered vaccine === 1 dose applied === 1 (partially) vaccinated human being?

2021-03-18 14:42 UTC, VWSCoronaDashboard8 approved these changes

2021-03-18 14:42 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/vaccine_coverage_per_age_group.json
> +        "date_unix",
You might want to add `date_of_report_unix` as well. It's not a requirement maybe but we are going to retroactively add it to all existing schema's AFAIK, so we might as well add it to all new ones to save some time.

2021-03-22 10:39 UTC, VWSCoronaDashboard8 approved these changes

2021-03-22 10:39 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/__index.json
> +    "vaccine_coverage_per_age_group"
I suggest to take it out of the required list so it can be merged before the data is there. Then also don't forget to re-run generate typescript

2021-03-22 17:38 UTC, VWSCoronaDashboard8 requested changes

2021-03-22 17:38 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  date_of_report_unix?: number;
You forgot to add date of report to the required list

2021-03-23 08:16 UTC, merged