Feature/region tiles to pages
minvws/nl-covid19-data-dashboard pull request #233
Opened 2020-09-03 15:18 UTC by VWSCoronaDashboard4

## Summary & Motivation

Moves the data logic from the old design's tiles to the new design's pages; adds appropriate locale strings.

## Detailed design

* Logic for Hospital admissions and positively tested people is fairly straightforward and just copied over.
* Logic for sewer water is made more readable by calculating the data to be used by the charts in separate methods.

## Drawbacks

n/a

## Alternatives

* Logic for the sewer water data could perhaps be moved to a utility file, but it's probably handy to have it close to the consuming charts too.

## Unresolved questions

* I have not fit everything according to the new design files. It is perhaps more logical to do that in a separate PR.

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-09-03 15:18 UTC, VWSCoronaDashboard4 commented on src/components/layout/MunicipalityLayout.tsx
> +  const { data } = useSWR(`/json/GM0014.json`);
Hardcoded, dynamically adjusted stuff is for a different PR.

2020-09-03 15:29 UTC, VWSCoronaDashboard1 commented on src/components/layout/MunicipalityLayout.tsx
> +  const { data } = useSWR(`/json/GM0014.json`);
```suggestion
  const { data } = useSWR<National>(`/json/GM0014.json`);
```
That will statically type the data, saves another cast later on ;)

2020-09-03 15:39 UTC, VWSCoronaDashboard1 requested changes

2020-09-03 15:39 UTC, VWSCoronaDashboard1 commented on src/pages/gemeente/positief-geteste-mensen.tsx
> +  const { data } = useSWR(`/json/GM0014.json`);
```suggestion
  const { data } = useSWR<Municipal>(`/json/GM0014.json`);
```

2020-09-03 15:39 UTC, VWSCoronaDashboard1 commented on src/pages/gemeente/rioolwater.tsx
> +function getSewerWaterMetadata(
There's quite a lot of functions in this component file, can these be put in separate files and imported? That keeps things readable. Also can you add some JSDoc comments to that describe in short what kind processing is performed.

2020-09-03 15:39 UTC, VWSCoronaDashboard1 commented on src/pages/gemeente/ziekenhuis-opnames.tsx
> +  const { data } = useSWR(`/json/GM0014.json`);
```suggestion
  const { data } = useSWR<Municipal>(`/json/GM0014.json`);
```

2020-09-03 15:39 UTC, VWSCoronaDashboard1 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +  const { data } = useSWR(`/json/VR01.json`);
```suggestion
  const { data } = useSWR<Regionaal>(`/json/VR01.json`);
```

2020-09-03 15:39 UTC, VWSCoronaDashboard1 commented on src/pages/veiligheidsregio/[code]/rioolwater.tsx
> +function getSewerWaterMetadata(
Same here. Can these functions live inside their own imports and receive some JSDoc comments? Please? :)

2020-09-03 15:39 UTC, VWSCoronaDashboard1 commented on src/pages/veiligheidsregio/[code]/ziekenhuis-opnames.tsx
> +  const { data } = useSWR(`/json/VR01.json`);
```suggestion
  const { data } = useSWR<Regionaal>(`/json/VR01.json`);
```

2020-09-04 09:40 UTC, VWSCoronaDashboard1 approved these changes

2020-09-04 09:40 UTC, VWSCoronaDashboard1 commented on src/pages/gemeente/positief-geteste-mensen.tsx
> +  siteText.gemeente_positief_geteste_personen;
this typing probably isn't necessary anymore after the changes to the locale typing. But for now I'm ok with it.

2020-09-04 09:46 UTC, VWSCoronaDashboard4 commented on src/pages/gemeente/positief-geteste-mensen.tsx
> +  siteText.gemeente_positief_geteste_personen;
we can clean it up in a separate PR perhaps, it's done in many other files as well

2020-09-04 11:31 UTC, VWSCoronaDashboard requested changes
Please extract the utility functions into helper methods in the utils folder.

2020-09-04 11:31 UTC, VWSCoronaDashboard commented on src/components/layout/MunicipalityLayout.tsx
> +  const { data } = useSWR<Municipal>(`/json/GM0014.json`);
Hardcoded region names? Where does the region ID come from? I'd rather see this work from the get-go.

2020-09-04 11:31 UTC, VWSCoronaDashboard commented on src/components/layout/MunicipalityLayout.tsx
> +import { getSewerWaterBarScaleData } from 'pages/gemeente/_rioolwater.util';
What kind of convention is this? Afaik Next.js does not support or endorse non-pages in the pages folder. The underscore seems to mark it private.

What is the purpose of this file?

2020-09-04 11:31 UTC, VWSCoronaDashboard commented on src/pages/gemeente/_rioolwater.util.ts
> +  allValues: any[][];
Does this need to be more strict?

2020-09-04 11:31 UTC, VWSCoronaDashboard commented on src/pages/gemeente/_rioolwater.util.ts
> +import {
I'm fully convinced this file needs to be moved to the utils folder.

2020-09-04 12:56 UTC, VWSCoronaDashboard approved these changes

2020-09-04 12:58 UTC, merged