Add source to positive tested choropleth on topical page
minvws/nl-covid19-data-dashboard pull request #2341
Opened 2021-03-18 08:56 UTC by VWSCoronaDashboard14

![Screenshot 2021-03-18 at 09 56 12](https://user-images.githubusercontent.com/76471292/111599068-2d6d0980-87d0-11eb-8b9a-c67318ddd8cb.png)

2021-03-18 09:35 UTC, VWSCoronaDashboard1 approved these changes

2021-03-19 13:49 UTC, VWSCoronaDashboard8 requested changes

2021-03-19 13:49 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/actueel/gemeente/[code].tsx
> +                  </Text>
It looks like this part ideally should be captured in a reusable component. It's a lot of details to place directly on the root of a page layout.

2021-03-19 13:49 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/actueel/veiligheidsregio/[code].tsx
> +                  </Text>
And if you're repeating the same thing again, then even more so.

2021-03-19 13:49 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/index.tsx
> +
So yes, if you're repeating yourself 3 times I think that's the threshold. Then it should definitely be refactored into a component.

2021-03-23 08:46 UTC, VWSCoronaDashboard14 commented
@VWSCoronaDashboard8 I've integrated this in the `metadata` component now

2021-03-25 09:13 UTC, VWSCoronaDashboard8 approved these changes
Much better 👍

2021-03-25 09:13 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/metadata.tsx
> +      )}
There doesn't seem to be a clear reason why these two variations of metadata are combined into a single component. I don't mind this for now, but I feel that ideally it should be two separate components. Metadata (or ContentHeaderMetadata) and TileMetadata for example.

2021-03-29 09:15 UTC, merged