Topic/tested per age group per 100k
minvws/nl-covid19-data-dashboard pull request #2359
Opened 2021-03-22 10:39 UTC by VWSCoronaDashboard4

## Summary

Schema for tested per age group per 100k over time

2021-03-22 10:56 UTC, VWSCoronaDashboard1 approved these changes

2021-03-22 11:30 UTC, VWSCoronaDashboard8 approved these changes

2021-03-22 11:30 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/tested_per_age_group.json
> +          "type": "integer"
👍

2021-03-23 08:58 UTC, VWSCoronaDashboard8 requested changes

2021-03-23 08:58 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  date_of_report_unix?: number;
You forgot to add this one to the required list

2021-03-25 10:22 UTC, VWSCoronaDashboard8 approved these changes

2021-03-30 11:33 UTC, merged