Add schema safety region risk level indicators
minvws/nl-covid19-data-dashboard pull request #2367
Opened 2021-03-22 15:05 UTC by VWSCoronaDashboard14

Schema for adding 2 new keys on the safety regions risk level page
Positive tested per 100k and hospital admissions per million.

2021-03-22 17:35 UTC, VWSCoronaDashboard8 requested changes

2021-03-22 17:35 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  hospital_admissions_per_million?: number;
Seems like you forgot to add them to the required list. Or maybe you did this on purpose to not break develop? I think I would only advise to use "optional" on the root of the schema, otherwise it quickly becomes messy to keep track of toggling things on and off.

I would suggest to add these properties to the required list and then don't merge it into develop. So use the "old" workflow for mutations of existing schema's.

2021-03-23 08:45 UTC, VWSCoronaDashboard14 commented
@VWSCoronaDashboard8 I've integrated this in the Metadata component now.

2021-03-23 08:54 UTC, VWSCoronaDashboard8 approved these changes

2021-03-23 08:55 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr/escalation_level.json
> +    },
Are you sure these need to be integer?

2021-03-23 08:57 UTC, VWSCoronaDashboard8 requested changes
If I look at other schemas per_100k the definitions are type number. So it would be logical to expect decimal here as well.

2021-03-29 08:33 UTC, closed without merging