Add styling for the "Risiconiveau van dit moment" on safety regions
minvws/nl-covid19-data-dashboard pull request #2380
Opened 2021-03-23 16:40 UTC by VWSCoronaDashboard14

A flexible component that renders a new tile on the safety region risk level page that displays with a bit more styling the determining risk levels, hospital admissions, and the positive tested people for that safety region.

<img width="923" alt="Screenshot 2021-03-24 at 10 11 27" src="https://user-images.githubusercontent.com/76471292/112284230-4e7aa200-8c89-11eb-960c-525734d430f3.png">

This is with dummy data, the correct data still needs to be connected.

2021-03-24 09:29 UTC, VWSCoronaDashboard8 requested changes

2021-03-24 09:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/escalation-level-icon.tsx
> +  isBig?: boolean;
Now something can be small and big at the same time.... If there are three flavors it would be better to implement this as a variant with a string literal. So for example a prop named `variant` or `size` with values `small | medium | large` 

I prefer the word large over big, since it's more in line with our other theme naming.

2021-03-24 09:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/escalation-level-icon.tsx
> +  if (isBig) size = asResponsiveArray({ _: 45, sm: 45 });
I find it odd that we mix logic of a size prop with media queries. So we have 3 different sizes of the component with each their own media queries to make them respond differently to screen sizes on top of that. Seems a bit convoluted to me.

2021-03-24 09:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/risiconiveau.tsx
> +  isAroundDate?: boolean;
Should this really be all optional? Seems like a lot. If you leave everything out, is it still a valid / complete list item?

2021-03-24 09:29 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/risiconiveau.tsx
> +              amount: <InlineText fontWeight="bold">{`${amount} `}</InlineText>,
```suggestion
              amount: <InlineText fontWeight="bold">{amount}</InlineText>,
```

2021-03-26 10:29 UTC, VWSCoronaDashboard14 commented on packages/app/src/pages/veiligheidsregio/[code]/risiconiveau.tsx
> +  isAroundDate?: boolean;
I totally get you, every list item has a small difference in dealing with data or dates. I thought creating new components or rendering everything inline and passing it on wasn't that nice. 

If you only use the standard list item without any optional props it should render an empty item with just a title and an icon. 
<img width="447" alt="Screenshot 2021-03-26 at 11 26 30" src="https://user-images.githubusercontent.com/76471292/112618485-77846980-8e26-11eb-8375-b2b262e5da9a.png">

2021-03-26 12:55 UTC, VWSCoronaDashboard8 requested changes

2021-03-26 12:55 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr/escalation_level.json
> +    },
These need to be number / decimal.

2021-03-26 12:55 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr_collection/escalation_levels.json
> +    },
And then of course these too

2021-03-26 12:55 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/risiconiveau.tsx
> +    <StyledList>
This component is called ListItem, yet the first thing it renders (as a container) is a list. Seems like a mixup. If this is really about the list item, when the container should be lifted to the calling context using composition. So render the StyledList where you are using the ListItem, and make ListItem its child.

2021-03-26 13:00 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/risiconiveau.tsx
> +  isAroundDate?: boolean;
I think the problem starts because you are trying to treat everything in that list as the same component. You could make a distinction between root level list items and other items.

Root-level list items seem to always have an icon, title and date so you can make those required. Then each of them is able to (optionally) contain a sublist.  That sublist then contains list items that are different components, because their icon is smaller and they do not have dates.

Those sub-lists see to always have childen and those children are rendered using bullet points instead of icons. So that is a third type of list item.

So a clean implementation would be to create three distinct list item types, each with their ons specific strict set of props/behavior. Then you don't need the variant I'm assuming and you can make most properties non-optional.

2021-03-26 14:44 UTC, VWSCoronaDashboard14 commented on packages/app/src/pages/veiligheidsregio/[code]/risiconiveau.tsx
> +  isAroundDate?: boolean;
Alright, gonna separate it a bit more. Thanks!

2021-03-29 14:17 UTC, VWSCoronaDashboard8 approved these changes

2021-03-30 11:21 UTC, merged