Improve article and weekly/custom blocks topical page
minvws/nl-covid19-data-dashboard pull request #2421
Opened 2021-03-26 09:17 UTC by VWSCoronaDashboard14

Update the styling of blocks on the topical page
Remove the editorial tile
Add an option to have 2 custom highlighted content blocks in the cms
Add a category input field in the CMS
Display on the article detail, overview, and on the topical page the category names

In the future, the category has predefined tags.

2021-03-26 09:47 UTC, VWSCoronaDashboard10 requested changes
Looking good overall, couple of changes requested though :-)

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/article-detail.tsx
> +            css={css({ textTransform: 'uppercase' })}
`textTransform` sounds like a property which can be part of the `Text` and `InlineText` component. This can be implemented the same way is we did for the Box's `spacing` prop (by creating a `/style/functions/text-transform.ts` file)

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/highlight-teaser.tsx
> +    },
please don't use strong selectors like these, in the future they will become a pain in the ass and they are also an indication that something is wrong with the codebase.
For example: the actual mistake here is that there's a color set inside the `PublicationDate` component. This color should be set by the container component (in your case on line 54). 

I'd suggest you to:
1.  remove the color from the PublicationDate component
2. apply the `isWeekly ? 'white' : 'annotation'` style on line 54
3. set correct color of all PublicationDate instance's parent components

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/topical/article-list.tsx
> +      lg: 'calc(33.33% - 32px)',
How about `calc(1 / 3 * 100% - 32px)`

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/topical/highlights-tile.tsx
> +      {highlights.map((item: HighlightTeaserProps, index: number) => (
types can be inferred
```suggestion
      {highlights.map((item, index) => (
```

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/actueel/gemeente/[code].tsx
> +            {content.weeklyHighlight && content.highlights && (
do you want to render when `content.highlights` is an empty array? If not: check also the length

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/index.tsx
> +            {content.weeklyHighlight && content.highlights && (
same here

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/queries/topical-page-query.ts
> +    }[0].highlights
pretty!

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/fields/article-fields.ts
> +    title: 'Category',
shouldn't the title be in dutch?

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/pages/topical-page.ts
> +              title: 'Category',
same here

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/pages/topical-page.ts
> +          title: 'Highlighted articles',
same here

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/pages/topical-page.ts
> +      title: 'Custom highlight blocks',
same here

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/topical/highlights-tile.tsx
> +          isWeekly
The `isWeekly` prop on a `HighlightTeaser` doesn't really make sense, context-wise. Maybe we can use a variants prop? `variant='blue'` with a default value of `white`?

2021-03-26 09:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/locale/en.json
> +    "read_weekly": "Read the weekly message",
This is imho not a common message but very specific one. Please rename the key to something like `read_weekly_message` and move it to a topical- or article-related context of the locale files.

2021-03-26 11:13 UTC, VWSCoronaDashboard14 commented on packages/app/src/queries/topical-page-query.ts
> +    }[0].highlights
🤣

2021-03-26 15:47 UTC, VWSCoronaDashboard10 requested changes
getting there!

2021-03-26 15:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/highlight-teaser.tsx
> +const StyledHightlightTeaser = styled.a<{ variant?: string }>((x) =>
shouldn't variant either be one if `blue` or `default`/`white`?

2021-03-26 15:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/highlight-teaser.tsx
> +  variant?: 'blue';
The default variant is missing, name it `white` or `default` or something like that .. you could create a separate type (`variant?: HightlightTeaserType;`) and use this type in the `StyledHightlightTeaser` component too.

2021-03-26 15:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/typography/text.tsx
> +})<TextProps>(compose(margin, padding, typography, color), textTransform);
it won't work as argument of the `compose`?

2021-03-26 15:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/topical/highlights-tile.tsx
> +          href={`weekberichten/${weeklyHighlight.slug.current}`}
you're missing a root slash in this href

2021-03-26 15:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/actueel/gemeente/[code].tsx
> +            {content.weeklyHighlight && content.highlights.length && (
Here's classic mistake being made :-) see:
```tsx
// this is the current situation:
{content.weeklyHighlight && content.highlights.length && <> ... </>}

// when the highlights array is empty, the length will be `0`
{content.weeklyHighlight && 0 && <> ... </>}

// it will stop evaluating when there's a falsy value

{content.weeklyHighlight && 0}

// and as you might know
const str = somethingTruthy && 'yeah!'
str === 'yeah!'

// so, this:
{content.weeklyHighlight && 0}

// basically becomes this:
{0}

// and voilia, suddenly a `0` is rendered by react :-)

2021-03-26 15:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/style/functions/text-transform.ts
> +  if (isDefined(x.textTransform)) {
I think we can make the textTransform responsive by using the `asResponsiveArray` as you can see in the spacing implementation (together with the `ResponsiveValue` type)

2021-03-26 15:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/style/functions/text-transform.ts
> +  if (isDefined(x.textTransform)) {
This allows us to use the textTransform as any other styled system prop `textTransform={{ _: 'uppercase', md: 'lowercase' }}`

2021-03-26 15:47 UTC, VWSCoronaDashboard10 commented on packages/app/src/style/functions/text-transform.ts
> +  if (isDefined(x.textTransform)) {
but I can image this won't ever be used .. so it's also fine to leave it as it is :-)

2021-03-29 14:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/topical/highlights-tile.tsx
> +export interface weeklyHighlightProps {
```suggestion
export interface WeeklyHighlightProps {
```

2021-03-29 14:35 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/topical/highlights-tile.tsx
> +  };
Why is it shaped like this? What's the point in having a nested property if there is only one? Also I wonder what "current" means in the context of a slug.

2021-03-30 08:12 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/topical/highlights-tile.tsx
> +  };
@VWSCoronaDashboard8 the way sanity gives back a generated slug based on the title is `slug.current`. It wasn't my choice using the format this way.

2021-03-30 13:43 UTC, merged