Kill lokalize part 1
minvws/nl-covid19-data-dashboard pull request #2504
Opened 2021-04-02 09:28 UTC by VWSCoronaDashboard8

## Summary

The basis for converting and handling Lokalize data in Sanity.

2021-04-06 13:13 UTC, VWSCoronaDashboard1 requested changes

2021-04-06 13:13 UTC, VWSCoronaDashboard1 commented on packages/cms/src/plugins/translate/select-language.tsx
> -                </>
I think we concluded that the validation error indicator would be kept next to the flag because it indicates in which language the error is contained in.

2021-04-06 13:13 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/documents/lokalize-subject.ts
> +  __experimental_actions: ['create', 'update', 'delete', 'publish'],
We don't use these experimental features anymore. They are deprecated actually.
The new way of defining actions per document type can be added to `resolve-document-actions.ts`. I think the code there speaks for itself.

2021-04-06 13:16 UTC, VWSCoronaDashboard8 commented on packages/cms/src/plugins/translate/select-language.tsx
> -                </>
@VWSCoronaDashboard1 I brought back the red outline for the flag, as I assumed that would be enough of an indication. Right next to the flags you then have the icon with the exclamation mark already, so I feel the combination of both is sufficient.

2021-04-07 08:40 UTC, VWSCoronaDashboard10 approved these changes
couple of comments/questions.

2021-04-07 08:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/import.ts
> +        );
Do we want the import/export scripts to fail silently or should it actually throw an error to block build scripts?

2021-04-07 08:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/import.ts
> +        );
or would console.error result in the same behavior as a throw?

2021-04-07 08:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/lokalize-subject.ts
> +      // hidden: true,
comment necessary?

2021-04-07 08:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/locale/locale-text.ts
> +      lang.id === 'nl' ? Rule.required().max(1000) : Rule.max(1000),
I checked out the branch and saw the following error pop up:
http://localhost:3333/desk/lokalize;jsonKey__ic_opnames_per_dag
![image](https://user-images.githubusercontent.com/73584448/113835845-9c64cf00-978c-11eb-85f1-d455623eb0d9.png)

is this configuration not working or not related?

2021-04-07 08:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/lokalize-text.ts
> +  },
is shortening the subtitle necessary? It looks like the sanity UI will automatically cut off long values together with an ellipsis.

2021-04-07 08:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/export.ts
> +  });
you forgot to catch errors on this promise

2021-04-07 08:41 UTC, VWSCoronaDashboard10 commented on packages/cms/src/desk-structure.ts
> +        .title('Lokalize')
or maybe leave it like this, it's probably more clear for the comm users to name it Lokalize.

2021-04-07 09:45 UTC, VWSCoronaDashboard8 commented on packages/cms/src/desk-structure.ts
> +        .title('Lokalize')
In my mind once we have this working we should move to a different structure in a next iteration and then call it something else. With this name it is clear that this feature is there to replace Lokalize at first. But the title we can always change at any time.

2021-04-07 09:46 UTC, VWSCoronaDashboard8 commented on packages/cms/src/lokalize/delete.ts
> +  interval: 1000 / 25,
This came from @VWSCoronaDashboard initial PoC, I am not sure how these limits have been chosen. Maybe it's just the Sanity API rate limit.

2021-04-07 09:47 UTC, VWSCoronaDashboard8 commented on packages/cms/src/lokalize/import.ts
> +        );
Import is something we do manually and only a few times until we hit the killswitch. So I think error messages in the console are fine.

2021-04-07 09:48 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/locale/locale-text.ts
> +      lang.id === 'nl' ? Rule.required().max(1000) : Rule.max(1000),
Yes the 120 limit error needs to be sorted out still. I'll add it to the trello ticket of step 2. Not sure why it's not picking up the 1000 limit

2021-04-07 11:02 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/documents/lokalize-subject.ts
> +  __experimental_actions: ['create', 'update', 'delete', 'publish'],
I'm putting them back in to wrap up this PR. I'll add a todo. Using document actions it is not immediately clear to me what the equivalent of and API document update action is and I don't have time to dive into these things now. The feature is also not deprecated yet.

2021-04-07 11:05 UTC, VWSCoronaDashboard8 commented on packages/cms/src/client.ts
> +});
Simply taking out this bit breaks the code (permissions errors), so I'm leaving this for another day.

2021-04-07 11:13 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/documents/lokalize-text.ts
> +  },
I must have added it because I was seeing strings that were too long, but I'll add a todo for the follow up work. I don't want to spent more time on this PR now.

2021-04-07 11:16 UTC, VWSCoronaDashboard10 approved these changes

2021-04-07 11:21 UTC, VWSCoronaDashboard1 approved these changes

2021-04-07 11:26 UTC, merged