Code improvements confirmed cases per age group chart
minvws/nl-covid19-data-dashboard pull request #2513
Opened 2021-04-02 12:56 UTC by VWSCoronaDashboard4

## Summary

Code improvements confirmed cases per age group chart

* Moved the static legend items to a regular `legend` component
* Extended the regular `legend` component to accept `dashed` lines
* Above changes allowed for some cleanup in `age-group-legend`
* Adjusted `tooltip-series-list` to accept an optional `columns` prop
* Cleaned up the odd code to pass columns from `infected-per-age-group` to the tooltip by using above prop
* Adjusted some names and added comments

2021-04-02 13:30 UTC, VWSCoronaDashboard1 approved these changes

2021-04-02 13:49 UTC, VWSCoronaDashboard10 requested changes
there are a couple of unnecessary useMemo hooks to clean up, besides that approved 👍

2021-04-02 13:49 UTC, VWSCoronaDashboard10 commented on packages/app/src/components-styled/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +  columns,
nit; you could define the default over here instead of on line 86
```suggestion
  columns = 1,
```

2021-04-02 13:49 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
> +  const staticLegendItems: LegendItem[] = useMemo(() => {
nit: caching this one and the previous one (dynamicLegendConfig) is not really necessary performance-wise, the legend component isn't doing a lot of magic with this data..

2021-04-02 13:49 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
> +  const staticLegendItems: LegendItem[] = useMemo(() => {
actually the same applies for the seriesConfig (no realneed to wrap that in a useMemo), because this `InfectedPerAgeGroup` is not re-rendered that often. Only on click of a legend item it will rerender, but that will also trigger a new seriesConfig array ..

So I guess you can get rid of all the useMemo hooks and experience even better performance than before.

2021-04-02 13:49 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
> +  );
The `useMemo` hook has AFAIK two main purposes:

1. cache expensive calculations
2. prevent expensive re-renders of a child-component which receives a non-primitive prop

both use-cases indicate that wrapping `list.length === 0 || list.length > 4 ? 2 : 1` in a useMemo hook is not necessary, and is even hurting performance :-)

2021-04-02 13:49 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/tested/infected-per-age-group/series-config.ts
> +};
It doesn't feel it's really necessary to create a const for this config

2021-04-02 13:58 UTC, VWSCoronaDashboard8 approved these changes

2021-04-02 13:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +  columns: 1 | 2;
If these are the only options that we'll ever use (which makes sense to me), I think an optional boolean `twoColumns` or `twoColumnLayout` would have been a little nicer API wise

2021-04-02 13:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components-styled/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +      <TooltipList columns={columns ?? 1}>
... then you also don't need this default/fallback things.

2021-04-02 13:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
> +  const underReported = useMemo(
```suggestion
  const underReportedConfigItem = useMemo(
```

It wasn't immediately clear to me what this variable contained.

2021-04-02 13:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
> +  );
I would use a boolean as suggested earlier, but if not, it helps if you name it clearly as a number, because otherwise it reads as if it contains the actual columns component. I'd suggest `numTooltipColumns`

2021-04-02 13:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/tested/infected-per-age-group/series-config.ts
>      NlTestedPerAgeGroupValue,
I you use `<T>` you don't need to tie this to the specific schema for NlTestedPerAgeGroupValue. Also the Omit is not necessary I think. The series config metricProperty is defined as `keyof T` which is fine IMO. I'd rather keep it simple.

2021-04-02 13:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/tested/infected-per-age-group/series-config.ts
> +export const UNDER_REPORTED_CONFIG: { shape: LegendShape; color: string } = {
It might read better if you just placed these things in the file where they are use (if one file) and gave them a normal non-capitalized name. I don't see much reason for isolating this in its own file.

2021-04-02 13:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/tested/infected-per-age-group/components/age-group-legend.tsx
>  interface AgeGroupLegendProps {
This component is still called AgeGroupLegend (and the name is used in its props), but there is nothing specific to age groups in this whole thing. It could be called `InteractiveLegend` for example and live outside of the age group chart. But I'll leave it up to you if you want to take that on.

2021-04-07 08:41 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +  columns: 1 | 2;
I went with `hasMultipleColumns` as boolean

2021-04-07 08:44 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/tested/infected-per-age-group/series-config.ts
>      NlTestedPerAgeGroupValue,
Where this config is used, the `metricProperty` is used to look for the proper label in `text`. Without omit here there, some other fix is needed there.

2021-04-07 08:54 UTC, VWSCoronaDashboard10 approved these changes

2021-04-07 08:54 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
> +  const hasMultipleColumns = list.length === 0 || list.length > 4;
It almost feels like this logic might become part of the TooltipSeriesList component itself, but maybe we should wait with that until we run into more tall tooltips with lots of items.

2021-04-07 08:54 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/tested/infected-per-age-group/series-config.ts
>      NlTestedPerAgeGroupValue,
Try this:
```tsx
export const BASE_SERIES_CONFIG = {
  ...,
  ...
} as const;

2021-04-07 09:00 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
> +  const hasMultipleColumns = list.length === 0 || list.length > 4;
Exactly, and it shouldn't be too difficult to move/adjust it at a later moment.

2021-04-07 09:00 UTC, VWSCoronaDashboard8 approved these changes

2021-04-07 09:18 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
> +  const hasMultipleColumns = list.length === 0 || list.length > 4;
Then all are selected.

2021-04-07 09:19 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/interactive-legend.tsx
> +}
that's a trip down the rabbit hole that I reverted; not all variants in seriesconfig have the `metricProperty`

2021-04-07 09:31 UTC, VWSCoronaDashboard4 commented on packages/app/src/components-styled/interactive-legend.tsx
> +}
and also not all of them have a `color`; though that could be made optional / with a fallback I guess.

2021-04-07 11:32 UTC, merged