Add schema for downscaling on national level
minvws/nl-covid19-data-dashboard pull request #2526
Opened 2021-04-06 13:56 UTC by VWSCoronaDashboard14

Add additional properties including if it is possible to downscale for certain metrics and national level, the benchmark, and the days needed.

2021-04-06 14:35 UTC, VWSCoronaDashboard1 requested changes

2021-04-06 14:35 UTC, VWSCoronaDashboard1 commented on packages/app/schema/nl/__index.json
> +    "downscaling",
I think at first (so before the data is actually ready) we don't make the new schema's required

2021-04-06 14:35 UTC, VWSCoronaDashboard1 commented on packages/app/schema/nl/downscaling.json
> +        "is_nl_possible": {
maybe `downscalable` is a better term here?

2021-04-06 14:46 UTC, VWSCoronaDashboard14 commented on packages/app/schema/nl/__index.json
> +    "downscaling",
You are right, forgot about it.

2021-04-06 14:49 UTC, VWSCoronaDashboard1 requested changes

2021-04-06 14:49 UTC, VWSCoronaDashboard1 commented on packages/app/schema/nl/downscaling.json
> +        "days_needed_for_downscale",
`days_required_for_downscale`?

2021-04-06 14:49 UTC, VWSCoronaDashboard1 commented on packages/app/schema/nl/downscaling.json
> +        "date_of_insertion_unix"
Didn't we also need a `total_downscalable` value as well? To indicate whether downscaling is at all possible?

2021-04-06 15:04 UTC, VWSCoronaDashboard14 commented on packages/app/schema/nl/downscaling.json
> +        "date_of_insertion_unix"
My take was `is_nl_possible ` but total_downscalable is also fine.

2021-04-06 15:36 UTC, VWSCoronaDashboard8 requested changes

2021-04-06 15:36 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/downscaling.json
> +        "is_reproduction_possibile": {
typo => spell checker?

2021-04-06 15:36 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/downscaling.json
> +        "days_needed_for_downscale": {
Some suggestions: `days_measured` or `clearance_number_of_days`.

2021-04-06 15:36 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/downscaling.json
> +        },
Usually I like to start the property names with the subject and then details about the data. This nicely groups things together. I would suggest something like:

`hospital_nice_benchmark` and then `hospital_nice_is_cleared`

2021-04-06 15:36 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/downscaling.json
> +        "days_needed_for_downscale",
If you're going with is_cleared, I would suggest days_required_to_clear. Downscale then happens when multiple metrics are cleared.

2021-04-06 15:36 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/downscaling.json
> +        "date_of_insertion_unix"
Since it's not a total in the traditional sense of summing numbers I'd use a different term. Also NL is already implied by the context of the schema.

Maybe `is_downscaling_active` ?

2021-04-06 15:36 UTC, VWSCoronaDashboard8 commented on packages/common/src/types/data.ts
> +  date_of_insertion_unix: number;
You are missing date_unix or date_start/end_unix

2021-04-07 06:25 UTC, VWSCoronaDashboard14 commented on packages/common/src/types/data.ts
> +  date_of_insertion_unix: number;
@VWSCoronaDashboard8 I would assume date_start/end_unix since we talk about a timespan of the `days_required_to_clear` right now.

2021-04-07 06:38 UTC, VWSCoronaDashboard4 requested changes

2021-04-07 06:38 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/__index.json
> +    "downscaling": {
we use the name `escalation_level` for VR; perhaps name this one `escalation_level_downscaling` ?

2021-04-07 06:38 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/downscaling.json
> +        "intensive_care_nice_is_cleared": {
this is a very confusing name; a cleared IC would mean it does not contain anything; perhaps a different name than `cleared` ?

2021-04-07 06:38 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/downscaling.json
> +        "intensive_care_nice_is_cleared": {
maybe flip the logic `is_intensive_care_nice_blocked` ?

2021-04-07 06:38 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/downscaling.json
> +        "days_required_to_clear": {
if you use the other suggestion, this could become eg `days_required_to_unblock`

2021-04-07 06:38 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/downscaling.json
> +        "is_downscaling_active",
and this could become `is_downscaling_blocked`

2021-04-07 06:38 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/downscaling.json
> +        "date_of_insertion_unix"
active seems like a vague term; what is active in what manner?

2021-04-07 08:14 UTC, VWSCoronaDashboard10 approved these changes
Wonderful ✨

2021-04-07 08:14 UTC, VWSCoronaDashboard1 approved these changes

2021-04-07 08:14 UTC, VWSCoronaDashboard8 approved these changes

2021-04-07 08:14 UTC, VWSCoronaDashboard4 approved these changes

2021-04-07 08:37 UTC, merged