Add schema and basic content items to afschaling page
minvws/nl-covid19-data-dashboard pull request #2546
Opened 2021-04-07 17:57 UTC by VWSCoronaDashboard1

## Summary

This adds the schema for the bits of content needed for the Afschaling page.

## Motivation

Feature request

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-04-08 08:18 UTC, VWSCoronaDashboard8 requested changes

2021-04-08 08:18 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/documents/pages/afschaling-page.ts
> +      fieldset: 'downScaleExplanation',
in other places downscale is written as one word

2021-04-08 08:18 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/documents/pages/afschaling-page.ts
> +      fieldset: 'downScaleExplanation',
same here

2021-04-08 08:18 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/documents/pages/afschaling-page.ts
> +      fieldset: 'downScaleExplanation',
etc

2021-04-08 08:18 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/objects/binary-choice.ts
> +  of: [{ type: 'binaryChoiceOption' }],
I don't understand why the binary choice has been implemented as an array of two items that each have their own boolean value. Would one always be set to true and then the other always false? That seems like an odd API to have for something that is binary.

Was it not a possibility to have a single document with one boolean field and then title and description fields for both sides of the binary all combined?

2021-04-08 08:40 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/afschaling.tsx
> +    (_context) => `*[_type == 'afschalingPage'][0]`
The rest of the documents are named after their page as well. And camelcased. Since these page names are in Dutch (because they are also part of the route) this name is in Dutch too.

2021-04-08 08:41 UTC, VWSCoronaDashboard1 commented on packages/app/src/types/cms.d.ts
> +};
Yea, this is a mistake. This type ought to be called BinaryOption, my bad. I'll fix this.

2021-04-08 08:43 UTC, VWSCoronaDashboard1 commented on packages/app/src/types/cms.d.ts
> +  downscalePossible: [BinaryChoice, BinaryChoice];
As mentioned in the other comment, I named the type wrong. It needs to be called BinaryOption instead.

2021-04-08 08:44 UTC, VWSCoronaDashboard1 commented on packages/app/src/types/cms.d.ts
> +  measuresDescription: RichContentBlock[];
I agree, good point. I'll add this.

2021-04-08 08:46 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/objects/binary-choice.ts
> +  of: [{ type: 'binaryChoiceOption' }],
For me, a binary choice is a choice out of two options. In this case a true value and a false value.
Its implemented as an array with two items, not just an arbitrary length. Plus using constraints, it's required to have one value set to true, the other to false.

2021-04-08 13:41 UTC, VWSCoronaDashboard8 requested changes

2021-04-08 13:59 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/afschaling.tsx
> +    (_context) => `*[_type == 'afschalingPage'][0]`
no, I'm just keeping the same naming convention already in place where the schema name is the same as the page name (the .tsx name). If I change it to English now, it would mean I have to rename all of the other types as well.
This is possible, but probably better suited for a separate PR.

2021-04-08 14:01 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/fields/title-description-fields.ts
> +    title: 'Inhoud',
Because they are shared with the collapsible object. And since this object is already used across several pages changing the field names would mean having to write a migration for all those documents. That's why I chose to stick with this name.

2021-04-08 14:02 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/objects/title-description-block.ts
> +    },
Fair enough. I'll change it so it won't share code with collapsible instead.

2021-04-08 14:06 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/afschaling.tsx
> +    (_context) => `*[_type == 'afschalingPage'][0]`
As I'm tired of debating here as well, I'll rename this to downscaling

2021-04-08 14:16 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/objects/title-description-block.ts
> +    },
I don't like it either really. I'd rather write code.

2021-04-08 14:18 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/afschaling.tsx
> +    (_context) => `*[_type == 'afschalingPage'][0]`
I'll add the discussion to the backlog, because as long as there is no consistency and people do not agree on the naming convention then we keep having this type of discussions and I hate to spend time on this too.

2021-04-08 19:02 UTC, VWSCoronaDashboard10 reviewed
I think we can simplify the binaryChoice thing a lot by replacing it with two simple fields..

2021-04-08 19:02 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/pages/downscale-page.ts
> +      title: 'Uitleg wel/niet mogelijkheid tot afschalen',
In cannot think of another use case of such a binaryChoice thing, especially with the label+description fields of each option. I have the feeling the `binaryChoice` abstractions is making stuff waaay more complex than necessary. Also the Sanity UI doesn't become very user-friendly either.

With the following two fields we can achieve the same, feature-wise:

```ts
    {
      fieldset: 'downscaleExplanation',
      name: 'downscaleIsPossibleText',
      type: 'localeBlock',
      title: 'Uitleg voor geen mogelijkheid tot afschalen',
    },
    {
      fieldset: 'downscaleExplanation',
      name: 'downscaleIsNotPossibleText',
      type: 'localeBlock',
      title: 'Uitleg voor wel een mogelijkheid tot afschalen',
    },
```

The "label" property of a binary-option content can simply be written inside the localeBlock (as bold text).

2021-04-08 19:30 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/documents/pages/downscale-page.ts
> +      title: 'Uitleg wel/niet mogelijkheid tot afschalen',
Good point, but binaryChoice was already greatly simplified from the original code. If we can think of more situations where we would switch between two texts based on a boolean then I think it can't hurt to have the abstraction.

2021-04-09 07:08 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/afschaling.tsx
> +      <Box bg="white" pt="5em" pb="3em">
I took the paddings from the over.module.css (also why I didn't use the theme), because the layout of this page is similar to that page but I didn't want to resort to using global css. Are you implying that they ought to be rems?

2021-04-09 07:14 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/pages/downscale-page.ts
> +      title: 'Uitleg wel/niet mogelijkheid tot afschalen',
Maybe @VWSCoronaDashboard1 knows another situation for this abstraction?

2021-04-09 07:20 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/afschaling.tsx
> +      <Box bg="white" pt="5em" pb="3em">
I thought we only used em when the size should be related to a font size of the same element. Otherwise it could be rems, or simply grab some keys from the theme. We could also have a look at the veelgestelde-vragen pages which doesn't rely on global css anymore, might be time to create a shareable wrapper for "content" pages.

2021-04-09 07:23 UTC, VWSCoronaDashboard10 commented on packages/cms/src/schemas/documents/pages/downscale-page.ts
> +      title: 'Uitleg wel/niet mogelijkheid tot afschalen',
And I think "was already greatly simplified" isn't a very strong argument to keep it like this when there's a simpler cleaner implementation possible (or @reinier should be able to enlighten me with the current approach)

2021-04-09 09:31 UTC, merged