Provide region name for new static props builds
minvws/nl-covid19-data-dashboard pull request #257
Opened 2020-09-09 08:48 UTC by VWSCoronaDashboard4

## Summary & Motivation

The static props reverted the implementation of the names for the regions.

## Detailed design

I've added `name` as part of the props so it can be used easily.

The JSONs do not uniformly provide a proper name for the regions (and data.name is incorrect)

## Unresolved questions

Maybe the `getMunicipalityData = getSafetyRegionData` shoudl become its own implementation?

### Governance

- [x] Documentation is added
- [x] Test cases are added or updated
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-09-09 13:04 UTC, VWSCoronaDashboard1 requested changes

2020-09-09 13:04 UTC, VWSCoronaDashboard1 commented on src/static-props/safetyregion-data.ts
> +
Shouldn't this code where the region or municipal name is retrieved be split up between municipality-data.ts and safetyregions-data.ts?
One is used for the municipal pages the other for the region, so I'm not sure how this works for both. But I might be missing something...

2020-09-09 13:54 UTC, VWSCoronaDashboard1 approved these changes

2020-09-10 11:10 UTC, VWSCoronaDashboard3 approved these changes

2020-09-23 13:34 UTC, VWSCoronaDashboard8 requested changes

2020-09-23 13:34 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +  const { data, name } = props;
Name is a very vague name in this case. As is data but alas. I'd suggest `municipalityName` or something similar

2020-09-23 13:34 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/rioolwater.tsx
> +  const { data, name } = props;
Same as previous comment

2020-09-23 13:34 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/ziekenhuis-opnames.tsx
> +  const { data, name } = props;
...etc

2020-09-23 13:34 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +  const { data, name } = props;
etc

2020-09-23 13:34 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/rioolwater.tsx
> +  const { data, name } = props;
almost there...

2020-09-23 13:34 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/ziekenhuis-opnames.tsx
> +  const { data, name } = props;
last one I hope :)

2020-09-23 13:34 UTC, VWSCoronaDashboard8 commented on src/static-props/municipality-data.ts
> +
These types look funky. Do we need props wrapped in props and params wrapped in params? Why not directly use IMunicipalityData without wrapping it in a new interface?

And for IParams why not use:

```
interface IParams {
  code: string;
}
```

2020-10-05 13:46 UTC, VWSCoronaDashboard4 commented on src/static-props/municipality-data.ts
> +
This structure is taken from the other file, region-data.ts, since the method getMunicipalityData previously proxied to it; If we want to adjust this, let's do so in a separate PR.

2020-10-05 13:50 UTC, VWSCoronaDashboard1 approved these changes

2020-10-05 13:52 UTC, merged