Add a deploy button in the CMS dashboard
minvws/nl-covid19-data-dashboard pull request #2622
Opened 2021-04-14 11:13 UTC by VWSCoronaDashboard

## Summary

This PR adds a button in the Sanity Dashboard where content managers can trigger a new deploy to staging/production.

It uses `sanity-secrets` to keep sensitive data safe.

## Motivation

The less developers need to be involved with releases, and the more we empower content managers, the better!

2021-04-14 11:15 UTC, VWSCoronaDashboard14 commented on packages/cms/plugins/sanity-deploy-button/index.js
> +  console.log({ secrets });
Log

2021-04-14 11:18 UTC, VWSCoronaDashboard1 requested changes

2021-04-14 11:18 UTC, VWSCoronaDashboard1 commented on packages/cms/plugins/sanity-deploy-button/index.js
> +  },
Please convert this file to typescript ;)

2021-04-14 11:48 UTC, VWSCoronaDashboard10 requested changes

2021-04-14 11:48 UTC, VWSCoronaDashboard10 commented on packages/cms/src/plugins/sanity-deploy-button/index.js
> +  }
What is the added value of that `get-it` dependency over plain fetch?

```tsx
try {
  const request = await window.fetch(secrets.webhookUrl)
  const response = await request.json()
  setData(response)
} catch(errpr) {
  setError(error)
}
```

2021-04-14 11:48 UTC, VWSCoronaDashboard10 commented on packages/cms/src/plugins/sanity-deploy-button/index.js
> +import React, { useState } from 'react';
can you convert the javascript to typescript?

2021-04-14 11:48 UTC, VWSCoronaDashboard10 commented on packages/cms/src/plugins/sanity-deploy-button/index.js
> +  // }, [secrets]);
comments

2021-04-14 11:51 UTC, VWSCoronaDashboard commented on packages/cms/src/plugins/sanity-deploy-button/index.js
> +  }
None. Copy pasted it from the example. I'm refactoring it to use fetch.

2021-04-14 11:51 UTC, VWSCoronaDashboard commented on packages/cms/src/plugins/sanity-deploy-button/index.js
> +import React, { useState } from 'react';
Yep.

2021-04-14 11:53 UTC, VWSCoronaDashboard commented on packages/cms/src/plugins/sanity-deploy-button/index.js
> +  }
Solved!

2021-04-14 11:53 UTC, VWSCoronaDashboard commented on packages/cms/src/plugins/sanity-deploy-button/index.js
> +  // }, [secrets]);
Keeping it here so you know how to change the secrets in the future.

2021-04-14 12:02 UTC, VWSCoronaDashboard10 commented on packages/cms/package.json
> +    "get-it": "^4.1.4",
you can get rid of the dependency

2021-04-14 12:02 UTC, VWSCoronaDashboard10 commented on packages/cms/src/plugins/sanity-deploy-button/index.tsx
> +      });
nothing should happen on fail or success of the request?

2021-04-14 12:03 UTC, VWSCoronaDashboard10 commented on packages/cms/src/plugins/sanity-deploy-button/index.tsx
> +  const { secrets }: { secrets: Secrets } = useSecrets(namespace);
this might read easier:
```suggestion
  const secrets = useSecrets(namespace).secrets as Secrets;
```

2021-04-14 12:05 UTC, VWSCoronaDashboard10 commented on packages/cms/src/plugins/sanity-deploy-button/index.tsx
> +          production. You should do this if you've published new content in
staging or production?
```suggestion
          staging. You should do this if you've published new content in
```

2021-04-14 12:06 UTC, VWSCoronaDashboard10 commented on packages/cms/src/plugins/sanity-deploy-button/index.tsx
> +        <h2 className={styles.title}>Deploy to production</h2>
staging or production?
```suggestion
        <h2 className={styles.title}>Deploy to staging</h2>
```

2021-04-15 07:52 UTC, VWSCoronaDashboard commented on packages/cms/src/plugins/sanity-deploy-button/index.tsx
> +      });
No, there's no feedback mechanism in place yet. At some point it would be great if we can embed the latest CI checks from GitHub in there as feedback.

2021-04-15 07:53 UTC, VWSCoronaDashboard commented on packages/cms/src/plugins/sanity-deploy-button/index.tsx
> +      });
Context: we're triggering a pretty minimal webhook that has no succes and error states defined yet. It either works or it doesn't and GitHub is the only place to see if it works.

2021-04-15 08:44 UTC, merged