Update Tile components to be a functional component
minvws/nl-covid19-data-dashboard pull request #2635
Opened 2021-04-15 14:21 UTC by VWSCoronaDashboard14

This started with the bug on the background of the article strip, where I had to refactor some small things to not rely on CSS set directly on the component.

2021-04-15 14:30 UTC, VWSCoronaDashboard1 requested changes

2021-04-15 14:30 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/tile.tsx
> +  isContentHeight?: boolean;
I guess `hasContentHeight` is more correct?

2021-04-15 14:37 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/tile.tsx
> +  isContentHeight?: boolean;
Why didn't I think of that ❓

2021-04-16 09:17 UTC, VWSCoronaDashboard8 approved these changes

2021-04-16 09:17 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/tile.tsx
> +  hasBlueBackground?: boolean;
We don't actually use the normal boolean naming pattern for props, because then they align with html elements better (a decision I possibly regret) but in that sense this prop could be `blueBackground`

2021-04-16 09:17 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/tile.tsx
> +  hasContentHeight?: boolean;
I think we can find a better name for this. Content always has a height to it, and so I don't know what this means when I read it.

2021-04-16 09:17 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/tile.tsx
> +    height: x.hasContentHeight ? '100%' : undefined,
Maybe `isFullHeight` or `isParentHeight`? The is part you can drop see earlier comment.

2021-04-16 09:19 UTC, VWSCoronaDashboard10 approved these changes
Approved, though I'd like to see the `hasContentHeight` prop being renamed.

2021-04-16 09:19 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/kpi-tile.tsx
> +    <Tile hasContentHeight>
I don't think `hasContentHeight` means `height='100%`. I'd rather see it named something like `isFullHeight` or, maybe better, even just keep the `height` props as is and pass it on to the styled component:
```diff
<StyledTile
      hasBlueBackground={hasBlueBackground}
-      hasContentHeight={hasContentHeight}
+      height={height}
    >
```

And to be honest: I think the height should actually be mutated by styles of the parent component of a tile but that's maybe too much refactoring for this PR.

2021-04-16 09:19 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/anchor-tile.tsx
> +    // spacing: 2,
comment

2021-04-16 09:19 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/anchor-tile.tsx
> +    pt: asResponsiveArray({ _: 3, lg: undefined }),
```suggestion
    pt: asResponsiveArray({ _: 3, lg: 0 }),
```

2021-04-16 09:19 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/anchor-tile.tsx
> +    mt: asResponsiveArray({ _: 3, md: undefined }),
```suggestion
    mt: asResponsiveArray({ _: 3, md: 0 }),
```

2021-04-16 09:19 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/tile.tsx
> +  hasBlueBackground,
nit; Instead of the `hasBlueBackground` prop we could also think about exporting a `<BlueTile />` component. Do whatever feels best.

2021-04-16 09:54 UTC, VWSCoronaDashboard1 approved these changes

2021-04-16 10:02 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/tile.tsx
> +  hasBlueBackground?: boolean;
ehhhm, that's a rule we came up with in another project, but AFAIK we do use the `is` pattern for booleans currently? Or am I mistaken?

2021-04-16 10:28 UTC, VWSCoronaDashboard10 requested changes

2021-04-16 10:28 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/tile.tsx
> +    height: x.height ? x.height : undefined,
fallback to undefined is unnecessary and would even fail when it equals `0` (`height={0}`)
```suggestion
    height: x.height,
```

2021-04-16 11:37 UTC, VWSCoronaDashboard10 approved these changes

2021-04-19 13:15 UTC, merged