Add explicit data selection to all metric pages
minvws/nl-covid19-data-dashboard pull request #2669
Opened 2021-04-20 09:21 UTC by VWSCoronaDashboard1

## Summary

This PR adds functionality that allows each metric page to explicitly select only the properties from a data file (nl.json, vr**json, gm**.json). This prevents the entire data file to be included in the HTML, which yields quite a significant size reduction.

For example, these are some VR pages before:
![regio_html_build_before](https://user-images.githubusercontent.com/69849293/115370939-d6d95d80-a1c9-11eb-8ba8-e71a8720f32b.png)
and this is after:
![regio_html_build_after](https://user-images.githubusercontent.com/69849293/115370993-e48ee300-a1c9-11eb-90fa-fea01f763a7a.png)

And here are the regional actueel pages before:
![actueel_html_build_before](https://user-images.githubusercontent.com/69849293/115371136-01c3b180-a1ca-11eb-8d0e-bfcf2a8b0d0e.png)
and after:
![actueel_html_build_after](https://user-images.githubusercontent.com/69849293/115371170-08522900-a1ca-11eb-9bf0-a65e6811cded.png)

## Motivation

Optimization.

## Detailed design

Instead of, for example, using the `getNlData` method, a new method called `selectNlPageMetricData` is introduced. This method returns all of the default National data that is required on each national metric page. Because the sidebar needs all of those properties. This method accepts an optional list of additional metric names which will be added to the output. This way a page can select exactly what it needs and no more.

## Drawbacks

It adds a bit of verbosity. Before we just pushed the entire data file (National, Regionaal or Municipal) in some components, but now things have to be defined a little bit more explicitly. The size improvements are worth it though, IMHO.

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-04-21 12:11 UTC, VWSCoronaDashboard8 reviewed
Nice to have these things typed and filtered 💯

2021-04-21 12:11 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/verpleeghuiszorg.tsx
> +  selectVrPageMetricData()
No metrics on this page?

2021-04-21 12:11 UTC, VWSCoronaDashboard8 commented on packages/app/src/static-props/get-data.ts
> + * optional extra metric property names can be added as separate arguments which will
Right, now I get the empty function calls

2021-04-21 12:11 UTC, VWSCoronaDashboard8 commented on packages/app/src/static-props/get-data.ts
> +  return selectNlData(...[...nationalPageMetricNames, ...additionalMetrics]);
nit; Would this work too?

```suggestion
  return selectNlData(...nationalPageMetricNames, ...additionalMetrics);
```

2021-04-21 12:11 UTC, VWSCoronaDashboard8 commented on packages/app/src/static-props/get-data.ts
> +export function selectNlData<T extends keyof National = never>(
What is the function of never here?

2021-04-21 12:11 UTC, VWSCoronaDashboard8 commented on packages/app/src/static-props/get-data.ts
> +    const selectedNlData = {} as Pick<National, T>;
nit; It's a little strange to declare the type like this when you still need to construct its contents. I would find it more logical to cast the return value, when it's ready.

2021-04-21 12:13 UTC, VWSCoronaDashboard8 approved these changes

2021-04-21 13:22 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/data-driven-text.tsx
> +  : never;
I'll add a comment in the file. In short, this typing makes sure that assign a metricName of `keyof National` that the data property needs to be of type `Pick<National, 'difference' | T>`. If the metricName is `keyof Regionaal`, then the data property needs to be of type `Pick<Regionaal, 'difference' | T>`, etc

2021-04-21 13:24 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +  return selectNlData(...[...nationalPageMetricNames, ...additionalMetrics]);
For some reason it doesn't, the compiler complains about it.

2021-04-21 13:24 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +export function selectNlData<T extends keyof National = never>(
This forces the selectNlData method to be called with at least 1 rest parameter

2021-04-21 13:24 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +    const selectedNlData = {} as Pick<National, T>;
Fair enough

2021-04-21 13:25 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +export function selectNlData<T extends keyof National = never>(
Since T is inferred from the rest parameters. If you default the generic to never, it will infer to never if you don't supply any arguments.

2021-04-21 15:48 UTC, VWSCoronaDashboard8 requested changes

2021-04-21 15:48 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/layout/municipality-layout.tsx
> +export type GMPageMetricNames = typeof gmPageMetricNames[number];
Please write acronyms as normal words. We do that in other places too

```suggestion
export type GmPageMetricNames = typeof gmPageMetricNames[number];
```

2021-04-21 15:48 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/layout/national-layout.tsx
> +export type NLPageMetricNames = typeof nlPageMetricNames[number];
Same comment

2021-04-21 15:48 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/layout/safety-region-layout.tsx
> +export type VRRegionPageMetricNames = typeof vrPageMetricNames[number];
You get my point :)

2021-04-21 15:48 UTC, VWSCoronaDashboard8 commented on packages/app/src/static-props/get-data.ts
> +    const selectedVrData: Record<string, any> = {};
Ah bummer I didn't realize you then also had to type this still. You can probably use string, unknown :)

2021-04-21 16:00 UTC, VWSCoronaDashboard8 commented on packages/app/src/static-props/get-data.ts
> +    const selectedVrData: Record<string, any> = {};
You could avoid using a temporary variable by using reduce. This is using lodash set:

```suggestion
    const selectedVrData: Pick<Regionaal, T> = metrics.reduce((acc, p) => set(acc, p, vrData.data[p]), {})
```

2021-04-21 16:56 UTC, VWSCoronaDashboard8 approved these changes

2021-04-23 12:46 UTC, VWSCoronaDashboard4 approved these changes
:100:

2021-04-23 13:01 UTC, VWSCoronaDashboard10 approved these changes

2021-04-23 13:01 UTC, VWSCoronaDashboard10 commented on packages/app/src/static-props/get-data.ts
> +  return selectVrData(...[...vrPageMetricNames, ...additionalMetrics]);
```suggestion
  return selectVrData(...vrPageMetricNames, ...additionalMetrics);
```

2021-04-23 13:01 UTC, VWSCoronaDashboard10 commented on packages/app/src/static-props/get-data.ts
> +  return selectGmData(...[...gmPageMetricNames, ...additionalMetrics]);
```suggestion
  return selectGmData(...gmPageMetricNames, ...additionalMetrics);
```

2021-04-23 13:11 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +  return selectVrData(...[...vrPageMetricNames, ...additionalMetrics]);
Alas, the compiler doesn't agree with this. I don't understand why, but it has something to do with the fact these are rest parameters...

2021-04-23 13:11 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +  return selectGmData(...[...gmPageMetricNames, ...additionalMetrics]);
same as my previous comment

2021-04-23 13:11 UTC, merged