Hospital Admissions per age group charts
minvws/nl-covid19-data-dashboard pull request #2672
Opened 2021-04-20 10:34 UTC by VWSCoronaDashboard13

## Summary

Adding overall and intensive care admission per age group charts

## Detailed design

Created a `hospital` domain that houses the `admissions-per-age-group` chart which accepts `NlIntensiveCareNicePerAgeGroupValue` and `NlHospitalNicePerAgeGroupValue` since both of them are the same structure allowing us to use this in both places. 

Also added the copy in the following structure
```  "hospital_admissions_per_age_group": {
    "overall_chart_title": "...",
    "overall_chart_description": "...",
    "ic_chart_title": "...",
    "ic_chart_description": "...",
    "legend": {
      "admissions_age_0_19_per_million": "0-19",
      "admissions_age_20_29_per_million": "20-29",
      "admissions_age_30_39_per_million": "30-39",
      "admissions_age_40_49_per_million": "40-49",
      "admissions_age_50_59_per_million": "50-59",
      "admissions_age_60_69_per_million": "60-69",
      "admissions_age_70_79_per_million": "70-79",
      "admissions_age_80_89_per_million": "80-89",
      "admissions_age_90_plus_per_million": "90+",
      "admissions_overall_per_million": "Alle leeftijden"
    },
    "legend_help_text": "...",
    "line_chart_legend_inaccurate_label": "...",
    "tooltip_labels": {
      "inaccurate": "..."
    }
  },```

Dummy data isn't perfect, but it's better than previous iterations 😬

## Alternatives

Make separate charts for ic and overall - I think this isn't necessary until there are notable differences between the two

2021-04-20 10:47 UTC, VWSCoronaDashboard1 approved these changes

2021-04-21 10:07 UTC, VWSCoronaDashboard10 approved these changes

2021-04-21 10:37 UTC, VWSCoronaDashboard8 requested changes

2021-04-21 10:37 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/en.json
> +    "ic_chart_description": "Deze grafiek laat zien hoeveel mensen met het coronavirus in een bepaalde leeftijdsgroep in het ziekenhuis zijn opgenomen. In de grafiek worden weektotalen getoond die zi
"hospital" and "ic" are two separate data subjects within our application, and they do not overlap even though ic can be seen as part of a hospital of course. 

So it seems there's a little mixup / confusion here with the keys.

2021-04-21 10:37 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/hospital/admissions-per-age-group/admissions-per-age-group.tsx
> +}
This chart contains a lot of logic related to config and legends. The interactive legend was an afterthought, so I think we will have to take a closer look at improving abstractions to related components, because this feels too much like a workaround for something that could be solved elsewhere.

Entirely not your fault of course. I think you did a great job here. I'll add this to the tech-dept backlog.

2021-04-22 14:50 UTC, VWSCoronaDashboard13 commented on packages/app/src/locale/en.json
> +    "ic_chart_description": "Deze grafiek laat zien hoeveel mensen met het coronavirus in een bepaalde leeftijdsgroep in het ziekenhuis zijn opgenomen. In de grafiek worden weektotalen getoond die zi
When you say `data subjects` are you referring to the different tabs in the side bar and how does that inform how it is structured in the locale files? I just put them together because the graph is shared between the two and they are related in that they are grouped together in the sidebar

Would something like this be better?
```
"hospital_admissions_per_age_group_chart": {
    chart text...
},
"hospital_admissions_per_age_group": {
   "chart_title": "...",
   "chart_description": "...",
},
"ic_admissions_per_age_group": {
   "chart_title": "...",
   "chart_description": "...",
},
```

2021-04-22 16:19 UTC, VWSCoronaDashboard8 commented on packages/app/src/locale/en.json
> +    "ic_chart_description": "Deze grafiek laat zien hoeveel mensen met het coronavirus in een bepaalde leeftijdsgroep in het ziekenhuis zijn opgenomen. In de grafiek worden weektotalen getoond die zi
Yes that looks good to me 👍  With subjects I mean the first name by which we group data/properties on the root level in the schema files. So for NL.json for example you have different data sets starting with hospital_ and ic_ and sewer_ etc. In that sense hospital and ic are considered two different / independent sources of data.

2021-04-23 09:03 UTC, VWSCoronaDashboard13 commented on packages/app/src/locale/en.json
> +    "ic_chart_description": "Deze grafiek laat zien hoeveel mensen met het coronavirus in een bepaalde leeftijdsgroep in het ziekenhuis zijn opgenomen. In de grafiek worden weektotalen getoond die zi
makes sense 👍

2021-04-23 14:59 UTC, VWSCoronaDashboard8 approved these changes

2021-04-28 09:36 UTC, merged