Add moving average to testing graphs
minvws/nl-covid19-data-dashboard pull request #2676
Opened 2021-04-20 14:43 UTC by VWSCoronaDashboard13

## Summary

Added moving average to testing graphs on NL, VR, and G

Also added new copy 🤼

2021-04-20 14:48 UTC, VWSCoronaDashboard1 approved these changes

2021-04-21 09:58 UTC, VWSCoronaDashboard10 approved these changes
Approved, but please have a look at this comment on a different PR https://github.com/minvws/nl-covid19-data-dashboard/pull/2677#discussion_r617377780

2021-04-21 10:44 UTC, VWSCoronaDashboard8 approved these changes

2021-04-28 09:22 UTC, VWSCoronaDashboard8 requested changes

2021-04-28 09:22 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +                        .infected_per_100k_moving_average,
The label text shows up in the legend + the tooltip by default. The shortLabel property is used to overrule that for the tooltip.  So passing a text which is meant for the tooltip to `label` is confusing and not entirely correct.

2021-04-28 09:23 UTC, VWSCoronaDashboard8 approved these changes

2021-04-28 09:23 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +                        .infected_per_100k_moving_average,
Never mind I see that this mistake has been made before already. I will add it to the tech dept. We'll fix this later

2021-05-10 12:52 UTC, merged