Feature/7 days average disability care living at home
minvws/nl-covid19-data-dashboard pull request #2680
Opened 2021-04-21 09:17 UTC by VWSCoronaDashboard14

Add moving averages for disability care and elderly at home.
Could have added the 7 days average label text in a more common way in Lokalise, but this gives them the flexibility to change it per graph if needed.

2021-04-21 09:30 UTC, VWSCoronaDashboard1 approved these changes

2021-04-21 11:05 UTC, VWSCoronaDashboard8 approved these changes

2021-04-28 09:17 UTC, VWSCoronaDashboard8 requested changes

2021-04-28 09:17 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/gehandicaptenzorg.tsx
> +                      positiveTestedPeopleText.tooltip_labels
This is not the place to pass tooltip labels. These show up in the legend + the tooltip _if_ there is no shortLabel set. So tooltip labels should go in `shortLabel`.

I think that means you still need to create `_moving_average` texts for labelling the average trends in the legend. Similar to what is done in #2676

2021-04-28 09:19 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/gehandicaptenzorg.tsx
> +                      positiveTestedPeopleText.tooltip_labels
I see that there are some similar mistakes in that PR as well.

2021-04-28 09:25 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/gehandicaptenzorg.tsx
> +                      positiveTestedPeopleText.tooltip_labels
These mistakes date back even further, so I will just add this to tech dept. But if you can still fix this for your texts in this PR that would be appreciated.

2021-04-28 11:17 UTC, VWSCoronaDashboard8 approved these changes

2021-04-28 13:07 UTC, merged