Handle null values in the tooltip for the timeSeriesChart
minvws/nl-covid19-data-dashboard pull request #2682
Opened 2021-04-21 11:24 UTC by VWSCoronaDashboard14

Render `-` when a null value is passed in the tooltip

2021-04-21 12:42 UTC, VWSCoronaDashboard1 requested changes

2021-04-21 12:42 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +    if (numberValue === null) return '-';
```suggestion
    if (numberValue === null) return '-';

    return isPresent(numberValue)
      ? isPercentage
        ? `${formatPercentage(numberValue)}%`
        : formatNumber(numberValue)
      : '-';
  }```

2021-04-21 15:40 UTC, VWSCoronaDashboard8 requested changes

2021-04-21 15:40 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +    if (numberValue === null) return '-';
isPresent is already catching null values. So I think we only need this part. Otherwise the second isPresent is only catching undefined and the checks are partially redundant.

```suggestion
    return isPresent(numberValue)
      ? isPercentage
        ? `${formatPercentage(numberValue)}%`
        : formatNumber(numberValue)
      : '-';
```

2021-04-22 09:13 UTC, VWSCoronaDashboard8 approved these changes

2021-04-23 13:03 UTC, VWSCoronaDashboard1 approved these changes

2021-04-26 07:13 UTC, merged