Move touch bar above the markers for the vaccine area graph
minvws/nl-covid19-data-dashboard pull request #2751
Opened 2021-04-30 11:03 UTC by VWSCoronaDashboard14

2021-04-30 11:16 UTC, VWSCoronaDashboard1 approved these changes

2021-05-05 12:40 UTC, VWSCoronaDashboard8 approved these changes

2021-05-10 10:47 UTC, VWSCoronaDashboard10 approved these changes

2021-05-10 14:30 UTC, VWSCoronaDashboard10 requested changes
I don't think this isn't the right solution. It looks like something is going wrong with the nearest point calculations, I guess it would be most efficient to have @VWSCoronaDashboard1 pick this up.

2021-05-12 19:10 UTC, VWSCoronaDashboard10 commented
closed in favor of #2835

2021-05-12 19:10 UTC, closed without merging