Rethink text sync strategy
minvws/nl-covid19-data-dashboard pull request #2756
Opened 2021-04-30 14:34 UTC by VWSCoronaDashboard8

## Summary

There were some oversights in the sanity lokalize text sync strategies. Texts that get deleted via the CLI can not actually be deleted straight-away from the development dataset without breaking other branches. This PR aims to solve those issues.

- CLI delete-text now marks the text for deletion, but actual deletion is postponed until the feature branch gets merged.
- The collapse mutations logic now clips at 1 delete action, because without deleting the actual text document you could easily run the delete command on the same key multiple times (which would create edge cases when synced)
- The `sync-additions` script is now named `sync-after-feature` because it now applies deletions to development, and additions to production.
- The `sync-deletions` script is now named `sync-after-release` because it now also includes clearing the mutations log. And then it's clear when the script should be ran.
- The `lokalize:import` script is removed from package.json as we should not ever need to run it anymore

@TODO the sync-after-feature script should be triggered from github actions, but I think it requires special access as it applies deletions. So I'll leave that for a different PR.

2021-04-30 16:34 UTC, VWSCoronaDashboard1 approved these changes

2021-04-30 16:34 UTC, VWSCoronaDashboard1 commented on packages/cms/src/lokalize/logic/mutations.ts
> +   * dataset.
```suggestion
   * for later. We still need to mark the keys that were first newly created, but
   * later deleted as action "delete" otherwise they will not be removed from the
   * dataset.
```

2021-05-03 09:40 UTC, VWSCoronaDashboard10 requested changes

2021-05-03 09:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/sync-after-feature.ts
> +  }
How does this prompts thing work when the script is called on gh actions?

2021-05-03 09:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/sync-after-feature.ts
> +    .map(({ key }) => allTextDocuments.find((x) => x.key === key))
Here's a bug because the query also includes drafts. Drafts should also be removed, and the client-facing bug is that delete only deletes a draft if that document is found earlier.

I think we should delete both drafts as documents.
```suggestion
    .flatMap(({ key }) => allTextDocuments.filter(x) => x.key === key))
```

2021-05-03 09:40 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/sync-after-feature.ts
> +  if (documentIdsToDelete.length !== deletions.length) {
This check will fail when we include drafts

2021-05-03 09:55 UTC, VWSCoronaDashboard8 commented on packages/cms/src/lokalize/sync-after-feature.ts
> +  }
Eeh I guess how it works is it doesn't 😅

2021-05-03 09:56 UTC, VWSCoronaDashboard8 commented on packages/cms/src/lokalize/sync-after-feature.ts
> +    .map(({ key }) => allTextDocuments.find((x) => x.key === key))
I wasn't aware that drafts are separate documents.

2021-05-03 10:26 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/sync-after-feature.ts
> +    .map(({ key }) => allTextDocuments.find((x) => x.key === key))
yep I think they are basically copies of the original document but the `id` is prepended with `drafts.`

2021-05-03 12:04 UTC, VWSCoronaDashboard8 commented on packages/cms/src/lokalize/sync-after-feature.ts
> +    .map(({ key }) => allTextDocuments.find((x) => x.key === key))
I think the easiest solution is to just not inject drafts from development into production. I think the mental model is a bit easier then. Otherwise the draft and published documents will both show up in the list of new documents on production.

2021-05-03 12:24 UTC, VWSCoronaDashboard10 approved these changes

2021-05-03 12:58 UTC, merged