Improve tooltip jumping on TimeSeriesChart
minvws/nl-covid19-data-dashboard pull request #2757
Opened 2021-04-30 16:07 UTC by VWSCoronaDashboard13

## Summary

Reduce tooltip width changes when hovering on TimeSeriesCharts

## Motivation

Tooltip was changing inside depending on the size of its' content which didn't look very smooth

## Detailed design

Moved the string formatting logic to hooks in the `formatStrings` file in the tooltip directory so it could be used in the time-series-chart to calculate the width of values

Found the largest number of characters that could be shown in the value and set that as the min width for all of the values

## Drawbacks

Doesn't calculate the width for each series individually, but I think this is sufficient and simpler

2021-04-30 17:54 UTC, VWSCoronaDashboard1 approved these changes

2021-04-30 17:54 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/tooltip/formatStrings.ts
> +export function useGetValueString() {
I'm not sure if it's absolutely necessary to wrap all of these in a useCallback. From what I understand the useCallback hook is specifically meant for functions that are passed down as component props:
https://aheadcreative.co.uk/articles/when-to-use-react-usecallback/

2021-05-03 07:32 UTC, VWSCoronaDashboard13 commented on packages/app/src/components/time-series-chart/components/tooltip/formatStrings.ts
> +export function useGetValueString() {
yeah, I can see how it doesn't make sense for this use case. I'll remove them 👍

2021-05-03 07:39 UTC, VWSCoronaDashboard8 requested changes

2021-05-03 07:39 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/tooltip/formatStrings.ts
> +import { useIntl } from '~/intl';
We choose to not camel-case file names

2021-05-03 07:39 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/tooltip/formatStrings.ts
> +export function useGetValueString() {
I don't yet see the point in applying useCallback either. Not in the way the functions are use now. Possibly if these are expected to be moved to a more common location and passed down via props it would be useful, but I suggest to keep it simple for now.

Having all these separate hooks is a little verbose. I think they can be a combined in a single hook which exposes a few utility functions. (See later comment also)

2021-05-03 07:39 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +  const getDateStringFromValue = useGetDateStringFromValue();
I think it would be a little cleaner if you combined these into one hook which returns the three function together like `useStringFormatting `

2021-05-03 07:39 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +                    {getValueString(
If you typed the function using generics passed to the hook the same way as the original code, you wouldn't need to cast it here. I think that would be cleaner, or is there a specific reason you choose to not do this?

Something like this

`const {getValueString, getRangeValueString, getDateStringFromValue} = useStringFormatting<T>()`

2021-05-03 07:39 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/tooltip/types.ts
> +   * tooltip content does not change in width due to differeing value lengths
nit; typo

2021-05-03 07:39 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +  useGetValueString,
Since these hooks are located in the tooltip subfolder but are used here in the root component I'd suggest to move them to `time-series-chart/logic` or `time-series-chart/hooks` or something similar.

2021-05-03 07:39 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +
It seems unnecessary to expose all this code in the root component. I think this is a perfect candidate for a `useValueWidth()` hook.

2021-05-03 07:47 UTC, VWSCoronaDashboard13 commented on packages/app/src/components/time-series-chart/components/tooltip/formatStrings.ts
> +import { useIntl } from '~/intl';
oops sorry!

2021-05-03 07:47 UTC, VWSCoronaDashboard13 commented on packages/app/src/components/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +  const getDateStringFromValue = useGetDateStringFromValue();
that would be much cleaner 👍

2021-05-03 08:08 UTC, VWSCoronaDashboard13 commented on packages/app/src/components/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +                    {getValueString(
I just thought the functions didn't need to be aware of the specific types used for the graph since they are just doing string formatting so it would be a bit cleaner to make them dumber so we could reduce the params as well. I can change it back to how it used to be if that's preferred though

2021-05-04 16:11 UTC, VWSCoronaDashboard1 approved these changes

2021-05-05 12:37 UTC, VWSCoronaDashboard8 approved these changes

2021-05-05 12:37 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +                    {getValueString(
I agree that the functions should not have to care about the type. Unfortunately the value object is not typed accurately as an escape hatch for other code and therefor the casting is required. With all the casting going on it looks quite messy, but yeah the problem should ideally be fixed elsewhere. 

So I'm fine if you leave it like this. We'll could look into improving the typing of `value` as a separate task

2021-05-05 12:49 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/logic/use-value-width.ts
> +        })
I think we could create a formatter function which does exactly this selected range ☝️ .
The formatSeriesValue can be used in this useValueWidth-hook and also in the tooltip series list to prevent all the type castings. Extra advantage is that the output in the DOM and the calculations of the longest value use the same output.

```tsx
  function formatSeriesValue(
    value: T,
    config: SeriesConfig<T>[number],
    isPercentage?: boolean
  ) {
    switch (config.type) {
      case 'line':
      case 'area':
      case 'bar':
      case 'stacked-area':
      case 'invisible':
        return getValueString(
          (value[config.metricProperty] as unknown) as number | null,
          isPercentage
        );
      case 'range':
        return getRangeValueString(
          (value[config.metricPropertyLow] as unknown) as number | null,
          (value[config.metricPropertyHigh] as unknown) as number | null,
          isPercentage
        );
    }
  }
```

2021-05-05 12:49 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/tooltip/tooltip-series-list.tsx
> +                    {getValueString(
See my comment on `use-value-width.tsx` for a prettier solution, it would boil down to this call:
```tsx
{formatSeriesValue(value, x, options.isPercentage)}

2021-05-10 09:35 UTC, VWSCoronaDashboard13 commented on packages/app/src/components/time-series-chart/logic/use-value-width.ts
> +        })
this is great suggestion 💯

2021-05-10 10:14 UTC, VWSCoronaDashboard10 approved these changes
looking good,  couple of nitpicks left but you have my approval.

2021-05-10 10:14 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/logic/use-string-formatting.ts
> +    };
nit; I think this date string formatter is very specific and it's also only called once. I'd suggest moving it back to its original location. The `use-string-formatting` could be renamed to the single formatter function it currently is..

```tsx
// use-format-series-values.tsx

export function useFormatSeriesValue( value, config, isPercentage) { ... }

2021-05-10 10:14 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/logic/use-value-width.ts
> +    });
nit; not sure the impact on performance, but this can create a very long array. We could call Math.max more often;
```suggestion
    const valueLengths: number[] = [];
    seriesConfig.forEach((config) => {
      return valueLengths.push(
        Math.max(...values.map(
          (value) => formatSeriesValue(value, config, isPercentage).length
        ))
      );
    });
```

2021-05-11 09:44 UTC, merged