Add schema deceased_rivm__covid_daily
minvws/nl-covid19-data-dashboard pull request #2765
Opened 2021-05-03 12:25 UTC by VWSCoronaDashboard14

2021-05-03 13:00 UTC, VWSCoronaDashboard4 approved these changes

2021-05-05 12:48 UTC, VWSCoronaDashboard8 approved these changes

2021-05-05 12:53 UTC, VWSCoronaDashboard8 requested changes

2021-05-05 12:53 UTC, VWSCoronaDashboard8 commented on packages/app/schema/gm/__difference.json
> +    "deceased_rivm__covid_daily_moving_average": {
See https://github.com/minvws/nl-covid19-data-dashboard/pull/2776#discussion_r626535610

2021-05-05 16:44 UTC, VWSCoronaDashboard8 approved these changes

2021-05-10 09:23 UTC, merged