Add moving averages in difference components
minvws/nl-covid19-data-dashboard pull request #2786
Opened 2021-05-05 08:10 UTC by VWSCoronaDashboard14

- Add new text to the homepage that indicates the moving average
- an option to add a moving average to an kpi bar scale (what would change the text)
- Sidebar differences has been changed for certain metrics

2021-05-06 12:12 UTC, VWSCoronaDashboard8 requested changes

2021-05-06 12:12 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/difference-indicator.tsx
> +  absoluteMovingAverage?: number;
I don't understand this. The difference indicator is able to show the difference based on value. It can be any number and ideally it should be agnostic to what that number means. 

Why do we need an extra property to pass in a moving average? 

And what does it mean that this value is absolute? Isn't a difference indicator by definition relative, because it is displaying a value in relation to another?

2021-05-06 12:12 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/difference-indicator.tsx
> +      );
I don't think this is the way to go. If you need a special component for a difference indicator that is substantially different from the original one, I suggest to fork it and name it something like `MovingAverageDifferenceIndicator`.

But the original indicator was just about the graphic, and did not include text. So I doubt if it is even a good idea to create an indicator that has text inlined. Can't we just handle the text outside the indicator like we do with the others?

2021-05-06 12:12 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/ziekenhuis-opnames.tsx
> +                differenceKey="hospital_nice__admissions_on_date_of_reporting_moving_average_moving_average"
This seems like a typo

2021-05-06 12:12 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +                absoluteMovingAverage={
Ah I get the naming now. You want to pass in the current value to show in the display. Then in the context of the difference indicator it doesn't care if this value is  related to moving average. It is related to the difference value no matter what that is.

So I would suggest to call it `currentValue` or `currentAbsoluteValue`, because `current` is a more important distinction than `moving average`

2021-05-06 12:13 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/difference-indicator.tsx
> +  absoluteMovingAverage?: number;
I get it now, the name is just not ok see later comments

2021-05-06 12:16 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/difference-indicator.tsx
> +      );
This could be ok if you pass in the value as "current" to make it generic, but then I think you also need to pass in the text to keep it generic, since you can't tie this component to specific moving average text. 

If possible I would create a separate component to display the current value + text for the moving average, and render that inline next to this component, because this seems to violate the "separation of concerns" principle.

2021-05-06 12:43 UTC, VWSCoronaDashboard14 commented on packages/app/src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +                absoluteMovingAverage={
Thanks for the feedback! I wasn't totally done yet but seems like I have to shuffle a couple of things. Yeah the difference text needs a couple of extra metrics now see screenshot below.

![Screenshot 2021-05-06 at 14 41 55](https://user-images.githubusercontent.com/76471292/117299924-524d3700-ae79-11eb-97c6-2fdd73c77832.png)

2021-05-06 13:32 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +                absoluteMovingAverage={
👍 Looks good. If you're not done yet maybe make it a draft PR ;)

2021-05-11 08:15 UTC, VWSCoronaDashboard8 approved these changes

2021-05-11 09:11 UTC, VWSCoronaDashboard4 approved these changes

2021-05-11 09:58 UTC, merged