FAQ and Cijferverantwoording schema refactor and migration
minvws/nl-covid19-data-dashboard pull request #2789
Opened 2021-05-05 12:47 UTC by VWSCoronaDashboard1

## Summary

The items for the FAQ and Cijferverantwoording schema's have been refactored into separate documents. This way the communication department can publish these items separately.
Two migrations have been added to implement these changes.

## Motivation

Feature request.

## Detailed design

Separate documents have been defined for faq questions and 'figure explanation' items.
The migrations retrieve the current question and item objects and save them as documents, the resulting ids are then placed as references in the specific pages.

Also, as part of this PR all of the schema documents and objects have been turned into named exports, placed in barrel files and these barrel imports are being used in the schema.ts to tie everything together.

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-05-05 13:42 UTC, VWSCoronaDashboard8 approved these changes

2021-05-05 13:42 UTC, VWSCoronaDashboard8 commented on packages/cms/src/desk-structure.ts
> +                'cijferVerantwoording'
Just wondering; Are these three type names all with different formats? 🤔

2021-05-05 13:42 UTC, VWSCoronaDashboard8 commented on packages/cms/src/migrations/sprint22/faq.ts
> +
nit; The functions in this file are all anonymous function expressions assigned to named const. In the rest of the codebase we use named function declarations, which has my preference for readability and other reasons. 

Arrow / lambda functions are useful for inline expressions and closures, but I see no reason to use them.

The very small functions like `const commitTransaction = (tx: any) => tx.commit();` are better written inline I think, because ` tx.commit()` is more clear then `commitTransaction(tx)` since you're not completely sure what the function does when you read that.

2021-05-05 13:42 UTC, VWSCoronaDashboard8 commented on packages/cms/src/migrations/sprint22/faq.ts
> +migrateNextBatch().catch((err: any) => {
I think you can expect error to be of type Error? Unless you're dealing with shitty libraries that throw strings or other things that are considered bad practice.

2021-05-05 13:42 UTC, VWSCoronaDashboard8 commented on packages/cms/src/migrations/sprint22/figure-explanation.ts
> +  client.fetch(`*[_type == 'cijferVerantwoording']`);
Unless used more than once, I don't see how this functions helps. I think it only obfuscates things. 

It seems to be only used once...

2021-05-05 13:42 UTC, VWSCoronaDashboard8 commented on packages/cms/src/migrations/sprint22/figure-explanation.ts
> +    client.transaction()
These functions seem to be repeated. I think they should be generic and moved to a shared location to make it DRY

2021-05-05 13:42 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/schema.ts
> +    ...Object.values(localeHelpers),
Nice cleanup! 👍

2021-05-05 13:42 UTC, VWSCoronaDashboard8 commented on packages/cms/src/schemas/schema.ts
> +import * as restrictionDocuments from './restrictions';
nit; I think the names of the folders are sufficient, as the concat below doesn't care. It prevents you from coming up with new names for things. So you could write 

```suggestion
import * as locale from './locale';
import * as objects from './objects';
import * as restrictions from './restrictions';
```
Then also rename allDocuments to documents I guess. Currently it's a little odd that there's both allDocuments and restrictionDocuments...

2021-05-05 14:00 UTC, VWSCoronaDashboard1 commented on packages/cms/src/desk-structure.ts
> +                'cijferVerantwoording'
One is a name, the other is a title.

2021-05-05 14:03 UTC, VWSCoronaDashboard1 commented on packages/cms/src/migrations/sprint22/faq.ts
> +
I used the previous migration as a starting off point, that migration was based on an example from the Sanity docs.
But sure, I can rename them...

2021-05-05 14:09 UTC, VWSCoronaDashboard1 commented on packages/cms/src/migrations/sprint22/figure-explanation.ts
> +    client.transaction()
To be honest, these functions only get run twice. Once to perform the migration on develop and once on production. I'm not sure its worth the effort to start refactoring things this deeply.
Unless we'll need these functions exactly like this in future migrations, which is hard to anticipate.

2021-05-05 14:10 UTC, VWSCoronaDashboard8 approved these changes

2021-05-10 07:47 UTC, VWSCoronaDashboard4 requested changes

2021-05-10 07:47 UTC, VWSCoronaDashboard4 commented on packages/cms/src/schemas/documents/pages/cijfer-verantwoording-page.ts
> +export const cijferVerantwoording = {
why are all the others in English and this one in Dutch?

2021-05-10 07:47 UTC, VWSCoronaDashboard4 commented on packages/cms/src/schemas/documents/pages/over-risico-niveaus-page.ts
> +export const overRisicoNiveaus = {
risiconiveaus is one word, so lowercase `n` for `niveaus`

2021-05-10 08:59 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/documents/pages/cijfer-verantwoording-page.ts
> +export const cijferVerantwoording = {
It's named after the schema, I thought it would become confusing if I started mixing the two. Renaming the schema involves a migration, so I think that needs to be moved to a separate ticket.

2021-05-10 09:55 UTC, VWSCoronaDashboard10 approved these changes

2021-05-10 10:09 UTC, merged