Schemas for situations
minvws/nl-covid19-data-dashboard pull request #2854
Opened 2021-05-17 12:51 UTC by VWSCoronaDashboard4

## Summary

Schemas for situations

2021-05-17 16:26 UTC, VWSCoronaDashboard8 requested changes

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "school_daycare": {
daycare doesn't seem to be one word

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "complete_data_count": {
This doesn't tell me much, because it's not saying what data. Is it the total number of reported infections over all the categories? We use the word "total" in other places so might be more fitting.

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "general_practitioner": {
This is called doctor in other places of the data, so I suggest to keep it consistent.

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "health_care_other": {
This seems to be the only category about health_care so does it need the suffix other?

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "daycare_elderly_disabled": {
day_care

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "daycare_other": {
idem

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "gathering": {
Maybe social_gathering would be a little clearer if that is what the data is about, because technically a lot of the others would also be gatherings.

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        },
Interesting that they choose to split travel and flight

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "school_daycare",
You have two other categories starting with daycare, so wouldn't it make sense to call this one day_care_school? Or if it is school _and_ day maybe make that more explicit; `school_and_day_care`.

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "religious_activity",
These two could be grouped under activity. So activity_student and activity_religious.

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "flight",
Maybe this can be travel_flight and travel_other

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr/situations.json
> +        "complete_data": {
This doesn't read like a boolean

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "situation_known_percentage",
nit; maybe plural reads a little better `situations_known_percentage`. Especially since you also have investigations_count. But that one doesn't show up in this list. Is that intentional?

2021-05-17 16:26 UTC, VWSCoronaDashboard8 commented on packages/app/schema/vr_collection/situations.json
> +    "complete_data": {
Before it was a boolean but here it is an integer. In any case the name isn't helping me much in understanding what the value is about.

2021-05-18 08:48 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/situations.json
> +        "health_care_other": {
It's not prefixed for eg hospitals as `health_care_hospital`; I'll swap it to make it `other_health_care`

2021-05-18 08:57 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/situations.json
> +        "religious_activity",
Not sure if these should be grouped; they are just parts of the words.

2021-05-18 09:02 UTC, VWSCoronaDashboard4 commented on packages/app/schema/nl/situations.json
> +        "flight",
There is no grouping going on for similar items in this list, so why just for these two?

2021-05-18 10:34 UTC, VWSCoronaDashboard10 approved these changes

2021-05-18 10:34 UTC, VWSCoronaDashboard10 commented on packages/app/schema/nl/__index.json
> +    "situations": {
I think this name is rather vague, how about something like:
- `infection_location`
- `infection_site`
- `site_of_infection`
- `site_of_contamination`
- `contamination_situation`
- `infection_situation`

2021-05-18 10:34 UTC, VWSCoronaDashboard10 commented on packages/app/schema/nl/situations.json
> +        "home": {
Would it make sense to prefix all "location"-properties (like home/work/doctor/hospital/etc) to distinguish them from non-location properties?

2021-05-18 13:14 UTC, VWSCoronaDashboard8 approved these changes

2021-05-18 13:14 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "home": {
I don't see a practical motivation within the context of this schema to make a distinction between locations and non-locations. I think without the prefix it's quite clear which ones are about a location and which ones are about an activity. So if the chart doesn't make the distinction I'd keep it without prefix.

2021-05-18 13:14 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "visit": {
Since there is also "home" I think we should clarify this one. Because a visit could be in your home, but I'm assuming here you visited someone else... 

Maybe `visiting` or `visit_someone`, `visit_made`... It's a tough one :)

2021-05-18 13:14 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "regions_with_sufficient_responses_total",
nit; I think in this case you can leave out total, since there is no sub-total for this category. You can also use _count but it's redundant because the others are also about count. 

Alternatively you can prefix it with num_ or number_of_ so `num_regions_with_sufficient_responses` so that it reads a little better. Than it's also clear that it's not one of the categories.

2021-05-18 13:15 UTC, VWSCoronaDashboard8 commented on packages/app/schema/nl/situations.json
> +        "visit": {
`on_visit`?

2021-05-28 07:45 UTC, VWSCoronaDashboard1 approved these changes

2021-05-28 07:46 UTC, VWSCoronaDashboard14 approved these changes

2021-05-31 13:43 UTC, merged