Refactor delivery and administration chart to use time-series-chart
minvws/nl-covid19-data-dashboard pull request #2855
Opened 2021-05-17 17:15 UTC by VWSCoronaDashboard1

## Summary

The new chart looks practically the same except for some minor visual details.
![image](https://user-images.githubusercontent.com/69849293/118528121-45b2c380-b742-11eb-9f93-00e7c9137daa.png)

The biggest difference is the fact that in the 'estimated' part the grid lines are also dashed, this is because of the hatched overlay. I tried several approaches to get this exactly the same as the previous incarnation but wasn't successful.

## Motivation

Code cleanup.

## Detailed design

Some minor changes to the time-series-chart were needed in order to get this to work:
- The StackedAreaTrend now also has a `strokeWidth` property (it needed to be zero in this case)
- All series now have a unique id, this was needed for one of the earlier incarnations of the estimate annotation. But I decided to keep it in because I think they will come in handy once the charts will get more 'special fx' added.
- TimespanAnnotionConfig now has a `type` property. For now, it can either be `bar` or `estimate`.
- TimespanAnnotationConfigType now also has an optional `shapeComponent` property which is used to be rendered in the legend. (This was needed to render the hatched pattern in the legend icon)
- The old area-chart component has been removed completely.

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-05-18 13:02 UTC, VWSCoronaDashboard10 requested changes
Spotted a couple of bugs and I'm also not entirely sure we should have an 'estimate' type annotation. I cannot imagine we would use that annotation on other charts besides the delivery chart.

We might want to look at an annotation api which allows us to draw lines, points and text on the chart. In the future this api could be used to display "events" on certain dates, and the delivery chart could use it to draw the delivery-specific stuff.

Curious what @VWSCoronaDashboard8 thinks about this.

2021-05-18 14:27 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +}
Hm, you might actually have a point, hehe. I'll try it out.

2021-05-18 14:28 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +    };
I discussed this with @VWSCoronaDashboard8 and we came to the conclusion that for now, it was OK.

2021-05-18 14:31 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/landelijk/intensive-care-opnames.tsx
> +                      type: 'bar',
I'm open to suggestions.

2021-05-18 14:34 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/series.tsx
> +                  id={`${chartId}_${config.metricProperty}`}
'In theory' being the operative word here. I discussed this particular implementation with @VWSCoronaDashboard8 where I had previously implemented a unique id for each series, but we came to the conclusion that the current implementation was good enough since its highly unlikely the same metric property will be displayed in the same chart twice, only in different visualisations.

2021-05-18 14:44 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +}
I guess this just saves the calling context from having to wrap one function.

2021-05-18 14:56 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +}
Ok, so I removed the `selectData()`, it was meant just for convenience, but I suppose we can live without it.

2021-05-18 15:01 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/data-selection/selected-delivery-and-administration-data.ts
> +  const nlData = getNlData().data;
Ah, the `selected` part is actually a typo...

2021-05-18 15:17 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +}
By the way, the same `selectData()` method is also in this PR https://github.com/minvws/nl-covid19-data-dashboard/pull/2824. So that'll need to be tweaked as well.

2021-05-18 15:36 UTC, VWSCoronaDashboard10 approved these changes

2021-05-18 15:36 UTC, VWSCoronaDashboard10 commented on packages/app/src/static-props/get-data.ts
> +
I don't think these functions should be exported since they're only used in this module

2021-05-18 15:36 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +  },
```suggestion
  () => selectDeliveryAndAdministrationData(getNlData().data),
```

2021-05-18 15:58 UTC, VWSCoronaDashboard8 requested changes

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/patterns.tsx
> + * in the defs section, so I'm keeping that logic here.
If this pattern relies on the defs being there. Why are the definitions configurable and not simply embedded / fixed?

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/patterns.tsx
> +    timespanAnnotations?.filter((x) => x.type === 'estimate') ?? [];
If all you need is to know whether there are estimates, than extracting a boolean would be a bit cleaner maybe.

```suggestion
  const hasEstimateAnnotation =
    isDefined(timespanAnnotations?.find((x) => x.type === 'estimate'))
    
   return hasEsimate ? <pattern/> : null
   ```
   
   Also it returns one pattern, so I wonder why this component is called `Patterns` in plural
```

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/series.tsx
> +                  id={`${chartId}_${config.metricProperty}`}
I think this is acceptable. I can't think of a practical situation where you'd want to render the same trend twice, unless you are trying to get a visual rendering as a combination of two trends, but I'd consider that a hack and then I think the proper solution would be to introduce a new trend type.

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +    case 'bar':
I'm not sure about the bar vs estimate naming. One is very generic and the other is very specific. We will probably only use the stripy stuff for estimates, but that doesn't mean we need to have this hardcoded in the chart. From the perspective of chart API I think it makes sense to keep it abstract as it shouldn't have to care about the concept of estimates.

Some suggestions:

`solid` and `hatched`
`solid` and `striped`

If you want to keep estimate I'd still rename bar to `block` as somehow it doesn't look like a bar to me.

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +    };
I agree that it would be nice if this can be made a little more generic. I already commented on the name estimate, and in this case we could choose to split this up into two different types of annotations. One is the hatched pattern, and the other could be a `Marker` or `LabelledMarker` which draws a line at a specific point and has props for setting labels on either side of the marker. This would be different from a timespan annotation, because the marker is just 1 point in time and doesn't span anything. So I'd suggest to pass that on a different prop `markers` on the chart.

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      shapeComponent?: ReactNode;
I forgot why this annotation now wants a shapeComponent... Can't we keep the same component for all "bar" style legend items?

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      shapeComponent?: ReactNode;
And in this case, could we maybe standardize the legend items (and avoid making this configurable) Or is that something design wouldn't tolerate?

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +              />
Yes this makes the public API of the chart very odd, so would be great if we can avoid this.

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +    .find((x) => x.metricProperty === 'total_delivered');
Why are you filtering on isLineConfig? Could it be that there is another type of config with this same metricProperty?

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +    data.value.date_end_unix <= estimateRange[1];
I believe the tooltip mechanism can pass what annotation is active as arguments to the render function, so maybe you can use that.

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +function formatLabel(labelKey: string | undefined, text: SiteText) {
Optional arguments typically come last, and then you con't need the | undefined. 

```suggestion
function formatLabel(text: SiteText, labelKey?: string) {
```

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +}
I find this whole function quite odd. Maybe pass in the product names object typed to record<string>. Something like this:

```suggestion
function formatLabel(productNames: Record<string, string>, productKey?: string) {
  return productKey
    ? productNames[productKey]
    : productKey;
}
```
But I wonder why this function needs to exist in the first place and why productKey is used as a fallback for rendering a product name.

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +              shapeComponent: <HatchedSquare />,
I mentioned this earlier. Can't this just be the default / fixed way of rendering an estimate in the legend. I'd rather have it standardized if possible.

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +            color: (colors.data.vaccines as any)[x],
You are using object lookup, so it's not any really

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/landelijk/intensive-care-opnames.tsx
> +                      type: 'bar',
Yes maybe we can make type optional with default to bar. It's a bit annoying having to set bar everywhere because one or two charts are using a different type of annotation.

2021-05-18 15:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/static-props/get-data.ts
> +}
Agree, I don't see why we would want to fall back to an empty string. An assertion seems appropriate to me.

2021-05-18 16:10 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/chart-container.tsx
> +  defs?: React.ReactNode;
I removed that functionality but forgot this prop. I'll remove it.

2021-05-18 16:14 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/patterns.tsx
> + * in the defs section, so I'm keeping that logic here.
Patterns are always part of the defs section, not sure what you mean

2021-05-18 16:14 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/patterns.tsx
> +  timespanAnnotations: TimespanAnnotationConfig[] | undefined;
I had already added a comment about this...

2021-05-18 16:17 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/patterns.tsx
> +  timespanAnnotations: TimespanAnnotationConfig[] | undefined;
But, since it confuses you, I'll just rename it.

2021-05-18 16:18 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/patterns.tsx
> +    timespanAnnotations?.filter((x) => x.type === 'estimate') ?? [];
Again, I had added a comment to the component. But I guess comments aren't read hehe. So I've renamed it.

2021-05-18 16:21 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      shapeComponent?: ReactNode;
Please read the PR comments...

2021-05-18 16:22 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      shapeComponent?: ReactNode;
I don't know, if we don't add the hatched pattern to the legend icon it will just become a grey square. So, either we don't show it or we show it with the pattern...

2021-05-18 16:23 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +    .find((x) => x.metricProperty === 'total_delivered');
No, in this case its to narrow the type to a type that has a property called 'metricProperty'

2021-05-18 16:23 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +    data.value.date_end_unix <= estimateRange[1];
I did not know this, I'll have a look. it sounds cleaner.

2021-05-18 16:31 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      shapeComponent?: ReactNode;
Oh wait, I read this wrong, but the solid annotation doesn't need a shapeComponent I suppose

2021-05-18 16:42 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +}
This was copied from the old tooltip, I didn't look into it that deeply.But you're right, the entire formatLabel function isn't needed. I removed it.

2021-05-18 16:45 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +
They're not used in this PR, but they are used in the scoreboard PR where a selection of all the VRs is being loaded.

2021-05-18 16:45 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +
(I copied the get-data.ts from that PR)

2021-05-18 16:47 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +    case 'bar':
So, I'm ok with the re-naming. But now that the estimate annotation is called 'hatched'. I don't think the extra line with the two labels can be part of the annotation anymore. (we discussed this before I started implementing this). I guess we'll have to come up with another data option or the third type of annotation.
For now, I'll implement it as a third type. I think that makes the most sense here.

2021-05-18 17:55 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +              shapeComponent: <HatchedSquare />,
Ok, I guess that's possible. I'll make the change.

2021-05-18 18:11 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +    case 'bar':
Hm, I've implemented it as new type of timespan annotation. But, it already doesn't make sense.
I think we need to add a new type of annotation. Let's call it a 'time-annotation' for now.
I've committed the span implementation, so you can see for yourself. But, it doesn't make sense since the divider only has one x coordinate, not a start and end.
So, this already proves imho, that it needs to be a separate thing. Its getting late, let's discuss this tomorrow morning.

2021-05-18 18:42 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +    case 'bar':
Ok, so the OCD brain wouldn't let me leave this unfinished. So to avoid not being able to sleep I implemented the divider as a new kind of annotation. I called it TimeAnnotation for now. Naming, etc is open for discussion, obviously. Check it out...

2021-05-18 18:44 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +    case 'bar':
I don't pass the time annotations to the tooltip yet, for instance. We can discuss whether that makes sense or not.

2021-05-19 06:57 UTC, VWSCoronaDashboard10 requested changes

2021-05-19 06:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +                domain={xScale.domain() as [number, number]}
I don't think we should cast this to a tuple of numbers because the array could hold more than 2 numbers. It's typed like `number[]` on purpose.
```suggestion
                domain=[first({xScale.domain()), last({xScale.domain())]}
```

2021-05-19 06:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        />
I think you should render the hatch pattern over here, extra advantage is that you can get rid of the timespanAnnotation checks in the pattern component, also the id can be defined on this level.
```suggestion
        <>
          <HatchedPattern id={`${chartId}_hatched_pattern`} />
          <Bar
            pointerEvents="none"
            height={height}
            x={x0}
            width={width}
            fill={`url(#${chartId}_hatched_pattern)`}
          />
        </>
```

2021-05-19 06:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +    <svg height="15" width="15">
Can you make sure this icon has the same width/height/viewbox implementation as the other icon?
```suggestion
export function HatchedTimespanAnnotationIcon({
  width = 15,
  height = 15,
}: TimespanAnnotationIconProps) {
  return (
    <svg width={width} height={height} viewBox={`0 0 ${width} ${height}`}>
```

2021-05-19 06:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +            style={{ stroke: 'grey', strokeWidth: 3 }}
did you mean `gray`?
```suggestion
            style={{ stroke: 'gray', strokeWidth: 3 }}
```

2021-05-19 06:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      type: 'solid';
I think we can get rid of the type property and have a single timespan annotation type with a `fill` prop
```suggestion
      fill?: 'solid' | 'hatched'; // optional so the default can be `solid`
```

2021-05-19 06:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +            />
see other comments about moving this component to the TimespanAnnotation

2021-05-19 06:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
Why is this typed so complex compared to `as const`?
```suggestion
const vaccines = [
  'pfizer',
  'moderna',
  'astra_zeneca',
  'cure_vac',
  'janssen',
  'sanofi',
] as const;
```

2021-05-19 06:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +    [vaccines, firstValue]
Unnecessary to add vaccines to the dep array since it's defined outside of the function component and won't change
```suggestion
    [firstValue]
```

2021-05-19 07:03 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        />
Ok, it also means we can only add one hatched annotation, otherwise we're duplicating the pattern. Thats why it was in the defs section in the first place.

2021-05-19 07:05 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +                domain={xScale.domain() as [number, number]}
Please expand your code suggestion to also cover the `TimespanAnnotation` component, this also takes the domain as a number tuple. That's where I copied this code from. ;)

2021-05-19 07:08 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      type: 'solid';
And what if there's a third type next week?

2021-05-19 07:09 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
Because it's been used as an indexer, so simply using strings will make the compiler sad

2021-05-19 07:10 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +                domain={xScale.domain() as [number, number]}
Ay yes might be better to turn it around;
```tsx
export function TimespanAnnotation({
  start,
  end,
  domain,
  getX,
  height,
}: {
  start: number;
  end: number;
  domain: number[];
  height: number;
  getX: GetX;
}) {
  const min = first(domain);
  const max = last(domain);
  assert(
    typeof min === 'number' && typeof max === 'number',
    `received invalid domain ${domain}`
  );

2021-05-19 07:11 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        />
I don't think duplicating a pattern is a big issue :-)

2021-05-19 07:12 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +                domain={xScale.domain() as [number, number]}
Addendum, while it is, in theory, possible there's a domain consisting of more than two values. In the time-series-chart all the domains are explicitly created with two values. So, I'm not sure if this changes is really that necessary...

2021-05-19 07:16 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        />
But I also fail to see why the change is necessary then. I don't think I'm adding an incredible amount of complexity here...

2021-05-19 07:16 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +    <svg height="15" width="15">
Done

2021-05-19 07:16 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +            style={{ stroke: 'grey', strokeWidth: 3 }}
Fixed

2021-05-19 07:17 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +    [vaccines, firstValue]
Fixed

2021-05-19 07:19 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
It looks like the compiler currently complains: https://github.com/minvws/nl-covid19-data-dashboard/pull/2855/checks?check_run_id=2617693033

I also think the compiler is complaining because the `vaccines` array contains more types of vaccines compared to the vaccines coming from lokalize. On my local checkout the following results in no TS errors:
```tsx
const vaccines = [
  'astra_zeneca',
  'janssen',
  'moderna',
  'pfizer',
  // 'cure_vac',
  // 'sanofi',
] as const;
```

2021-05-19 07:19 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
See line 42, 111, 114 and 115 for reference

2021-05-19 07:21 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +                domain={xScale.domain() as [number, number]}
I think the domain check is a good one though, that definitely simplifies the code, so I'm using that

2021-05-19 07:21 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      type: 'solid';
That's not really an argument 😛  we've been working with a single type for several months, also a solid/hatched fill makes sense configuration-wise imho, but do what feels best.

2021-05-19 07:23 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +                domain={xScale.domain() as [number, number]}
Oops, no, I thought your code suggestion was valid. But now I realize that the values are already being clipped. As the comment states, this allows for Infinity to be passed in as an end date.

2021-05-19 07:30 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      type: 'solid';
We've also been working with a domain that consists of two values for several months, yet you insist on checking for larger domains...
But, if it helps you sleep at night, I'll change this to the fill prop solution. I'm getting a bit tired of the back and forth here.

2021-05-19 07:33 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
If remove those vaccine names then we'll have to make a manual change here once those vaccines are on the market. We added the entire list so that BE only has to add the values and this chart will automatically 'grow' accordingly...

2021-05-19 07:36 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        />
Well I actually think it is:
- there's an unclear link between a HatchedPattern and a specific case of a timespanannotation
- It's weird that a pattern should receive information about timespan annotations
- The timespanAnnotation component could be rendered by different chart implementations (e.g. vertical bar chart, mini bar chart). It would be a broken component because it has unclear dependencies on a component rendered somewhere else.

2021-05-19 07:41 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      type: 'solid';
> We've also been working with a domain that consists of two values for several months, yet you insist on checking for larger domains..

that's because I read that in d3 documentation last week ;-)

2021-05-19 07:43 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
Sure, makes sense, but another way of fixing is by adding `cure_vac` and `sanofi` in lokalize. Otherwise BE is still unable to add values without our help.

2021-05-19 07:49 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
They are in the Lokalise, no?

2021-05-19 07:55 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        />
Hm, I think I placed the hatch-pattern component inside the 'components' directory of the time-series-chart. WHich kind of implies its tied to that component.
Currently, the hatched pattern is tied to the timespan annotation, that's why I placed the check inside that component, with the idea that if more patterns would be needed in the future this logic would be lifted outside this component to more upstream logic that would decide which patterns wound need to be rendered or not.

2021-05-19 07:58 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
At least, in my nl_export.json they are...

2021-05-19 08:02 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +    case 'bar':
I do remember talking about the labels in combination with the annotation but I don't remember what the outcome/motivation was to be honest. Reading your code, and how specific the implementation for estimate was, I feel it would be better to break up the timespan annotation and the marker line with the labels into two separate concepts.

Do I'm guessing what I call a marker you are here referring to as a TimeAnnotation? Seems fine with me too.

2021-05-19 08:04 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        />
I understand, but it's still unnecessarily complex if there's a simpler implementation possible?

2021-05-19 08:04 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +      shapeComponent?: ReactNode;
I thought you could choose the shapeComponent based on the type of annotation. So when it's estimate you use the hatched pattern, without specifying it in the config. But possibly I'm missing some things here.

2021-05-19 08:06 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
that's odd, because they are not part of the dataset:
![image](https://user-images.githubusercontent.com/73584448/118777860-d1833780-b889-11eb-96b2-b503ec052510.png)

2021-05-19 08:14 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
Oh, I guess I have an old export locally then. These keys have probably been removed during cleanup, I suppose.

2021-05-19 08:22 UTC, VWSCoronaDashboard8 approved these changes
Nice (team) work on this one!

2021-05-19 08:22 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/time-annotation.tsx
> +  const clippedPosition = Math.min(Math.max(position, min), max);
Wouldn't this result in the annotation being positioned on one side of the chart, even though according to its position it should lie outside of the chart / is not visible?

I think if the position of the annotation doesn't fall within the domain, we can simply not draw anything.

2021-05-19 08:22 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/components/time-annotation.tsx
> +    case 'divider':
👍  I'm not sure we'll need others in the future, but this is a clear name.

2021-05-19 08:22 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/time-series-chart/logic/common.ts
> +};
🥳

2021-05-19 08:22 UTC, VWSCoronaDashboard8 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +  const isEstimate = data.timespanAnnotation?.fill === 'hatched';
👍

2021-05-19 08:37 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
whoopsy, must have been my bad then

2021-05-19 09:08 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/vaccine-delivery-and-administrations-area-chart.tsx
> +>)[];
don't forget to re-add those vaccines again with the cli :-)

2021-05-25 10:57 UTC, VWSCoronaDashboard10 approved these changes
Couple of clean up thingies but I guess we're there 👍

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/use-vaccine-names.ts
>  import { assert, NlVaccineAdministeredValue } from '@corona-dashboard/common';
I think this file `use-vaccine-names` can be removed now, looks like it's not used anymore

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/time-annotation.tsx
> +  const fontSize = !breakpoints.lg ? theme.fontSizes[0] : theme.fontSizes[1];
shouldn't this ideally be based on the chart width instead of a breakpoint

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/time-annotation.tsx
> +            fill="grey"
Shouldn't this become a color from the theme?

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/time-annotation.tsx
> +            fill="grey"
idem

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/time-annotation.tsx
> +            stroke="gray"
idem

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +            : `url(#${chartId}_hatched_pattern)`
```tsx
const patternId = `${chartId}_hatched_pattern`;

// ...

<pattern id={patternId}>

// ...

fill={`url(#${patternId})`}
```

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +            style={{ stroke: 'gray', strokeWidth: 3 }}
theme color?

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +        <Spacer mb={1} />
I guess this component cannot be a child of a `<ol />`

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +`;
we have fontweights in our theme, using the SC backtick notation ignores all theme values
```suggestion
const TooltipValueContainer = styled.span(css({
  fontWeight: 'bold',
  ml: '1em' // or pick a theme value
  }));
```

2021-05-25 10:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/data-selection/select-delivery-and-administration-data.ts
> +  ];
I think something like this is easier for the eyes:
```tsx
const values: VaccineDeliveryAndAdministrationsValue[] = [];

for (const [index] of vaccine_administered.values.entries()) {
  values.push({
    total_delivered: vaccine_delivery.values[index].total,
    ...vaccine_delivery.values[index],
    ...vaccine_administered.values[index],
  });
}

for (const [index] of vaccine_administered_estimate.values.entries()) {
  values.push({
    total_delivered: vaccine_delivery_estimate.values[index].total,
    ...vaccine_delivery_estimate.values[index],
    ...vaccine_administered_estimate.values[index],
  });
}

2021-05-26 06:58 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/use-vaccine-names.ts
>  import { assert, NlVaccineAdministeredValue } from '@corona-dashboard/common';
I think you're correct ;)

2021-05-26 06:59 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/time-series-chart/components/time-annotation.tsx
> +  const fontSize = !breakpoints.lg ? theme.fontSizes[0] : theme.fontSizes[1];
You're probably right. This is also an issue in the x ticks PR. I'm going to implement a `useChartBreakPoints` feature there, so for now I'm going to leave this one as is.

2021-05-26 07:22 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +          id={`${patternId}`}
```suggestion
          id={patternId}
```

2021-05-26 07:23 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/vaccine/components/vaccine-delivery-and-administrations-tooltip.tsx
> +        <TooltipListItem mt={1}>
it's a styled component so you could go for the following and keep the TooltipListItem simple:
```suggestion
        <TooltipListItem css={css({{ mt: 1 })}>
```

2021-05-26 07:31 UTC, merged