Add new choropleth tile behavior page
minvws/nl-covid19-data-dashboard pull request #2873
Opened 2021-05-20 13:30 UTC by VWSCoronaDashboard14

This features 2 choropleths next to each other sharing the same data in the tooltip
Added a new threshold
Kinda worked my way around the Choropleth component and the way he receives data to load in the correct threshold

2021-05-25 08:57 UTC, VWSCoronaDashboard1 requested changes

2021-05-25 08:57 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/choropleth/region-thresholds.ts
> +const behaviorComplienceThresholds: ChoroplethThresholdsValue[] = [
```suggestion
const behaviorComplianceThresholds: ChoroplethThresholdsValue[] = [
```

2021-05-25 08:57 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/choropleth/region-thresholds.ts
> +  behavior_compliance: behaviorComplienceThresholds,
```suggestion
  behavior_compliance: behaviorComplianceThresholds,
```

2021-05-25 08:57 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/choropleth/choropleth.tsx
> +      timeout.current = window.setTimeout(() => setTooltip(undefined), 10);
why such a small timeout?

2021-05-25 08:57 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/choropleth/tooltips/region/behavior-tooltip.tsx
> +          title="Naleving"
This title should probably come from the siteText

2021-05-25 08:57 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/behavior/behavior-choropleth.tsx
> +export function BehaviorChoropleth({
This name is not appropriate for a component that shows two choropleths.  At the very least it ought to be called `BehaviorChoropleths`, but perhaps `BehaviorChoroplethsTile` is better.

2021-05-25 09:43 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/choropleth/choropleth.tsx
> +      timeout.current = window.setTimeout(() => setTooltip(undefined), 10);
Unfortunately, I just picked a number, couldn't find any drawbacks when lowering it to 10 (and it looks good having not to wait 0.5 seconds for a tooltip to disappear). But it might be good to test it a bit more and if it does impact other choropleths performances.

2021-05-25 09:53 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/choropleth/choropleth.tsx
> +      timeout.current = window.setTimeout(() => setTooltip(undefined), 10);
AFAICR, the 500ms wait was chosen so that switching between tooltips won't result in a flicker. But if 10ms works too, then fine.

2021-05-26 12:34 UTC, VWSCoronaDashboard4 approved these changes

2021-05-26 12:34 UTC, VWSCoronaDashboard4 commented on packages/app/src/components/choropleth/safety-region-choropleth.tsx
> +  hasNoDataFillColor?: string;
This name indicates a boolean, but the value is a string?

2021-05-26 13:22 UTC, merged