Feature/situations kpi tile
minvws/nl-covid19-data-dashboard pull request #2932
Opened 2021-06-03 08:24 UTC by VWSCoronaDashboard14

Add KPI block on the new situations page on VR levle.
This includes new Lokalize keys.

2021-06-03 08:58 UTC, VWSCoronaDashboard8 approved these changes

2021-06-04 12:40 UTC, VWSCoronaDashboard8 commented on packages/app/src/pages/veiligheidsregio/[code]/brononderzoek.tsx
> +            ) : undefined}
React components that do not render anything should typically return null but maybe undefined works as well in this case... You could also use `&&` and then you don't need the else part I guess.

2021-06-04 12:41 UTC, VWSCoronaDashboard8 approved these changes

2021-06-07 08:04 UTC, VWSCoronaDashboard10 requested changes

2021-06-07 08:04 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/veiligheidsregio/[code]/brononderzoek.tsx
> +  const mockData = mockKpiBlock();
please get rid of this and use data from the props (`data.situations.last_value`)

2021-06-07 08:04 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/veiligheidsregio/[code]/brononderzoek.tsx
> +            <Tile>Empty tile</Tile>
what's this?

2021-06-07 08:04 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/veiligheidsregio/[code]/brononderzoek.tsx
> +                  data-cy="covid_total"
copy-paste?

2021-06-07 08:04 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/veiligheidsregio/[code]/brononderzoek.tsx
> +                      date_start_unix: (
can you rename the variables to something without `_unix`? Also you can use the `intl.formatDateSpan` utility for formatting these dates.

2021-06-07 08:27 UTC, VWSCoronaDashboard14 commented on packages/app/src/pages/veiligheidsregio/[code]/brononderzoek.tsx
> +            <Tile>Empty tile</Tile>
A placeholder for https://github.com/minvws/nl-covid19-data-dashboard/pull/2939

2021-06-07 09:45 UTC, merged