Add situations table on VR level
minvws/nl-covid19-data-dashboard pull request #2937
Opened 2021-06-03 14:26 UTC by VWSCoronaDashboard14

Add a table with a similar setup to the new behavior table.
Went wrong with some Lokalize keys so had to remove a bunch of them and add new ones

Note: Still need to add the toggletip explainer to the graph, currently using a placeholder.

Mandatory screenshot:
<img width="938" alt="Screenshot 2021-06-03 at 16 24 43" src="https://user-images.githubusercontent.com/76471292/120661284-68eeaa00-c488-11eb-8dcc-8d33569865b6.png">

2021-06-03 15:05 UTC, VWSCoronaDashboard1 approved these changes

2021-06-03 15:05 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +              borderTopColor: 'lightGrey',
Is this color part of the theme yet?

2021-06-04 06:29 UTC, VWSCoronaDashboard4 requested changes

2021-06-04 06:29 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +              borderTopColor: 'lightGrey',
then one in the theme is spelled `lightGray` ;-)

2021-06-04 06:29 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +            {situations.map((situation, index) => (
Shouldn't these rows be sorted from highest percentage to lowest?

2021-06-04 06:29 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +                      amount={Math.floor(Math.random() * 50) + 1}
It's probably better to swap this for the mock data, which is easier to swap when actual data is available. A random at a random spot in the code might easy to oversee.

2021-06-04 06:29 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +    borderBottomColor: 'lightGrey',
lightGray

2021-06-04 06:29 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +      content: '"i"',
shouldn't this be an icon, perhaps?

2021-06-04 06:29 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +      <InlineText css={css({ minWidth: 40 })}>{`${amount}%`}</InlineText>
Use `formatPercentage` here

2021-06-04 06:29 UTC, VWSCoronaDashboard4 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +              date_start_unix: formatDateFromSeconds(1622727076),
Same comment as the mock data, use the mock data available in develop; weaving this with the code might make it hard to spot them and remove them.

2021-06-04 07:23 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +              borderTopColor: 'lightGrey',
I actually copied it from the old behavior table, so I will also change it there also

2021-06-04 07:23 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +            {situations.map((situation, index) => (
It has a fixed order!

2021-06-04 07:24 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +      content: '"i"',
Yeah, I need to add it later, the icon functionality is living in another branch still. This is a temporality placeholder.

2021-06-04 11:34 UTC, VWSCoronaDashboard10 requested changes

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +  const data = useMemo(() => mockTableData(), []);
You can use the page-level mock data and pass that on to this component instead of defining it over here

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +  descriptionDate: string;
same comment as on the other PR, these texts shouldn't be on the props.

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +          </InlineText>
I'd suggest to have the `date_start` and `date_end` variables be part of the `brononderzoek_text.table.description` text. You can use the `intl.formatDateSpan` as suggested in the other PR. 

When we render the string with a markdown component the bold style of the date span can be applied using markdown (`**{{date_from}} tot en met {{date_to}}**`).

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +          </InlineText>
The same trick can be used for the other PR date span.

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +            {situations.map((situation, index) => (
There's a `useSituations` hook with titles and descriptions.

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +                      {siteText.vr_brononderzoek.table[situation]}
So you can get rid of these `table.[situationId]` keys

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +                      amount={Math.floor(Math.random() * 50) + 1}
What's up with the random?

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/key-mutations.csv
> +2021-06-03T13:50:07.769Z,add,vr_brononderzoek.table.title
Like I said in the other PR, I think it's fine to have these table located under the root key `brononderzoek` but let's wait on other dev's opinions

2021-06-04 11:34 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/key-mutations.csv
> +2021-06-04T10:23:28.361Z,add,vr_brononderzoek.table.other_description
all these keys are already part of the lokalize keys under the `brononderzoek` root key, and they are accessible with a `useSituations()` hook

2021-06-04 12:24 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/situations/logic/situations.ts
> +];
Apparently only on `.tsx` files, not `.ts`

2021-06-07 07:59 UTC, VWSCoronaDashboard10 approved these changes

2021-06-07 09:24 UTC, merged