Add data coverage tile situations page
minvws/nl-covid19-data-dashboard pull request #2939
Opened 2021-06-04 09:19 UTC by VWSCoronaDashboard14

Adding a new tile, that has 2 states either enough or not enough data
New Lokalize texts
Some mock data
Had to do some fancy replaceComponentsInText in replaceComponentsInText because the whole text had to be bold inside, couldn't find a better way.

**Mandatory screenshots**
_Enough data:_
<img width="746" alt="Screenshot 2021-06-04 at 11 15 31" src="https://user-images.githubusercontent.com/76471292/120778339-840ff700-c526-11eb-92ee-ccc5fd6f5d44.png">

_Not enough data:_
<img width="746" alt="Screenshot 2021-06-04 at 11 19 33" src="https://user-images.githubusercontent.com/76471292/120778559-bf122a80-c526-11eb-85dd-e63351e8ff1e.png">

2021-06-04 10:29 UTC, VWSCoronaDashboard10 requested changes

2021-06-04 10:29 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-data-coverage-tile.tsx
> +                      {formatDateFromSeconds(data.date_start_unix)}
There's a `intl.formatDateSpan()` utility to format date spans in a single month as `van 3 tot 5 april` instead of `van 3 april tot 5 april`, usage:
```
const [start, end] = intl.formatDateSpan(
    { seconds: value.date_start_unix },
    { seconds: value.date_end_unix }
  );
```

Also the replaceable variable `date_start_unix`/`date_end_unix` should be renamed to something without `_unix` since it's not a unix we're replacing but a readable string.

2021-06-04 10:29 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-data-coverage-tile.tsx
> +    },
It looks like the two icons have different dimensions. You should request design to fix that instead of playing around with paddings and margins. Icon sizes/dimensions should be predictable.

2021-06-04 10:29 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-data-coverage-tile.tsx
> +    color: 'white',
You can inherit the background color from the containing component, this will work when you move the `color` to the svg style block.
```suggestion
    backgroundColor: 'currentcolor',
    svg: {
      color: 'white',
```

2021-06-04 10:29 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-data-coverage-tile.tsx
> +  dateText: string;
Why are you injecting these texts instead of reading them from inside this component?

2021-06-04 10:29 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-data-coverage-tile.tsx
> +    mb: 1,
I think a lot of vertical margins and paddings can be removed, also on the CoverageIndicator component and the mb on the Heading component.

Instead a wrapping `<Box spacing={2}>` component can define all spacings between those components.

2021-06-04 10:29 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/veiligheidsregio/[code]/brononderzoek.tsx
> +            dateText={vrText.tile_coverage.date_text}
Like I mentioned earlier: these texts can be read from inside the component. It's not shareable component in the component directory so it's not a problem imho.

2021-06-04 10:29 UTC, VWSCoronaDashboard10 commented on packages/cms/src/lokalize/key-mutations.csv
> +2021-06-04T08:54:58.663Z,add,vr_brononderzoek.tile_coverage.title_not_enough_coverage
I think it's not necessary to have these texts under `vr_brononderzoek`. Imho they can be placed under something like `brononderzoek.veiligheidsregio_dekking`.
Also within "brononderzoek" I tried to stick to dutch keys, such as `.titel` and `.beschrijving`. Not sure what we really want though? @VWSCoronaDashboard1 @VWSCoronaDashboard4 @VWSCoronaDashboard8

2021-06-04 12:02 UTC, VWSCoronaDashboard4 reviewed
Looks good apart from the suggestions by others!

2021-06-04 12:02 UTC, VWSCoronaDashboard4 commented on packages/cms/src/lokalize/key-mutations.csv
> +2021-06-04T08:54:58.663Z,add,vr_brononderzoek.tile_coverage.title_not_enough_coverage
I'm fine with the first suggestion, though having a separate main key is how other NL/VR keys are organised.

The second suggestion, with the other keys in the repo being 50%-ish EN/NL, I'd prefer EN keys for new keys. Though, consistency within one subject would be better, so for this feature stick to NL?

2021-06-04 13:04 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/situations/situations-data-coverage-tile.tsx
> +  };
This can be typed as SituationsValue

2021-06-07 07:57 UTC, VWSCoronaDashboard10 approved these changes

2021-06-07 09:30 UTC, merged