Add error boundary
minvws/nl-covid19-data-dashboard pull request #2948
Opened 2021-06-07 14:29 UTC by VWSCoronaDashboard1

## Summary

This PR adds an error boundary. I used react-error-boundary for the basis of the component, added a default implementation for the whole dashboard to this and wrapped as many appropriate components in the wrapper.

The error boundary shows a generic message, an error report, and a button that allows the user to copy the error report to their clipboard.

The component looks like this when it encounters an error:
![image](https://user-images.githubusercontent.com/69849293/121034392-47a1fc80-c7ad-11eb-9584-8001bbcc55eb.png)

## Motivation

Feature request.

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-06-07 18:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/error-boundary/index.tsx
> +  const copyErrorReport = () => {
```suggestion
  function copyErrorReport(){
```

2021-06-07 18:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/error-boundary/index.tsx
> +${error.stack}`;
This doesn't look nice. Maybe use https://www.npmjs.com/package/dedent I suspect we can use it in more places than this

2021-06-07 18:09 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/error-boundary/index.tsx
> +  }
This looks odd. You're placing a try/catch around a promised function so I don't think it'll throw. And if writeText returns a promise what are you trying to achieve that is different from 

```
function copyErrorMessage(errorReport: string) {
   return navigator.clipboard.writeText(errorReport)
}
```

2021-06-07 18:10 UTC, VWSCoronaDashboard8 approved these changes

2021-06-07 18:29 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/error-boundary/index.tsx
> +  }
Yea, it's kinda my paranoia about the error boundary component throwing errors (which would be kinda dumb), in theory, the clipboard object could throw an error before it created its promise or whatever. lol.

2021-06-08 09:40 UTC, VWSCoronaDashboard10 requested changes

2021-06-08 12:54 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/error-boundary/index.tsx
> +  const body = 'test'; //;encodeURIComponent(errorReport);
Oops.

2021-06-08 13:03 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/error-boundary/index.tsx
> +${error.stack}`;
That's printing it out as a JSON object, I don't think that's much of an improvement to be honest...

2021-06-08 13:04 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/error-boundary/index.tsx
> +${error.stack}`;
Oh, and the stacktrace gets serialized with literal '\n' characters in it that way hehe

2021-06-08 15:02 UTC, VWSCoronaDashboard8 approved these changes

2021-06-09 09:10 UTC, VWSCoronaDashboard4 requested changes

2021-06-09 09:10 UTC, VWSCoronaDashboard4 commented on packages/app/src/components/age-demographic/age-demographic.tsx
> +import { ErrorBoundary } from '../error-boundary';
```suggestion
import { ErrorBoundary } from '~/components/error-boundary';
```

2021-06-09 09:10 UTC, VWSCoronaDashboard4 commented on packages/app/src/components/error-boundary/index.tsx
> +    border: '1px solid silver',
Not a color from the theme? Same for the ErrorReport below

2021-06-09 09:10 UTC, VWSCoronaDashboard4 commented on packages/app/src/components/error-boundary/index.tsx
> +  return `url: ${window.location.href}
This could look a bit cleaner perhaps using an object/array that you `join` or `reduce` to a string.

2021-06-09 09:10 UTC, VWSCoronaDashboard4 commented on packages/app/src/components/choropleth-tile.tsx
> +            <ErrorBoundary>{children}</ErrorBoundary>
The choropleth tile is not the only component that includes choropleths. Eg topical, situations, behavior use a different mechanism. Let's add this wrapper there as well

2021-06-09 14:42 UTC, VWSCoronaDashboard10 approved these changes

2021-06-09 14:42 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/error-boundary/index.tsx
>  }
I think an object reads better..
```tsx
  const report = {
    'url': window.location.href,
    'platform': navigator.platform,
    'userAgent': navigator.userAgent,
    'browser dimensions': `${window.innerWidth}x${window.innerHeight}`,
    'screen resolution': `${window.screen.width * window.devicePixelRatio}x${
      window.screen.height * window.devicePixelRatio
    }`,
    'error': error.message,
    'stacktrace': error.stack ?? 'No stack trace available',
  }

  return Object.entries(report).map(([key, value]) => `${key}: ${value}`).join('\n')
}
```

or maybe, if you don't like that approach and want to stick to an array:
```tsx
  return [
    `url: ${window.location.href}`,
    `platform: ${navigator.platform}`,
    `userAgent: ${navigator.userAgent}`,
    `browser dimensions: ${window.innerWidth}x${window.innerHeight}`,
    `screen resolution: ${window.screen.width * window.devicePixelRatio}x${
      window.screen.height * window.devicePixelRatio
    }`,
    `error: ${error.message}`,
    `stacktrace:`,
    error.stack ?? 'No stack trace available',
  ].join('\n');
}
```

2021-06-10 09:58 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/error-boundary/index.tsx
>  }
What was the problem with using something like dedent? I don't see how any of this is cleaner 🤷‍♂️ 

Also I don't see why userAgent is camel-cased and some others have spaces. If there are no spaces I guess declaring it as an object which is then formatted to a string could also be ok. But I still think a template string is nicer.

2021-06-10 10:37 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/error-boundary/index.tsx
>  }
As much as I absolutely LOVE discussing the perfect way of formatting a string, I'm gonna leave it as it is right now with the last tweak made to the naming and casing. If this prevents someone else from sleeping soundly at night, feel free to change it in a subsequent PR ;)

2021-06-11 09:27 UTC, merged