Add variants page
minvws/nl-covid19-data-dashboard pull request #3000
Opened 2021-06-15 09:20 UTC by VWSCoronaDashboard14

- Add the variants page behind a feature flag
- Add the top header on the variants page
- Add mock data based on the schema
- Added a page in Sanity with articles + handy links
- Some new Lokalize keys

2021-06-15 09:56 UTC, VWSCoronaDashboard1 approved these changes

2021-06-15 09:56 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/objects/decorated-link.ts
> +export const link = {
I don't understand this rename. decoratedLink is renamed to link, while the filename is called decorated-link and the schema name is also decoratedLink...

2021-06-15 09:56 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/objects/link.ts
> +export const decoratedLink = {
And here the variable is called decoratedLink, but the file is called link and the schema name is link.

2021-06-15 10:03 UTC, VWSCoronaDashboard14 commented on packages/cms/src/schemas/objects/decorated-link.ts
> +export const link = {
Oops, I've messed that up, that should be at least be switched.

2021-06-15 13:13 UTC, VWSCoronaDashboard8 commented on packages/cms/src/lokalize/key-mutations.csv
> +2021-06-15T08:31:20.696Z,add,covid_varianten.informatie_block.nuttige_links_titel
typo

2021-06-15 13:43 UTC, VWSCoronaDashboard10 requested changes

2021-06-15 13:43 UTC, VWSCoronaDashboard10 commented on packages/app/src/assets/chevron-2.svg
> +<svg focusable="false" width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
I don't really like the name `chevron-2`

2021-06-15 13:43 UTC, VWSCoronaDashboard10 commented on packages/app/src/config/features.ts
> +    name: 'variantsPagePage',
```suggestion
    name: 'variantsPage',
```

2021-06-15 13:43 UTC, VWSCoronaDashboard10 commented on packages/app/src/domain/variants/logic/mock-data.ts
> +  const value = {
```suggestion
  const value: YouCanAddATypeOverHere = {
```

2021-06-15 13:43 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/landelijk/covid-varianten.tsx
> +    },
I don't think this belongs here? It will inject values/last_value on the props?

2021-06-15 13:43 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/landelijk/covid-varianten.tsx
> +  assert(data.variants, 'no situations data found');
```suggestion
  assert(data.variants, 'no variants data found');
```

2021-06-15 13:43 UTC, VWSCoronaDashboard10 commented on packages/app/src/pages/landelijk/covid-varianten.tsx
> +            {content.page.pageLinks && (
It appears you're checking the existence of an array, maybe also check on length?

2021-06-15 13:43 UTC, VWSCoronaDashboard10 commented on packages/app/src/utils/is-absolute-url.ts
> +export const isAbsoluteUrl = (url: string) => /^https?:\/\//.test(url);
Javascript has this beatiful function keyword:
```suggestion
export function isAbsoluteUrl(url: string) {
  return /^https?:\/\//.test(url);
}
```

2021-06-16 07:14 UTC, VWSCoronaDashboard10 commented on packages/app/src/utils/is-absolute-url.ts
> +  return /^https?:\/\//.test(url);
I just realize a url starting with `//` is also an absolute url
```suggestion
  return /^(https?:)?\/\//.test(url);
```

2021-06-16 07:58 UTC, merged