Fix collapsibles not opening when linked to from the same page
minvws/nl-covid19-data-dashboard pull request #3006
Opened 2021-06-16 11:59 UTC by VWSCoronaDashboard16

Collapsible sections currently only open if their hash is already present on page load. If there is a link to a collapsible section on the same page, clicking that link moves to the section, but does not open the collapsible. This PR makes sure collapsibles also open in those cases.

You can find such a link in the development data on the `/verantwoording` page, within 'Vaccinaties', click on 'gedragsonderzoek van het RIVM'.

2021-06-16 12:00 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +  const [open, setOpen] = useState(false);
@VWSCoronaDashboard10 I see you once explicitly changed this to `true`. Do I break any invisible functionality by changing it back? (it seems to work fine)

2021-06-16 12:15 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +  const [open, setOpen] = useState(false);
If I recall correctly that is due to the fact when Javascript is disabled, they are by default open.

2021-06-16 12:22 UTC, VWSCoronaDashboard1 approved these changes

2021-06-16 12:24 UTC, VWSCoronaDashboard8 requested changes

2021-06-16 12:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +  const [open, setOpen] = useState(false);
While you're changing this code anyway maybe use a better name for the boolean. We normally prefix them so it's clear that it's a boolean. "open" can be anything, and I would expect it to be a function most of all. 

```suggestion
  const [isOpen, setIsOpen] = useState(false);
```

2021-06-16 12:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +    const onHashChange = function () {
We use this pattern of `onEvenName`/`handleEventName`, where the `on` is used for prop names, and `handle` is used for the function actually handling the event. It makes things more clear especially when you need to locally handle the event and then call another handler from the props.

Also we prefer named functions over unnamed lambdas and usually only use lambdas inline

 ```suggestion
    function handleHashChange()  {
```

2021-06-16 12:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +      const isOpenedByQueryParam = window.location.hash.substr(1) === id;
nit; I think this is a little more readable. Param is kind of implied by the use of query already.

```suggestion
      const isOpenedByQuery = window.location.hash.includes(id);
```

2021-06-16 12:24 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +    onHashChange();
I suspect you can do this

```
function isOpenedByQuery(id: string) { 
   return window.location.hash.includes(id);
}
```

```
const [isOpen, setIsOpen] = useState(isOpenedByQuery(id))
```

Then you can omit the `const isOpenedByQueryParam` and you no longer need to call the handler onHashChange in the effect, because that feels an odd way to set what appears to be the initial state.

2021-06-16 12:37 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +  const [open, setOpen] = useState(false);
yep that's the use case for initially open collapsibles

2021-06-16 12:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +    onHashChange();
Nope, that won't work because server-side there's no window.location

2021-06-16 12:44 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +  const [open, setOpen] = useState(false);
Would be great to have that in a comment then :)

2021-06-16 12:48 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +    onHashChange();
Why are we reading from window.location anyway. Can't we get the param from the nextjs route api? If the server is rendering a page for a url with a query parameter, then that should define the state of the collapsible, right?

2021-06-16 12:57 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +    onHashChange();
It's reading the hash which is not part of the router, hashes aren't available server-side either.

2021-06-16 13:05 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +    onHashChange();
Ah right, I didn't know that, obviously 👍 

So in short, we render the collapsibles open by default for non-JS, and we need to call the hash handler in use-effect to close them again client-side if no hash is set on the url.

2021-06-16 13:35 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +      const isOpenedByQueryParam = window.location.hash.substr(1) === id;
I think the current method is most resilient. Using `includes()` or even `endsWith()` will be risky when IDs have overlapping parts. In the case of `includes()`, if you go to `http://localhost:3000/verantwoording#sterftemonitor-cbs` the 'Sterfte' section will also open, for example.

2021-06-16 13:48 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +      const isOpenedByQueryParam = window.location.hash.substr(1) === id;
👍

2021-06-16 13:52 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +      const isOpenedByQueryParam = window.location.hash.substr(1) === id;
Agree. For readability this is also an option:
```suggestion
      const isOpenedByQueryParam = window.location.hash === `#${id}`;
```

2021-06-16 14:02 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +     * all sections which are not opened by a hash now
tip; there's this plugin called re-wrap in vscode that can reformat comments like these, so you don't have to mess with line endings yourself.

2021-06-16 14:02 UTC, VWSCoronaDashboard8 approved these changes

2021-06-16 14:04 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +    }
With the current use-case there is not really a need to place it in a function anymore. A variable like you had before I guess makes a little more sense.

2021-06-16 14:07 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +    }
It does make a little bit of sense because otherwise the `window.location.hash.substr(1) === id` should be duplicated (one in the effect and another in the event handler).

An improvement could be to create a function outside of the component's scope;

```tsx
function equalsLocationHash(id: string) {
  return window.location.hash.substr(1) === id
}

2021-06-16 15:19 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +      const isOpenedByQueryParam = window.location.hash.substr(1) === id;
Even that would not be functionally equivalent. This would open all collapsibles without an `id` if the hash would be literally '#undefined', while the former also protects against that particular case.

Then again, I don't think a hash will ever be 'undefined', so I think we can go for readability here.

2021-06-16 16:15 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> +function locationHashEquals(id?: string) {
id should not be undefined

2021-06-17 08:01 UTC, VWSCoronaDashboard10 approved these changes

2021-06-22 13:41 UTC, merged