Add new information header element international page
minvws/nl-covid19-data-dashboard pull request #3072
Opened 2021-06-28 12:35 UTC by VWSCoronaDashboard14

2021-06-28 15:47 UTC, VWSCoronaDashboard1 approved these changes

2021-06-28 15:47 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/information-block/articles.tsx
> +        as="span"
InlineText already is a span

2021-06-28 15:47 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/information-block/information-block.tsx
> +export function InformationBlock({
`InformationBlock` might be a tad too general. Perhaps `PageInformationBlock` or `SectionInformationBlock`?

2021-06-28 15:47 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/information-block/information-block.tsx
> +import css from '@styled-system/css';
This file should be renamed to `index.tsx` since it already lives in a directory called information-block. The existing index.tsx now only contains one export.

2021-06-28 15:47 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/information-block/metadata.tsx
> +      <Box as="span" minWidth="1.8rem" mt="3px">
There is a styled component called `Span`, is that not usable instead of a Box as  span?

2021-06-28 15:47 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/information-block/useful-links.tsx
> +interface usefulLinksProps {
nit: put a space between the imports and the interface

2021-06-28 15:47 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/information-block/useful-links.tsx
> +        as="span"
Same here, the InlineText already is a span

2021-06-28 15:47 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/information-block/useful-links.tsx
> +function TitleWidthIcon({
Typo? I'm guessing this ought to be called `TitleWithIcon`?

2021-06-29 07:50 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/information-block/articles.tsx
> +        as="span"
Aah, I've copied the old metadata from the content header. Will also remove them there.

2021-07-01 10:38 UTC, VWSCoronaDashboard10 requested changes

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/metadata.tsx
> +      <Box minWidth="1.8rem" mt="3px">
same here

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +        mt: id ? asResponsiveArray({ _: 4, md: 5 }) : 0,
please no outside margins. Also setting a margin based on the existence of an `id` prop is rather surprising from the calling context. This style must be lifted.

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +      )}
fragment wrapper is unnecessary (`<> </>`)

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +          display={{ _: 'block', md: 'grid' }}
If you stick to grid- of flex-display on mobile. you can use the row-gap for spacing between elements, instead of the outside margin you applied on the Metadata component. Or, if you'd like to keep it like this, apply the responsive bottom margin on a metadata wrapper element inside this component.

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/useful-links.tsx
> +      mt={3}
no outside margins :-)

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/useful-links.tsx
> +        mb={2}
this mb can be replaced with a `spacing={2}` on the container Box

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/useful-links.tsx
> +              </>
unnecessary fragment

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/useful-links.tsx
> +const IconContainer = styled.div(
Better not to render divs inside spans
```suggestion
const IconContainer = styled.span(
```
this might need an additional display style though (e.h. display:inline-block) you'll figure out whether its necessary or not.

2021-07-01 10:38 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/useful-links.tsx
> +}
Here's a simpler version:

```tsx
function TitleWithIcon({ title, icon }: { title: string; icon?: JSX.Element }) {
  const [lastWord, ...splittedWords] = title.split(' ').reverse();
  const titleWithoutLastWord = splittedWords.reverse().join(' ');

  return (
    <InlineText fontFamily="body" fontSize="1rem">
      {titleWithoutLastWord}{' '}
      <InlineText display="inline-flex" position="relative">
        {lastWord}
        <IconContainer>{icon}</IconContainer>
      </InlineText>
    </InlineText>
  );
}
```

Only extra change needed outside this file is a bugfix on the (inline-)text component, otherwise the `position` props on Text and InlineText won't work (though they were added to the types 🤷‍♂️ )

```diff
diff --git a/packages/app/src/components/typography/text.tsx b/packages/app/src/components/typography/text.tsx
index 87e716067..e1c05b834 100644
--- a/packages/app/src/components/typography/text.tsx
+++ b/packages/app/src/components/typography/text.tsx
@@ -11,6 +11,7 @@ import {
   ColorProps,
   PositionProps,
   TypographyProps,
+  position,
 } from 'styled-system';
 import { styledShouldForwardProp } from '~/utils/styled-should-forward-prop';
 import {
@@ -32,14 +33,14 @@ export type TextProps = SpaceProps &
 export const Text = styled.p.withConfig({
   shouldForwardProp: styledShouldForwardProp,
 })<TextProps>(
-  compose(margin, padding, typography, color, layout),
+  compose(margin, padding, typography, color, layout, position),
   textTransform
 );
 
 export const InlineText = styled.span.withConfig({
   shouldForwardProp: styledShouldForwardProp,
 })<TextProps>(
-  compose(margin, padding, typography, color, layout),
+  compose(margin, padding, typography, color, layout, position),
   textTransform
 );
```

2021-07-01 11:44 UTC, VWSCoronaDashboard8 approved these changes

2021-07-01 11:46 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/information-block/information-block.tsx
> +import css from '@styled-system/css';
I remember we started adopting a pattern where we deliberately do not put the main component inside of an index file, because it makes it confusing to have multiple index files open.

So you can still create an index file, but I would advise to only use it for exporting the component from information-block.tsx

2021-07-02 07:30 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/information-block/information-block.tsx
> +import css from '@styled-system/css';
He already did that. I suggested renaming this to index.tsx because otherwise it would only contain one export. I was unaware of the aforementioned convention.

2021-07-02 09:15 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/information-block/information-block.tsx
> +import css from '@styled-system/css';
No worries, I'll change it back

2021-07-02 09:41 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/page-information-block/useful-links.tsx
> +}
Clever

2021-07-02 09:51 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +        mt: id ? asResponsiveArray({ _: 4, md: 5 }) : 0,
Ah, yeah this was from my old branch when content blocks are a bit lower on the page. Then it needed a bit more breathing room from the component that is above it. And since they all have an ID to scroll to them I figured it was an easy way of figuring out it wasn't the first element on the page. But I see that I might be a little strange.

2021-07-02 09:53 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +        mt: id ? asResponsiveArray({ _: 4, md: 5 }) : 0,
I understand, but you should configure that margin outside of this component. Component should only define spacing inside the container.

2021-07-05 08:13 UTC, merged