Add schema for international tested overall
minvws/nl-covid19-data-dashboard pull request #3078
Opened 2021-06-29 12:26 UTC by VWSCoronaDashboard8

## Summary

These are the first schema definitions for international data. Currently only for `tested_overall.infected_per_100k` aka confirmed cases.

- Time series data is split into a single file per country, similar to what we do already with VR and GM
- Country files have a `IN_` prefix because everything ends up in one folder, and otherwise we have no way to pick out just the country specific files.
- Choropleth data is defined in IN_COLLECTION.json similar to what we do already with VR and GM
- I have left in the total number of cases as a property, even though it is not shown in the charts (yet) I think it makes sense to have this data similar to how we have it for NL and VR.
- I have not included the moving average, since I'm assuming the charts do not use them

## TODO after this PR:

- Define a fixes list of countries and their codes, to enforce these in filenames as enum.

2021-06-29 12:39 UTC, VWSCoronaDashboard1 approved these changes

2021-06-29 12:39 UTC, VWSCoronaDashboard1 commented on packages/app/schema/in_collection/tested_overall.json
> +  "title": "regions_tested_overall",
```suggestion
  "title": "countries_tested_overall",
```

2021-06-29 12:39 UTC, VWSCoronaDashboard1 commented on packages/cli/src/schema/schema-info.ts
> +          'vrcode'
```suggestion
          'country_code'
```

2021-06-29 12:43 UTC, VWSCoronaDashboard8 commented on packages/app/schema/in_collection/tested_overall.json
> +  "title": "regions_tested_overall",
Good catch. It should be `in_tested_overall` then.

2021-06-29 12:46 UTC, VWSCoronaDashboard1 commented on packages/app/schema/in_collection/tested_overall.json
> +  "title": "regions_tested_overall",
ah yes, sorry ;)

2021-06-29 13:15 UTC, VWSCoronaDashboard14 approved these changes

2021-06-29 15:44 UTC, VWSCoronaDashboard1 approved these changes

2021-06-29 15:45 UTC, VWSCoronaDashboard1 requested changes
You forgot to run `yarn generate-typescript` ;)

2021-06-29 15:50 UTC, VWSCoronaDashboard1 approved these changes

2021-06-29 15:53 UTC, VWSCoronaDashboard1 approved these changes

2021-06-30 10:00 UTC, VWSCoronaDashboard1 approved these changes

2021-06-30 10:00 UTC, VWSCoronaDashboard1 commented on packages/app/schema/in_collection/tested_overall.json
> +      "pattern": "^[A-Z]+$"
I think its been established that we'll receive ISO A3 codes, so perhaps we can put a check on the country_code for a min and max char count of 3?

2021-06-30 10:28 UTC, VWSCoronaDashboard8 commented on packages/app/schema/in_collection/tested_overall.json
> +      "pattern": "^[A-Z]+$"
I think I would prefer to use an enum here with the exact selection / whitelist of country codes.

2021-06-30 15:29 UTC, VWSCoronaDashboard1 approved these changes

2021-07-01 08:23 UTC, merged