Add percentages KPI differences
minvws/nl-covid19-data-dashboard pull request #3208
Opened 2021-07-19 13:51 UTC by VWSCoronaDashboard14

When there was a difference with a percentage it didn't show the `%`. in the text. This should fix that for the moving average as well the normal difference. 

<img width="819" alt="Screenshot 2021-07-19 at 14 42 37" src="https://user-images.githubusercontent.com/76471292/126170582-84b7e438-3775-4ff6-ab35-61f821ded9ca.png">

2021-07-19 13:55 UTC, VWSCoronaDashboard4 approved these changes

2021-07-19 14:25 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/difference-indicator/tile-average-difference.tsx
> +  );
whatsup with the uppercase `V` of `Value`?

2021-07-19 14:25 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/kpi-value.tsx
>            />
did you mean `isDefined(percentage)`?

2021-07-20 09:29 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/kpi-value.tsx
>            />
Ah yeah, good catch.

2021-07-20 11:04 UTC, VWSCoronaDashboard10 requested changes

2021-07-20 11:04 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/kpi-value.tsx
> +          {`${formatNumber(absolute)} (${formatPercentage(percentage)}%)`}as
```suggestion
          {`${formatNumber(absolute)} (${formatPercentage(percentage)}%)`}
```

2021-07-20 11:10 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/kpi-value.tsx
> +          {`${formatNumber(absolute)} (${formatPercentage(percentage)}%)`}as
oops

2021-07-20 11:18 UTC, VWSCoronaDashboard10 approved these changes

2021-07-20 11:18 UTC, VWSCoronaDashboard10 commented on packages/app/src/components/difference-indicator/tile-average-difference.tsx
> +  const valueText = (
nit; maybe `oldValue` makes sense as name

2021-07-20 12:15 UTC, merged