Clean up isWeeklyData from sidebar-metric
minvws/nl-covid19-data-dashboard pull request #3241
Opened 2021-07-22 14:53 UTC by VWSCoronaDashboard14

It is not needed anymore to set is explicit. Right now we are just looking for a `date_unix` and when not found we can safely assume it is a week range.

2021-07-22 16:01 UTC, VWSCoronaDashboard1 approved these changes

2021-07-26 07:15 UTC, VWSCoronaDashboard8 requested changes

2021-07-26 07:15 UTC, VWSCoronaDashboard8 commented on packages/app/src/components/sidebar-metric/sidebar-metric.tsx
> +    metricProperty ?? ''
This looks odd to me. If metricProperty needs to be optional then I think we should make it optional in the function arguments. An empty string should not be treated as a valid metric property.

It looks like you have been able to remove the use of NO_METRIC_PROPERTY so I think it can just be optional in the arguments and handle that inside the function.

2021-07-26 09:27 UTC, VWSCoronaDashboard8 commented on packages/app/src/metric-config/index.ts
> +    [scope, metricName, metricProperty ?? ''],
nit; I think this is a little cleaner, because then you don't use '' as a property.

```suggestion
    metricProperty ? [scope, metricName, metricProperty] : [scope, metricName],
```

2021-07-26 09:27 UTC, VWSCoronaDashboard8 approved these changes

2021-07-26 09:57 UTC, merged