Add groups for data explanation page
minvws/nl-covid19-data-dashboard pull request #3266
Opened 2021-07-26 16:20 UTC by VWSCoronaDashboard13

## Summary

Updates schemas for CMS to require a group selection for every data explanation and updated UI to reflect this categorization.

## Motivation

Improved readability

## Detailed design

Modeled schema additions and styling after FAQ page. Any items that are not assigned to a group are grouped together at the bottom of the page without a title. All groups and items within them are sort alphabetically

2021-07-27 07:14 UTC, VWSCoronaDashboard4 commented on packages/app/src/pages/verantwoording.tsx
> +        {Object.entries(groups)
I'd sort/map/check this array outside the JSX, it keeps the JSX cleaner.

2021-07-27 07:14 UTC, VWSCoronaDashboard4 commented on packages/app/src/pages/verantwoording.tsx
> +            if (a[0] === 'null') return 1;
Strings values 'null' ? Can't we tweak the query to return something better perhaps?

2021-07-27 08:09 UTC, VWSCoronaDashboard1 reviewed
I think this change requires a migration as well. Since the group field is required, every explanation will become invalid. This can be fixed manually in the UI, but a migration will take care of it automatically.

if you have a look at `cms/src/migrations/sprint18`, this migration can probably be copied verbatim (since it uses the same pattern and I think you've copied the schema's from the FAQ bits), but with the correct schema names replaced.

Once the migration has run, you also won't be needing the null checks because you'll be sure that every item will be assigned to a group.

2021-07-27 10:11 UTC, VWSCoronaDashboard13 commented on packages/app/src/pages/verantwoording.tsx
> +        {Object.entries(groups)
removed most of it! Do you still think it's necessary to sort outside of the jsx?

2021-07-27 10:11 UTC, VWSCoronaDashboard13 commented on packages/app/src/pages/verantwoording.tsx
> +            if (a[0] === 'null') return 1;
added a migration script so there should be no nulls 👍

2021-07-27 10:33 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/verantwoording.tsx
> +        {Object.entries(groups)
We prefer to do any kind of data manipulation outside of the JSX

2021-07-27 10:35 UTC, VWSCoronaDashboard1 approved these changes

2021-07-27 10:35 UTC, VWSCoronaDashboard1 commented on packages/cms/src/migrations/sprint28/index.ts
> + * SANITY_STUDIO_API_DATASET=production sanity exec src/migrations/sprint28 --with-user-token
This is no longer true, to run this migration against the production dataset you simply need to change `getClient('development')` to `getClient('production')`,

2021-07-28 09:19 UTC, VWSCoronaDashboard8 requested changes

2021-07-28 09:19 UTC, VWSCoronaDashboard8 commented on packages/cms/src/migrations/sprint28/index.ts
> +          _type: 'figureExplanationItem',
I think this patch / PR could a be good opportunity to move away from the `figureExplanationItem`. I think the name is poorly chosen, as "cijferverantwoording" is about the data and is not tied to any sort of visual representation.

Also for the groups you are using the type `cijferVerantwoordingGroups` which seems inconsistent with the English type name `figureExplanationItem`. So if it's not too much of a hassle, I'd suggest to copy that data over to a new type named something like `cijferVerantwoordingItem`

Also, shouldn't `cijferVerantwoordingGroups` be named `cijferVerantwoordingGroup` instead? Isn't the type defining a single group?

2021-07-28 09:27 UTC, VWSCoronaDashboard8 commented on packages/cms/src/migrations/sprint28/index.ts
> +          _type: 'figureExplanationItem',
If you do decide to stick with `figureExplanationItem` that's fine to, but then I'd expect the group to be named `figureExplanationGroup` or `figureExplanationItemGroup` instead.

2021-07-28 09:32 UTC, VWSCoronaDashboard8 commented on packages/cms/src/migrations/sprint28/index.ts
> +          _type: 'figureExplanationItem',
I see that the word "figure" is used a lot in the English texts that these items contain. And that figure in English can also just mean statistics without having a visual representation attached to it. So I guess the word figure is fine here after all.

My suggestions for consistent type naming still stand then.

2021-07-28 14:37 UTC, VWSCoronaDashboard13 commented on packages/cms/src/migrations/sprint28/index.ts
> +          _type: 'figureExplanationItem',
I can update `figureExplanationItem` to `cijferVerantwoordingItem`. I will say it looks like the other documents like FAQ also use a mix of english and dutch naming so in a way this change will result in inconsistency with those. 

As for the `cijferVerantwoordingGroup` document I think it should be plural since it houses all of the groups? 
```
export const cijferVerantwoordingGroups = {
  name: 'cijferVerantwoordingGroups',
  type: 'document',
  title: 'Cijfer verantwoording groepen',
  fields: [
    {
      name: 'group',
      type: 'localeString',
      title: 'Groepsnaam',
    },
  ],
  preview: {
    select: {
      title: 'group',
    },
    prepare: prepareLocalized,
  },
};
```

2021-07-28 16:29 UTC, VWSCoronaDashboard8 commented on packages/cms/src/migrations/sprint28/index.ts
> +          _type: 'figureExplanationItem',
You're right `cijferVerantwoordingGroups` is correct then 👍

2021-07-28 16:30 UTC, VWSCoronaDashboard8 approved these changes

2021-07-29 11:30 UTC, merged