Add command line script to add an element
minvws/nl-covid19-data-dashboard pull request #3282
Opened 2021-07-29 13:52 UTC by VWSCoronaDashboard1

## Summary

Kind of what the title states.
The prompt lets you choose from a list of generated types and metric names (pulled from the schema's).
When finished successfully it checks if an element with the given values already exists
and if bot, it saves it to both development and production.

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2021-07-29 14:25 UTC, VWSCoronaDashboard8 requested changes

2021-07-29 14:25 UTC, VWSCoronaDashboard8 commented on packages/cms/src/elements/add.ts
> +  const elemenTypeChoices = [
typo

2021-07-29 14:25 UTC, VWSCoronaDashboard8 commented on packages/cms/src/elements/logic/load-schema.ts
> +export function loadSchemaMetricProperties(scope: Scope, metricName: string) {
nit; the fact that it's loading something to get to the metric properties is not so interesting for the consumer I think. This could just be named `getMetricProperties` or something, because then you also know that you're getting.

2021-07-29 14:25 UTC, VWSCoronaDashboard8 commented on packages/cms/src/elements/logic/load-schema.ts
> +function loadJSONFromFile(filePath: string) {
```suggestion
function loadJsonFromFile(filePath: string) {
```

2021-07-29 14:25 UTC, VWSCoronaDashboard8 commented on packages/cms/src/elements/add.ts
> +    return element;
An element needs to be stored under a specific id formatted as [scope, metricName, elementType, (optional) metricProperty]. Then these would be run through change-case snakeCase function and joined together using `__`. 

Also see https://coronadashboard.sanity.studio/desk/elements;nl;nl__hospital_nice__time_series

I don't think I have the original script anymore which did this for the initial set, but I'm sure you'll figure it out :)

2021-07-29 14:25 UTC, VWSCoronaDashboard8 commented on packages/cms/src/elements/add.ts
> +}
Based on that fixed id, this function can be simplified because you only need to check for documents with a specific id.

2021-07-29 14:25 UTC, VWSCoronaDashboard8 commented on packages/cms/src/elements/add.ts
> +  return `${element.scope}.${element.metricName}.${element.metricProperty}.${element._type}`;
This is not correct from the identifier point of view. The optional property comes last. I don't think it matters much because this is just visual feedback but to keep it consistent with what is visible in the CMS I think it's better to match the order of the id.

You might want to prompt the user for the property last as well. I think that makes sense because it's the only optional part, but also not important

2021-07-29 15:04 UTC, VWSCoronaDashboard1 commented on packages/cms/src/elements/add.ts
> +}
Indeed, way simpler!

2021-07-29 15:05 UTC, VWSCoronaDashboard1 commented on packages/cms/src/elements/add.ts
> +  return `${element.scope}.${element.metricName}.${element.metricProperty}.${element._type}`;
I agree, I placed the metric property last in the prompt cycle. And fixed the id generation order.

2021-07-30 06:29 UTC, VWSCoronaDashboard8 approved these changes

2021-07-30 06:29 UTC, VWSCoronaDashboard8 commented on packages/cms/src/elements/add.ts
> +}
No need to roll our own I think. We already use the change-case module which has a method to convert things to snake case

```
import { snakeCase } from 'change-case';
```

2021-07-30 06:41 UTC, VWSCoronaDashboard1 commented on packages/cms/src/elements/add.ts
> +}
Ah, sorry, I missed that one, I'll replace it

2021-08-02 12:12 UTC, merged