Feature/align dropdowns international page
minvws/nl-covid19-data-dashboard pull request #3301
Opened 2021-08-03 11:52 UTC by VWSCoronaDashboard14

2021-08-10 08:35 UTC, VWSCoronaDashboard1 requested changes

2021-08-10 08:35 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/international/select-country/select-country.tsx
> +   * Everytime the user inputs a new value reset the focus index to the beginning of the results.
```suggestion
   * Every time the user inputs a new value reset the focus index to the beginning of the results.
```

2021-08-10 08:35 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/international/select-country/select-country.tsx
> +         * Set the currently selected country when opened, otherwise fall back to the currently selected country.
set the currently selected country, otherwise fall back to...the currently selected country?
This comment is confusing ;)

2021-08-10 08:35 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/international/select-country/select-country.tsx
> +    fontSize: '1em',
size should come from the theme. Perhaps add a text variant for this specific instance, or choose one that already has these properties.

2021-08-10 08:35 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/international/select-country/select-country.tsx
> +    border: `1px solid silver`,
color should come from the theme

2021-08-10 08:35 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/international/select-country/select-country.tsx
> +    backgroundColor: 'white',
color should come from the theme

2021-08-10 08:35 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/international/select-country/select-country.tsx
> +    color: 'black',
color should come from the theme

2021-08-10 08:35 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/international/select-country/use-hit-selection.ts
> +import { useRef, useState } from 'react';
I see there are already two use-hit-selection hooks in the code base. Is this an exact copy? Then perhaps use the existing one. If not, maybe its an idea to investigate whether it is possible to create a generic hook that can be used for all the current instances.

2021-08-10 08:35 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/modulo.ts
> +export function modulo(current: number, max: number) {
I don't think `modulo` quite covers the implementation here, it looks like a specialized use of modulo. Perhaps the name can better reflect this?

2021-08-12 07:46 UTC, Denniswegereef commented on packages/app/src/domain/international/select-country/select-country.tsx
> +    backgroundColor: 'white',
Isn't white in the theme?

2021-08-12 07:49 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/international/select-country/select-country.tsx
> +    backgroundColor: 'white',
Isn't white coming from the theme?

2021-08-12 07:56 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/international/select-country/use-hit-selection.ts
> +import { useRef, useState } from 'react';
This isn't an exact copy hit has some specific behavior for this dropdown. I understand that maybe using a more generic approach could be feasible. But on the other end, I'd like to keep this behavior tied to this component.

2021-08-12 08:25 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/positive-modulo.ts
> + * For example floorMudulo8, 5) => 3
```suggestion
 * For example positiveModulo(8, 5) => 3
```

2021-08-12 09:18 UTC, VWSCoronaDashboard14 commented on packages/app/src/utils/positive-modulo.ts
> + * For example floorMudulo8, 5) => 3
Ah yeah, that was my old naming

2021-08-18 09:57 UTC, VWSCoronaDashboard1 approved these changes

2021-08-18 09:57 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/international/select-country/select-country.tsx
> +        onMouseUp={() => setIsMouseDown(false)}
Have you tested the following scenario with this approach:
Click on the component, drag your mouse pointer outside of the component and THEN release the mouse button.
I suspect that the state won't be reverted in that case. But perhaps this won't really interfere that much, just something to test before release, I suppose.

2021-08-18 12:37 UTC, merged