Add GGD measurements
minvws/nl-covid19-data-dashboard pull request #338
Opened 2020-09-16 14:22 UTC by VWSCoronaDashboard4

## Summary & Motivation

Adds GGD measurements to the UI.

## Detailed design

Most things are similar to the other tiles.

Is there any feedback on the way I render the KPI sentence around the percentage?

## Drawbacks

n/a

## Alternatives

n/a

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-09-16 15:26 UTC, VWSCoronaDashboard1 approved these changes

2020-09-16 15:26 UTC, VWSCoronaDashboard1 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +                        )}</span>`,
Indeed this looks very verbose in order to just replace a few values. I wouldn't know of a cleaner way to do this though, but this is something we might need to discuss and see if we can come up with a nicer solution. For now, it works, so let's leave it.

2020-09-16 18:23 UTC, VWSCoronaDashboard commented on src/locale/nl.json
> +    "percentage_ggd_positief_getest_getest_week_uitleg": "dit is {{percentage}} van {{totaal}} geteste personen"
nit: Might be easier to put this all in one object, to keep them contained/namespaced.

2020-09-16 18:24 UTC, VWSCoronaDashboard commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +import { useState, Fragment } from 'react';
No need for Fragment, you can use `<>`

2020-09-17 07:54 UTC, VWSCoronaDashboard4 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +import { useState, Fragment } from 'react';
No, that's not possible for the way it is used.

2020-09-17 11:55 UTC, VWSCoronaDashboard1 approved these changes

2020-09-23 13:25 UTC, VWSCoronaDashboard8 requested changes

2020-09-23 13:25 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +const percentageGgdText: typeof siteText.positief_geteste_personen_ggd =
This looks weird. Using typeof on a value to extract a type, and then assigning the same value to the type. Typescript should infer the same time if you leave out the type definition @VWSCoronaDashboard4 

Looks like it happened before in this file, so maybe that inspired you...

2020-09-23 13:25 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            title={percentageGgdText.titel}
There's a lot of `percentageGgdText.` type of prefixes in this file. I would destructure it first.

2020-09-23 13:25 UTC, VWSCoronaDashboard8 commented on src/utils/replaceKpisInText.ts
> +  translation?: string | undefined | null,
Why undefined *and* null? Also undefined is already implied by the `?`

2020-09-23 13:25 UTC, VWSCoronaDashboard8 commented on src/utils/replaceKpisInText.ts
> + * @param kpis - An object with keys representing kpi object containing a value and class name available for replacement.
These king of annotations are a little redundant. Typescript will tell you the shape of the kpis. So now you have to remember to update the comments whenever the code changes.

2020-09-23 13:25 UTC, VWSCoronaDashboard8 commented on src/utils/replaceKpisInText.ts
> +  translation?: string | undefined | null,
In what situation would you want to call "replace in text" without passing an actual text? Similarly why would you call this to replace kpis in a string if you do not have any kpis? In other words, are you sure these function arguments need to be optional?

2020-09-23 13:25 UTC, VWSCoronaDashboard8 commented on src/utils/replaceKpisInText.ts
> +  const variables: { [key: string]: string | undefined } = {};
I don't see any code below that would make the result undefined. Looks like all iterations will produce a string.

2020-09-23 14:46 UTC, VWSCoronaDashboard1 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +const percentageGgdText: typeof siteText.positief_geteste_personen_ggd =
This is legacy code, the typing is no longer necessary since the entire locale struct is typed in locale/index.ts

2020-09-25 11:15 UTC, VWSCoronaDashboard4 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            title={percentageGgdText.titel}
I've adjusted this variable name, but destructing it first causes other troubles (and it's not consistent with our use of `text.` in other pages)

2020-09-25 11:50 UTC, VWSCoronaDashboard commented
In this situation I would prefer a different message

![image](https://user-images.githubusercontent.com/66416946/94263868-04ad3b00-ff36-11ea-8cb9-7f65b56d8c63.png)

would be better as:

**"Geen van de GGD testen was positief"**

2020-09-25 12:00 UTC, VWSCoronaDashboard reviewed
Please add tests for your new utility method.

Besides that, I think we should start thinking about different i18n and l10n solutions to make maintenance of this project a bit easier. I know bundle size is a concern, but still...

2020-09-25 12:15 UTC, VWSCoronaDashboard4 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +                  }}
Not sure if any of these packages would solve / improve any of the attached code. What specific part do you want to see to be simplified?

2020-09-25 12:18 UTC, VWSCoronaDashboard4 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            Icon={Fragment}
Now that I look at this again... I'll work on simplifying this! It's working around the problem that without the icon it messes up the spacing of the layout, which is a silly excuse.

2020-09-25 13:16 UTC, VWSCoronaDashboard4 commented
@VWSCoronaDashboard The -% would be a data issue, I've added an extra safeguard to prevent this from getting displayed.

2020-09-25 13:18 UTC, VWSCoronaDashboard commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +                  }}
It would make pluralization easier, and it would remove the need for our custom replacement methods.

2020-09-25 13:18 UTC, VWSCoronaDashboard commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +                  }}
But we can take that off the table and put it on the tech debt backlog!

2020-09-25 13:19 UTC, VWSCoronaDashboard commented on src/components/layout/Content.tsx
> +  Icon?: React.ComponentType;
👍

2020-09-25 13:19 UTC, VWSCoronaDashboard approved these changes

2020-09-25 13:28 UTC, merged