PoC: Create generic page type and add conditional fields to Sanity
minvws/nl-covid19-data-dashboard pull request #3414
Opened 2021-08-30 11:43 UTC by VWSCoronaDashboard

## Summary

Trying to reduce the amount of unique schema's we have in Sanity

## Motivation

- Easier to add new pages
- Easier to remove pages
- Easier to group by schema type in Sanity and create an organized CMS
- In the future... add localizations per page?

## Detailed design

Coming soon...

2021-09-10 07:57 UTC, VWSCoronaDashboard1 requested changes
This is a pretty cool start. As for this comment: `In the future... add localizations per page`
I think if we use the pageidentifier key as the root key for all the lokalize keys that belong to a page, then it should already be possible to create apge that show a subselection of lokalize keys, no?

2021-09-10 07:57 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +  console.log(content);
Remove console

2021-09-10 07:57 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/documents/pages/article-page-articles.ts
> +      };
I don't really grasp what's going on here. The `prepare` creates a title and subtitle based off, what I understand, three articles, yet in the `select` 4 articles are used?

2021-09-10 07:57 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/documents/pages/article-page-articles.ts
> +  name: 'articlePageArticle',
nit: keep the export and document the same. I also think that perhaps `pageArticles` is a better name for the document, instead of `articlePageArticle` which is a bit convoluted. If we prefix all of the documents that have a pageIdentifier with `page` I think we can keep a consistent naming scheme.

2021-09-10 07:57 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/documents/pages/article-page-links.ts
> +      };
Same comment as on the page articles, I'm not following the intent of this code. (I'm not very smart, so that might be an issue...)

2021-09-10 07:57 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/documents/pages/article-page.ts
> +  name: 'articlePage',
I'd call this `pageIdentifier`, I think it a little clearer for the intent of this document.

2021-11-09 08:11 UTC, VWSCoronaDashboard7 commented
We're ended up going with a slightly different route so this became obsolete. Closing for that reason.

2021-11-09 08:11 UTC, closed without merging