Update vaccination per age group table
minvws/nl-covid19-data-dashboard pull request #3505
Opened 2021-09-13 10:08 UTC by VWSCoronaDashboard14

2021-09-15 13:14 UTC, VWSCoronaDashboard1 requested changes

2021-09-15 13:14 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/bar.tsx
> +}
```suggestion
type BarWithValue = {
  value: number;
};
type BarWithLabel = {
  label: string | null;
};

type BarProps = {color: string;} & (BarWithValue  |  BarWithLabel );

function isBarWithValue(props:BarProps): value is BarWithValue  {
  return 'value' in props;
}
function isBarWithLabel (props:BarProps): value is BarWithLabel {
  return 'label' in props;
}

```

2021-09-15 13:14 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/bar.tsx
> +export function Bar({ value, color, label }: BarProps) {
```suggestion
export function Bar(props: BarProps) {
```

2021-09-15 13:14 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/bar.tsx
> +  }
```suggestion
  const percentageBarValue = isBarWithLabel(props) ? parseFullyVaccinatedPercentageLabel(props.label).value :  isBarWithValue(props) ? props.value : undefined;
```

2021-09-15 13:14 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/bar.tsx
> +      )}
```suggestion
      {isDefined(percentageBarValue) && (
        <PercentageBar
          percentage={percentageBarValue}
          height={8}
          color={color}
          backgroundStyle={isBarWithLabel(props) ? 'hatched' : 'normal'}
        />
      )}
```

2021-09-15 13:21 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/percentage-bar.tsx
> +          })}
Can't we use transparent instead of white so we don't run into trouble if we ever change our background color to some off-white color?

2021-09-15 14:49 UTC, VWSCoronaDashboard16 requested changes

2021-09-15 14:49 UTC, VWSCoronaDashboard16 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/age-group.tsx
> +    </Box>
Why use `InlineText` and then make the container flex column? It has the same visual result as using a non-styled container with `Text` elements, right?

2021-09-15 14:49 UTC, VWSCoronaDashboard16 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/narrow-percentage.tsx
> +        />
Instead of doubling this template I would determine the textValue above in a variable and just insert it here as value.

Also, I think we can maybe write a more common function which does this whole value/label formatting. The same is done for the tooltip in the choropleth and we now have multiple lokalize keys for this. We can do that later though.

2021-09-15 14:49 UTC, VWSCoronaDashboard16 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/wide-percentage.tsx
> +    </>
Same here, would put the textValue in a variable so you don't have the double template here.

2021-09-15 15:27 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/narrow-percentage.tsx
> +        />
Let's do it later, please.

2021-09-16 09:05 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/age-group.tsx
> +    </Box>
Want to use spans for the text instead of regular paragraph elements. I could either set the spans as block elements or just use a flex-direction to put them horizontally under each other.

2021-09-16 09:07 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/wide-percentage.tsx
> +    </>
Keeping this for now since we're gonna get a more generic function for this.

2021-09-16 09:11 UTC, merged