Add new actueel KPI/Chart section
minvws/nl-covid19-data-dashboard pull request #3578
Opened 2021-09-27 11:20 UTC by VWSCoronaDashboard1

## Summary

This PR adds the new KPI/Chart selector on the national, municipal and safety region Actueel page, as per design:

### National

![image](https://user-images.githubusercontent.com/69849293/134898660-487310fa-9391-4ffd-9f10-3a4ff815cb90.png)

### Municipality

![image](https://user-images.githubusercontent.com/69849293/134897390-4c4a2de1-425b-4604-8b62-26c4283a9bfa.png)

This PR also re-implemented the element warnings as a separate document, instead of a property on the timeseries.

2021-09-27 11:52 UTC, VWSCoronaDashboard17 reviewed
<img width="1371" alt="Screenshot 2021-09-27 at 13 51 54" src="https://user-images.githubusercontent.com/89384854/134902734-63aa6538-b111-4f63-884e-c5ea70687d21.png">

Should these tiles maybe be stacks instead of columns? It looks quite squished.

2021-09-27 11:52 UTC, VWSCoronaDashboard17 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/bar.tsx
> +              left: `calc(${Math.round(barValue)}% - 30px)`,
<img width="486" alt="Screenshot 2021-09-27 at 13 48 41" src="https://user-images.githubusercontent.com/89384854/134902338-61f7765e-ce99-49be-a87c-689a7f3abf5a.png">

Is this going to overlap with the 100% label if the score gets any higher?

2021-09-27 11:53 UTC, VWSCoronaDashboard17 approved these changes

2021-09-27 12:00 UTC, VWSCoronaDashboard14 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/bar.tsx
> +              left: `calc(${Math.round(barValue)}% - 30px)`,
There is a subtle gradient behind the value that hides the 100% text

2021-09-27 14:04 UTC, VWSCoronaDashboard16 requested changes
Some questions and bugs I found. Some of the comments obviously apply to all three implementations

2021-09-27 14:40 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/vaccine/vaccine-coverage-per-age-group/components/bar.tsx
> +              left: `calc(${Math.round(barValue)}% - 30px)`,
^ what he said

2021-09-27 14:46 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/topical/mini-tile.tsx
> +        <Box position="relative" pl={{ _: 0, md: 3 }}>
The designs never look like the end result since there's no design system, but there is a theme. But I'll add some more space, why not.

2021-09-27 14:48 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/topical/mini-tile-selector-layout.tsx
> +          {collapsible.button()}
I'm keeping this as tight as possible because on the smallest screens this gets REALLY cozy when everything is shown. So, the sparkbar, a long label, a warning icon and a large percentage value.

2021-09-27 14:51 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/topical/mini-tile-selector-layout.tsx
> +          )}
The WarningIconWrapper has a small right margin.

2021-09-27 15:00 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/actueel/gemeente/[code].tsx
> +                          renderedAgeGroup18Pluslabels,
Please explain what the bug is...

2021-09-27 15:27 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/actueel/gemeente/[code].tsx
> +                      ?.fully_vaccinated_percentage ?? 0,
I've added the sign to the bar label as well, since it was missing there too

2021-09-28 07:02 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/actueel/gemeente/[code].tsx
> +                          renderedAgeGroup18Pluslabels,
So, that's not a parsing issue, but a copy issue ;)

2021-09-28 09:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/actueel/gemeente/[code].tsx
> +                          renderedAgeGroup18Pluslabels,
@VWSCoronaDashboard16 Alright, I tweaked the label rendering, should be good now:
![image](https://user-images.githubusercontent.com/69849293/135062799-fe90f1e0-9119-4f31-9359-dbd2c70b7fed.png)

2021-09-28 11:29 UTC, VWSCoronaDashboard1 commented
> <img alt="Screenshot 2021-09-27 at 13 51 54" width="1371" src="https://user-images.githubusercontent.com/89384854/134902734-63aa6538-b111-4f63-884e-c5ea70687d21.png">
> 
> Should these tiles maybe be stacks instead of columns? It looks quite squished.

This is a screenshot of the current actueel page, not of the new screen that is part of this PR, so I'm not sure what you mean ;)

2021-09-28 20:25 UTC, merged