Add a border to the spark bars
minvws/nl-covid19-data-dashboard pull request #3777
Opened 2021-11-02 15:03 UTC by VWSCoronaDashboard14

Quite subtle but it's there. Can't simply use a border-bottom since the SVG is a bit wider than the bars.

<img width="443" alt="Screenshot 2021-11-02 at 16 03 02" src="https://user-images.githubusercontent.com/76471292/139873307-f33f0a6b-7da9-45ff-a995-686de7a3837d.png">

2021-11-02 16:11 UTC, VWSCoronaDashboard16 requested changes
If I read the code correctly you shift all SVG content down by `BORDER_HEIGHT`, which explains the need for having an `overflow: visible`. Why not keep everything on its 'normal' place?

2021-11-02 16:11 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/spark-bars.tsx
> +          y={y(Math.max(0, d[averageProperty])) + BORDER_HEIGHT}
If we add the border height we shift all bars to be partly behind the border, that's not what we want right?

2021-11-02 16:11 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/spark-bars.tsx
> +        y={BAR_HEIGHT + BORDER_HEIGHT}
Ah right you add the border height here as well, so the whole SVG gets shifted 2 pixels down. Why?

2021-11-02 16:26 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/spark-bars.tsx
> +      })}
In some weird way yes. When not using this it show a small rendering bug on the second spark bar? But unsure why.

2021-11-02 16:28 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/spark-bars.tsx
> +        y={BAR_HEIGHT + BORDER_HEIGHT}
Nope, I had to extend the view box by 2 pixels and let the bars render on Y with their height. And let the border render at the height of the bars + the height of the border. By not doing that the border is overlapping the bottom of the bars, but I want to keep the height of the bars.

2021-11-03 07:50 UTC, VWSCoronaDashboard17 commented on packages/app/src/components/spark-bars.tsx
> +          y={y(Math.max(0, d[averageProperty])) + BORDER_HEIGHT}
Instead, the `y` scale should probably go from `0` to `height - BORDER_HEIGHT`.

2021-11-05 08:41 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/spark-bars.tsx
> +          y={y(Math.max(0, d[averageProperty])) + BORDER_HEIGHT}
If I understand correctly the bars should still go from `0` to `BAR_HEIGHT` but we add a border with `BORDER_HEIGHT` below. I would expect that we only need to extend the viewbox and add the border at `y=BAR_HEIGHT`. 

I just don't understand why both the bars as the border are shifted down by `BORDER_HEIGHT`, it only results in all bars starting two pixels lower and the border being outside the SVG:

![image](https://user-images.githubusercontent.com/85888969/140482593-ef11e4ec-c6c8-4009-bd70-ec63ca6397f1.png)

2021-11-08 09:13 UTC, VWSCoronaDashboard16 approved these changes

2021-11-08 09:15 UTC, merged