Feature/add aria label to interactive legend buttons
minvws/nl-covid19-data-dashboard pull request #3838
Opened 2021-11-22 14:30 UTC by VWSCoronaDashboard22

Added an aria label to interactive legends which use age. Screen readers were not able to let the user know what unit the number were in.

2021-11-22 14:37 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/interactive-legend.tsx
> +  ariaLabel?: 'string';
` ariaLabel?: 'string';` -> `ariaLabel?: string;`

2021-11-22 14:41 UTC, VWSCoronaDashboard1 requested changes
Are you 100% sure that those are the only charts with interactive legends? I thought there were more, but I could be mistaken...

2021-11-22 14:41 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/interactive-legend.tsx
> +  ariaLabel?: 'string';
```suggestion
  legendAriaLabel?: string;
```

2021-11-22 14:54 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/interactive-legend.tsx
> +  ariaLabel?: 'string';
Fixed SelectOption interace and renamed ariaLabel property

2021-11-23 10:51 UTC, VWSCoronaDashboard1 approved these changes

2021-11-23 12:57 UTC, VWSCoronaDashboard14 approved these changes

2021-11-23 13:02 UTC, merged