Add more chart sanity configs
minvws/nl-covid19-data-dashboard pull request #3839
Opened 2021-11-22 14:56 UTC by VWSCoronaDashboard1

## Summary

This PR adds support for the age demographic charts, donut charts and choropleths to Sanity. In order for he editors to be able to add these charts to articles and other portable text content

2021-11-22 16:12 UTC, VWSCoronaDashboard19 commented on packages/app/src/components/cms/inline-age-demographic.tsx
> +  if (!isDefined(data)) {
Is it convenient to create a seperate file for line 39 to 45 (repeated piece of code), so it can also be used in the `inline-choropleth.tsx` and  `inline-donut-chart.tsx`?

2021-11-22 16:30 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/cms/inline-age-demographic.tsx
> +  if (!isDefined(data)) {
Sure, I'll make the change

2021-11-23 10:25 UTC, VWSCoronaDashboard16 requested changes
Nice one! Found some small bugs though. And I would have expected that the age demographic chart adhered to the content width, or is it by design that it's wider?
![image](https://user-images.githubusercontent.com/85888969/143007825-ea3cb7f4-941f-46e5-af7a-fe7373c7edea.png)

2021-11-23 10:25 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/cms/inline-choropleth.tsx
> +  };
Links are not working right now because it's trying to get the links from the reverseRouter hook itself instead of from the router it returns.

```suggestion
  const { siteText } = useIntl();
  
  const reverseRouter = useReverseRouter();

  const dateUrl = getDataUrl(undefined, undefined, configuration, 'choropleth');

  const { data } = useSWRImmutable(dateUrl, (url: string) =>
    fetch(url).then((_) => _.json())
  );

  if (!isDefined(data)) {
    return <InlineLoader />;
  }

  const dataOptions = {
    getLink: isDefined(configuration.link)
      ? get(reverseRouter, configuration.link, undefined)
      : undefined,
    tooltipVariables: parseTooltipVariables(
      configuration.tooltipVariables,
      siteText
    ),
  };
```

2021-11-23 10:25 UTC, VWSCoronaDashboard16 commented on packages/cms/src/schemas/documents/choropleth-configuration.ts
> +      title: 'Highlight stroke width',
```suggestion
      title: 'Highlight stroke',
```

2021-11-23 10:25 UTC, VWSCoronaDashboard16 commented on packages/cms/src/schemas/documents/choropleth-configuration.ts
> +      title: 'Area stroke width',
```suggestion
      title: 'Area stroke',
```

2021-11-23 10:25 UTC, VWSCoronaDashboard16 commented on packages/cms/src/schemas/documents/choropleth-configuration.ts
> +    },
None of these options are passed through to the actual choropleth component, so what's the use of having them here?

2021-11-23 10:25 UTC, VWSCoronaDashboard16 commented on packages/cms/src/schemas/documents/age-demographic-chart-configuration.ts
> +    },
This one is not passed on to the actual component yet

2021-11-23 10:54 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/cms/inline-choropleth.tsx
> +  };
haha, good catch, this was a dumb mistake of mine haha

2021-11-23 10:56 UTC, VWSCoronaDashboard1 commented on packages/cms/src/schemas/documents/choropleth-configuration.ts
> +    },
That's a mistake on my part as well, I was using a simpler implementation as a reference, but I need to add all of these options to the choropleth config. Well spotted, I obviously was sleeping at the end of the is PR hehe

2021-11-23 13:01 UTC, VWSCoronaDashboard16 approved these changes

2021-11-23 13:03 UTC, merged

2021-11-23 13:30 UTC, VWSCoronaDashboard1 commented
> Nice one! Found some small bugs though. And I would have expected that the age demographic chart adhered to the content width, or is it by design that it's wider? 

Yes indeed, this is by design