Feature/lazy loading component
minvws/nl-covid19-data-dashboard pull request #3877
Opened 2021-12-02 07:55 UTC by VWSCoronaDashboard22

Added a component to detect it a child is in view and render it when it is

2021-12-02 09:41 UTC, VWSCoronaDashboard19 commented on packages/app/src/components/in-view.tsx
> +  once?: boolean;
Maybe a better name for this as it is a boolean, instead of `once`. Prefixing it with `is`, `has` or `can`.

2021-12-02 17:03 UTC, VWSCoronaDashboard20 approved these changes

2021-12-02 17:03 UTC, VWSCoronaDashboard20 commented on packages/app/src/components/in-view.tsx
> +  once?: boolean;
That name is pre-defined by the package we use. I think we are not able to change this.

2021-12-03 09:49 UTC, VWSCoronaDashboard1 reviewed
I have checked out the branch locally and when switching from the vaccination page to positive tests I get this error:
![image](https://user-images.githubusercontent.com/69849293/144582052-727d8755-742b-4e99-afba-b73103f4b9ec.png)

2021-12-03 12:16 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/in-view.tsx
> +  once?: boolean;
Changed prop name

2021-12-03 12:29 UTC, VWSCoronaDashboard1 requested changes
This PR will reduce the DOM size considerably, because the charts are lazy rendered, therefore improving the user experience.  It doesn't lazy *load* the components though, so the component and data will be part of the initial download. Another improvement here could be to dynamically load the chart component and associated data (which was the original plan behind the ticket).
Have you checked the lighthouse scores before and after this improvement?

2021-12-03 12:29 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/in-view.tsx
> +  }, [isInView]);
Is this really necessary? `isInview ` already returns a stateful value, so if it changes the component will be re-rendered.

2021-12-03 12:29 UTC, VWSCoronaDashboard1 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +            <InView>
I see you've added to rootMargin as an optional prop on `InView` perhaps use a negative margin roughly the height of a chart so that the chart gets loaded right before it scrolls into view. This might give a smoother UX because it will prevent charts 'plopping into view' a bit.

2021-12-06 12:49 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/in-view.tsx
> +  }, [isInView]);
Changed it to useRef

2021-12-06 12:50 UTC, VWSCoronaDashboard22 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +            <InView>
Added rootMargins to all InView components

2021-12-06 15:36 UTC, VWSCoronaDashboard1 requested changes

2021-12-06 15:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/use-is-in-view.ts
> +    observer.observe(htmlElement);
```suggestion
  const connect = useCallback(
    (observer: IntersectionObserver, htmlElement: HTMLElement) =>
      observer.observe(htmlElement),
    []
  );
```

2021-12-06 15:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/use-is-in-view.ts
> +    return () => element.current && disconnect(observer, element.current);
```suggestion
    if (!element.current) return;
    
    const currentElement = element.current;

    const observer = new IntersectionObserver(
      ([entry]) => setIsInView(entry.isIntersecting),
      { rootMargin }
    );

    connect(observer, currentElement );
    return () => currentElement  && disconnect(observer, currentElement );
```

2021-12-06 15:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/use-is-in-view.ts
> +  }, []);
```suggestion
  }, [connect, disconnect, element, rootMargin]);
```

2021-12-06 15:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/use-is-in-view.ts
> +    observer.observe(htmlElement);
By the way, instead of using callbacks you could also move these two functions outside of the component. Since they have no dependencies on any local data.

2021-12-06 15:39 UTC, VWSCoronaDashboard1 commented on packages/app/src/utils/use-is-in-view.ts
> +    return () => element.current && disconnect(observer, element.current);
There was actually a lint warning that described this issue, so I made these change accordingly.

2021-12-07 08:11 UTC, VWSCoronaDashboard1 approved these changes

2021-12-07 08:13 UTC, merged