Increase back button spacing
minvws/nl-covid19-data-dashboard pull request #3885
Opened 2021-12-02 15:55 UTC by VWSCoronaDashboard16

Adjusted the general link-with-icon component because all `iconPlacement=left` are back buttons.

2021-12-02 15:59 UTC, VWSCoronaDashboard1 requested changes

2021-12-02 16:13 UTC, VWSCoronaDashboard1 approved these changes

2021-12-02 16:13 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/link-with-icon.tsx
> +              <IconSmall icon={icon} width={11} height={10} mr={1} />
oh wait, nevermind, this is an internally used component, forget what I said hehe

2021-12-03 08:04 UTC, VWSCoronaDashboard19 approved these changes

2021-12-03 08:41 UTC, merged