Feature/loading indicator
minvws/nl-covid19-data-dashboard pull request #3890
Opened 2021-12-03 12:55 UTC by VWSCoronaDashboard18

Added a Loading Indicator and show it while a topical page loads.

2021-12-06 13:22 UTC, VWSCoronaDashboard22 commented
Please use the proper code formatting

2021-12-06 13:26 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/loader/loader.tsx
> +          <Text aria-label={loadingText} lineHeight="1.0">{loadingText}</Text>
Don't use aria-label or aria-labelledby on any other non-interactive content such as p, legend, li, or ul, because it is ignored. https://www.w3.org/TR/using-aria/#label-support

2021-12-06 13:33 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/loader/loader.tsx
> +      ref={el => {
Why not do this with css?

2021-12-06 13:44 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/loader/loader.tsx
> +  const transitionProps:TransitionProps = {
Why use TransitionProps here? Types will be inferred

2021-12-06 13:56 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/loader/loader.tsx
> +  const toTopOverlay:ToTopOverlay = {
What's the use of creating two variables to pass into the Box

2021-12-06 14:02 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/loader/loading-router.tsx
> +      { isLoading && <Loader/> }
Maybe render either the loader or the children.

2021-12-06 14:04 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/loader/loading-router.tsx
> +  children?: React.ReactNode;
Why is children optional?

2021-12-06 14:06 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/loader/loading-router.tsx
> +  layout?: string;
Confusing parameter name. Think this is more about the url than the layout

2021-12-06 14:17 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loader.tsx
> +  const toTopOverlay:ToTopOverlay = {
Because line 85 & line 99

2021-12-06 14:43 UTC, VWSCoronaDashboard20 commented on packages/app/src/components/loader/loading-router.tsx
> +        setTimeout(() => {
The way it is set up now, it will start after 700ms. If you set setIsLoading to true before the setTimeOut and in the setTimeOut set it to false, it will stop 700ms after, that's I think the intended behavior. See example below:

` if (url.startsWith('/' + layout)) {
      setIsLoading(true);
        setTimeout(() => {
          setIsLoading(false);
          setHasCompleted(!hasCompleted);
        }, 700);
      }
    });`

2021-12-06 14:43 UTC, VWSCoronaDashboard20 commented on packages/app/src/components/loader/loading-router.tsx
> +
Do we want to do something with routeChangeError as well?

2021-12-06 14:43 UTC, VWSCoronaDashboard20 commented on packages/app/src/components/loader/loading-router.tsx
> +import React, { useEffect, useState }from 'react';
loading-router doesn't describe what this component is doing. Can you think of something more descriptive? It will not only make it more readable but also helps you think about your component.

2021-12-06 15:03 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-router.tsx
> +        setTimeout(() => {
I think your assumption is incorrect. The requirement is that the loading indicator only is visible after a certain amount of milliseconds. So, the logic that sets the state to loading is correct in this case.

2021-12-06 15:07 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/typography.tsx
> +  lineHeight?: CSSProperties['lineHeight'];
do NOT add css properties to the Text component. Text styles are only allowed as variants, so no inline css props are allowed. Please refer to the docs: https://minvws.github.io/nl-covid19-data-dashboard/styled-system.html

2021-12-06 15:09 UTC, VWSCoronaDashboard1 commented on packages/app/src/domain/layout/gm-layout.tsx
> +        </LoadingRouter>
See my comment about rendering page as children of the loading indicator. I believe this makes more sense:
```
<ErrorBoundary>
  <LoadingRouter previousUrl={"gemeente/" + code}/>
  {children}
</ErrorBoundary>
```

2021-12-06 15:12 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loader.tsx
> +        const elBottom = rect.bottom > windowHeight ? windowHeight : rect.bottom;
As previously indicated, this is better solved using CCS.
Another problem with this code is that calling functions like `getBoundingClientRect` and even assigning `window.innerHeight` will trigger a reflow in the browser, so you potentially start layout thrashing here.

2021-12-06 15:14 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-router.tsx
> +        }, 700);
The requirement stated 700ms as a starting off point, but it was also mentioned that this value should be tweaked during development to find the sweet spot. Did you do you this and did 700ms turn out to be exactly the sweet spot?

2021-12-06 15:15 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loader.tsx
> +            {delayTiming.map((delayPercentage, i) => <MotionBox key={i} {...attributes} transition={{...transitionProps, delay: delayPercentage}} />)}
nitpick: The requirements state that movement of the bars should happen at random, as far as I can see, currently they are deterministic. ;)

2021-12-06 15:20 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loader.tsx
> +  const toTopOverlay:ToTopOverlay = {
Its probably cleaner to just create two styled div instances and to give them a proper name that reflects their usage. That's sort of the point of styled components, imho.

2021-12-06 15:34 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/loader/loader.tsx
> +            ))}
Using motion elements for this is quite expensive performance wise. I think the animation you are building here can also easily be defined as a css animation, no?

2021-12-06 16:38 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loading-router.tsx
> +    <Box position="relative">
Then it needs an additional relative box on the parent of the siblings. Now it is a generic solution and works with any parent.

2021-12-06 16:38 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loading-router.tsx
> +        }, 700);
When testing 700ms felt right to me. I tried other values lower and higher, but this looked good.

2021-12-07 11:36 UTC, VWSCoronaDashboard1 requested changes

2021-12-07 11:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +    }
```suggestion
    const handleRouteChangeStart  = (url, { shallow }: { shallow: boolean }) => {
      if (shallow) return;
      setRouterLoadState('idle');
      window.scrollTo(0, 0);
      setTimeout(() => {
        setRouterLoadState('loading');
      }, 700);
    }
```

2021-12-07 11:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +  );
```suggestion
return state === 'complete'
  ? null
  : <Loader showLoader={routerLoadState === 'loading'} />;
```

2021-12-07 11:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +    }
the setTimeout method on line 23  doesn't get cleaned up here

2021-12-07 11:36 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +    }
I think checking the `shallow` param probably negates the need for the `currentRoute` state and the `previousUrl` prop. It will need some testing and tweaking obviously, but I think its worth investigating.

2021-12-07 14:06 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loader.tsx
> +            {delayTiming.map((delayPercentage, i) => <MotionBox key={i} {...attributes} transition={{...transitionProps, delay: delayPercentage}} />)}
Won't do

2021-12-07 14:06 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loader.tsx
> +        const elBottom = rect.bottom > windowHeight ? windowHeight : rect.bottom;
It needs this for the right CSS heigt

2021-12-07 14:22 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +        const heightOfInView = elBottom - elTop + 'px';
This isn't possible with regular CSS? I saw a comment from @VWSCoronaDashboard1 also mentioning this.

2021-12-07 15:10 UTC, VWSCoronaDashboard18 commented on packages/app/src/style/preset.ts
> +    },
https://minvws.github.io/nl-covid19-data-dashboard/styled-system.html#:~:text=Typography,body1%20preset%3C/Text%3E.

2021-12-07 15:11 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loader.tsx
> +        const heightOfInView = elBottom - elTop + 'px';
No it's not. Because css doesn't know the height of the top of the parent till the bottom of the parent OR the fold.

2021-12-07 15:26 UTC, VWSCoronaDashboard16 commented on packages/app/src/components/loader/loader.tsx
> +        const heightOfInView = elBottom - elTop + 'px';
What about 
```
height: 100%;
maxHeight: 100vh;
```?

2021-12-07 15:30 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loader.tsx
> +        const heightOfInView = elBottom - elTop + 'px';
Because 100vh is to high, the header and navigation height needs to be subtracted.

2021-12-07 15:48 UTC, VWSCoronaDashboard1 submitted a review, later dismissed

2021-12-07 15:48 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +  const loaderTimeout = useRef(() => setTimeout(handleLoadingTimeout, 700));
This code doesn't make sense I'm afraid. The correct way to handle this is to create an empty ref and each time that `setTimeout()` is called assign the resulting id to it.
I.e. `const timeoutIdRef = useRef(0);`

Your `clearTimeout` calls in the rest of the file would otherwise always be called with a different id, so the original timeout would never get cleared. Did you run these code changes? Because I suspect that the loader would now always pop up, regardless of the timeout clearances.

2021-12-07 15:48 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +      url.startsWith('/' + previousUrl) && currentRoute !== url && loaderTimeout.current();
```suggestion
      if (url.startsWith('/' + previousUrl) && currentRoute !== url) {
        timeoutIdRef.current = setTimeout(handleLoadingTimeout, 700);  
      }
```

2021-12-07 15:48 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +      clearTimeout(loaderTimeout.current());
```suggestion
      if (timeoutIdRef.current > 0) {
        clearTimeout(timeoutIdRef.current);
        timeoutIdRef.current = 0;
      }
```

2021-12-07 15:48 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +      clearTimeout(loaderTimeout.current());
```suggestion
      if (timeoutIdRef.current > 0) {
        clearTimeout(timeoutIdRef.current);
        timeoutIdRef.current = 0;
      }```

2021-12-07 15:48 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +      clearTimeout(loaderTimeout.current());
```suggestion
      if (timeoutIdRef.current > 0) {
        clearTimeout(timeoutIdRef.current);
        timeoutIdRef.current = 0;
      }```

2021-12-07 15:48 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loader.tsx
> +}
As mentioned before, instead of having all of these css property interfaces here, its better to just create a few styled divs with the appropriate styles configured there.
In the same way that LoaderBar is styled. You're mixing two styles of coding here, so for consistency sake its best to choose one approach and in the rest of the code base its preferred to use styled components.

2021-12-07 16:07 UTC, VWSCoronaDashboard16 commented
I think we need to up some z-index somewhere 
![image](https://user-images.githubusercontent.com/85888969/145064361-0a7cfd72-19c4-4206-b417-cb980ef572a1.png)

2021-12-07 18:29 UTC, VWSCoronaDashboard20 approved these changes

2021-12-08 08:38 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +    }
I think the spacing prop on a box component works perfectly here.

2021-12-08 08:48 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +    },
The same goes for here, and also the `asResponsiveArray` received now 1 argument (which is not an object nor an array), so I'm not sure if it even does the job. But maybe we should stronger type this function to avoid confusion.

2021-12-08 08:51 UTC, VWSCoronaDashboard14 reviewed
If you're having a folder name that exports the same name for the component it might look a bit strange in the folder structure. We tend to use a barrel file for that, you can see an example in the folder for the page-information-block, and see what the `index.ts` does.

2021-12-08 08:53 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +const duration = .7;
When using constants we tend to use capital letters for the variable name `const DURATION = 0.7`.

2021-12-08 08:54 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +  const delayTiming = [0, 0.3, 0.5, 0.2, 0.4];
Since these are almost the same as duration and won't change I would also put them above the component and make the variable in capitals letters.

2021-12-08 08:55 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +  const loadingText = siteText.common.loading_text;
I don't think it's necessary to create a variable to hold this text that only gets used once. Just reference in the `<Text>` component directly.

2021-12-08 08:56 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +    bg: colors.white,
You can also use the string notation how we're using it in most places `'colors.white'`.

2021-12-08 08:58 UTC, VWSCoronaDashboard14 commented on packages/app/src/style/preset.ts
> +    },
Is this resolved, I believe the variant is still there. :)

2021-12-08 09:01 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loading-wrapper.tsx
> +  const handleLoadingTimeout = () => setRouterLoadState('loading');;
I see a double `;;`, are you sure the auto-linter is working on save?

2021-12-08 09:09 UTC, VWSCoronaDashboard1 commented on packages/app/src/components/loader/loader.tsx
> +    bg: colors.white,
'white' will do, no need for the colors prefix

2021-12-08 10:19 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loader.tsx
> +  const loadingText = siteText.common.loading_text;
It's used on lines 51 & 52 too.

2021-12-08 10:53 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +          <Text variant="loaderText" >{loadingText}</Text>
We don't need the visually hidden text if it contains the same text as the regular text

2021-12-08 11:44 UTC, VWSCoronaDashboard14 commented on packages/app/src/components/loader/loader.tsx
> +    bg: colors.white,
Oops, you are right

2021-12-08 11:50 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/loader/loader.tsx
> +    }
https://github.com/minvws/nl-covid19-data-dashboard/pull/3890#discussion_r764127407

2021-12-08 14:13 UTC, merged