Add key to `sewer_measurements` schema
minvws/nl-covid19-data-dashboard pull request #391
Opened 2020-09-21 11:30 UTC by VWSCoronaDashboard5

## Summary

The data used in the line-charts of Rioolwater and Huisartsen is the average value over time (one week), the fact that this value is based on a week-basis should be made more clear. This ticket changes the tooltips shown for those graphs to show the `week_start_unix` and the `week_end_unix` in the tooltip for the concerned value.

2020-09-22 13:40 UTC, VWSCoronaDashboard4 commented on src/components/lineChart/regionalSewerWaterLineChart.tsx
> +        const { start, end } = weeklyMeasurements[this.point.index];
I'd prefer a method over a calculated array. Eg have `function getWeekStartEndByIndx(index: number): Week[] { ... }`

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +  value: number | undefined | null;
Are both undefined and null needed?

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +  const multipleAverageValues = values.length > 1;
Prefix booleans to make clear it's a boolean. In this case `hasMultipleValues` or something. Otherwise the name is very vague and it even wrongly implies that it holds multiple values.

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +      data: values.map((value) => [value.date, value.value]),
Nitpick; Personally I like using `x` in these type of short inline functions. It saves space and in this case avoids value.value. So `values.map(x => [x.date, x.value])`

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +        },
```suggestion
        legendItemClick: () => false,
```

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +        },
I don't think a return type definition should be required here. Also an arrow function would be nice for inline. But I guess you got this code from somewhere else.

 ```suggestion
        formatter: () =>
          this.isFirst || this.isLast
            ? formatDate(this.value * 1000, 'axis')
            : '',
   
```

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +      formatter: function (): string {
Similar as previous comment

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +      },
```suggestion
        formatter: () => formatNumber(this.value),
```

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +    const filteredValues = getFilteredValues<Value>(
I don't think `<Value>` is required if the type is inferred from the `values` argument

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/regionalSewerWaterLineChart.tsx
> +        const { start, end } = weeklyMeasurements[this.point.index];
Nitpick; I think it would be good to check the return value before using the values.

2020-09-22 13:41 UTC, VWSCoronaDashboard8 commented on src/utils/assert.ts
> +export default function assert(
This should probably be a named export now.

2020-09-22 13:45 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +        },
Oops this won't work like that because you don't get the same "this" in the fat arrow context. So keep it a normal function declaration, but you can still do this:

```
formatter: function () {
         return this.isFirst || this.isLast
           ? formatDate(this.value * 1000, 'axis')
           : '' },
```

2020-09-22 16:17 UTC, VWSCoronaDashboard5 commented on src/components/lineChart/nationalPractitionerLineChart.tsx
> +        },
I applied a refactor in the other places where this syntax was used

2020-09-22 16:35 UTC, VWSCoronaDashboard5 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +        assert(typeof start === 'number' && typeof end === 'number');
@VWSCoronaDashboard8 is this what you meant by checking the return value before using the values through an assert function?

2020-09-22 19:50 UTC, VWSCoronaDashboard8 requested changes
Don't let the amount of comments discourage you. I like picking out details 😉

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +  value: number | undefined;
```suggestion
  value?: number;
```

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +        assert(typeof start === 'number' && typeof end === 'number');
I meant something like this:

```
const weekStartEnd = getWeekStartEndByIndex(
          values.map((x) => x.week),
          this.point.index
        );

assert(weekStartEnd, `Missing week start/end for index ${this.point.index}`)
```

... and then you can safely destructure.

But I am not familiar with the data so I'm not sure it out-of-range index is something we should worry about. I generally like this kind of "defensive programming" because it catches problems early and gives better error messages. But there's a balance of course, because you don't want to litter the code with all sorts of unnecessary assert statements.

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/utils/getWeekStartEndByIndex.ts
> +export function getWeekStartEndByIndex(weekSet: Week[], index: number): Week {
I think this is a silly utility. All it does is get an item from an index. Why not just access the items directly?

You could make it generic at least so it accepts any type of array, but then I still don't see the point. Unless you want to build the assert in here, then it at least adds some value if this pattern is used often.

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +  title: string;
The other line chart has a description next to a title. Did you leave it out on purpose here?

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +        return `<strong>${formatDate(start * 1000, 'short')} - ${formatDate(
I see this formatDate(x * 1000, ...) quite often. Would be a good candidate for a utility function. Maybe check all uses of formatDate, because I would expect the conversion of unix epoch to seconds to be part of the format function if all we use is epoch.

Might be better handled in a different PR if it is all over the codebase.

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +          // @ts-ignore
This can be simplified like the other instance.

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +export function LineChart({ values, title, timeframeOptions }: LineChartProps) {
I think it's best to export a more specific name `LineChartWithWeekTooltip`, because it will clash with the other LineChart if we start using barrel files. Also, I don't see an advantage in having them both share the same name.

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +          {title && <h3>{title}</h3>}
Same question here about the description. It was already optional in de other LineChart, so why is it not the same here?

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/regionalSewerWaterLineChart.tsx
> +  value: number | undefined;
```suggestion
  value?: number;
```

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/regionalSewerWaterLineChart.tsx
> +  const weekSet: Week[] = averageValues.map((value) => ({
Nitpick; I name lists usually just using the plural. So `const weeks: Week[] =` If it's plural you kind of know that it's a list already. If its a map instead I'll make it explicit in the name.

A "set" is also a little confusing because the Javascript `Set()` would be a special array-like object with only unique values and different API from Array.

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/regionalSewerWaterLineChart.tsx
> +          end * 1000,
This pattern again :)

2020-09-22 19:50 UTC, VWSCoronaDashboard8 commented on src/utils/assert.ts
> +export function assert(condition: any, msg?: string): asserts condition {
I don't think `msg` should be optional. If you do an assertion you should specify a clear error message.

2020-09-22 19:53 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/regionalSewerWaterLineChart.tsx
> +        const { start, end } = weeklyMeasurements[this.point.index];
@VWSCoronaDashboard4 I only see a point in creating a specific method if the method contains something like an assertion. Otherwise you might as well use something like Lodash `get()`, no? Or am I missing something?

2020-09-22 19:57 UTC, VWSCoronaDashboard8 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +        assert(typeof start === 'number' && typeof end === 'number');
I would advise you to move the assertion to the `getWeekStartEndByIndex` utility, and than it's not so silly anymore 😉

2020-09-23 09:21 UTC, VWSCoronaDashboard5 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +  title: string;
I could add it as an extra prop, but these charts have no descriptions according to the design (also no descriptions there at prod)

2020-09-23 09:22 UTC, VWSCoronaDashboard5 commented on src/components/lineChart/lineChartWithWeekTooltip.tsx
> +        return `<strong>${formatDate(start * 1000, 'short')} - ${formatDate(
good point. I will make this refactor a separate PR!

2020-09-23 10:01 UTC, merged