Get page lokalize texts via static props for deceased page
minvws/nl-covid19-data-dashboard pull request #3923
Opened 2021-12-16 17:31 UTC by VWSCoronaDashboard22

Added a function to extract lokalize texts from a lokalize export file and used in on the deceased page.

2021-12-16 17:39 UTC, VWSCoronaDashboard1 requested changes

2021-12-16 17:39 UTC, VWSCoronaDashboard1 commented on packages/app/src/static-props/get-data.ts
> +}
```suggestion
  return {
    pageText: keys.reduce(
    (acc, key) => ({
      ...acc,
      [key]: languages[locale][key],
    }),
    {}
  ) as Pick<SiteText, T>
  } as const;
}
```

2021-12-17 07:35 UTC, VWSCoronaDashboard1 requested changes
One last comment for this: Don't forget to make the same changes on the VR and GM page as well

2021-12-17 08:10 UTC, VWSCoronaDashboard22 commented on packages/app/src/static-props/get-data.ts
> +}
Committed this

2021-12-17 08:11 UTC, VWSCoronaDashboard1 approved these changes

2021-12-17 09:08 UTC, VWSCoronaDashboard20 approved these changes

2021-12-17 10:45 UTC, merged