Added rounded corners to combobox
minvws/nl-covid19-data-dashboard pull request #3928
Opened 2021-12-20 15:11 UTC by VWSCoronaDashboard22

Added rounded corners to combobox. Visible on pages Veiligheidsregio's, Gemeenten and pages like /veiligheidsregio/VR03/maatregelen

2021-12-20 15:29 UTC, VWSCoronaDashboard18 approved these changes

2021-12-20 15:44 UTC, VWSCoronaDashboard19 requested changes
Not sure which data attribute you have to target, but the border radius at the bottom (left and right) need to be 0 when the listbox pops up. The border radius at the top of the list box (left and right) also need to be 0. Same as the "Actueel" page search box

2021-12-20 16:40 UTC, VWSCoronaDashboard20 approved these changes

2021-12-20 20:38 UTC, VWSCoronaDashboard22 commented
> Not sure which data attribute you have to target, but the border radius at the bottom (left and right) need to be 0 when the listbox pops up. The border radius at the top of the list box (left and right) also need to be 0. Same as the "Actueel" page search box

Discussed this with design. I was told this was the way to go

2021-12-21 08:00 UTC, VWSCoronaDashboard19 approved these changes

2021-12-21 09:03 UTC, VWSCoronaDashboard19 commented
Hold before merge:

- [ ] Made last changes before merge

2021-12-21 10:20 UTC, VWSCoronaDashboard19 approved these changes

2021-12-21 10:24 UTC, merged