Feature/boostershot coverage
minvws/nl-covid19-data-dashboard pull request #3932
Opened 2021-12-22 08:15 UTC by VWSCoronaDashboard18

Update of booster layout on vaccine page and actueel landelijk

2021-12-22 08:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=3932) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=3932) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: VWSCoronaDashboard19<br/>:x: VWSCoronaDashboard18<br/><hr/>**VWSCoronaDashboard18** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=3932) it.</sub>

2021-12-22 10:28 UTC, VWSCoronaDashboard19 approved these changes

2021-12-22 11:09 UTC, VWSCoronaDashboard22 commented on packages/app/src/domain/vaccine/components/metadata.tsx
> +export type source = {
Please capitalize the first letter of a type

2021-12-22 11:09 UTC, VWSCoronaDashboard22 commented on packages/app/src/domain/vaccine/components/metadata.tsx
> +  href: string;
Why does a source require an href when it is not used in this component?

2021-12-22 11:09 UTC, VWSCoronaDashboard22 commented on packages/app/src/domain/vaccine/components/metadata.tsx
> +export interface MetadataProps extends MarginBottomProps {
Why extend this with MarginBottomProps?

2021-12-22 12:47 UTC, VWSCoronaDashboard22 commented on packages/app/src/domain/topical/mini-vaccination-coverage-tile.tsx
> +          boosterShotAdministeredLabel && (
This value is not being passed in index.tsx and is undefined. Therefore the bar will never be visisble.

2021-12-22 13:10 UTC, VWSCoronaDashboard22 commented on packages/app/src/components/metadata.tsx
> +                {`. ${intervalString}`}
Render conditionally. Value could be undefined

2021-12-22 13:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=3932) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=3932) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: VWSCoronaDashboard19<br/>:x: VWSCoronaDashboard18<br/><hr/>**VWSCoronaDashboard18** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=3932) it.</sub>

2021-12-22 20:49 UTC, VWSCoronaDashboard20 requested changes

2021-12-22 20:49 UTC, VWSCoronaDashboard20 commented on packages/app/src/domain/topical/mini-vaccination-coverage-tile.tsx
> +          boosterShotAdministeredBarLabel && (
Is there a particular reason for all these checks? (Except for the feature flag, I understand that one)

2021-12-22 20:49 UTC, VWSCoronaDashboard20 commented on packages/app/src/domain/vaccine/vaccinations-booster-kpi-section.tsx
> +            source={source}
The source doesn't work on the page. I will elaborate on it when I cover the vaccine page.

2021-12-22 20:49 UTC, VWSCoronaDashboard20 commented on packages/app/src/domain/vaccine/vaccine-booster-administrations-kpi-section.tsx
> +          <Message variant="warning">
Shouldn't this check if the warning is set and display it based on that?

2021-12-22 20:49 UTC, VWSCoronaDashboard20 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +                source={text.vaccination_grade_toggle_tile.source}
```vaccination_grade_toggle_tile``` doesn't in its place here. Could that be why TypeScript is complaining, and the source for this component is curently displaying [object Object]?

2021-12-23 09:31 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/mini-vaccination-coverage-tile.tsx
> +          boosterShotAdministeredBarLabel && (
They are optional props that's why the check is there.

2021-12-23 10:32 UTC, VWSCoronaDashboard20 commented on packages/app/src/domain/topical/mini-vaccination-coverage-tile.tsx
> +          boosterShotAdministeredBarLabel && (
Check! Is there a reason for it being optional? The reason for asking is looking at, for example, to the ```fullyVaccinatedPercentage``` there it is not.

2021-12-23 17:07 UTC, merged