Feature/booster coverage
minvws/nl-covid19-data-dashboard pull request #3971
Opened 2022-01-12 13:55 UTC by VWSCoronaDashboard19

2022-01-12 14:18 UTC, VWSCoronaDashboard20 requested changes

2022-01-12 14:18 UTC, VWSCoronaDashboard20 commented on packages/app/schema/nl/booster_coverage.json
> +      "title": "nl_booster_coverage",
The key has the same title as line 3, this results in interface names with a 1 behind them when generated based on this file. Are you sure this is correct?

2022-01-12 14:18 UTC, VWSCoronaDashboard20 commented on packages/common/src/types/data.ts
> +export interface NlBoosterCoverage1 {
The number 1 behind the interface usually indicates a duplicate key; see the previous comment.

2022-01-12 14:24 UTC, VWSCoronaDashboard19 commented on packages/app/schema/nl/booster_coverage.json
> +      "title": "nl_booster_coverage",
Sharp! that's correct, will double check it again and verify with be!

2022-01-12 15:02 UTC, VWSCoronaDashboard24 commented on packages/app/schema/nl/booster_coverage.json
> +      "maxItems": 1,
Is this correct? Max 1 value in the array?

2022-01-12 15:52 UTC, VWSCoronaDashboard18 commented on packages/app/schema/nl/booster_coverage.json
> +      "maxItems": 1,
Yes, there is no historical data in this entry point

2022-01-12 15:53 UTC, VWSCoronaDashboard18 approved these changes

2022-01-12 16:10 UTC, VWSCoronaDashboard24 approved these changes

2022-01-13 08:35 UTC, VWSCoronaDashboard22 approved these changes

2022-01-14 09:40 UTC, VWSCoronaDashboard19 commented on packages/app/src/pages/index.tsx
> +                                boosterCoverageFeature.isEnabled &&
Added a feature flag here and also checking if the currently existing percentage is in `boosterCoverageEstimatedLastValue`. When `booster_coverage` data goes live, it won't show NaN on the dashboard, but switch over to the new data in the `else`

2022-01-14 09:41 UTC, VWSCoronaDashboard19 reviewed
Small note added

2022-01-17 13:17 UTC, merged