Added Variant_code and order
minvws/nl-covid19-data-dashboard pull request #4343
Opened 2022-07-27 13:19 UTC by VWSCoronaDashboard18

Updated variant graph and table to be compliant with backend data and set order based on backend input

2022-07-28 16:39 UTC, VWSCoronaDashboard25 requested changes

2022-07-28 16:39 UTC, VWSCoronaDashboard25 commented on packages/app/src/domain/variants/static-props/get-variant-table-data.ts
> +          (variantColors) => variantColors.variant === variant.variant_code
If `variantColors` is an array, please use `variantColor` to name a single element of that array

2022-07-28 16:39 UTC, VWSCoronaDashboard25 commented on packages/app/src/domain/variants/static-props/get-variant-table-data.ts
> +  variant: keyof VariantCodes;
I think it's better to name the property `variantCode` as well:
```
  variantCode: keyof VariantCodes;
```

2022-07-28 16:39 UTC, VWSCoronaDashboard25 commented on packages/app/src/domain/variants/variants-table-tile/components/variant-name-cell.tsx
> +  variant: keyof VariantCodes;
Same as for `VariantRow`, I think it's nicer to name the property `variantCode` as well.

2022-07-28 16:39 UTC, VWSCoronaDashboard25 commented on packages/app/src/domain/variants/variants-table-tile/types.ts
> +  B_1_1_529: string;
This interface is named `VariantCodes`, but I thought `B_1_1_529` is a variant code. But this the name of one property of `VariantCodes`.
So what is the value of that property going to be?

I've seen quite some `keyof VariantCodes` usage. Maybe it's better to create an `enum` instead?

2022-07-28 16:39 UTC, VWSCoronaDashboard25 commented on packages/cms/src/lokalize/key-mutations.csv
> +2022-07-26T16:29:31.892Z,delete,common.variants.alpha.countryOfOrigin,ATrwynrL85JmIH7bDlAcr5,__
On line 1817 you've already deleted `common.variants.alpha.country_of_origin` which is where `common.variants.alpha.countryOfOrigin` was moved to, so this line (and the next 30 or 40 or so) will at best generate log lines that can be avoided, at worst it will crash some Sanity script. 😱

2022-07-28 16:39 UTC, VWSCoronaDashboard25 commented on packages/common/src/types/data.ts
> +    | "BA_2_75"
I think these can be a separate type or enum, so if a new variant is added, it needs to only be added in one place.

2022-07-29 15:06 UTC, VWSCoronaDashboard25 commented on packages/cms/src/lokalize/key-mutations.csv
> -2022-07-26T16:26:05.902Z,delete,common.variants.alpha.country_of_origin,ATrwynrL85JmIH7bDlAcr5,__
I think you removed one line too many, otherwise I assume the rest of the lines with different virus names can be removed as well, unless `alpha.country_of_origin` is something special of course.

2022-08-01 08:11 UTC, VWSCoronaDashboard25 commented on packages/app/src/domain/variants/static-props/get-variant-chart-data.ts
> +export type VariantCode = keyof VariantCodesAll;
Can you maybe make `VariantCode` a TypeScript enum with the possible values coming from `SiteText['common']['variant_codes']` instead?

In some places of the code, you need a property of type `VariantCodesAll` and pas it along, which is weird to me because it is a list of all possible variant codes which does not change. So either it can be imported there where they are needed or something else is going on. Which I don't fully understand.

2022-08-01 08:17 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-order-colors.ts
> +  const firstVariant = variantsOfConcern.shift();
Didn't need the shift at all.

2022-08-01 08:18 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-order-colors.ts
> +  variant: string;
Correct, added the VariantCode type

2022-08-01 08:18 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-order-colors.ts
> +          : colors.data.variants.colorList[index],
Thanks, I added the separate function.

2022-08-01 08:20 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-table-data.ts
> +const EMPTY_VALUES = {
Changed both of them according to your review

2022-08-01 08:21 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-order-colors.ts
> +export type colorMatch = SingleColorMatchType[];
Replaced 'c' with 'C'

2022-08-01 08:22 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-table-data.ts
> +          (variantColors) => variantColors.variant === variant.variant_code
Done, updated multiple types.

2022-08-01 08:22 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-table-data.ts
> +  variant: keyof VariantCodes;
Done, updated multiple types.

2022-08-01 08:22 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/variants-table-tile/components/variant-name-cell.tsx
> +  variant: keyof VariantCodes;
Done, updated multiple types.

2022-08-01 08:25 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/variants-table-tile/types.ts
> +  B_1_1_529: string;
It now has the type containing all variant codes. Thus named is VariantCodesAll.

And what you stated is correct. B_1_1_529 is a variant code. It's not the name of the property of variantCodes anymore. Enum had some index issues. But it's typed as [string1, string2, string3, ...]

2022-08-01 08:26 UTC, VWSCoronaDashboard18 commented on packages/cms/src/lokalize/key-mutations.csv
> +2022-07-26T16:29:31.892Z,delete,common.variants.alpha.countryOfOrigin,ATrwynrL85JmIH7bDlAcr5,__
This script is automatically generated. Therefor we don't normally change it manually. But this seems a bug so removed the extra line.

2022-08-01 08:28 UTC, VWSCoronaDashboard18 commented on packages/common/src/types/data.ts
> +    | "BA_2_75"
This already is an enum. This data.ts is generated based on the json schema's. And there it's typed to be one of the variants.

2022-08-01 09:03 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-order-colors.ts
> +export type ColorMatch = SingleColorMatchType[];
Changed the naming

2022-08-01 10:51 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/static-props/get-variant-chart-data.ts
> +export type VariantCode = keyof VariantCodesAll;
No, due to legacy code

2022-08-01 11:03 UTC, VWSCoronaDashboard25 approved these changes
Thanks for your patience!

2022-08-01 11:07 UTC, merged