COR-1057 Vaccinations page
minvws/nl-covid19-data-dashboard pull request #4430
Opened 2022-09-26 15:00 UTC by VWSCoronaDashboard24

2022-09-27 16:08 UTC, VWSCoronaDashboard26 requested changes

2022-09-27 16:08 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +  birthyear: string;
Nitpicky comment, but 'birthyear' is technically not grammatically correct. it's a combination of two independent words: 'birth year'. One could then argue that this should be written as `birthYear` (or even opt for 'year of birth' and `yearOfBirth` as it is more commonly used).

2022-09-27 16:08 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +      (x) => x.age_group_range === '60+'
Something about meaningful names for variables. 😉

2022-09-28 07:58 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/tile.tsx
> +    pb: x.hasNoPaddingBottom ? undefined : asResponsiveArray({ _: 3, sm: 4 }),
Changed 'x' variable.
About the positive point of view. I think I can prefer that too, but that flows through a lot of code. And out of the scope of this ticket. It can be something for the code convention or a refactor.

2022-09-28 09:29 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/index.ts
> +export * from './components/search';
Not sure why it was changed, but it's reverted.

2022-09-28 10:11 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/autumn-2022-shot-coverage-per-age-group.tsx
> +export function Autumn2022ShotCoveragePerAgeGroup({
Converted to a function expression

2022-09-28 10:12 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/data-selection/select-vaccine-coverage-data.ts
> +    if (isPresent(el.autumn_2022_vaccinated_percentage_label)) {
This is based on the schema name. Therefor cannot be changed without changing the backend name as well.

2022-09-28 10:13 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/autumn-2022-shot-coverage-per-age-group.tsx
> +    const index = sortingOrder.findIndex((x) => x === ageGroup);
Changed te other variable name

2022-09-28 10:15 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +      (x) => x.age_group_range === '60+'
Changed the variable

2022-09-28 10:15 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +  birthyear: string;
This is also from the schema communication with the backend

2022-09-28 10:19 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +      <Box> {metadata && <Metadata {...metadata} isTileFooter />}</Box>{' '}
Good comments, adjusted accordingly

2022-09-28 10:19 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth-per-gm.tsx
> +    }
Update description

2022-09-28 10:32 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/components/narrow-coverage-table.tsx
> +}
Totally agree

2022-09-28 10:39 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/components/narrow-coverage-table.tsx
> +export function NarrowCoverageTable({
Changed accordingly

2022-09-28 10:40 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/components/narrow-coverage-table.tsx
> +  values: NlVaccineCoveragePerAgeGroupValue[];
Moved the props

2022-09-28 10:41 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/components/wide-coverage-table.tsx
> +export function WideCoverageTable({ values, text }: WideCoverageTable) {
Good point! Done

2022-09-28 10:44 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/components/wide-coverage-table.tsx
> +                    item.autumn_2022_vaccinated_percentage === null
Adjusted accordingly

2022-09-28 10:44 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/components/age-group-select.tsx
> +          if (shownAgeGroups && shownAgeGroups.includes(el.ageGroup)) {
Adjusted accordingly

2022-09-28 10:44 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/components/wide-coverage-table.tsx
> +const HeaderCell = styled.th<{ isColumn?: boolean }>((x) =>
Adjusted accordingly

2022-09-28 10:46 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/autumn-2022-shot-coverage-per-age-group/autumn-2022-shot-coverage-per-age-group.tsx
> +    (a, b) =>
Not sure what names to give. And not seeing a big (blocking) issue here. Chat sent separately

2022-09-28 12:08 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/data-selection/select-vaccine-coverage-data.ts
> +    if (isPresent(el.autumn_2022_vaccinated_percentage_label)) {
Adjusted 'el' aswell

2022-09-28 12:08 UTC, VWSCoronaDashboard26 approved these changes

2022-09-28 12:14 UTC, merged

2022-11-17 14:04 UTC, VWSCoronaDashboard21 reviewed
Looks good!