SVG icons states for screenreader
minvws/nl-covid19-data-dashboard pull request #4451
Opened 2022-10-11 14:04 UTC by VWSCoronaDashboard27

## Summary

- added new text for icons to the Sanity
- hided unnecessary icons from screenreader

2022-10-12 11:12 UTC, VWSCoronaDashboard19 approved these changes

2022-10-14 07:23 UTC, VWSCoronaDashboard25 commented
There are several `aria-hidden="true"` and some `aria-hidden='true'` added, so with double quotes and with single quotes.
Could you make them all `aria-hidden="true"`?

Basically we want strings in JavaScript to be single quotes. However in the HTML-like part of JSX we use double quotes, because in plain HTML you _must_ use double quotes.

2022-10-14 10:11 UTC, VWSCoronaDashboard18 requested changes
I'm missing the aria-label at the trend icons on the topical theme tiles.

Are the external links and warning icons the only ones missing context for the visually impaired?

2022-10-24 16:51 UTC, VWSCoronaDashboard25 commented on packages/app/src/components/difference-indicator/tile-difference.tsx
> +  const TrendLabelNeutral = ariaLabel || commonTexts.accessibility.visual_context_labels.neutral_trend_label;
I see this returning in three components now:
- `components/difference-indicator/tile-difference.tsx`
- `components/behaviour-trend.tsx`
- `components/topical-tile.tsx`
Each uses the `<Up />`, `<Down />` or maybe `<Dot />` icon and each result in the same aria-label.

I think we should invest in a `TrendIcon` component instead, and use that in all three places.

Something like:

```typescript
import { useIntl } from '~/intl';
import { Down, Dot, Up } from '@corona-dashboard/icons';

export enum TrendDirection {
  UP,
  DOWN,
  NEUTRAL
};

interface TrendIconProps {
  trendDirection: TrendDirection;
  ariaLabel?: string;
}

export const TrendIcon = ({ trendDirection, ariaLabel }: TrendIconProps) => {
  const { commonTexts } = useIntl();

  const TrendLabelUp = ariaLabel || commonTexts.accessibility.visual_context_labels.up_trend_label;
  const TrendLabelDown = ariaLabel || commonTexts.accessibility.visual_context_labels.down_trend_label;
  const TrendLabelNeutral = ariaLabel || commonTexts.accessibility.visual_context_labels.neutral_trend_label;

  switch(trendDirection) {
    case TrendDirection.UP: return <Up aria-label={TrendLabelUp} />;
    case TrendDirection.DOWN: return <Down aria-label={TrendLabelDown} />;
    case TrendDirection.NEUTRAL: return <Dot aria-label={TrendLabelNeutral} />;
    default:
      const exhaustiveCheck: never = trendDirection;
      throw new Error(`Unhandled TrendDirection case: ${exhaustiveCheck}`);
  }
};
```

2022-10-24 16:56 UTC, VWSCoronaDashboard25 commented on packages/app/src/components/difference-indicator/tile-difference.tsx
> +  const TrendLabelNeutral = ariaLabel || commonTexts.accessibility.visual_context_labels.neutral_trend_label;
But we can create a separate ticket for it, off course.

2022-10-27 13:40 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/difference-indicator/tile-difference.tsx
>    if (difference > 0) {
I think this part could also be optimised a little bit to get rid of some if conditions, which are essentially doing the same thing, i.e. setting `content` and `containerWithIcon`. Of course, this is not a blocking comment and merely a suggestion for optimisation. I understand if you just want to merge this PR and not implement this optimisation for now. I would suggest something like the following:

```
let content: string = text.waarde_gelijk;
let containerWithIcon: React.ReactNode = <ContainerWithIcon icon={<TrendIcon trendDirection={TrendDirection.NEUTRAL} />} color="neutral" />;

const containerWithIconMapping = [
  {
    condition: difference > 0,
    content: isAmount ? text.waarde_meer : text.waarde_hoger,
    icon: <ContainerWithIcon icon={<TrendIcon trendDirection={TrendDirection.UP} />} color="red2" />,
  },
  {
    condition: difference < 0,
    content: isAmount ? text.waarde_minder : text.waarde_lager,
    icon: <ContainerWithIcon icon={<TrendIcon trendDirection={TrendDirection.DOWN} />} color="primary" />,
  }
];

containerWithIconMapping.forEach(mapping => {
  const { condition, content: mappingContent, icon } = mapping;
  if (condition) {
    content = mappingContent;
    containerWithIcon = icon;
  }
});
```

I tested it out by converting everything to a string to see what would log to the console for `content` and `containerWithIcon` in different scenarios and it looks like it works. But again, not blocking at all.

2022-10-27 13:42 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/topical/components/topical-tile.tsx
> +  // const TrendLabelUp = ariaLabel || commonTexts.accessibility.visual_context_labels.up_trend_label;
I'm not sure why the labels are removed but I would assume if they are not needed then these commented lines can also be removed?

2022-10-27 13:45 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/variants/variants-table-tile/components/variant-difference.tsx
> +type TrendIcon = {
I notice this type declaration in a number of files in this commit. If i'm not wrong, it should be possible to also define this type in the scope of `packages/app/src/components/trend-icon.tsx` and then import it where required? I'm no typescript expert so I might be wrong, but seems like it should be possible.

2022-10-27 14:01 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/variants/variants-table-tile/components/variant-difference.tsx
>    if (value === undefined) {
Same as my first comment, this is not blocking and merely a suggestion for optimisation. I tested it with some console logs and it looks like it works.

```
let returnValue: React.ReactNode = (
  <Difference color={colors.neutral}>
    <Dot color={colors.neutral} aria-label={TrendLabelNeutral} />
    <TrendIcon trendDirection={TrendDirection.NEUTRAL} />
    {text.verschil.gelijk}
  </Difference>
);

const renderingConditionMapping = [
  {
    condition: value === undefined,
    renderingValue: <>-</>
  },
  {
    condition: value?.difference > 0,
    renderingValue: (
      <Difference color={colors.black}>
        <Up aria-label={TrendLabelUp} />
        <TrendIcon trendDirection={TrendDirection.UP} />
        {formatPercentage(value.difference, options)} {text.verschil.meer}
      </Difference>
    )
  },
  {
    condition: value?.difference < 0,
    renderingValue: (
      <Difference color={colors.black}>
        <Down aria-label={TrendLabelDown} />
        <TrendIcon trendDirection={TrendDirection.DOWN} />
        {formatPercentage(-value.difference, options)} {text.verschil.minder}
      </Difference>
    )
  }
]

renderingConditionMapping.forEach(mapping => {
  const { condition, renderingValue } = mapping;
  if (condition) {
    returnValue = renderingValue;
  }
});

return {returnValue};
```

2022-11-02 09:50 UTC, VWSCoronaDashboard28 approved these changes

2022-11-03 08:47 UTC, merged