Font size of home page/ COR-1110
minvws/nl-covid19-data-dashboard pull request #4457
Opened 2022-10-13 12:56 UTC by VWSCoronaDashboard27

## Summary

Changed font-size for descriptions at Home Page.

2022-10-14 07:07 UTC, VWSCoronaDashboard25 approved these changes

2022-10-14 10:02 UTC, VWSCoronaDashboard18 requested changes

2022-10-14 10:02 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/topical-theme-header.tsx
> +      <Box fontSize={3}>
Why is this box created? Cant the font size be set on the markdown element?

2022-10-17 08:07 UTC, VWSCoronaDashboard19 commented on packages/app/src/domain/topical/components/topical-theme-header.tsx
> +      <Box fontSize={3}>
It is not possible to set a `font-size` to a `Markdown` component, therefore a `Box` element an easier solution.

2022-10-17 10:14 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/topical-theme-header.tsx
> +      <Box fontSize={3}>
I did not know about the markdown not accepting extra CSS. (Not sure why though it doesn't)
It makes sense to have a box element for the font-size instead.

2022-10-17 10:14 UTC, VWSCoronaDashboard18 approved these changes

2022-10-17 13:32 UTC, merged