feat: restructured logic for internal links
minvws/nl-covid19-data-dashboard pull request #4525
Opened 2022-12-05 16:33 UTC by VWSCoronaDashboard27

## Summary

- Restructured logic for internal links in [is-internal-url.ts](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1193-markdown-interpreter-links-recogniser?expand=1#diff-c9520341c40a823666a408f72d4808ef8cd506c7cd943744c086c2bd464d817f) 
- Renamed  file to <is-internal-url.ts>
- Flipped structure in following files: 
[rich-content.tsx](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1193-markdown-interpreter-links-recogniser?expand=1#diff-57bc7049b9d33126ea2df2de48349169ba42ff600c793be7e35bca58ca9aeee5)
[content-teaser.tsx](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1193-markdown-interpreter-links-recogniser?expand=1#diff-950179fe563bc4924151788ec1ddfa900628aeba548a46487a11a7f5d81e6d0f)
[markdown.tsx](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1193-markdown-interpreter-links-recogniser?expand=1#diff-ad49f9e31c1b4922416f7acdc0ad86489cd75c76762f0bf088a9ab36b19d8686)
[page-links.tsx](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1193-markdown-interpreter-links-recogniser?expand=1#diff-400357feb24d25946dc8df02ee253571f0c6a29868baee202b215e248ace6241)
- Adjusted test components [is-internal-url.spec.ts](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1193-markdown-interpreter-links-recogniser?expand=1#diff-7ecc3576c923a213718090aef950348fc2df731ad79e29086229b13b896e77f3)

2022-12-06 16:14 UTC, VWSCoronaDashboard28 commented on packages/app/src/utils/is-internal-url.ts
> +/**
I'm not entirely sure why this is renamed to `isInternalUrl`. From my understanding we return if its an external URL or NOT and internal URL. Or am i missing something? 

This piece of code: `!regExInternal.test(url)` reads to me as `Not internal url`.

2022-12-06 16:25 UTC, VWSCoronaDashboard26 commented on packages/app/src/utils/is-internal-url.ts
> +  const regExExternal = new RegExp('(https?://coronadashboard.)');
Maybe I am misinterpreting this code, but this should actually also be considered an internal link, right?

2022-12-07 08:17 UTC, VWSCoronaDashboard27 commented on packages/app/src/utils/is-internal-url.ts
> +  const regExExternal = new RegExp('(https?://coronadashboard.)');
Yes, this is an internal link.

2022-12-07 09:48 UTC, VWSCoronaDashboard28 commented on packages/app/src/utils/is-internal-url.ts
> +  const regExExternal = new RegExp('(https?://coronadashboard.)');
Then maybe it should not be `regEXExternal` but something which indicates that it is internal?

2022-12-07 09:55 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/is-internal-url.ts
> + */
I think it's a good idea to update this comment as well to describe the new logic in this function.

2022-12-07 10:03 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/is-internal-url.ts
> +  const regExExternal = new RegExp('(https?://coronadashboard.)');
I think this regex needs a bit more cases than only "https://corondashboard." & "http://corondashboard.".

I think this needs to be at the beginning of the URL. What if for example, we have a link where the link has a tracking property in it referencing its own URL?
https://www.linkToOtherSIte.nl/artikel-about-dashboard?trackingId="1234"&comesFrom="https://www.coronadashboard.rijksoverheid.nl/artikel/more-about-this-metric".

And maybe have it in another way defined than a string. Because we also want this to apply for the development and local environment. (without hardcoding those values. Probably get them from the ENV files)

2022-12-07 10:07 UTC, VWSCoronaDashboard18 requested changes
See the review comments

2022-12-08 08:21 UTC, VWSCoronaDashboard28 commented on packages/app/src/utils/is-internal-url.ts
> +  const regExExternal = new RegExp('(https?://coronadashboard.)');
Im still not sure why its called `regExExternal` as it is also matching internal links. 

Maybe something like:
```
const regExInternal = new RegExp('^(https?://coronadashboard.)') || new RegExp('^(https?:)?//');
```

2022-12-12 15:47 UTC, VWSCoronaDashboard28 approved these changes
I am pre-approving as it works, but please see my comment and consider it before merging.

2022-12-12 15:50 UTC, VWSCoronaDashboard28 commented on packages/app/src/utils/is-internal-url.ts
> + * Return true if the given url starts with http://coronadashboard. or https://coronadashboard.
Perhaps the comment can be a bit more descriptive. Its pretty clear what the function is doing, but I'm also wondering why we need this check? Is it only so that we render the correct Icon? If so, then maybe its good to mention that here. 

Another thing thats not clear, it says `Return true if the given url starts with http://coronadashboard. or https://coronadashboard.` but `Return false if the given url starts with http or https` which can be a bit misleading as the ones for which you return `true` also start with `http` or `https`.

2022-12-12 15:51 UTC, VWSCoronaDashboard28 requested changes
Please ignore the approval above, Could you adjust the comment in `packages/app/src/utils/is-internal-url.ts` based on the feedback, please?

2022-12-12 20:42 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/is-internal-url.ts
> + * Return true if the given url starts with http://coronadashboard. or https://coronadashboard.
Indeed, this was not a correct description. It's been updated.

2022-12-12 20:42 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/is-internal-url.ts
> +export function isInternalUrl(url: string) {
All the regexes are combined now

2022-12-14 08:23 UTC, VWSCoronaDashboard28 commented on packages/app/src/utils/is-internal-url.ts
> +  const totalRegEx = new RegExp('(^(#))|(^(/)[^/]|^(/)$)|(^(((https?://(www.)?)?|www.)coronadashboard(.rijskoverheid|.government)?.nl))');
This is a bit nitpicky but:
```
coronadashboard(.rijskoverheid|.government)
```

You could just have one `.` after `coronadashboard` and not have a `.` before `rijskoverheid` and `government`.

2022-12-14 08:23 UTC, VWSCoronaDashboard28 approved these changes
Looks good, left one small comment

2022-12-14 13:12 UTC, VWSCoronaDashboard21 commented on packages/app/src/components/page-information-block/components/page-links.tsx
>      <Box spacing={2} pt={3}>
As agreed upon in the code conventions, we avoid using magic numbers in code. You can change this for example to paddingTop={space[3]}

2022-12-14 13:12 UTC, VWSCoronaDashboard21 commented on packages/app/src/utils/__tests__/is-internal-url.spec.ts
> +  'www.rijksoverheid.nl/see-our-new-dahsboard/?tracking="coronadashboard.rijksoverheid.nl"',
Is it spelled 'dahsboard' on purpose? Or should this be 'dashboard' (correct spelling)?

2022-12-14 13:12 UTC, VWSCoronaDashboard21 commented on packages/app/src/utils/__tests__/is-internal-url.spec.ts
> +    assert.not.ok(isInternalUrl(url), `${url} is seen as an internal link but probbably is an external url`);
This is a bit nitpicky but: 'probbably' is misspelled, should be 'probably'.

2022-12-14 13:12 UTC, VWSCoronaDashboard21 commented on packages/app/src/utils/__tests__/is-internal-url.spec.ts
> +    assert.ok(isInternalUrl(url), `${url} is seen as an external link but probbably is an internal url`);
This is a bit nitpicky but: 'probbably' is misspelled, should be 'probably'.

2022-12-15 09:00 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/is-internal-url.ts
> +  const totalRegEx = new RegExp('(^(#))|(^(/)[^/]|^(/)$)|(^(((https?://(www.)?)?|www.)coronadashboard(.rijskoverheid|.government)?.nl))');
But then you have to put it at the end and remove it just before the ".nl"

2022-12-15 09:08 UTC, VWSCoronaDashboard28 commented on packages/app/src/utils/is-internal-url.ts
> +  const totalRegEx = new RegExp('(^(#))|(^(/)[^/]|^(/)$)|(^(((https?://(www.)?)?|www.)coronadashboard(.rijskoverheid|.government)?.nl))');
Well it would be something like this, `(^#)|(^\/)|^((https?:\/\/)?(www.)?coronadashboard.(rijskoverheid|government)?.?nl)`. But I'm fine with what you have right now so ill resolve this.

2022-12-15 14:27 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/__tests__/is-internal-url.spec.ts
> +    assert.ok(isInternalUrl(url), `${url} is seen as an external link but probbably is an internal url`);
Adjusted it

2022-12-15 14:27 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/__tests__/is-internal-url.spec.ts
> +    assert.not.ok(isInternalUrl(url), `${url} is seen as an internal link but probbably is an external url`);
Adjusted it

2022-12-15 14:27 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/__tests__/is-internal-url.spec.ts
> +  'www.rijksoverheid.nl/see-our-new-dahsboard/?tracking="coronadashboard.rijksoverheid.nl"',
It was not on purpose, and I adjusted it

2022-12-15 14:28 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/page-information-block/components/page-links.tsx
>      <Box spacing={2} pt={3}>
Adjusted it

2022-12-15 14:29 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/__tests__/is-internal-url.spec.ts
> +  'https://coronadashboard.rijskoverheid.nl',
Nice catch

2022-12-15 14:29 UTC, VWSCoronaDashboard18 approved these changes
Looks good 2 me

2022-12-15 16:11 UTC, merged