Match area chart to line chart implementation
minvws/nl-covid19-data-dashboard pull request #453
Opened 2020-09-28 13:23 UTC by VWSCoronaDashboard8

Line charts were recently updated with improved layout, better y-axis scaling and signaalwaarde labeling with both text and value. The area chart was not adapted.

This PR matches area-chart with the current line-chart implementation.

2020-09-28 17:46 UTC, VWSCoronaDashboard4 reviewed
Some nitpicks; some things I comment on already occur on other places in the areachart, maybe it just needs a little bit of brushing up in a separate PR.

2020-09-28 17:46 UTC, VWSCoronaDashboard4 commented on src/components/areaChart/areaChart.module.scss
> +.root {
empty property block

2020-09-28 17:46 UTC, VWSCoronaDashboard4 commented on src/components/areaChart/areaChart.module.scss
> +$breakpoint: 1200px;
not sure about this variable name, it's very generic

2020-09-28 17:46 UTC, VWSCoronaDashboard4 commented on src/components/areaChart/index.tsx
> +  description?: string;
optional properties should be at the bottom

2020-09-28 17:46 UTC, VWSCoronaDashboard4 commented on src/components/areaChart/index.tsx
> +        if (!rangePoint) return '';
you can also return false; then it will not display an empty tooltip

2020-09-28 18:22 UTC, VWSCoronaDashboard1 approved these changes

2020-09-28 18:22 UTC, VWSCoronaDashboard1 commented on src/components/areaChart/index.tsx
> +  description?: string;
Is there a lint rule for this perhaps? Would be nice if these kinds of things get triggered.

2020-09-28 18:33 UTC, VWSCoronaDashboard8 commented on src/components/areaChart/areaChart.module.scss
> +$breakpoint: 1200px;
It's also very local. I think that's the beauty of css modules, that you can keep the naming super simple.

2020-09-28 18:35 UTC, VWSCoronaDashboard8 commented
@VWSCoronaDashboard1 A lint rule for what exactly?

2020-09-28 18:39 UTC, VWSCoronaDashboard8 commented on src/components/areaChart/index.tsx
> +  description?: string;
That's a pretty subjective claim I think. I don't agree with it. I think it helps if you try to logically group things together and title and description in my mind belong together.

It's different for function arguments. There I agree that you would place optional arguments at the end, so that you can call the function leaving those out. But I don't see a point in interface definitions.

2020-09-28 18:41 UTC, VWSCoronaDashboard8 commented on src/components/areaChart/index.tsx
> +        if (!rangePoint) return '';
👍 The function definition claimed it wanted to return a string, so I've removed that also.

2020-09-28 19:01 UTC, VWSCoronaDashboard commented on src/components/areaChart/areaChart.module.scss
> +$breakpoint: 1200px;
Agree, with module files this does not matter at all.

2020-09-28 19:02 UTC, VWSCoronaDashboard commented on src/components/areaChart/index.tsx
> +  description?: string;
I think putting optional at the end mostly makes sense for arguments. Other types, I don't see a reason to be dogmatic.

2020-09-28 19:09 UTC, VWSCoronaDashboard requested changes
Please don't put the padding multiplier in your max function. Besides that I'm good with this.

2020-09-28 19:09 UTC, VWSCoronaDashboard commented on src/components/areaChart/index.tsx
> +  return Math.max(signaalwaarde * 1.2, ...flatValues);
While this solves your problem, I don't think this is the right solution. Adding padding/margin to your graph is a concern for the presentational layer. 

`calculateYMax` now is an impure function which does not return what its name implies. 

I think it's easy to fix though:

```
  const PADDING_INCREASE = 1.2;
  const yMax = calculateYMax(rangeData, signaalwaarde) * PADDING_INCREASE;
```

2020-09-28 19:09 UTC, VWSCoronaDashboard commented on src/components/lineChart/index.tsx
> +              zIndex: 10,
This is a duplicate of 104, so should this be a constant at the top of the file?

2020-09-28 19:19 UTC, VWSCoronaDashboard8 commented on src/components/areaChart/index.tsx
> +  return Math.max(signaalwaarde * 1.2, ...flatValues);
Impure as in has side-effects? 

The result is a value that is used to set the ymax of the chart, so I don't really see how this function name is so misleading. Also have a look at lineChart where I did the exact same and no one made any comments there.

I feel like we're really nitpicking here, especially considering the current state of the codebase 🤷‍♂️

2020-09-29 06:41 UTC, VWSCoronaDashboard8 commented on src/components/areaChart/index.tsx
> +  return Math.max(signaalwaarde * 1.2, ...flatValues);
@VWSCoronaDashboard Your proposed solution doesn't produce the same result. The function currently only adds to the max if the signaalwaarde + extra margin is a higher value than the maximum value in the time series.

2020-09-29 06:59 UTC, VWSCoronaDashboard8 commented on src/components/areaChart/index.tsx
> +  return Math.max(signaalwaarde * 1.2, ...flatValues);
I can make it like this `const yMax = calculateYMax(rangeData, signaalwaarde * PADDING_INCREASE)`. That could be the compromise.

2020-09-29 07:20 UTC, VWSCoronaDashboard4 approved these changes

2020-09-29 07:29 UTC, merged