feature/COR-1260-variants-colour-updates
minvws/nl-covid19-data-dashboard pull request #4537
Opened 2022-12-15 08:26 UTC by VWSCoronaDashboard26

## Summary
* updated colour order for variant colours;
* updated `getVariantOrderColors` function to filter out variants with an 'other'-prefix;
* updated `VariantStackedAreaTileWithData` component to set the default timeframe selection to three months;

### Screenshots
Both screenshots show the complete timeframe and not the updated default selection of three months. This is done to
* show that the order of colours has been updated;
* the bug with skipping a first colour has been fixed (`#D360E5` is the new first colour, but this used to be `#FFC000`, which was skipped);

#### Before
<img width="927" alt="image" src="https://user-images.githubusercontent.com/107395524/207809253-c15cf9e5-41ec-4ce5-bdf1-46aceddf3260.png">

#### After
<img width="930" alt="image" src="https://user-images.githubusercontent.com/107395524/207809157-6473d351-a93a-477f-aadb-4bac9d138b56.png">

2022-12-15 12:56 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
> -export function VariantsStackedAreaTile({
The props type up top could and should be an interface

2022-12-15 12:59 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
> +      timeframeInitialValue={TimeframeOption.THREE_MONTHS}
This is out of scope here, but an idea for making this future ready would be to allow these kinds of options to be selected from Sanity.

2022-12-15 13:01 UTC, VWSCoronaDashboard19 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
> -export function VariantsStackedAreaTile({
Agreed

2022-12-15 13:03 UTC, VWSCoronaDashboard28 approved these changes
Looks good, I've left a small comment about type vs interface

2022-12-15 13:27 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
> -export function VariantsStackedAreaTile({
I have updated both lines 24 and 52 to use `interface` rather than `type`.

2022-12-15 13:36 UTC, VWSCoronaDashboard19 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
> +const NoDataBox = styled(Box)`
Is there a specific reason why there is a custom styled-component of `<Box />`? Why not pass all these attributes directly to a `<Box />` component?

2022-12-15 13:36 UTC, VWSCoronaDashboard19 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
> +    <VariantStackedAreaTileWithData text={text} values={values} metadata={metadata} variantColors={variantColors}>
I know it's formatting, but I am not really super happy with the name of this component because it sounds weird, as if `VariantsStackedAreaTile` component has no data. Also not sure why we need a separate component for this one. Why not directly put the contents from `VariantStackedAreaTileWithData` in here?

2022-12-15 14:17 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
> +const NoDataBox = styled(Box)`
I have thought about this and while I have used `<Box />` with inline props, I do think that it messes with the flow of the JSX, or more so the 'flow of reading' the JSX a bit. We have not really agreed on which approach should be used, so I am also completely fine with converting it to a `<Box />` and adding inline props for styling purposes, but do note that not all styles are applicable through props. In that case, you'd still have to use either a `style={ ... }` prop (for inline styles) or a `css={css({ ... })}` (using the `css` method from styles system) for 'unsupported' styles, which is not the case when using styled components.

2022-12-15 15:05 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
> +    <VariantStackedAreaTileWithData text={text} values={values} metadata={metadata} variantColors={variantColors}>
Great idea! Simplified this component.

2022-12-15 15:06 UTC, VWSCoronaDashboard19 approved these changes

2022-12-15 17:13 UTC, VWSCoronaDashboard18 approved these changes
Nice PR

2022-12-15 17:16 UTC, VWSCoronaDashboard18 requested changes

2022-12-15 17:16 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
>    values: VariantChartValue[];
I see a typescript error. Maybe have this checked in a early return and have it also possible null here as well

2022-12-16 09:31 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/variants/variants-stacked-area-tile/variants-stacked-area-tile.tsx
>    values: VariantChartValue[];
I've updated the entire `VariantsStackedAreaTile` component to not leverage `children` and `noDataMessage` and render the component conditionally instead.

2022-12-16 09:38 UTC, VWSCoronaDashboard18 approved these changes
Great!

2022-12-16 09:39 UTC, merged