feat: Move all legend's to vertical designs
minvws/nl-covid19-data-dashboard pull request #4550
Opened 2022-12-20 10:37 UTC by VWSCoronaDashboard18

Before:
<img width="974" alt="Screenshot 2022-12-20 at 11 27 42" src="https://user-images.githubusercontent.com/93984341/208645599-39a01365-7809-4a14-83b3-55b71f8643d2.png">

<img width="1022" alt="Screenshot 2022-12-20 at 11 27 51" src="https://user-images.githubusercontent.com/93984341/208646142-0bd2be5d-201f-4de8-acfd-8119c5325a5e.png">

<img width="622" alt="Screenshot 2022-12-20 at 11 28 44" src="https://user-images.githubusercontent.com/93984341/208645552-71ba9725-b2d6-438e-a840-52d64427fc20.png">

After:
<img width="1008" alt="Screenshot 2022-12-20 at 11 27 28" src="https://user-images.githubusercontent.com/93984341/208646050-76b7d513-c00d-43fb-9072-28cc1ed206dd.png">

<img width="1012" alt="Screenshot 2022-12-20 at 11 28 10" src="https://user-images.githubusercontent.com/93984341/208646233-4e65b4f3-5de7-473e-90e5-2b43f8127ae2.png">

<img width="617" alt="Screenshot 2022-12-20 at 11 28 33" src="https://user-images.githubusercontent.com/93984341/208646296-7c5d2524-cdb7-48a0-9da5-1433eb756a0b.png">

2022-12-20 12:43 UTC, VWSCoronaDashboard26 requested changes

2022-12-20 12:43 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/choropleth-legenda.tsx
> -      {'bar' === type ? (
Since we are completely removing this, do we still need to pass in a `type` prop to this component as defined on line [18](https://github.com/minvws/nl-covid19-data-dashboard/pull/4550/files#diff-99dd104e084a2cd2a59e0c4a078e1b6e883c4f32b635f901113c59a4a1fe643bL18)?

2022-12-20 12:43 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/choropleth-legenda.tsx
>        {pageType === 'sewer' && (
This item is not in the design language of the other legend items, which I think it should. You probably also want to make some adjustments to this as well as making sure that it is actually part of the legend and not an individual item.

2022-12-20 12:43 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/choropleth-legenda.tsx
>  const LegendaColor = styled.div<{
I think we should rewrite these things to be 'vanilla' styled components instead of using the styled systems.

2022-12-20 12:43 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/choropleth-tile.tsx
> +            <Box display="flex" justifyContent={'flex-start'} pt={4}>
I think we can rewrite it like this.

```suggestion
<Box display="flex" justifyContent="flex-start" paddingTop={space[4]}>
```

2022-12-20 13:30 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/choropleth-legenda.tsx
> -      {'bar' === type ? (
This is already removed

2022-12-21 16:18 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/choropleth-legenda.tsx
>        {pageType === 'sewer' && (
I've added it to the list with legends

2022-12-21 16:18 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/choropleth-legenda.tsx
>        {pageType === 'sewer' && (
Can you resolve this if you're oke with the solution?

2022-12-21 16:19 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/choropleth-legenda.tsx
>  const LegendaColor = styled.div<{
This is not there anymore because of another change

2022-12-21 16:22 UTC, VWSCoronaDashboard18 commented
There are new 'after' screenshots:

![Screenshot 2022-12-21 at 17 21 11](https://user-images.githubusercontent.com/93984341/208954019-4f0ef612-03ce-4636-b727-dbd33dbba253.png)
![Screenshot 2022-12-21 at 17 22 03](https://user-images.githubusercontent.com/93984341/208954028-3477707c-ffcc-433a-a8ca-2f69713cef6b.png)

2022-12-22 08:31 UTC, VWSCoronaDashboard26 approved these changes
Very elegant solution and a proper clean up! :shipit:

2022-12-22 12:07 UTC, merged