cleanup
minvws/nl-covid19-data-dashboard pull request #4576
Opened 2022-12-30 15:29 UTC by VWSCoronaDashboard18

2023-01-04 15:05 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/choropleth-tile.tsx
> +            <Box display="flex" justifyContent={{ _: 'center', lg: 'flex-start' }} paddingTop={space[4]}>
I believe this change is not entirely intended? 🤔

2023-01-05 15:05 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/article-detail.tsx
>              spacingHorizontal={3}
Is this also a magic number? 🤔

2023-01-05 15:09 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/aside/menu.tsx
>        backgroundSize: '0.6em 1.2em',
No related to this PR but its a bit weird that `em`s are being used here 🤔

2023-01-05 15:26 UTC, VWSCoronaDashboard28 approved these changes
1 almost down, 11 to go!

2023-01-05 16:10 UTC, VWSCoronaDashboard28 requested changes
Please see the comments

2023-01-05 16:12 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/aside/menu.tsx
>        backgroundSize: '0.6em 1.2em',
Indeed not related. If you want you can create a jira ticket.

2023-01-09 08:26 UTC, VWSCoronaDashboard19 commented on packages/app/src/components/article-teaser.tsx
>            <ZoomContainer height={200}>
Same `height="200px" ` should also be applied here

2023-01-09 12:54 UTC, VWSCoronaDashboard21 approved these changes
Looks good to me!

2023-01-10 09:06 UTC, VWSCoronaDashboard25 commented on packages/app/src/components/age-demographic/age-demographic-tooltip-content.tsx
> +  padding: ${space[2]} ${space[0]};
I think this was brought up earlier as well, but I don't think we should change `0` in `space[0]`.
If there is no margin or padding, it's more helpful to stress that instead of referring to a lookup.

2023-01-31 10:41 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/age-demographic/age-demographic-tooltip-content.tsx
> +  padding: ${space[2]} ${space[0]};
But it is still a magic number. Then we should discuss this in the chapter

2023-01-31 10:45 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/age-demographic/age-demographic-tooltip-content.tsx
> +  padding: ${space[2]} ${space[0]};
<img width="456" alt="Screenshot 2023-01-31 at 11 42 39" src="https://user-images.githubusercontent.com/93984341/215738607-8b9f5def-35dc-48dd-b83e-7a52e0ae71bd.png">
<img width="467" alt="Screenshot 2023-01-31 at 11 42 51" src="https://user-images.githubusercontent.com/93984341/215738616-a6387daa-de72-4c94-9e1e-4fa99914846d.png">


Because of the nonagreement and this being an undiscussed opinion while having many differents files dealing with this. I would like to ask you to resolve this and take this to for example the chapter.

2023-01-31 10:46 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/aside/menu.tsx
>        mt="-3px"
Updated this, please resolve.

2023-01-31 10:48 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/article-teaser.tsx
> +            <BackgroundImage image={cover} height={'200px'} sizes={coverSizes} />
adjusted accordingly, please resolve.

2023-01-31 11:11 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/aside/menu.tsx
>        mt="-3px"
adjusted accordingly, please resolve.

2023-01-31 11:12 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/choropleth-tile.tsx
> +            <Box display="flex" justifyContent={{ _: 'center', lg: 'flex-start' }} paddingTop={space[4]}>
adjusted accordingly, please resolve.

2023-01-31 11:12 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/article-teaser.tsx
>            <ZoomContainer height={200}>
adjusted accordingly, please resolve.

2023-01-31 11:44 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/age-demographic/age-demographic-tooltip-content.tsx
> +  padding: ${space[2]} ${space[0]};
I agree, adjusted it across the PR's

2023-02-01 08:10 UTC, VWSCoronaDashboard26 approved these changes
Pre-approving as all my earlier remarks have been resolved. Do note that there is a compilation issue in this branch.

2023-02-02 20:11 UTC, VWSCoronaDashboard25 commented on packages/app/src/components/anchor-tile.tsx
> +    marginTop: asResponsiveArray({ _: space[3], md: space[0] }),
some `space[0]`'s left, here

2023-02-02 20:11 UTC, VWSCoronaDashboard25 commented on packages/app/src/components/article-detail.tsx
> +            padding={space[0]}
and here

2023-02-03 11:14 UTC, VWSCoronaDashboard25 approved these changes

2023-02-04 17:16 UTC, merged