clean up
minvws/nl-covid19-data-dashboard pull request #4581
Opened 2022-12-30 15:29 UTC by VWSCoronaDashboard18

2023-01-05 13:18 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/time-series-chart/components/timeline/components/tooltip-content.tsx
> +      py="15px"
Shouldn't this be as below?
```
paddingX="18px"
paddingY="15px"
```

Or, even shorthanded as `padding="15px 18px"`?

2023-01-05 13:18 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/time-series-chart/components/timeline/components/tooltip-content.tsx
> +        <Box paddingTop={space[3]} marginX={'-27px'} borderTop="1px solid" borderTopColor="gray2" display="flex" justifyContent="center" textVariant="label1">
See my earlier remarks regarding combining static values with `{ ... }`.

2023-01-05 13:18 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +    paddingTop: showWeekNumbers ? 20 : undefined, // Still a magic number, but this is not easaly possible without refactoring the useDimensions function
🙌

2023-01-05 13:18 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +            {highlightZero && <rect x={0} y={yScale(0)} width={bounds.width} height={'1px'} fill="black" />}
See my earlier remarks regarding combining static values with `{ ... }`.

2023-01-06 09:57 UTC, VWSCoronaDashboard28 requested changes

2023-01-06 09:57 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/time-series-chart/components/bar-trend.tsx
> +                <PatternLines id="diagonal-pattern" height={6} width={6} stroke={colors.neutral} strokeWidth={2} orientation={['diagonal']} />
`height={6} width={6}` should be in pixel values

2023-01-06 09:57 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        <pattern id={patternId} width="8" height="8" patternTransform="rotate(-45 0 0)" patternUnits="userSpaceOnUse">
`width="8" height="8"` should be pixel values?

2023-01-06 09:57 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        <pattern id={patternId} width="4" height="4" patternUnits="userSpaceOnUse">
`width="4" height="4"` should be pixel values?

2023-01-16 11:46 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +    paddingTop: showWeekNumbers ? 20 : undefined, // Still a magic number, but this is not easaly possible without refactoring the useDimensions function
Thanks for noticing and valuing my comment!

2023-01-31 12:26 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/time-series-chart/components/timeline/components/tooltip-content.tsx
> +      py="15px"
adjusted accordingly, please resolve.

2023-01-31 12:26 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/time-series-chart/components/timeline/components/tooltip-content.tsx
> +        <Box paddingTop={space[3]} marginX={'-27px'} borderTop="1px solid" borderTopColor="gray2" display="flex" justifyContent="center" textVariant="label1">
adjusted accordingly, please resolve.

2023-01-31 12:26 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +            {highlightZero && <rect x={0} y={yScale(0)} width={bounds.width} height={'1px'} fill="black" />}
adjusted accordingly, please resolve.

2023-01-31 12:26 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/time-series-chart/components/bar-trend.tsx
> +                <PatternLines id="diagonal-pattern" height={6} width={6} stroke={colors.neutral} strokeWidth={2} orientation={['diagonal']} />
This is a VisX number type requirement

2023-01-31 12:27 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        <pattern id={patternId} width="4" height="4" patternUnits="userSpaceOnUse">
See previous comments

2023-01-31 12:27 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/time-series-chart/components/timespan-annotation.tsx
> +        <pattern id={patternId} width="8" height="8" patternTransform="rotate(-45 0 0)" patternUnits="userSpaceOnUse">
see previous comments

2023-02-02 14:36 UTC, VWSCoronaDashboard26 approved these changes
Pre-approving as all my earlier remarks have been resolved.

2023-02-06 10:33 UTC, merged