Magic number cleanup part 9
minvws/nl-covid19-data-dashboard pull request #4584
Opened 2022-12-30 15:33 UTC by VWSCoronaDashboard18

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/situations/situations-data-coverage-choropleth-tile.tsx
> +        <Box flex={{ lg: 1 }} marginLeft={[0, 0, 3]} display="flex" flexDirection="column" height="100%">
I think we would want to reference the `space` array for `marginLeft` here as well.

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +              <Box size={15} marginRight={space[2]} bg={colors.gray2} position="relative" top={'3px'} />
See my earlier remarks regarding combining static values with `{ ... }`.

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +        <InlineTooltip content={description} css={css({ fontWeight: 'heavy', fontSize: 2 })}>
Nitpicky comment, but should `2` also reference the theme's `fontSizes`?

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +      <InlineText textAlign="right" css={css({ minWidth: 40 })}>{`${formatPercentage(amount, {
Should this be written as `minWidth: '40px'`?

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +        <Box width={`${amount}%`} height={'12px'} backgroundColor={color} />
See my earlier remarks regarding combining static values with `{ ... }`.

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/indicator-level-description.tsx
>          css={css({ columnGap: 3, rowGap: asResponsiveArray({ _: 3, sm: 1 }) })}
Should these values also reference `space`?

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/search/hit-list.tsx
> +    paddingLeft: ['50px', null, null, space[5]],
Could this reference `paddedStyle.paddingLeft`?

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/search/hit-list.tsx
> +  paddingLeft: ['50px', null, null, space[5]],
Is there a particular reason this is written as such and not leveraging the `asResponsiveArray` method?

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/search/search-input.tsx
> +  paddingX: [ICON_SPACE, null, null, ICON_SPACE_LARGE],
Similar remark as before.

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/search/search-results.tsx
> +    margin-bottom: ${asResponsiveArray({ _: space[5], xs: space[0] })};
You changed `2em` to `space[5]` here. `space` is in `rem`, not `em`. Does this always give the same results? If so, any particular reason why `padding: 1em ${space[0]}` is not `padding: ${space[3]} ${space[0]}`?

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/search/search.tsx
> +                    marginY={`-${space[1]}`}
`my={'-1px'` and `marginY={`-${space[1]}`}` do not evaluate to the same result.

2023-01-05 14:00 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/topical-section-header.tsx
> +              <Box marginBottom={'2px'}>
See my earlier remarks regarding combining static values with `{ ... }`.

2023-01-06 10:36 UTC, VWSCoronaDashboard28 submitted a review, later dismissed

2023-01-06 10:36 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +        <InlineTooltip content={description} css={css({ fontWeight: 'heavy', fontSize: 2 })}>
Same goes for `fontWeight`

2023-01-06 10:36 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/topical/components/search/search-results.tsx
> +    margin-bottom: ${asResponsiveArray({ _: space[5], xs: space[0] })};
`em` is based on the parent vs `rem` being based on the `html` element. If the results are the same, then I would argue all `em` values should be adjusted.

2023-01-11 11:01 UTC, VWSCoronaDashboard21 requested changes

2023-02-02 17:29 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-data-coverage-choropleth-tile.tsx
> +        <Box flex={{ lg: 1 }} marginLeft={[0, 0, 3]} display="flex" flexDirection="column" height="100%">
adjusted accordingly, please resolve.

2023-02-02 17:31 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +              <Box size={15} marginRight={space[2]} bg={colors.gray2} position="relative" top={'3px'} />
adjusted accordingly, please resolve.

2023-02-02 17:35 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +        <InlineTooltip content={description} css={css({ fontWeight: 'heavy', fontSize: 2 })}>
adjusted accordingly, please resolve.

2023-02-02 17:37 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +      <InlineText textAlign="right" css={css({ minWidth: 40 })}>{`${formatPercentage(amount, {
adjusted accordingly, please resolve.

2023-02-02 17:37 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-table-tile.tsx
> +        <Box width={`${amount}%`} height={'12px'} backgroundColor={color} />
adjusted accordingly, please resolve.

2023-02-02 17:37 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/search/hit-list.tsx
> +  paddingLeft: ['50px', null, null, space[5]],
No, no idea... Out of scope.
adjusted accordingly, please resolve.

2023-02-02 17:38 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/search/search-input.tsx
> +  paddingX: [ICON_SPACE, null, null, ICON_SPACE_LARGE],
No, no idea... Out of scope. please resolve.

2023-02-02 17:40 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/search/search-results.tsx
> +    margin-bottom: ${asResponsiveArray({ _: space[5], xs: space[0] })};
I do agree with #28, that was there reason for the adjustment.
please resolve

2023-02-02 17:41 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/search/search.tsx
> +                    marginY={`-${space[1]}`}
True reverted

2023-02-02 17:42 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/topical-section-header.tsx
> +              <Box marginBottom={'2px'}>
adjusted accordingly, please resolve.

2023-02-02 17:43 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +              <Box size={15} marginRight={space[2]} bg={colors.gray2} position="relative" top={'3px'} />
adjusted accordingly, please resolve.

2023-02-03 07:49 UTC, VWSCoronaDashboard21 approved these changes
Pre-approved but one small comment was not yet resolved.

2023-02-03 07:49 UTC, VWSCoronaDashboard21 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +              <Box size={15} marginRight={space[2]} bg={colors.gray2} position="relative" top={'3px'} />
It's not yet resolved, could you please have a look at it.

2023-02-03 10:52 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/situations/situations-data-coverage-choropleth-tile.tsx
> +        <Box flex={{ lg: '1' }} as="figcaption">
Does converting `1` to `'1'` make sense in this case? Wouldn't that have any possible implications for rendering this component?

2023-02-03 10:52 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/situations/situations-data-coverage-choropleth-tile.tsx
> +        <Box flex={{ lg: 1 }} marginLeft={[0, 0, 3]} display="flex" flexDirection="column" height="100%">
Already better, but not yet resolved.

2023-02-03 10:55 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +              <Box size={15} marginRight={space[2]} bg={colors.gray2} position="relative" top={'3px'} />
It's not yet resolved.

2023-02-03 10:59 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/search/hit-list.tsx
> +    paddingLeft: ['50px', null, null, space[5]],
This is yet to be resolved.

2023-02-03 11:01 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/search/search.tsx
> +                    marginY={`-${space[1]}`}
Already better, but since this is still static value, I would argue that simply `marginY="-1px"` is more readable.

2023-02-03 11:02 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/topical-section-header.tsx
> +              <Box marginBottom={'2px'}>
This is yet to be resolved.

2023-02-05 11:58 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-data-coverage-choropleth-tile.tsx
> +        <Box flex={{ lg: 1 }} marginLeft={[0, 0, 3]} display="flex" flexDirection="column" height="100%">
Ahl I understand, looked at the wrong thing that could be improved... And did the one thing that wasn't actually the title of this PR series... 🤦‍♂️

2023-02-05 11:58 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +              <Box size={15} marginRight={space[2]} bg={colors.gray2} position="relative" top={'3px'} />
I think it now is...

2023-02-05 11:59 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/search/search.tsx
> +                    marginY={`-${space[1]}`}
In agree, adjusted it, please resolve

2023-02-05 11:59 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/topical-section-header.tsx
> +              <Box marginBottom={'2px'}>
It now is, if i'm correct

2023-02-05 12:00 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-overview-choropleth-tile.tsx
> +              <Box size={15} marginRight={space[2]} bg={colors.gray2} position="relative" top={'3px'} />
Now it is, if I'm correct, please resolve if you agree

2023-02-06 08:26 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/search/hit-list.tsx
> +    paddingLeft: ['50px', null, null, space[5]],
Friendly reminder.

2023-02-06 08:52 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/situations/situations-data-coverage-choropleth-tile.tsx
> +        <Box flex={{ lg: '1' }} as="figcaption">
adjusted accordingly, please resolve.

2023-02-06 09:10 UTC, VWSCoronaDashboard26 approved these changes

2023-02-06 09:33 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/search/hit-list.tsx
> +    paddingLeft: ['50px', null, null, space[5]],
I missed this one, and it's been solved accordingly, please resolve it.

2023-02-06 11:38 UTC, VWSCoronaDashboard27 approved these changes

2023-02-06 12:03 UTC, merged