Magic number cleanup part 10
minvws/nl-covid19-data-dashboard pull request #4585
Opened 2022-12-30 15:33 UTC by VWSCoronaDashboard18

2023-01-05 14:17 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/artikelen/index.tsx
> +              marginTop={space[4]}
`marginTop={space[4]` is not the same as `mt={3}`.

2023-01-05 14:17 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/gemeente/index.tsx
> +          <Box display="flex" flex="1" justifyContent="center" height="75vh" width="100%" maxHeight={960} flexDirection="column" spacing={3}>
Should this be written as `maxHeight="960px"`?

2023-01-05 14:17 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/coronamelder.tsx
> +                  <span css={css({ maxWidth: 200 })}>{corona_melder_app.rapport.link.text}</span>
Should this be written as `maxWidth: '200px'`?

2023-01-05 14:17 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +              source: textNl.bronnen.rivm,
Is this change intentional?

2023-01-05 14:17 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/veiligheidsregio/index.tsx
> +          <Box display="flex" flex="1" justifyContent="center" height="75vh" maxHeight={960} width="100%" flexDirection="column" spacing={3}>
Should this be written as `maxHeight="960px"`?

2023-01-05 14:17 UTC, VWSCoronaDashboard26 commented on packages/app/src/style/preset.ts
> +  /** padding: inherit p-styles from the container */
I have a feeling that this should remain `p` as it refers to a `<p>` element.

2023-01-06 10:44 UTC, VWSCoronaDashboard28 submitted a review, later dismissed

2023-01-06 10:44 UTC, VWSCoronaDashboard28 commented on packages/app/src/utils/use-tab-interactive-button.tsx
>      fontSize: 1,
Is this a magic number?

2023-01-12 08:23 UTC, VWSCoronaDashboard21 requested changes

2023-01-12 08:23 UTC, VWSCoronaDashboard21 commented on packages/app/src/utils/use-tab-interactive-button.tsx
>      borderColor: 'blue8',
Nitpicky comment, but to avoid unnecessary short-hand variables you can change this to `background: x.isActive ? 'blue8' : 'white',` on line 91.

2023-02-02 17:47 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/artikelen/index.tsx
> +              marginTop={space[4]}
adjusted accordingly, please resolve.

2023-02-02 17:48 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/index.tsx
> +          <Box display="flex" flex="1" justifyContent="center" height="75vh" width="100%" maxHeight={960} flexDirection="column" spacing={3}>
adjusted accordingly, please resolve.

2023-02-02 17:48 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/coronamelder.tsx
> +                  <span css={css({ maxWidth: 200 })}>{corona_melder_app.rapport.link.text}</span>
adjusted accordingly, please resolve.

2023-02-02 17:49 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +              source: textNl.bronnen.rivm,
No, reverted, adjusted accordingly, please resolve.

2023-02-02 17:49 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/veiligheidsregio/index.tsx
> +          <Box display="flex" flex="1" justifyContent="center" height="75vh" maxHeight={960} width="100%" flexDirection="column" spacing={3}>
adjusted accordingly, please resolve.

2023-02-02 17:50 UTC, VWSCoronaDashboard18 commented on packages/app/src/style/preset.ts
> +  /** padding: inherit p-styles from the container */
adjusted accordingly, please resolve.

2023-02-02 17:51 UTC, VWSCoronaDashboard18 commented on packages/app/src/locale/use-lokalize-text.tsx
> +    <Box border="1px solid" borderColor="gray3" marginX={space[2]} borderRadius={1} overflow="hidden">
This is going to be picked up in a separate ticket.

2023-02-02 17:52 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/use-collapsible.tsx
> +          height: '0px',
adjusted accordingly, please resolve.

2023-02-02 17:52 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/use-tab-interactive-button.tsx
>      fontSize: 1,
adjusted accordingly, please resolve.

2023-02-02 17:54 UTC, VWSCoronaDashboard18 commented on packages/app/src/locale/use-lokalize-text.tsx
>              display: 'inline-block',
Out of scope, please resolve

2023-02-02 17:54 UTC, VWSCoronaDashboard18 commented on packages/app/src/locale/use-lokalize-text.tsx
>      bg: x.isActive ? 'blue8' : 'transparent',
Out of scope, please resolve.

2023-02-02 17:56 UTC, VWSCoronaDashboard18 commented on packages/app/src/utils/use-tab-interactive-button.tsx
>      borderColor: 'blue8',
adjusted accordingly, please resolve.

2023-02-03 11:04 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/gemeente/index.tsx
> +          <Box display="flex" flex="1" justifyContent="center" height="75vh" width="100%" maxHeight={960} flexDirection="column" spacing={3}>
This has been adjusted from `maxHeight={960}` to `minHeight="960px"`. Is the replacement of `maxHeight` with `minHeight` actually desired?

2023-02-03 11:05 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/veiligheidsregio/index.tsx
> +          <Box display="flex" flex="1" justifyContent="center" height="75vh" maxHeight={960} width="100%" flexDirection="column" spacing={3}>
This has been adjusted from maxHeight={960} to minHeight="960px". Is the replacement of maxHeight with minHeight actually desired?

2023-02-03 11:07 UTC, VWSCoronaDashboard26 requested changes
Simply decided to not pre-approve due to a difference in how a component should work. Other than that, all my earlier comments have been marked as resolved.

2023-02-05 12:07 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/index.tsx
> +          <Box display="flex" flex="1" justifyContent="center" height="75vh" width="100%" maxHeight={960} flexDirection="column" spacing={3}>
Not sure what happened, It should be okay by now.

2023-02-05 12:07 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/veiligheidsregio/index.tsx
> +          <Box display="flex" flex="1" justifyContent="center" height="75vh" maxHeight={960} width="100%" flexDirection="column" spacing={3}>
Not sure what happened, It should be okay by now.

2023-02-06 08:37 UTC, VWSCoronaDashboard26 approved these changes

2023-02-06 10:12 UTC, VWSCoronaDashboard27 approved these changes

2023-02-06 10:45 UTC, VWSCoronaDashboard21 approved these changes

2023-02-06 10:47 UTC, merged