Magic number cleanup part 11
minvws/nl-covid19-data-dashboard pull request #4586
Opened 2022-12-30 15:33 UTC by VWSCoronaDashboard18

2023-01-05 14:31 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/vaccine/components/narrow-percentage.tsx
> +      <Box width={'10px'} height={'10px'} backgroundColor={color} borderRadius="50%" marginRight={space[2]} />
See my earlier remarks regarding combining static values with `{ ... }`.

2023-01-05 14:31 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/vaccine/components/wide-percentage.tsx
> +      <Box width={'10px'} height={'10px'} backgroundColor={color} borderRadius="50%" marginRight={space[2]} />
See my earlier remarks regarding combining static values with `{ ... }`.

2023-01-05 14:31 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/vaccine/vaccinations-per-supplier-over-last-week-tile.tsx
> +      <PieChart data={mappedData} dataConfig={dataConfig} donutWidth={25} icon={<VaccinationIcon />} iconFill={colors.black} innerSize={180} marginLeft={32} marginRight={32} />
Should this be written as `marginLeft="32px"` and `marginRight="32px"`?
I am not too sure about `innerSize`.

2023-01-06 10:48 UTC, VWSCoronaDashboard28 requested changes

2023-01-06 10:48 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/vaccine/vaccinations-kpi-header.tsx
> +    <Box paddingTop="40px" borderTopWidth={2} borderColor="gray3" borderStyle="solid">
`borderTopWidth={2}` - Is this using a magic number, and if not, should it be a pixel value?

2023-01-12 12:24 UTC, VWSCoronaDashboard21 requested changes

2023-01-12 12:24 UTC, VWSCoronaDashboard21 commented on packages/app/src/domain/vaccine/vaccinations-per-supplier-over-last-week-tile.tsx
> +      <PieChart data={mappedData} dataConfig={dataConfig} donutWidth={25} icon={<VaccinationIcon />} iconFill={colors.black} innerSize={180} marginLeft={32} marginRight={32} />
Is it then also possible to write this as `marginLeft={space[4]}` and `marginRight={space[4]}` ?

2023-02-02 18:01 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/components/narrow-percentage.tsx
> +      <Box width={'10px'} height={'10px'} backgroundColor={color} borderRadius="50%" marginRight={space[2]} />
adjusted accordingly, please resolve.

2023-02-02 18:01 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/components/wide-percentage.tsx
> +      <Box width={'10px'} height={'10px'} backgroundColor={color} borderRadius="50%" marginRight={space[2]} />
adjusted accordingly, please resolve.

2023-02-02 18:03 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccinations-per-supplier-over-last-week-tile.tsx
> +      <PieChart data={mappedData} dataConfig={dataConfig} donutWidth={25} icon={<VaccinationIcon />} iconFill={colors.black} innerSize={180} marginLeft={32} marginRight={32} />
No, only number inputs...

2023-02-02 18:03 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccinations-per-supplier-over-last-week-tile.tsx
> +      <PieChart data={mappedData} dataConfig={dataConfig} donutWidth={25} icon={<VaccinationIcon />} iconFill={colors.black} innerSize={180} marginLeft={32} marginRight={32} />
please resolve

2023-02-02 18:04 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccinations-kpi-header.tsx
> +    <Box paddingTop="40px" borderTopWidth={2} borderColor="gray3" borderStyle="solid">
adjusted accordingly, please resolve.

2023-02-03 11:09 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/vaccine/components/narrow-percentage.tsx
> +      <Box width={'10px'} height={'10px'} backgroundColor={color} borderRadius="50%" marginRight={space[2]} />
Resolving because this is no longer part of this pull request, yet I am actually not sure if the fix has been applied.

2023-02-03 11:09 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/vaccine/components/wide-percentage.tsx
> +      <Box width={'10px'} height={'10px'} backgroundColor={color} borderRadius="50%" marginRight={space[2]} />
Resolving because this is no longer part of this pull request, yet I am actually not sure if the fix has been applied.

2023-02-03 11:10 UTC, VWSCoronaDashboard26 approved these changes
Pre-approving as all my earlier remarks have been resolved.

2023-02-06 09:54 UTC, VWSCoronaDashboard27 approved these changes

2023-02-06 10:46 UTC, VWSCoronaDashboard21 approved these changes

2023-02-06 10:47 UTC, merged