Feature/cor 1268 modified legends
minvws/nl-covid19-data-dashboard pull request #4592
Opened 2023-01-03 14:26 UTC by VWSCoronaDashboard27

## Summary
### DONE

 For National on: 
>   Hospital Admissions page
>   IC admissions page
>   Positive tests page

- disabled legend component from the `time-series-chart.tsx`;
- added button "Alle leeftijden" to `interactive-legend.tsx`;

**Before:** 
![Screenshot 2023-01-03 at 15 24 14](https://user-images.githubusercontent.com/111750729/210376230-9df94633-b7d8-43b5-bff4-48c58a958d1f.png)

**After:** 
![Screenshot 2023-01-03 at 15 25 18](https://user-images.githubusercontent.com/111750729/210376422-bc15cd20-b08e-48fd-bb2a-5dab3759f4d8.png)

2023-01-04 09:45 UTC, VWSCoronaDashboard18 approved these changes
Looks good to me!

2023-01-04 12:40 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/legend.tsx
> +const Line = styled.div<{ color: string; lineStyle: LegendLineStyle }>(({ color, lineStyle }) =>
Same comment as above for this file.

2023-01-04 12:45 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/hospital/admissions-per-age-group/admissions-per-age-group.tsx
> +        disableLegend
This addition results in incorrect behaviour as per the acceptance criteria / design proposal. This prop completely disables the legend for this component, yet we want to keep the legend item indicating incomplete/incorrect data (the grey square mentioning 'Data for recent days is incomplete due to reporting delays'). The same applies for `packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx`.

2023-01-04 12:52 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/hospital/admissions-per-age-group/admissions-per-age-group.tsx
>    const alwaysEnabled = ['admissions_overall_per_million'];
This line keeps 'admissions_overall_per_million' (the value used for 'All age groups') in the graph regardless of the selected filter/interactive legend item. This previously made sense because 'All age groups' was not a selectable item. 'All age groups' is now a selectable item, which means it should function exactly the same as how other age groups work:

* selecting no specific age groups will show all age groups in the graph
* selecting one (or more) specific age groups will only show the selected age group(s) in the graph

The logic to always enable this property, and therefor the logic to render the contents of the graph, should be adjusted accordingly. The same applies for `packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx`.

2023-01-05 14:56 UTC, VWSCoronaDashboard28 approved these changes
I am approving this as I do not have any additional comments to @VWSCoronaDashboard26's comments, however please do address those.

2023-01-05 16:05 UTC, VWSCoronaDashboard28 requested changes
Please see the existing comments

2023-01-10 08:53 UTC, VWSCoronaDashboard26 approved these changes
Nice changes! I have left one technically non-blocking comment as the code looks fine and does what the feature is supposed to do hence I'll approve this.

Another thing that I commented on earlier but hasn't been picked up is rewriting the styled components to no longer leverage `css()` by styled system but instead the backtick-notation as agreed upon in the coding conventions. Again, this is technically not blocking.

2023-01-10 08:53 UTC, VWSCoronaDashboard26 commented on packages/app/src/components/interactive-legend.tsx
> +    </svg>
I did not consider the usage of magic numbers earlier, but I think it would be wise to also fix them proactively inside this pull request as the [pull request](https://github.com/minvws/nl-covid19-data-dashboard/pull/4578/files#diff-383c16b4db0cb49599167eeeea894cd496480eb436298bac6605a627dcf30d8a) that covers magic numbers inside this file will be conflicting as soon as this is merged plus this is a new addition.

This comment applies to all changes in this file as well as the usage of CSS / React property names such as `pl` or `py` on lines 116 and 117.

This comment also applies to `packages/app/src/components/legend.tsx`.

2023-01-11 16:48 UTC, VWSCoronaDashboard28 approved these changes

2023-01-12 09:28 UTC, merged