Feature/cor 1358 archiving disability care elderly at home
minvws/nl-covid19-data-dashboard pull request #4613
Opened 2023-01-23 14:16 UTC by VWSCoronaDashboard21

## Summary

- Archived the full page 'Gehandicaptenzorg' and 'Thuiswonende 70-plussers'.
- Added yellow warning tile on the page 'Gehandicaptenzorg' and 'Thuiswonende 70-plussers'.
- Updated the warning tile with the 'informational' variant type and used that on the previous archived pages.
- Archived graphs on the page Verpleeghuiszorg.

## Screenshots

The screenshots only cover bits of the dashboard and give an impression more so than a full overview of everything that has changed.

**Before**
<details>
  <summary>Toggle before screenshot</summary>
</details>

**After**
<details>
  <summary>Toggle after screenshot</summary>
</details>

2023-01-23 16:34 UTC, VWSCoronaDashboard26 reviewed
Nice changes, though some things either need clearing up or some minor work. Do note that I stopped repeating placing the same comment in several places.

2023-01-23 16:34 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/gehandicaptenzorg.tsx
> -
Nitpicky and non-blocking comment, but I can't help but notice the removal of quite some white space that separates components from one another. I personally prefer to (sparingly) leverage white space to group or separate components that are (un)related, making the file 'flow' more naturally. We have never discussed this as a team, yet I would like to know the motivation of why this should be removed.

2023-01-23 16:34 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/kwetsbare-groepen-70-plussers.tsx
> +} from '~/components';
This change now uses a barrel file rather than that it targets the component directly, which is something we opted not to do according to the coding conventions.

2023-01-23 16:34 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/kwetsbare-groepen-70-plussers.tsx
> +            title="Kwetsbare groepen en 70+"
Should this come from Sanity?

2023-01-23 16:34 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/kwetsbare-groepen-70-plussers.tsx
> +  const [hasHideArchivedCharts, setHideArchivedCharts] = useState<boolean>(false);
React conventions dictate that the state setter should follow the name of the actual state variable, meaning it ought to be `setHasHideArchivedCharts`.

However, I very much dislike `hasHideArchivedCharts` as a name because it doesn't flow off the tongue very well, but also contradicts what it is supposed to do. Basically, if this value is `false`, I would argue that the 'archived charts' or **not** hidden, because the `hasHide` part implies that they **should not** be hidden. Yet, they are.

Instead, I personally opted to go with `isArchivedContentShown` as can be seen in [this pull request](https://github.com/minvws/nl-covid19-data-dashboard/pull/4612/files#diff-a489c1ce2f01c8c91f3412448da6a29c061759ee69ecb4487be192499fa12ce7R60). The variable name both reads nicely and actually does what it says given its value.

2023-01-23 16:34 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/thuiswonende-ouderen.tsx
> +          {textShared.belangrijk_bericht && textShared.belangrijk_bericht !== '' && <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="emphasis" />}
Any particular reason why `!isEmpty` has been removed in favour of `!== ''`? Could we not use double bangs to achieve the same but in a shorter format?

2023-01-23 16:34 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/verdenkingen-huisartsen.tsx
> +          {text.belangrijk_bericht && text.belangrijk_bericht !== '' && <WarningTile isFullWidth message={text.belangrijk_bericht} variant="informational" />}
Any particular reason why `isPresent` has been removed in favour of `!== ''`? Could we not use double bangs to achieve the same but in a shorter format?

2023-01-23 16:34 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/veiligheidsregio/[code]/gedrag.tsx
> +import { WarningTile, Markdown, PageInformationBlock, Tile, TileList, TwoKpiSection } from '~/components';
See my earlier comment regarding barrel files.

2023-01-23 16:34 UTC, VWSCoronaDashboard26 commented on packages/common/src/data/reverse-router.ts
> +      verpleeghuiszorg: () => `/landelijk/kwetsbare-groepen-70-plussers`,
Without too much context on this: should the `verpleeghuiszorg` key both here and on line 45 still remain? I would argue that it is a completely different page, so why would be keep it around?

2023-01-24 08:24 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +    border-radius: ${radii[1]}pxpx;
The border-radius can be useful on an SVG. Only if it contains a background color. That is not the case and is obsolete on this line.

![Screenshot 2023-01-24 at 09 19 32](https://user-images.githubusercontent.com/93984341/214242834-7be743b6-9926-486d-a28c-4834449c9f7e.png)

2023-01-24 08:28 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +  },
Correct I will adjust it.

2023-01-24 09:09 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +  },
Done and resolved

2023-01-24 09:20 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/kwetsbare-groepen-70-plussers.tsx
> +export default VulnerableGroups;
Perhaps a comment about this change could make it more clear why this is the case when someone happens upon it in the future.

2023-01-24 09:43 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +    border-radius: ${radii[1]}pxpx;
Removed as it's obsolete

2023-01-24 10:37 UTC, VWSCoronaDashboard28 requested changes

2023-01-24 10:37 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/coronamelder.tsx
> +                  <span css={css({ maxWidth: 200 })}>{corona_melder_app.rapport.link.text}</span>
Could be changed to `<Box as="span" maxWidth="200px" />`. Not sure if you're leaving these things because of the magic number PRs.

2023-01-24 10:37 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/veiligheidsregio/[code]/gehandicaptenzorg.tsx
> +          {textShared.belangrijk_bericht && textShared.belangrijk_bericht !== '' && <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="emphasis" />}
I think refactoring this to:

```
{ textShared.belangrijk_bericht && textShared.belangrijk_bericht !== '' && (
    <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="emphasis" />
)}
```

Improves the readability.

2023-01-24 11:22 UTC, VWSCoronaDashboard18 commented on packages/common/src/data/reverse-router.ts
> +      verpleeghuiszorg: () => `/landelijk/kwetsbare-groepen-70-plussers`,
This is picked up in branch COR-1357 and the PR regarding that branch.

2023-01-24 11:26 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/kwetsbare-groepen-70-plussers.tsx
> +export default VulnerableGroups;
All the archived data is entered as a subset of nursing homes. either 'achieved' or 'vulnerable'.
But the page is visually called on the frontend client VulnerableGgroups and elderly people. (Kwetsare groepen en 70 plussers) Therefore somewhere in the code, there will be an overlap in those two different terms. And that's happening on this page where the data naming is conflicting with the name of the page's subject.

I will close this conversation. Because it's also out of scope and can be discussed elsewhere.

2023-01-24 11:26 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/veiligheidsregio/[code]/kwetsbare-groepen-70-plussers.tsx
> +export default NursingHomeCare;
See my previous answer.

2023-01-24 11:55 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/besmettelijke-mensen.tsx
> +          {!!textShared.belangrijk_bericht && <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="informational" />}
the two !! can be removed...

2023-01-24 12:14 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +    </Article>
Solved, thanks for letting me know about the fontWeights theming.

2023-01-24 12:20 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +    margin-left: 10px;
You are right, although a bit nitpicky... 🤓👍

2023-01-24 15:03 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +    margin-top: ${fontSizes[0]};
Thanks for catching this.

2023-01-24 15:03 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
>  import { Warning } from '@corona-dashboard/icons';
because of urgency and non-blocking label, I solve this.

2023-01-24 15:04 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +    text-decoration-style:  ${({ hasTooltip }) => (hasTooltip ? 'dotted' : undefined)};
because of urgency and non-blocking label, I solve this.

2023-01-24 15:43 UTC, VWSCoronaDashboard25 commented on packages/app/src/pages/landelijk/besmettelijke-mensen.tsx
> +          {!!textShared.belangrijk_bericht && <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="informational" />}
The `!!` explicitly tell the reader this is interpreted as a boolean. Please leave this be!

2023-01-24 15:49 UTC, VWSCoronaDashboard25 commented on packages/app/src/pages/veiligheidsregio/[code]/gehandicaptenzorg.tsx
> +          {textShared.belangrijk_bericht && textShared.belangrijk_bericht !== '' && <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="emphasis" />}
Even better, earlier:
```
const hasActiveWarningTile = !!textShared.belangrijk_bericht;
```
And here:
```
{hasActiveWarningTile && <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="emphasis" />}
```

Similar to how this is done in this other PR: https://github.com/minvws/nl-covid19-data-dashboard/pull/4612/files#diff-a489c1ce2f01c8c91f3412448da6a29c061759ee69ecb4487be192499fa12ce7

2023-01-24 15:53 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/veiligheidsregio/[code]/kwetsbare-groepen-70-plussers.tsx
> +export default NursingHomeCare;
I am marking this conversation as to-be-resolved again, as I do think we would want this page component to leverage the same name as on NL level (`VulnerableGroups`).

2023-01-24 15:57 UTC, VWSCoronaDashboard25 commented on packages/common/src/types/data.ts
> +  age_group_range: "12+" | "18+";
Please undo all of these changes. Manually if needed.
Flipping from `'` to `"` and back each time ruins the traceability of actual changes.

2023-01-24 16:00 UTC, VWSCoronaDashboard25 commented on packages/common/src/types/data.ts
> +  age_group_range: "12+" | "18+";
For future PRs, check what you are going to commit and push before doing so and make haste in fixing this auto-change on your machine.

2023-01-24 16:16 UTC, VWSCoronaDashboard25 commented on packages/app/src/components/warning-tile.tsx
> +  border-bottom-right-radius: ${radii[1]}px;
I actually prefer it this way for readability, otherwise I need to lookup what position in the shorthand is for which corner again.

2023-01-24 16:22 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/veiligheidsregio/[code]/kwetsbare-groepen-70-plussers.tsx
> +export default NursingHomeCare;
I mis-interpreted your comment. It is fixed now.

2023-01-24 16:23 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/besmettelijke-mensen.tsx
> +          {!!textShared.belangrijk_bericht && <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="informational" />}
I tested this specific case a couple of times and it does work without the !!. But I will leave it for now...

2023-01-24 16:26 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +  border-bottom-right-radius: ${radii[1]}px;
I do agree with @VWSCoronaDashboard25, let's take it to our frontend chapter.

2023-01-24 16:27 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/warning-tile.tsx
> +  border-bottom-right-radius: ${radii[1]}px;
Same answer as above

2023-01-24 16:28 UTC, VWSCoronaDashboard28 approved these changes

2023-01-24 16:29 UTC, VWSCoronaDashboard18 approved these changes
Because I did half of this PR, I approve but will wait for another approval.

2023-01-24 16:29 UTC, merged

2023-01-24 16:35 UTC, VWSCoronaDashboard25 commented on packages/common/src/types/data.ts
> +  age_group_range: "12+" | "18+";
I was in the understanding that is autogenerated by your machine, not by any settings in this project, because otherwise this wouldn't be a thing or it's because of some local settings on someone else's machine.

2023-01-24 16:35 UTC, VWSCoronaDashboard25 commented on packages/app/src/pages/landelijk/besmettelijke-mensen.tsx
> +          {!!textShared.belangrijk_bericht && <WarningTile isFullWidth message={textShared.belangrijk_bericht} variant="informational" />}
Sure, that is how JavaScript works, because `&&` is binary operator that takes an argument in front and one after the operator, and evaluates them as booleans. But because of that, as a reader you only learn it is evaluated as a boolean when you reach the `&&`.

But by adding `!!` it can be recognised as a boolean check immediately, which improves readability.