Feature/COR-1263-table-consistency-implementations
minvws/nl-covid19-data-dashboard pull request #4614
Opened 2023-01-23 17:03 UTC by VWSCoronaDashboard28

# Summary

The motivation behind this ticket was to make the tables across the site consistent in terms of design. It was taken one step further by refactoring/removing some components so that there is reduced duplicity of components. This results in quite a few changes, but should help in the long run.

The changes impact the following pages:

- Behaviour - NL and VR
- Vaccinations - NL
- Variants - NL

The changes impact all the tables on those pages. 2 on the behaviour pages and 3 on the vaccination pages.

**NOTE:** For the Vaccinations page you see the before and after of only one Vaccine Coverage table. The 2 others are in the archived section and have been made to be exactly the same as the non-archived one. Additionally, in the mobile/narrow screenshots, some of the tables might be cut off due to a lack of vertical screen space when taking a screenshot.

### BEFORE - Desktop
<img width="951" alt="image" src="https://user-images.githubusercontent.com/116002914/214098495-5241efea-2bcc-423a-a497-76e2e3a5c46e.png">
___
<img width="920" alt="Screenshot 2023-01-23 at 17 47 42" src="https://user-images.githubusercontent.com/116002914/214098964-2ffaeac7-d8e6-4862-980f-12da435012d8.png">
___
<img width="920" alt="image" src="https://user-images.githubusercontent.com/116002914/214099102-f90242f3-2ead-4a3f-94d5-14e62d27fb67.png">
___
<img width="944" alt="image" src="https://user-images.githubusercontent.com/116002914/214100133-b8d65701-16d1-4cd4-8273-3437723f846a.png">

### BEFORE - Mobile
<img width="743" alt="Screenshot 2023-01-23 at 17 50 49" src="https://user-images.githubusercontent.com/116002914/214099672-3e62b6b1-b253-4577-a1c0-666a1dad4325.png">
---
<img width="740" alt="Screenshot 2023-01-23 at 17 53 30" src="https://user-images.githubusercontent.com/116002914/214100326-7b4adeee-0a09-4870-b68e-052f94e1e1d5.png">
---
<img width="743" alt="Screenshot 2023-01-23 at 17 53 45" src="https://user-images.githubusercontent.com/116002914/214100405-fb5f9691-43a7-487c-85b7-482b168e6e91.png">
---
<img width="604" alt="Screenshot 2023-01-23 at 17 54 11" src="https://user-images.githubusercontent.com/116002914/214100520-b66d4518-173e-4e80-9652-7b12ff1a3558.png">

### AFTER - Desktop
<img width="935" alt="Screenshot 2023-01-23 at 17 55 40" src="https://user-images.githubusercontent.com/116002914/214100869-1ba8c000-27ef-4ced-9049-61b224576733.png">
---
<img width="931" alt="image" src="https://user-images.githubusercontent.com/116002914/214101028-aae89c8d-0e7a-47b4-b509-1ca303f97a8c.png">
---
<img width="926" alt="image" src="https://user-images.githubusercontent.com/116002914/214101124-9841382d-317d-4498-a001-0391f4c293c1.png">
---
<img width="920" alt="image" src="https://user-images.githubusercontent.com/116002914/214101365-160b50bc-0464-4264-96ac-1879d2e48e21.png">

### AFTER - Mobile
<img width="715" alt="Screenshot 2023-01-23 at 17 58 23" src="https://user-images.githubusercontent.com/116002914/214101540-b31ec140-93cb-4e57-b570-44bea1c2cbbc.png">
---
<img width="670" alt="image" src="https://user-images.githubusercontent.com/116002914/214101672-e880ee54-37c8-4619-9504-928e275fdea9.png">
---
<img width="678" alt="image" src="https://user-images.githubusercontent.com/116002914/214101817-5c1648bf-b4ba-4920-aa1d-1bf961fd926c.png">
---
<img width="603" alt="Screenshot 2023-01-23 at 18 00 04" src="https://user-images.githubusercontent.com/116002914/214101977-ba336121-cc0c-4f98-abf7-7478e5841fdc.png">

2023-01-24 10:45 UTC, VWSCoronaDashboard26 reviewed
I salute the elegant solution and the amazing clean up that followed. Great stuff! 🙌🏻 

Still some minor comments and a `TODO` left, but other than that it looks really good.

2023-01-24 10:45 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/behavior/behavior-per-age-group-tile.tsx
> +                  fourthColumn: '',
Would it help to add a comment stating that this `fourthColumn` text is left empty intentionally because it it mainly used for spacing purposes?

This comment also applies to the other instances in this pull request.

2023-01-24 10:45 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/behavior/behavior-per-age-group-tile.tsx
> +              <NarrowTable headerText="Corona adviezen" tableData={requiredData} percentageData={percentageData} />
I think we'd rather use a Sanity key for `headerText`.

2023-01-24 10:45 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/behavior/behavior-table-tile.tsx
> +            <Text variant="label1" color="gray7">
Let's use `color={colors.gray7}` here and on lines 69 and 76.

2023-01-24 10:45 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/behavior/components/behavior-icon-with-label.tsx
> +      <Box minWidth="32px" color="black" paddingRight={space[2]} display="flex">
Let's use `color={colors.black}` here and on line 35.

2023-01-24 10:45 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/behavior/components/behavior-trend.tsx
> +      <Trend color={colors.black} hasMarginRight={hasMarginRight || false}>
Nitpicky comment, but how about instead of falling back to `false` if `hasMarginRight` is undefined, we assign `false` as a default value for the parameter? In that case,

2023-01-24 10:45 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/variants/variants-table-tile/components/percentage-bar-with-number.tsx
> +    <Box display="flex" alignItems="center" pr={{ _: 0, sm: 2, lg: 4, xl: 5 }} spacingHorizontal={2}>
Nitpicky comment, but you could also refactor `pr` to `paddingRight` if you'd like.

2023-01-24 10:45 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/variants/variants-table-tile/components/shared-table-components.tsx
> +  padding: ${({ hasPaddingRight }) => (hasPaddingRight ? `${space[3]} ${space[3]} ${space[3]} ${space[0]}` : `${space[3]} ${space[0]}`)};
This feels a bit tricky: we're applying `padding: 1.125rem 1.125rem 1.125rem 0` as styles when `hasPaddingRight` evaluates to `true`. However, the aforementioned styles apply padding styles around the entire element _except_ on the left side if the cell?

2023-01-24 12:25 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/age-groups/age-group.tsx
> +      <InlineText variant="label1">{`${yearOfBirthRange}${peopleInAgeGroup ? `: ${totalText}` : ''}`}</InlineText>
Why the check here for peopleInAgeGroup? Can't the check be done at line 19? where peopleInAgegroup is used...

2023-01-26 10:51 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/percentage-bar.tsx
> +  backgroundColor = backgroundStyle === 'normal' ? backgroundColor ? backgroundColor : 'gray2' : backgroundColor;
Done

2023-01-26 11:10 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/age-groups/age-group.tsx
> +export function AgeGroup({ range, peopleInAgeGroup, birthYearRange }: AgeGroupProps) {
Done

2023-01-26 11:11 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/age-groups/age-group.tsx
> +  birthYearRange: string;
Done

2023-01-26 11:12 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/tables/components/wide-percentage-data.tsx
> +              percentage={typeof percentageDataPoint.percentage.value === 'number' ? percentageDataPoint.percentage.value : parseFloat(percentageDataPoint.percentage.value)}
Done

2023-01-26 11:13 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/tables/components/wide-percentage.tsx
> +      <Box minWidth="10px" width="10px" height="10px" backgroundColor={color} borderRadius="50%" mr={2} />
Done

2023-01-26 11:13 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/tables/components/wide-percentage.tsx
> +interface PercentageWideNumberProps {
Doen

2023-01-26 11:14 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/tables/logic/get-percentage-data.ts
> +  dataset: any[], // TODO:AP - figure out how to properly type this
This is outdated as the comment has been addressed. Ill go ahead and resolve this.

2023-01-26 11:14 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/tables/logic/get-percentage-data.ts
> +    return percentage !== null ? `${formatPercentage(percentage)}%` : noDataText;
This has also been addressed and the file in question has been refactored. Ill go ahead an resolve this.

2023-01-26 11:15 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/behavior/behavior-per-age-group-tile.tsx
> +                  fourthColumn: '',
Doooooooone

2023-01-26 11:16 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/behavior/behavior-per-age-group-tile.tsx
> +              <NarrowTable headerText="Corona adviezen" tableData={requiredData} percentageData={percentageData} />
Good catch

2023-01-26 11:21 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/behavior/behavior-per-age-group-tile.tsx
> +              <NarrowTable headerText="Corona adviezen" tableData={requiredData} percentageData={percentageData} />
Done

2023-01-26 11:22 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/behavior/behavior-table-tile.tsx
> +            <Text variant="label1" color="gray7">
Done

2023-01-26 11:23 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/behavior/components/behavior-icon-with-label.tsx
> +      <Box minWidth="32px" color="black" paddingRight={space[2]} display="flex">
Done

2023-01-26 11:24 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/behavior/components/behavior-trend.tsx
> +      <Trend color={colors.black} hasMarginRight={hasMarginRight || false}>
Done

2023-01-26 11:25 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/variants/variants-table-tile/components/percentage-bar-with-number.tsx
> +    <Box display="flex" alignItems="center" pr={{ _: 0, sm: 2, lg: 4, xl: 5 }} spacingHorizontal={2}>
Done

2023-01-26 11:27 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/variants/variants-table-tile/components/shared-table-components.tsx
> +  padding: ${({ hasPaddingRight }) => (hasPaddingRight ? `${space[3]} ${space[3]} ${space[3]} ${space[0]}` : `${space[3]} ${space[0]}`)};
Yeah so in one case we need padding on the right, in the other case we don't. I've changed `space[0]` to `0` now though.

2023-01-26 11:29 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/age-groups/age-group.tsx
> +      <InlineText variant="label1">{`${yearOfBirthRange}${peopleInAgeGroup ? `: ${totalText}` : ''}`}</InlineText>
Done

2023-01-26 11:32 UTC, VWSCoronaDashboard28 reviewed
@VWSCoronaDashboard26 and @VWSCoronaDashboard18 I have applied the changes required from your feedback. Some comments which were outdated at the time I went through them were already marked as resolved. I've left the rest unresolved for you to resolve them yourselves if you are happy with the changes.

2023-01-26 14:41 UTC, VWSCoronaDashboard21 requested changes

2023-01-26 14:41 UTC, VWSCoronaDashboard21 commented on packages/app/src/domain/behavior/components/behavior-icon-with-label.tsx
> +      <Box minWidth="32px" color={colors.black} paddingRight={space[2]} display="flex">
You could use `minWidth={space[4]}` here.

2023-01-26 14:41 UTC, VWSCoronaDashboard21 commented on packages/app/src/components/tables/components/percentage-bar-without-number.tsx
> +        <PercentageBar percentage={isNaN(percentage) ? 0 : percentage} height="8px" />
This can be converted to space value: `height={space[2]`

2023-01-26 14:41 UTC, VWSCoronaDashboard21 commented on packages/app/src/components/percentage-bar.tsx
> +  backgroundColor = backgroundStyle === 'normal' ? (backgroundColor ? backgroundColor : colors.gray2) : backgroundColor;
I think we can remove line 16 completely because on line 14, the `backgroundColor = colors.gray2` by default.

2023-01-26 14:52 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/veiligheidsregio/[code]/gedrag.tsx
>              description={text.vr.basisregels.description}
Good question, Its separated on purpose. The titles of the graph will be the same therefore they are shared (as it is the same graph) however, the descriptions could be different (and they are) given that one is on the national level and one is on the VR level.

2023-01-26 14:52 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/gedrag.tsx
>              description={textNl.basisregels.description}
Same comment as above: Good question, Its separated on purpose. The titles of the graph will be the same therefore they are shared (as it is the same graph) however, the descriptions could be different (and they are) given that one is on the national level and one is on the VR level.

2023-01-26 14:55 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/variants/variants-table-tile/components/percentage-bar-with-number.tsx
> +    <Box display="flex" alignItems="center" paddingRight={{ _: 0, sm: 2, lg: 4, xl: 5 }} spacingHorizontal={2}>
Done

2023-01-26 14:55 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/behavior/components/behavior-icon-with-label.tsx
> +      <Box minWidth="32px" color={colors.black} paddingRight={space[2]} display="flex">
Done

2023-01-26 14:56 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/tables/components/percentage-bar-without-number.tsx
> +        <PercentageBar percentage={isNaN(percentage) ? 0 : percentage} height="8px" />
Done

2023-01-26 14:59 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/percentage-bar.tsx
> +  backgroundColor = backgroundStyle === 'normal' ? (backgroundColor ? backgroundColor : colors.gray2) : backgroundColor;
Nice one, done!

2023-01-27 13:15 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/behavior/components/behavior-icon-with-label.tsx
> +      <Box minWidth="32px" color="black" paddingRight={space[2]} display="flex">
I think you might've forgotten line 35.

2023-01-27 13:18 UTC, VWSCoronaDashboard26 approved these changes
Pre-approving, but one very minor comment has been left as unresolved as it might've been forgotten. :shipit:

2023-01-31 08:54 UTC, VWSCoronaDashboard21 approved these changes

2023-01-31 10:28 UTC, merged