feature/COR-1380-missing-sanity-keys
minvws/nl-covid19-data-dashboard pull request #4646
Opened 2023-02-06 11:06 UTC by VWSCoronaDashboard26

## Summary

* updated 'Positive tests' pages on NL and VR to receive GGD graph titles from Sanity rather than hardcoded values;
* added Sanity keys for NL and VR
* updated graphs to use new toggle logic introduced as part of COR-1275 for consistency purposes;
* cleaned up because of consistency changes;

### Screenshots
Screenshots cover only the NL scope, yet these changes have also been applied for VR. GM does not contain these toggle-able graphs. Screenshots show the Sanity key paths.

#### Before
<img width="800" alt="image" src="https://user-images.githubusercontent.com/107395524/216955781-09d4b3ce-c172-4939-8fb6-8db7b0a922c7.png">

#### After
<img width="800" alt="image" src="https://user-images.githubusercontent.com/107395524/216955550-e6361ac1-1430-412b-87a1-0a4047181620.png">

2023-02-08 09:33 UTC, VWSCoronaDashboard21 requested changes

2023-02-08 09:33 UTC, VWSCoronaDashboard21 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +import { ChartTile, ChoroplethTile, Divider, DynamicChoropleth, InView, Markdown, PageInformationBlock, TileList, TimeSeriesChart } from '~/components';
As mentioned in the Code conventions, we aim to stop using barrel files.

2023-02-08 09:33 UTC, VWSCoronaDashboard21 commented on packages/app/src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +import { ChartTile, ChoroplethTile, Divider, DynamicChoropleth, InView, Markdown, PageInformationBlock, TileList, TimeSeriesChart } from '~/components';
As mentioned in the Code conventions, we aim to stop using barrel files.

2023-02-08 10:35 UTC, VWSCoronaDashboard21 submitted a review, later dismissed
LGTM!

2023-02-08 12:44 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
>  import { colors, NlTestedOverallValue, TimeframeOption, TimeframeOptionsList } from '@corona-dashboard/common';
We don't use barrel files anymore. Maybe split this line in separate lines.

2023-02-08 12:46 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
>  import { GNumberBarChartTile, InfectedPerAgeGroup } from '~/domain/tested';
See earlier comment about the barrel files.

2023-02-08 12:47 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
>  import { replaceComponentsInText, replaceVariablesInText, useReverseRouter } from '~/utils';
See earlier comment about the barrel files.. And this goes for the whole PR...

2023-02-09 07:59 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
>  import { colors, NlTestedOverallValue, TimeframeOption, TimeframeOptionsList } from '@corona-dashboard/common';
These imports come from an entirely different package, meaning we would have to adjust the loader to facilitate this. I would personally argue that that is beyond the scope of this ticket and should be picked up in its own ticket if desired. What do you think?

2023-02-09 08:36 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
>  import { GNumberBarChartTile, InfectedPerAgeGroup } from '~/domain/tested';
Appropriate changes have been applied. Please feel free to resolve this conversation if approved.

2023-02-09 08:37 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
>  import { replaceComponentsInText, replaceVariablesInText, useReverseRouter } from '~/utils';
Appropriate changes have been applied. Please feel free to resolve this conversation if approved.

2023-02-09 10:25 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
>  import { colors, NlTestedOverallValue, TimeframeOption, TimeframeOptionsList } from '@corona-dashboard/common';
Technically I think it is a barrel file, but I'm not sure if we would want to do it this way... But then the pros and cons wouldn't change with importing from outside the current package...
For now, I think it's up to you to adjust or not. And I would be fine with either one of them. And you could resolve this when you choose not to do it. Or let me now when you choose the first option and adjusted it.

2023-02-09 10:27 UTC, VWSCoronaDashboard18 approved these changes
Great PR!

2023-02-09 11:12 UTC, VWSCoronaDashboard28 approved these changes

2023-02-09 11:21 UTC, VWSCoronaDashboard27 approved these changes

2023-02-09 13:00 UTC, merged