magic numbers - part 14 (left over and check branch)
minvws/nl-covid19-data-dashboard pull request #4647
Opened 2023-02-06 14:41 UTC by VWSCoronaDashboard18

😅

2023-02-07 12:24 UTC, VWSCoronaDashboard26 requested changes

2023-02-07 17:18 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +  color: black;
THanks for pointing out this improvement. I Adjusted it, do you think this is solved? please resolve the conversation

2023-02-07 17:19 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
>    padding-right: ${asResponsiveArray({ _: '3px', xs: '24px' })};
No, you are correct, It was causing some problems. I reverted it to media queries.
If you are oke with the solution, please resolve the comment.

2023-02-08 09:19 UTC, VWSCoronaDashboard26 approved these changes

2023-02-08 09:56 UTC, VWSCoronaDashboard21 requested changes

2023-02-08 09:56 UTC, VWSCoronaDashboard21 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +import { Markdown, KpiValue, KpiTile } from '~/components';
We aim to avoid using barrel files.

2023-02-08 09:56 UTC, VWSCoronaDashboard21 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +    padding-left: 24px;
I think the padding is incorrect on the different break points, compared to production. Please have a look at this.

2023-02-08 10:15 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/icon-button.tsx
> +  padding: ${({ padding }) => (padding ? `${padding}px` : '0')};
Couldn't you just use `0` as an integer for the false scenario for `padding`? 🤔

2023-02-08 10:17 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +    padding-left: 24px;
I would also consider refactoring padding to `padding: 0 24px` or `padding-inline: 24px`

2023-02-08 10:18 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +  padding-right: 3px;
Lots of padding styles, as I understand it, this could just be `padding: 24px 3px`?

2023-02-08 10:19 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +    padding-right: 24px;
Similar comment here, I would consider refactoring padding to `padding-inline: 24px`

2023-02-08 10:21 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/kpi-value.tsx
> +    <Box marginBottom={isDefined(difference) ? space[3] : '0'}>
I think the value can be `0` as an integer in the false scenario.

2023-02-08 10:21 UTC, VWSCoronaDashboard28 requested changes
Please see my comments

2023-02-08 12:13 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +import { Markdown, KpiValue, KpiTile } from '~/components';
Thanks for noticing, It's adjusted, please resolve?

2023-02-08 12:19 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +    padding-left: 24px;
Thanks for noticing, It's adjusted, please resolve?

2023-02-08 12:19 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/icon-button.tsx
> +  padding: ${({ padding }) => (padding ? `${padding}px` : '0')};
Thanks for noticing, It's adjusted, please resolve?

2023-02-08 12:19 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +  padding-right: 3px;
Thanks for noticing, It's adjusted, please resolve?

2023-02-08 12:20 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +  padding-right: 3px;
Thanks for noticing, I didn't know this syntax, thanks! It's adjusted, please resolve?

2023-02-08 12:20 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/vaccine/vaccine-coverage-tile/vaccine-coverage-tile.tsx
> +    padding-right: 24px;
Thanks for noticing, I didn't know this syntax, thanks! It's adjusted, please resolve?

2023-02-08 12:21 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/kpi-value.tsx
> +    <Box marginBottom={isDefined(difference) ? space[3] : '0'}>
Thanks for noticing, It's adjusted, please resolve?

2023-02-08 12:55 UTC, VWSCoronaDashboard28 approved these changes
Looking good

2023-02-08 15:08 UTC, VWSCoronaDashboard26 approved these changes
:shipit:

2023-02-08 20:32 UTC, merged