Feature/cor 1498 vaccinations toggle button removal cherrypick
minvws/nl-covid19-data-dashboard pull request #4728
Opened 2023-04-04 13:42 UTC by VWSCoronaDashboard27

## Summary

- Removed toggle button, keys, vr connections at  [vaccine-coverage-choropleth.tsx](https://github.com/minvws/nl-covid19-data-dashboard/compare/epic/COR-1475-safety-region-removal...feature/COR-1498-vaccinations-toggle-button-removal?expand=1#diff-682a0b5666a3b5a4d56ff6f94bf6174f38abd387c77eff6d36177fb6ab1372af)
- Merged together `vaccine-coverage-choropleth_vr_and_gm.tsx` to `vaccine-coverage-choropleth.tsx `
- Removed `vaccine-coverage-choropleth_vr_and_gm.tsx`

## Screenshots
**_Before_**
<details>

  <summary>Toggle before screenshot</summary> 

<img width="931" alt="Screenshot 2023-03-29 at 13 55 27" src="https://user-images.githubusercontent.com/111750729/228528058-4d832d56-c01f-46bc-874a-6a52ca5da39b.png">

</details>

**_After_**
<details>
  <summary>Toggle after screenshot</summary> 

<img width="952" alt="Screenshot 2023-03-29 at 13 55 04" src="https://user-images.githubusercontent.com/111750729/228528120-26b1c741-3aba-4606-ad75-d78033f7fabb.png">

</details>

2023-04-04 14:00 UTC, VWSCoronaDashboard26 submitted a review, later dismissed

2023-04-05 16:40 UTC, VWSCoronaDashboard18 requested changes
See the comments on the CSV file. (The rest is awesome!)

2023-04-06 11:38 UTC, VWSCoronaDashboard26 approved these changes

2023-04-06 11:49 UTC, VWSCoronaDashboard27 commented on packages/cms/src/lokalize/key-mutations.csv
> +<<<<<<< HEAD
Done

2023-04-06 11:50 UTC, VWSCoronaDashboard27 commented on packages/cms/src/lokalize/key-mutations.csv
> +=======
Done

2023-04-06 11:50 UTC, VWSCoronaDashboard27 commented on packages/cms/src/lokalize/key-mutations.csv
> +>>>>>>> 433f97e7e (fix: merged conflicts)
Done

2023-04-06 13:39 UTC, VWSCoronaDashboard21 commented on packages/app/src/components/choropleth/logic/thresholds.ts
>      autumn_2022_vaccinated_percentage: vaccineCoveragePercentageThresholds,
Maybe out of scope, but could we also remove these thresholds?

2023-04-11 07:00 UTC, VWSCoronaDashboard21 approved these changes
Looks good to me!

2023-04-11 09:07 UTC, merged