bugfix/COR-1555-fix-whitespace-add-titles
minvws/nl-covid19-data-dashboard pull request #4735
Opened 2023-04-12 10:15 UTC by VWSCoronaDashboard21

## Summary

* Fixed whitespace
* Added titles above dropdown
* Created new Sanity keys for titles
* On National and Municipality level.

## Screenshots
#### Before
<details>
<summary>Toggle before screenshots</summary>

</details>

#### After
<details>
<summary>Toggle after screenshots</summary>

</details>

2023-04-12 11:36 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth.tsx
> +                <BoldText>{text?.vaccinationKindLabel}</BoldText>
It looks like the labels for the select boxes here are optional. If that is indeed the case, then I would wrap the `BoldText` element in a guard (i.e. for example: `text?.vaccinationKindLabel && ...`). The other options is to make these labels mandatory but I'm not sure if they can be mandatory or not.

2023-04-12 11:37 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth.tsx
> +                <BoldText>{text?.ageGroupLabel}</BoldText>
Same comment as above about `ageGroupLabel` being optional.

2023-04-12 11:42 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth.tsx
> +    flex: 1 0;
Not blocking, but maybe nice for readability - could you add some spaces between style declarations. So below `flex: 1 0;` and between the two media queries.

2023-04-12 11:43 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth.tsx
> +const SelectBoxes = styled(Box)`
A lot of the properties in the styled component here could be directly applied to the `<SelectBoxes>` component you have on line 68. I believe everything except for `column-gap` and `row-gap` can be applied as a prop on the `<SelectBoxes>` component directly. 

This is not a blocking comment, as your code works perfectly fine this way as well. Just something to consider given that the box component allows us to add most styling props directly on it.

2023-04-12 11:44 UTC, VWSCoronaDashboard28 requested changes
Please see my comments.

2023-04-12 15:09 UTC, VWSCoronaDashboard21 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth.tsx
> +                <BoldText>{text?.vaccinationKindLabel}</BoldText>
Thanks, as discussed, I have wrapped the `BoldText` in a guard.

2023-04-12 15:12 UTC, VWSCoronaDashboard21 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth.tsx
> +const SelectBoxes = styled(Box)`
As discussed, I have removed the `SelectBoxes` styled component and added the props to a `Box` component on line 67, this cleans it up nicely.

2023-04-13 07:32 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth.tsx
> +            <Box display="grid" gridTemplateColumns={{ _: '1 fr', lg: 'repeat(2, 1fr)' }} gridGap={{ _: '24px', lg: '${space[2]}' }} margin="24px 0" minWidth="100%">
There's a tiny mistake on this line: the `lg` value of `gridGap` is a string value which, seemingly, interpolates the value of `space[2]` into the string. However, you are using single quotes (`'`) instead of backticks, meaning this format is incorrect. This will result in the value of `24px` always being applied. You can resolve this by either converting the quotes to backticks or simplifying the value as a whole: `... lg: space[2] ...`.

2023-04-13 07:52 UTC, VWSCoronaDashboard28 approved these changes
Approved but please see @VWSCoronaDashboard26's comment.

2023-04-13 07:53 UTC, VWSCoronaDashboard18 reviewed
I have reviewed and separately from the comment Luuk made, it looks great!
I'm not approving because the approval is discarded after a new commit.

2023-04-13 07:55 UTC, VWSCoronaDashboard21 commented on packages/app/src/domain/vaccine/vaccine-coverage-choropleth.tsx
> +            <Box display="grid" gridTemplateColumns={{ _: '1 fr', lg: 'repeat(2, 1fr)' }} gridGap={{ _: '24px', lg: '${space[2]}' }} margin="24px 0" minWidth="100%">
Sharp, I have adjusted this.

2023-04-13 07:55 UTC, VWSCoronaDashboard28 approved these changes

2023-04-13 07:59 UTC, VWSCoronaDashboard18 approved these changes
Great job! Here is a approval!

2023-04-13 08:03 UTC, VWSCoronaDashboard26 approved these changes

2023-04-13 11:35 UTC, merged