feat: COR-1547 archived National and Municipalities Positive tests pages
minvws/nl-covid19-data-dashboard pull request #4751
Opened 2023-04-19 09:25 UTC by VWSCoronaDashboard27

## Summary
# Done
- Place on National and Municipalities _"Positive Tests"_ pages in the archived section in [nl-layout.tsx](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1547-archiving-positive-tests-page?expand=1#diff-28e390aba8b17946ab0b7651888ae13110a8655693631325907494237223eac8) and [gm-layout.tsx](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1547-archiving-positive-tests-page?expand=1#diff-099a92d67d995d8dfcb0c40af083d67b55ab8f93ff9c597b3fb06dbd229c65f1).
- Change sub-title of "Positive Tests"  page _"Ontwikkeling van het virus"_ => _**"Gearchiveerde pagina's"**_  on National and Municipalities levels.
- Added right under the introduction of the page - a grey notification bar, to indicate the page is archived on National and Municipalities levels.
- Remove first graph _"Zelfgerapporteerde positieve coronatestuitslagen"_ from the archived page, as this graph will still be displayed at the new _"Testen"_ page on National level.
- Adjusted the margin between title < - > toggle and toggle < - > text both to be 24 px.
- Removed the _"Gearchiveerde grafieken"_ section with button and  kept the _"Positieve testen groeigetal"_   graph that appeared after clicking. 
- Adjusted accordingly and renamed all connected schemas files.
- VR connections was removed from NL [positief-geteste-mensen.tsx](https://github.com/minvws/nl-covid19-data-dashboard/compare/feature/COR-1547-archiving-positive-tests-page?expand=1#diff-8e7646c3094376fe95f9e858441ab57b1b626ae513deadc0e9fa0c70d2651006)

## In edition
- **Grey notification bars** on NL level at _"Positieve testen groeigetal"_ and _"Positieve GGD tests over time"_ sections can be removed by communication.

2023-04-19 13:18 UTC, VWSCoronaDashboard28 reviewed
Please see my comments

2023-04-19 13:18 UTC, VWSCoronaDashboard28 commented on packages/app/schema/gm/tested_overall_archived_20230417.json
> +  "$id": "tested_overall_archived_20230417.json",
Why is the `$id` needed? I feel like I haven't seen this added before. I could be wrong, but still curious what this does.

2023-04-19 13:18 UTC, VWSCoronaDashboard28 commented on packages/app/schema/nl/tested_overall_archived_20230417.json
> +  "title": "nl_tested_overall_archived_20230417",
In this case the `$id` that used to be there is now removed 🤔 Is this supposed to happen?

2023-04-19 13:18 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/chart-tile-toggle.tsx
> +    <Box display="flex" style={{ marginTop: '24px', marginBottom: '24px' }}>
The style here can make use of CSS shorthand properties. You could choose between:
1. `style={{ margin: '24px' 0 }}`
2. `style={{ marginBlock: '24px'}}`

Additionally, is there a specific reason for why you chose adding an inline style on the `Box`? If not then I would suggest simply adding `margin="24px 0"` to the  `Box` component here.

2023-04-19 13:18 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +
I think this empty line could be removed?

2023-04-19 13:22 UTC, VWSCoronaDashboard28 reviewed
I also noticed that the Typecheck action fails. Something to do with the warning text. Could you double check whats happening there by running `yarn typecheck` locally?

2023-04-20 09:04 UTC, VWSCoronaDashboard26 requested changes

2023-04-20 09:04 UTC, VWSCoronaDashboard26 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-04-13T07:26:08.198Z,delete,pages.positive_tests_page.shared.belangrijk_bericht,mt9hMqvnezW3fDtFvfvcu2,__
Is the addition and deletion of the same key intentional?

2023-04-20 09:49 UTC, VWSCoronaDashboard27 commented on packages/app/schema/gm/__static_values_archived_20230417.json
> +  "title": "gm_static_values_archived_20230417",
Done

2023-04-20 09:59 UTC, VWSCoronaDashboard27 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-04-13T07:26:08.198Z,delete,pages.positive_tests_page.shared.belangrijk_bericht,mt9hMqvnezW3fDtFvfvcu2,__
Nope, probably I made a mistake which I fixed later.

2023-04-20 10:04 UTC, VWSCoronaDashboard27 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +
done

2023-04-24 07:42 UTC, VWSCoronaDashboard27 commented on packages/app/schema/gm/__index.json
Changes have been reverted.

2023-04-24 07:46 UTC, VWSCoronaDashboard27 commented on packages/app/schema/gm/tested_overall_archived_20230417.json
> +      "title": "gm_tested_overall_archived_20230417_value",
Changes have been reverted

2023-04-24 07:54 UTC, VWSCoronaDashboard27 commented on packages/app/schema/gm/tested_overall_archived_20230417.json
> +  "$id": "tested_overall_archived_20230417.json",
Changes have been reverted.

2023-04-24 09:02 UTC, VWSCoronaDashboard18 commented on packages/app/schema/gm/__difference.json
> +    "tested_overall__infected_per_100k_moving_average_archived_20230417": {
Not to be nitpicky, and it's definitely non-blocking. But we usually use the date we go live with archiving as the date suffix. And this seems to be the date the code is changed.

But as I said, this is definitely nonblocking and feel free to resolve it by yourself.

2023-04-24 09:59 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +        "elements": ${getElementsQuery('gm', ['tested_overall_archived_20230417'], locale)}
These elements currently do not exist in sanity. Are the _archived elements added? Or was it unintentional? See at @VWSCoronaDashboard26 's comment about this and the timelines shared in the standup last week.

2023-04-24 10:54 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +  const hasActiveWarningTile = !!textShared.belangrijk_bericht;
`textShared.belangrijk_bericht` doesn't exist in sanity, making it impossible to show the warning.

2023-04-24 12:02 UTC, VWSCoronaDashboard27 commented on packages/app/src/components/chart-tile-toggle.tsx
> +    <Box display="flex" style={{ marginTop: '24px', marginBottom: '24px' }}>
@VWSCoronaDashboard28  The style component used here to be able to overwrite margin only for this specific toggle.

2023-04-24 12:18 UTC, VWSCoronaDashboard26 approved these changes

2023-04-24 12:36 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/chart-tile-toggle.tsx
> +    <Box display="flex" style={{ marginTop: '24px', marginBottom: '24px' }}>
I don't see this comment solved or adjusted to use the `space[2]` value.

2023-04-24 13:39 UTC, VWSCoronaDashboard28 approved these changes
Two small additional comments

2023-04-24 13:39 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +  const hasActiveWarningTile = !!textShared.warning;
Nitpicky/non-blocking, but this is a very small.short condition, I don't see the need to abstract/extract `!!textShared.warning` to the `hasActiveWarningTile` variable. 

You could just:
```
{!!textShared.warning && <WarningTile isFullWidth message={textShared.warning} variant="informational" />}
```

2023-04-24 13:39 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +  const hasActiveWarningTile = !!textShared.warning;
Same comment as before, seems unnecessary to extract this condition to its own variable.

2023-04-24 13:39 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/chart-tile-toggle.tsx
> +    <Box display="flex" style={{ marginTop: '24px', marginBottom: '24px' }}>
I'm slightly confused as the file on which my comments were made is no longer a part of this PR?

2023-04-24 13:41 UTC, VWSCoronaDashboard27 commented on packages/app/src/components/chart-tile-toggle.tsx
> +    <Box display="flex" style={{ marginTop: '24px', marginBottom: '24px' }}>
@VWSCoronaDashboard28  After discussion with design changes have been reverted back to 16px.

2023-04-24 13:58 UTC, VWSCoronaDashboard25 approved these changes
Looks good to me!

2023-04-24 13:59 UTC, VWSCoronaDashboard27 commented on packages/app/src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +  const hasActiveWarningTile = !!textShared.warning;
done.

2023-04-24 14:07 UTC, VWSCoronaDashboard26 approved these changes

2023-04-24 14:32 UTC, VWSCoronaDashboard18 approved these changes
Nice! Let's go!

2023-04-24 14:43 UTC, merged