feature/COR-1529-advices-section-homepage
minvws/nl-covid19-data-dashboard pull request #4760
Opened 2023-05-02 16:29 UTC by VWSCoronaDashboard26

## Summary

* added advice component schemas for Sanity;
* updated Sanity desk structure;
* added Sanity query and types for fetching the topical page's new advice section;
* added Advice component;

### Screenshots
#### Before
<details>
<summary>Toggle before screenshots</summary>

![COR-1529_before_desktop](https://user-images.githubusercontent.com/107395524/235727462-dc15fe69-a7ef-420d-839b-409f9c5cfbd6.png)
![COR-1529_before_mobile](https://user-images.githubusercontent.com/107395524/235727477-83c4abab-cfc6-4316-bcf9-acfce2ae19a1.png)
</details>

#### After
<details>
<summary>Toggle after screenshots</summary>

![COR-1529_after_desktop](https://user-images.githubusercontent.com/107395524/235727419-271698c8-2a0c-4a97-a4eb-99b0bdd69d95.png)

<img width="373" alt="COR-1529_after_mobile" src="https://user-images.githubusercontent.com/107395524/235727482-a45a5315-8332-4ce7-bb4c-e5031ada6e7e.png">
</details>

2023-05-04 07:57 UTC, VWSCoronaDashboard28 approved these changes

2023-05-04 07:57 UTC, VWSCoronaDashboard28 commented on packages/cms/src/schemas/topical/advice-link.ts
> +  title: "'Adviezen' sectie link",
Why is `Adviezen` in single quotes? 🤔

2023-05-04 09:03 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/advice.tsx
> +        flexDirection={{ _: 'column', sm: 'row' }}
It looks like the image is not centered on the mobile viewport.
Which I would expect to happen.

![Screenshot 2023-05-04 at 11 03 09](https://user-images.githubusercontent.com/93984341/236159103-b2be8a72-b570-479d-9870-d0e6e11908ad.png)

2023-05-04 09:06 UTC, VWSCoronaDashboard18 commented on packages/cms/src/schemas/topical/advice.ts
> +      of: [{ type: 'reference', to: { type: 'adviceLink' } }],
Is there a reason you created a new specific link document? There is a document of type link that also has proper validation.

2023-05-04 09:40 UTC, VWSCoronaDashboard18 reviewed
I've added some nonblocking comments, as everything works as intended. But there are things that could be improved.

There is something I would suggest would be blocking: The not-center alignment of the image on mobile.

Feel free tor resolve the others, or if it is solved.

2023-05-04 09:40 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/index.tsx
> +        <Spacer marginBottom={{ _: space[5], md: space[6] }} />
Was this change intentional? It doesn't appear in the designs and also not on other pages. The distance between other sections on the page is also 'just' space[5], unlike the distance between themes where it is [6].

Feel free to resolve this yourself, as I understand the inconsistency.

2023-05-04 09:40 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/advice.tsx
> +    display: flex;
Why add a display flex? What's wrong with inline?

2023-05-04 09:40 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/advice.tsx
> +    align-items: center;
Why align-items? There is no need for alignment here and should work out-of-the-box.

2023-05-05 15:55 UTC, VWSCoronaDashboard25 approved these changes
Still interested for the replies to some of the earlier comments by @VWSCoronaDashboard18.

But assuming a satisfying response to those comments and assuming that Design agrees with the current mobile view solution, I'll approve.

2023-05-05 15:55 UTC, VWSCoronaDashboard25 commented on packages/cms/src/schemas/topical/advice.ts
> +      of: [{ type: 'reference', to: { type: 'adviceLink' } }],
@VWSCoronaDashboard18, for now and in the future, if you know there is another solution somewhere in the code, presumably better, please add a link to that with your comment.

You (knowing where to look) going through the effort once is better then making @VWSCoronaDashboard26  **and all interested reviewers** search for it one by one.

2023-05-06 11:20 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/advice.tsx
> +        flexDirection={{ _: 'column', sm: 'row' }}
@VWSCoronaDashboard25, that will not work. As the box doesn't have a 100% width. But line 31 as I suggested would also not work, as with would also center the Title, text, and buttons.

I would suggest removing the `<Box>` element on line 60.
Create a new styled component at the end if the file:

```
const AdviceImage = styled(SanityImage)`
  align-self: center;
`;
```

And replace the image with this styled component:

`<AdviceImage {...getImageProps(image, { defaultWidth: '300px' })} />`

2023-05-06 11:21 UTC, VWSCoronaDashboard18 commented on packages/cms/src/schemas/topical/advice.ts
> +      of: [{ type: 'reference', to: { type: 'adviceLink' } }],
Thanks #25 here is the file I was referring to:
`packages/cms/src/schemas/objects/link.ts`

2023-05-08 07:56 UTC, VWSCoronaDashboard25 commented on packages/app/src/domain/topical/components/advice.tsx
> +        flexDirection={{ _: 'column', sm: 'row' }}
Ah yes, you are right.

Another solution can be `align-self: 'center'` to the line 60 box. https://css-tricks.com/snippets/css/a-guide-to-flexbox/#aa-align-self
I don't think it needs a display flex then.

```
<Box align-self={{ _: 'center', sm: 'flex-start' }}>
```

2023-05-08 09:09 UTC, VWSCoronaDashboard26 commented on packages/app/src/pages/index.tsx
> +        <Spacer marginBottom={{ _: space[5], md: space[6] }} />
I would personally argue that this _is_ in the design and it is also not something that can be considered inconsistent as the homepage is not like any other page. This essentially balances out the spacing on either side of the new component.

I will resolve this comment for now, but please do unresolve it if you disagree.

2023-05-08 09:12 UTC, VWSCoronaDashboard26 commented on packages/app/src/queries/get-topical-structure-query.ts
> +        'url': url,
Given how the `link` type works, which I will now use according to your [suggestion](https://github.com/minvws/nl-covid19-data-dashboard/pull/4760/files/f07b6f294819d989eda872033f656470c72ee9db#r1184748915), there is no way to 'localise' internal links as far as I am aware. However, I think it is always wise to use relative links for internal URLs and absolute URLs for external URLs. This logic is also handled in the component itself.

2023-05-08 09:14 UTC, VWSCoronaDashboard26 commented on packages/cms/src/schemas/topical/advice-link.ts
> +  title: "'Adviezen' sectie link",
Adjusted this accordingly, though not in this file as it is removed due to this [comment](https://github.com/minvws/nl-covid19-data-dashboard/pull/4760/files/f07b6f294819d989eda872033f656470c72ee9db#r1184748915). Please feel free to resolve.

2023-05-08 09:20 UTC, VWSCoronaDashboard26 commented on packages/cms/src/schemas/topical/advice.ts
> +      of: [{ type: 'reference', to: { type: 'adviceLink' } }],
Good suggestion to opt with the `link` type. Feel free to resolve this conversation if you both agree on the result.

2023-05-08 09:21 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/advice.tsx
> +    align-items: center;
This is a by-product of the previous usage of `display: flex;`, so this is removed and this comment can be resolved accordingly.

2023-05-08 09:25 UTC, VWSCoronaDashboard27 approved these changes

2023-05-08 09:33 UTC, VWSCoronaDashboard25 approved these changes
Looks good to me, speaking for myself, all comments can be resolved.

2023-05-08 09:44 UTC, VWSCoronaDashboard18 reviewed
Nice! Great job!

2023-05-08 09:44 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/advice.tsx
> +}
This could be directly imported like this:


```import { Advice as AdviceProps } from '~/queries/query-types';```

2023-05-08 11:31 UTC, VWSCoronaDashboard18 submitted a review, later dismissed
Great stuff!

2023-05-08 11:31 UTC, VWSCoronaDashboard18 commented on packages/app/src/domain/topical/components/advice.tsx
> +`;
Nice! Good solution!

2023-05-08 12:47 UTC, VWSCoronaDashboard27 approved these changes

2023-05-08 15:25 UTC, VWSCoronaDashboard25 requested changes

2023-05-08 15:25 UTC, VWSCoronaDashboard25 commented on packages/app/src/domain/topical/components/advice.tsx
> +import { Advice as AdviceProps } from '~/queries/query-types';
Not too keen on using the query type as component props.

But if you really want this tight coupling, you should double down on it and do `<Advice {{...advice}} />` instead of `<Advice title={advice.title} description={advice.description} links={advice.links} image={advice.image} />`.

If that feels wrong, you should remove this tightly coupling.

2023-05-09 05:54 UTC, VWSCoronaDashboard26 commented on packages/app/src/domain/topical/components/advice.tsx
> +import { Advice as AdviceProps } from '~/queries/query-types';
I must admit that I also had my doubts about using the type of the query for the component props definition. It just _happens_ to be the exact same structure and thus can we use it. I did however, when working on this ticket, also opt to go with `<Advice {...advice} />` earlier. I reverted this after some thought and a second opinion as

* spreading the `advice` props might not always be as clear
* spreading the `advice` props will not tell you what is there on hover, forcing one to click-through to see what it takes

I agree with that using the query type might not be desirable. I will revert that change.

2023-05-09 08:25 UTC, VWSCoronaDashboard18 approved these changes
Looks great! Nice esthetic.

2023-05-09 09:02 UTC, VWSCoronaDashboard28 approved these changes

2023-05-09 13:23 UTC, VWSCoronaDashboard25 commented on packages/app/src/domain/topical/components/advice.tsx
> +import { Advice as AdviceProps } from '~/queries/query-types';
I'd argue that the first is just something we should learn to feel comfortable with because it's a common pattern to use in React, just not our project.
And the second, that's true. But you would just be piping the data through **without interacting with it**. So at the level where `<Advice ... />` is used, there is no real reason to know what it takes apart from personal interest.

2023-05-09 13:23 UTC, VWSCoronaDashboard25 approved these changes

2023-05-11 08:01 UTC, merged