COR-1660-archive-thermometer
minvws/nl-covid19-data-dashboard pull request #4818
Opened 2023-07-10 16:40 UTC by VWSCoronaDashboard29

Archived the coronadashboard thermometer to it's separate page

2023-07-10 16:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4818) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4818) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: beek<br/>:x: VWSCoronaDashboard30<br/><hr/>**beek** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=4818) it.</sub>

2023-07-11 14:12 UTC, VWSCoronaDashboard18 requested changes
Some of the comments maybe elaborated on in a separate meeting.

2023-07-17 06:24 UTC, VWSCoronaDashboard21 requested changes

2023-07-17 06:24 UTC, VWSCoronaDashboard21 commented on packages/app/src/pages/index.tsx
> +          <Spacer marginBottom={{ _: space[5], md: space[6] }} />
I think it's sufficient to have `<Spacer marginBottom={space[5]} />` here.

2023-07-17 06:24 UTC, VWSCoronaDashboard21 commented on packages/app/src/pages/landelijk/corona-thermometer.tsx
> +
Based on the design and other pages, I think there needs to be a divider added here.

2023-07-17 09:08 UTC, VWSCoronaDashboard28 reviewed
Please see my comments. I also notice some merge conflicts so those need to be fixed too.

2023-07-17 09:08 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/corona-thermometer.tsx
> +              paddingX={{ _: space[3], sm: space[4] }}
I think there may be a small misalignment with design here. If you look at the screenshot, the thermometer is narrower than the rest of the page. It should be the same width as the content in the `pageInformationBlock`. This padding should be removed, I think.
 
![image](https://github.com/minvws/nl-covid19-data-dashboard/assets/116002914/9b8055ce-abd1-4ab7-83b7-78870ad66d01)

2023-07-17 09:08 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/corona-thermometer.tsx
> +          <Box marginY={space[3]}>
This `Box` seems unnecessary given that `OrderedList` is already a styled component. You could add this margin to the styled component using `margin-block` and then get rid of this box.

2023-07-17 09:08 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/corona-thermometer.tsx
> +  css({
According to our conventions, we typically try to avoid using this `css` method. You could convert it to using the backtick notation if you'd like. This would mean you could get rid the import of `css` as well.

2023-07-17 09:08 UTC, VWSCoronaDashboard28 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-07-10T16:34:50.027Z,delete,common.choropleth_tooltip.vr.infected_locations_percentage.content,WcslWj37E82J6PAznCRyfn,__
+1

2023-07-18 06:56 UTC, VWSCoronaDashboard18 commented on packages/cms-v2/src/schemas/topical/weekly-summary-item.ts
Can it be that this change is unintentional?

2023-07-18 08:26 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/weekly-summary/topical-weekly-summary-tile.tsx
> +              <Box display="flex">
Im not sure if this needs to have a display of `flex` 🤔

2023-07-18 08:26 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/topical/components/topical-theme-header.tsx
> +        {icon && (
This check for the icon can also be reverted as the icon is no longer optional.

2023-07-18 08:26 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/corona-thermometer.tsx
> +  margin: ${space[3]} 0;
I think this should be just `margin-top` and should have a value of `space[4]` so its consistent with the section above.

2023-07-18 08:26 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/corona-thermometer.tsx
> +                    <IndicatorLevelDescription key={index} level={indicatorTexts.level as SeverityLevel} label={indicatorTexts.label} description={indicatorTexts.description} />
The last `IndicatorLevelDescription` should not have any bottom margin. It does at the moment and this is resulting in too much space below the list.

2023-07-18 08:26 UTC, VWSCoronaDashboard28 commented on packages/cms/src/lokalize/key-mutations.csv
This file still needs to be fixed before merging

2023-07-18 09:00 UTC, VWSCoronaDashboard21 commented on packages/app/src/pages/index.tsx
>              {kpiThemes.themes.map((theme) => {
On line 112 and 113, `gridColumnGap` and `gridRowGap` are deprecated. You could have a look at how it's done in the `SeverityIndicatorTile` component on how to refactor this.

2023-07-18 09:22 UTC, VWSCoronaDashboard18 commented on packages/app/src/queries/query-types.ts
Should the description on line 80 be updated as well??

2023-07-18 12:51 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/weekly-summary/topical-weekly-summary-tile.tsx
> +              <Box display="flex">
flex will break the row

2023-07-18 12:54 UTC, VWSCoronaDashboard28 submitted a review, later dismissed

2023-07-18 13:15 UTC, VWSCoronaDashboard28 approved these changes

2023-07-18 13:17 UTC, VWSCoronaDashboard21 approved these changes
Awesome job!

2023-07-18 13:18 UTC, VWSCoronaDashboard18 approved these changes
Awesome!

2023-07-18 13:48 UTC, merged