feat(COR-1690): Archived positive tests metrics
minvws/nl-covid19-data-dashboard pull request #4827
Opened 2023-07-31 10:38 UTC by VWSCoronaDashboard30

2023-07-31 11:37 UTC, VWSCoronaDashboard28 commented on packages/app/schema/archived_nl/__difference.json
I feel like the date of archival suffix might not be correct. Usually, this suffix references the next release as thats when this data would be archived.

2023-07-31 11:39 UTC, VWSCoronaDashboard28 commented on packages/app/schema/archived_nl/__index.json
> +    "g_number_archived_20220307",
For example, the date of `20220307` is in the past. As far as I can tell, this metric has not been archived before, so it should receive the date of `20230810`. It is possible I am missing some context as I am not able to access the ticket at the moment.

2023-07-31 12:00 UTC, VWSCoronaDashboard28 reviewed
Please see my comments

2023-08-01 10:17 UTC, VWSCoronaDashboard28 reviewed
I also noticed that the typecheck is failing. Seems like the issue is related to the `constants.ts` file.

2023-08-01 11:34 UTC, VWSCoronaDashboard21 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +        "elements": ${getElementsQuery('nl', ['tested_overall_archived_20230331', 'tested_ggd_archived_20230321', 'tested_per_age_group_archived_20230331'], locale)}
Next to the comment of @VWSCoronaDashboard28 , I think `tested_ggd_archived_20230321` or `tested_ggd` is not necessary.

2023-08-01 12:24 UTC, VWSCoronaDashboard27 requested changes
@VWSCoronaDashboard30 I don't see anything done on GM level in this PR

2023-08-02 10:24 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +  const dataGgdLastValue = data.tested_ggd_archived_20230321.last_value;
For clearity I would expect to have the variable name change as well. To `dataTestedOverallArchivedLastValue` and `dataTestedGgdArchivedLastValue`

2023-08-02 10:30 UTC, VWSCoronaDashboard18 requested changes
What I've seen from the separate from the comments on this PR, is that the archiving goes well...

Although I have a question left, in the ticket the GM level is mentioned as well. Is there something I'm missing about why there is no GM archiving happening in this PR?

2023-08-07 16:33 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +        "elements": ${getElementsQuery('archived_gm', ['tested_overall_archived_20230331'], locale)}
As I said on the other PR and I think is mentioned before: Be careful with this change, as this is a dangerous thing to do. As sanity is not auto-updated with the archived suffix...

2023-08-07 16:38 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/choropleth/logic/types.ts
> +export type ArchivedGmDataItem = ArchivedGmDataCollection[number];
I would advise to keep them in pairs, just like the [archivedVr PR](packages/app/src/components/choropleth/logic/types.ts).
Now they are sorted by dataItem and DataCollection. I would say sort them by Archived and current data.

2023-08-07 16:40 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +        "elements": ${getElementsQuery('archived_nl', ['tested_overall_archived_20230331', 'tested_ggd_archived_20230321', 'tested_per_age_group_archived_20230331'], locale)}
Here goes the same as my earlier comment:
Be careful with this change, as this is a dangerous thing to do. As sanity is not auto-updated with the archived suffix...

2023-08-07 16:40 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +                timelineEvents: getTimelineEvents(content.elements.timeSeries, 'tested_overall_archived_20230331'),
Here goes the same as my earlier comment:
Be careful with this change, as this is a dangerous thing to do. As sanity is not auto-updated with the archived suffix...

2023-08-07 16:41 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +                timelineEvents={getTimelineEvents(content.elements.timeSeries, 'tested_per_age_group_archived_20230331')}
Please have some focus here @VWSCoronaDashboard30  and @VWSCoronaDashboard29>

This happens across both of your open PR's

2023-08-07 16:44 UTC, VWSCoronaDashboard18 commented on packages/app/src/static-props/get-data.ts
> +  archivedVr?: (collection: VrCollection, context: GetStaticPropsContext) => T1;
Here you are still pointing to the `VrCollection` and not the `VrArchivedCollection`.

2023-08-07 16:46 UTC, VWSCoronaDashboard18 commented on packages/cli/src/schema/schema-info.ts
>    return {
Not sure how intentional this change was. But I think an extra line is very useful over here.

Non-blocking though, but nonetheless a very good effort vs. gain ratio!

2023-08-07 16:52 UTC, VWSCoronaDashboard18 commented on packages/cms/src/studio/scripts/add-chart.ts
This doesn't seem like a part of this ticket. Where is this coming from? And would it be nice for this code to have it's own PR...

2023-08-07 16:53 UTC, VWSCoronaDashboard18 commented on packages/cms/src/studio/constants.ts
> +export const RELATIVE_SCHEMA_PATH = '../../../../app/schema';
I'm not sure if this is intentional or needed. It feels like part of my comment on the add-chart.ts file

2023-08-07 16:54 UTC, VWSCoronaDashboard18 commented on packages/common/src/types/feature-flags.ts
Again, was this intentional? I'm not sure how this is related to the PR. Although it might be useful to look into the feature flag files to do a clean up..

2023-08-07 16:55 UTC, VWSCoronaDashboard18 requested changes
Good complex stuff! Although I have left some comments. I think I also included if they are non-blocking or need updating.

2023-08-08 14:53 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +  const dataGgdLastValue = data.tested_ggd_archived_20230321.last_value;
Nice! Thanks for adjusting.

2023-08-08 14:54 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/choropleth/logic/types.ts
> +export type ArchivedGmDataItem = ArchivedGmDataCollection[number];
Nice! Thanks for adjusting.

2023-08-08 14:56 UTC, VWSCoronaDashboard18 commented on packages/app/src/static-props/get-data.ts
> +  archivedVr?: (collection: VrCollection, context: GetStaticPropsContext) => T1;
Nice! Thanks for adjusting.

2023-08-08 14:56 UTC, VWSCoronaDashboard28 approved these changes

2023-08-08 14:56 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/positieve-testen.tsx
> +        "elements": ${getElementsQuery('archived_nl', ['tested_overall_archived_20230331', 'tested_ggd_archived_20230321', 'tested_per_age_group_archived_20230331'], locale)}
So i guess you also added two additional timelines since we last worked on the first one?

2023-08-08 14:57 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
> +                timelineEvents={getTimelineEvents(content.elements.timeSeries, 'tested_per_age_group_archived_20230331')}
Nice! Thanks for explaining. I think you can close this @VWSCoronaDashboard28

2023-08-08 14:57 UTC, VWSCoronaDashboard18 approved these changes
Looks awesome! Happy to have this in the release!!!

2023-08-08 15:00 UTC, VWSCoronaDashboard27 approved these changes

2023-08-08 15:00 UTC, merged