Feature/cor 1760 spacing text and arrow components
minvws/nl-covid19-data-dashboard pull request #4840
Opened 2023-08-14 06:57 UTC by VWSCoronaDashboard35

## Summary

There's now a spacing of min. 64xp.

## Motivation

To maintain a clear distance from text and the icons because the text could first overflow onto/ really close to the icon.

![MicrosoftTeams-image (3)](https://github.com/minvws/nl-covid19-data-dashboard/assets/141616488/6067fb8d-63ae-46f6-96db-b62a535d27d6)

2023-08-14 06:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4840) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4840) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=4840) it.</sub>

2023-08-14 08:15 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> -        <Box width="100%" position="relative">
![Screenshot 2023-08-14 at 10 12 06](https://github.com/minvws/nl-covid19-data-dashboard/assets/93984341/b8f17153-1cc7-476b-bdca-c3ba8c7af3e5)

It doesn't work entirely correctly right now. (In the screenshot you can see the arrow overflowing into the padding)

2023-08-14 08:19 UTC, VWSCoronaDashboard18 requested changes
See the comments

2023-08-14 11:56 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> -        <Box width="100%" position="relative">
My appologies, I have edited my description. The changes in the collapsible-section affect this
![image](https://github.com/minvws/nl-covid19-data-dashboard/assets/141616488/2d2326ee-4036-4f74-81c0-1bf22bc8f38e)

2023-08-14 12:53 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <Box pr={5}>
I'm not quite sure how else  I would go about this one. 
![image](https://github.com/minvws/nl-covid19-data-dashboard/assets/141616488/0dc4ab6a-42b1-413b-934d-7d2477971364)

2023-08-15 08:11 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> -        <Box width="100%" position="relative">
We stopped the use of `magic numbers`. You can check the documentation on this one.

And I think you mixed up the screenshot. As this screenshot is not part of this piece of code.

2023-08-15 08:13 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/page-information-block/page-information-block.tsx
>                    <PageInformationButton href={pageInformationHeader.dataExplained.link}>
It is also happening at the FAQ section
 
![Screenshot 2023-08-15 at 10 13 00](https://github.com/minvws/nl-covid19-data-dashboard/assets/93984341/62fc1cff-ba77-4b7c-8632-10e88d9211f8)

2023-08-15 08:13 UTC, VWSCoronaDashboard18 requested changes
Some comments left.

2023-08-15 09:58 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <Box pr={5}>
You could also opt to convert this entire button into a flexbox or a grid.

2023-08-15 13:49 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
>                    <PageInformationButton href={pageInformationHeader.dataExplained.link}>
I understood that as well, but I have changed stylings for the button so the changes will be propagated to it as well.

2023-08-15 15:36 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <Box pr={5}>
I took the grid approach for this.

2023-08-15 15:41 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <ChevronRight class="arrow" />
This class is not being used and also `class` is a reserved keyword and cannot be used in React like this. What you want instead is `className`.

2023-08-15 15:41 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +
Each media query here has this extra empty line within the block.

2023-08-15 15:41 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +    margin-top: auto:
Type on this line: `:`

2023-08-15 15:42 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <Box pr={5}>
Any particular reason for choosing one over the other?

2023-08-16 11:58 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <ChevronRight class="arrow" />
I have removed this since I don't need it anymore.

2023-08-16 11:58 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +    margin-top: auto:
Good catch!

2023-08-16 11:58 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +
It's consistent now.

2023-08-17 11:13 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <Box pr={5}>
Since the title and text are two separate components positioned vertically under each other and the svg is positioned horizontally I went for Grid.

2023-08-18 07:35 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <Box pr={5}>
Please see my message in our direct channels.

2023-08-18 08:27 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +                    <Box pr={5}>
Thank you for your message. I have considered you changes and used the flexbox approach to maintain the consistency.

2023-08-18 08:39 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +    margin-right: ${space[5]};
Is this `margin-right` actually needed? It doesn't seem to be doing much on larger screens and on smaller screens it creates a very large gap. 

If it is really needed, I would suggest changing the `div` to a `Box` and adding the margin as a prop - `marginRight`.

2023-08-18 09:08 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +    margin-right: ${space[5]};
The box approach is something I already attemted. I think you can see it in the commit history.

2023-08-18 09:38 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/collapsible/collapsible-section.tsx
> -        <Box width="100%" position="relative">
I have removed the use of the magic number.

2023-08-21 07:37 UTC, VWSCoronaDashboard28 approved these changes

2023-08-22 07:52 UTC, VWSCoronaDashboard28 submitted a review, later dismissed

2023-08-22 08:55 UTC, VWSCoronaDashboard28 commented
> On mobile, I still have problems with the arrow not having space to the left.
> 
> ![Screenshot 2023-08-22 at 10 38 37](https://user-images.githubusercontent.com/93984341/262289468-b2f5f640-8f4a-4d5a-b534-2a2c992d279e.png)
> 
> And I don't see why for the same issue, you are creating two solutions. (on padding-right on the collapsible, and a flexbox on the page information block items) But this last comment is non-blocking.

This is a very specific edge case, one which could be deemed totally unrealistic because there are very low chances of COM using single letters to form the copy of their buttons. While I do agree it's good to take edge cases into consideration, this is quite an extreme edge case. The screenshot below is a little more realistic, in my opinion, and it looks just fine.

Additionally, your comment is non-blocking however you are still requesting changes. 

![image](https://github.com/minvws/nl-covid19-data-dashboard/assets/116002914/838c4957-6b08-4507-810c-2395e14f7636)

2023-08-23 15:24 UTC, VWSCoronaDashboard18 commented
Let me say it like this: there needs to be a gap between the elements! Not a visual gap between the text and the SVG. There is a mayor difference in those two things.

2023-08-24 07:48 UTC, VWSCoronaDashboard28 approved these changes

2023-08-24 14:07 UTC, VWSCoronaDashboard18 approved these changes
Awesome!

2023-08-25 07:01 UTC, merged