Feature/cor 1713 spacing and sizing archived title
minvws/nl-covid19-data-dashboard pull request #4841
Opened 2023-08-14 07:01 UTC by VWSCoronaDashboard35

## Summary

Chaining the sizing of the title and moving one article section to the bottom

## Motivation

To maintain a clear hierarchy structure of the section on the pages

![image](https://github.com/minvws/nl-covid19-data-dashboard/assets/141616488/d5d697da-f3cc-44c0-b55e-be4ddd4ce3c7)

2023-08-14 07:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4841) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4841) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=4841) it.</sub>

2023-08-14 07:20 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/page-information-block/components/header.tsx
> +      <Heading level={level ? level : 1} hyphens="auto" css={css({ gridArea: 'title' })}>
Instead of a ternary return, it's a good idea to set a default value at line 23 to level. So you don't have to check if it exists.

2023-08-14 07:34 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +          <Divider style={{ marginBottom: space[3] }} />
Please apply this within the divider. And use a property to apply this margin bottom

2023-08-14 08:09 UTC, VWSCoronaDashboard18 requested changes
See my other comments

2023-08-14 08:39 UTC, VWSCoronaDashboard30 requested changes

2023-08-14 08:39 UTC, VWSCoronaDashboard30 commented on packages/app/src/pages/landelijk/sterfte.tsx
> +          <Divider style={{ marginBottom: space[3] }} />
I believe the spacing should also be bigger.

2023-08-14 11:26 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/components/header.tsx
> +      <Heading level={level ? level : 1} hyphens="auto" css={css({ gridArea: 'title' })}>
I have added a devault value for this and removed the ternary return.

2023-08-14 11:40 UTC, VWSCoronaDashboard35 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +          <Divider style={{ marginBottom: space[3] }} />
Got it. I have passed the margin as a prop now.

2023-08-14 11:40 UTC, VWSCoronaDashboard35 commented on packages/app/src/pages/landelijk/sterfte.tsx
> +          <Divider style={{ marginBottom: space[3] }} />
Good catch! I have also changed this one.

2023-08-14 13:45 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/divider.tsx
> +    marginBottom: `${marginBottom} !important`,
Why do you use the `!important`? I don't think we need it here...

2023-08-14 13:48 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +          <Divider marginBottom={space[4]} />
This wasn't exactly what I meant. I think you should use a boolean to indicate the different usage of the Divider. For example: `nextBlockIsATitleBlock`, or something that indicates why it has a smaller margin or what use it is for.

2023-08-14 13:49 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/sterfte.tsx
> +          <Divider marginBottom={space[4]} />
The same goes for here!

2023-08-14 13:49 UTC, VWSCoronaDashboard18 requested changes
See my comments

2023-08-15 07:59 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +  headingLevel,
A new prop is not necessary for this. Essentially, you want a different heading level when the `PageInformationBlock` is used to render the archived section toggle. You could probably just use the `showArchivedToggleButton` variable instead to determine the size of the title.

2023-08-15 07:59 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +          <Divider marginBottom={space[4]} />
This divider appears to be used before a `PageInformationBlock` when it's not the first component on a page. I see that you have added a new prop and used this new prop on two pages. If you see the screenshot below, you will see that this divider is also used on a few other pages, without this new prop you have added. 

Could you double-check that this does not cause an inconsistency between pages? I.e all the divider's should be used the same way for consistency.

![image](https://github.com/minvws/nl-covid19-data-dashboard/assets/116002914/2a8254ac-8139-4d6c-977e-520d1f2b4e1e)

2023-08-15 08:00 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/divider.tsx
> +  marginBottom?: any;
+1

2023-08-15 08:02 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +          <Divider marginBottom={space[4]} />
Adding to my comment, if the other pages also need to be updated, then the `margin-bottom` is not needed as a prop.

2023-08-15 08:23 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +          <Divider style={{ marginBottom: space[3] }} />
See my new comment

2023-08-15 08:25 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/divider.tsx
> +    marginBottom: `${marginBottom} !important`,
I don't think so either. It's always a good indication something is not setup using 'best practices'

2023-08-15 08:25 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +  headingLevel,
Good high-level/abstract thinking @VWSCoronaDashboard28

2023-08-15 08:26 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +          <Divider marginBottom={space[4]} />
+1

2023-08-15 14:07 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +  headingLevel,
The headingLevel was already present, but wasn't being used until now (see dev). However I could do what you have suggested here as well.

2023-08-15 14:36 UTC, VWSCoronaDashboard35 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +          <Divider marginBottom={space[4]} />
I understand the point you are making here. These extra pages that you have mentioned are achieved pages, meaning there's no title "Gearchiveerde grafieken". The ticket is specifically about the consistency of **that** title with respect to other titles. Also it is about the distance of that title and the divider. 

On the other pages there is a PageInformationBlock that is not the first one, but it still maintains the larger distance to make it clear that it is the start of some section check [here](https://coronadashboard.rijksoverheid.nl/landelijk/kwetsbare-groepen-70-plussers) at Sterfte Section. 

If you still find that my line of reasoning is not in accordance with the ticket I will attempt the changes you are suggesting @VWSCoronaDashboard28.

2023-08-16 10:42 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/divider.tsx
> +  hasPageInfoBlock: boolean;
Should this be an optional prop?

2023-08-16 10:43 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +  headingLevel,
If it was already there and you're using it now, that's fine by me.

2023-08-16 10:49 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +  headingLevel,
Hold on, it actually was not there as a prop. It was part of the interface but not being used as a prop. I would think of it like this: If the only case where the `headingLevel` is different is when this component is used to render the archived section title, then I would go with using `showArchivedToggleButton`. This allows you to get rid of an import and a few other pieces of code. However, the outcome will remain the same. So I'll leave it up to you to do what you prefer.

2023-08-17 10:06 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +  headingLevel,
I understand what you mean by this now. I have rendered  the size of the heading and border if the page info block is an archiving block.

2023-08-17 10:09 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/divider.tsx
> +  hasPageInfoBlock?: boolean;
If I'm not wrong, I see that the divider is no longer being used. Does that make this redundant?

2023-08-17 10:11 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +  headingLevel,
You could also remove its import and usage in the interface

2023-08-17 10:56 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/divider.tsx
> +  hasPageInfoBlock: boolean;
Since I am not using this anymore I am removing it.

2023-08-17 11:00 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/divider.tsx
> +  hasPageInfoBlock?: boolean;
It is still a component in some of the archived pages like e.g. packages\app\src\pages\landelijk\gehandicaptenzorg.tsx

2023-08-17 11:29 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/divider.tsx
> +  hasPageInfoBlock?: boolean;
Yes, I meant the prop not the component, my bad.

2023-08-18 07:23 UTC, VWSCoronaDashboard28 approved these changes

2023-08-18 09:41 UTC, VWSCoronaDashboard35 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +          <Divider style={{ marginBottom: space[3] }} />
This has been removed.

2023-08-18 09:42 UTC, VWSCoronaDashboard35 commented on packages/app/src/pages/landelijk/sterfte.tsx
> +          <Divider marginBottom={space[4]} />
My comments from above apply here too.

2023-08-22 07:52 UTC, VWSCoronaDashboard30 approved these changes
Well done!

2023-08-25 07:16 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/page-information-block/page-information-block.tsx
> +      spacing={{ _: 3, md: 4 }}
Sorry, this spacing is not refactored yet.

2023-08-25 07:35 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/page-information-block/page-information-block.tsx
HeadingLevel is still in the type definition. Please remove it here as it is not being used.

2023-08-25 07:36 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/sterfte.tsx
> +            headingLevel={3}
The PageInformationBlock is not using any headingLevel.
This line does nothing at all...

2023-08-25 07:38 UTC, VWSCoronaDashboard35 commented on packages/app/src/components/page-information-block/page-information-block.tsx
Done

2023-08-25 07:39 UTC, VWSCoronaDashboard35 commented on packages/app/src/pages/landelijk/sterfte.tsx
> +            headingLevel={3}
Absolutely, I have removed it now

2023-08-25 08:11 UTC, VWSCoronaDashboard18 approved these changes
Awesome!

2023-08-25 08:12 UTC, merged