feat(COR-1765): ZKH in beeld – gemiddelde bedbezetting per dag
minvws/nl-covid19-data-dashboard pull request #4842
Opened 2023-08-15 13:37 UTC by VWSCoronaDashboard30

- Changed the schemas to accept new properties.
- Enhanced BorderedKpiSectionProps to accept a date range.
- Swapped the new metrics with the old ones.

2023-08-16 11:30 UTC, VWSCoronaDashboard28 commented on packages/app/schema/nl/hospital_lcps.json
Correct me if I'm wrong, but are we not supposed to now receive a `date_start_unix` and a `date_end_unix` to display a date range?

2023-08-16 11:30 UTC, VWSCoronaDashboard28 commented on packages/app/schema/nl/intensive_care_lcps.json
Correct me if I'm wrong, but are we not supposed to now receive a date_start_unix and a date_end_unix to display a date range?

2023-08-16 11:30 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/kpi/types.ts
> +  dateUnix: number | [number, number];
This will work but I'm not so sure about how well it reads. As per my understanding, `dateUnix` refers to a singular point in time. Now we are saying that it can either be a single point in time, or a range between two points in time. 

I would rather see something more descriptive or a range. Or change the name here to indicate it could be a range or just a single date.

2023-08-16 11:30 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/ziekenhuizen-in-beeld.tsx
> +            dateUnix={[borderedKpiPeriod.old_date_unix, borderedKpiPeriod.new_date_unix]}
So the difference values will be used to create the date span and not the actual average values?

2023-08-21 07:31 UTC, VWSCoronaDashboard28 commented on packages/app/src/components/kpi/types.ts
> +  dateUnix: number | [number, number];
What did you do?

2023-08-21 08:33 UTC, VWSCoronaDashboard18 commented on packages/app/schema/nl/hospital_lcps.json
>          "date_unix",
I'm still missing the date range, like @VWSCoronaDashboard28 also mentioned.

2023-08-21 08:33 UTC, VWSCoronaDashboard18 commented on packages/app/schema/nl/intensive_care_lcps.json
>          "influx_covid_patients_moving_average",
I'm still missing the date range, like @VWSCoronaDashboard28 also mentioned.

2023-08-21 08:35 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +              dataRangeUnix={filteredVaccination.autumn2022.date_unix}
This is just getting a single date. Not a range. Please change the prop or the value. (I think the latter is to update 😉)

2023-08-21 08:35 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/gemeente/[code]/vaccinaties.tsx
> +            dataRangeUnix={filteredVaccination.primarySeries.date_unix}
This is just getting a single date. Not a range. Please change the prop or the value. (I think the latter is to update 😉)

2023-08-21 08:36 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/kpi/types.ts
> +  dateUnix: number | [number, number];
It was changed from `dateUnix` to `dateRangeUnix`

2023-08-21 08:41 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/kpi/types.ts
> +  dataRangeUnix: number | [number, number];
We have other ways to implement a date range prop. Check for example lines 19 to 22 in the file:
`packages/app/src/components/page-information-block/components/metadata.tsx`

2023-08-21 08:41 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/kwetsbare-groepen-70-plussers.tsx
> +            dataRangeUnix={vulnerableNursingHomeDataLastValue.date_unix}
This is just getting a single date. Not a range. Please change the prop or the value. (I think the latter is to update 😉)

2023-08-21 08:41 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +            dataRangeUnix={vaccineCoverageEstimatedAutumn2022.date_unix}
This is just getting a single date. Not a range. Please change the prop or the value. (I think the latter is to update 😉)

2023-08-21 08:41 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/vaccinaties.tsx
> +            dataRangeUnix={vaccineCoverageEstimatedFullyVaccinated.date_unix}
This is just getting a single date. Not a range. Please change the prop or the value. (I think the latter is to update 😉)

2023-08-21 08:45 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/ziekenhuizen-in-beeld.tsx
> +  const borderedKpiPeriod = data.difference.hospital_lcps__beds_occupied_covid;
As shown last Tuesday this is not the property that is matching what you are showing. I've not heard this we indeed will use this "incorrect" metric property.

Short recap: This is the metric for the date the last value was displayed on the dashboard. And not the date of the start of the current value. (They might overlap often, but it's not the same)

2023-08-21 08:46 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/ziekenhuizen-in-beeld.tsx
> +            dataRangeUnix={mostRecentDateUnix}
This is just getting a single date. Not a range. Please change the prop name or the value. (I think the name is to update 😉)

2023-08-21 09:16 UTC, VWSCoronaDashboard18 requested changes
See the comments

2023-08-21 11:42 UTC, VWSCoronaDashboard18 commented on packages/app/src/components/metadata.tsx
>          })
Lines `38 - 42` can be removed as `date` is never an array anymore.

2023-08-23 14:18 UTC, VWSCoronaDashboard18 commented on packages/app/schema/nl/intensive_care_lcps.json
>          "influx_covid_patients_moving_average",
You just simply do not know if that's going to be the case. It might be for the coming weeks, but it might change further down the road again. And I can assure you, when you have issues about this, it's gonna be a way bigger hassle to deal with than now just add it.
And I genuinely don't understand why this is so hard to comply with, it's a common practice we do very often on the dashboard.

I see this as very low-hanging fruit. No big effort now. But can save you a lot of problems and research in the future.

2023-08-23 14:21 UTC, VWSCoronaDashboard18 submitted a review, later dismissed
I do think the start and end unix is not the right thing to merge. But as long as there are no changes to the moment of updating or at the interval. there is no immediatee problem.

2023-08-24 07:50 UTC, VWSCoronaDashboard28 submitted a review, later dismissed

2023-08-24 11:48 UTC, VWSCoronaDashboard28 approved these changes

2023-08-24 13:49 UTC, VWSCoronaDashboard18 approved these changes
Looks good to me!

2023-08-25 10:45 UTC, VWSCoronaDashboard27 approved these changes

2023-08-25 14:52 UTC, merged