feat(COR-1705): Infection Radar graph
minvws/nl-covid19-data-dashboard pull request #4844
Opened 2023-08-18 12:47 UTC by VWSCoronaDashboard30

- Added the redirects
- Renamed the page
- Added the new graph
- Added the required keys for the page and graph

2023-08-21 08:21 UTC, VWSCoronaDashboard28 reviewed
Do you have some data to test with?

2023-08-21 08:21 UTC, VWSCoronaDashboard28 commented on packages/app/src/next-config/redirects/redirects.js
> +      destination: '/landelijk/infectie-radar',
According to the ticket the new route should be `landelijk/infectieradar`

2023-08-21 08:21 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/infectie-radar.tsx
> +  const [confirmedCasesCovidSimptomsPerAgeTimeFrame, setConfirmedCasesCovidSimptomsPerAgeTimeFrame] = useState<TimeframeOption>(TimeframeOption.ALL);
Typo. Simptoms -> Symptoms.

2023-08-21 09:32 UTC, VWSCoronaDashboard28 reviewed
Small reminder that the page parts should be updated when this is released

2023-08-21 09:34 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/infectie-radar.tsx
To double-check, the designs don't show a date range, should I assume this has been discussed?

2023-08-21 10:23 UTC, VWSCoronaDashboard18 commented on packages/cms/src/lokalize/key-mutations.csv
Be aware of this moving of keys. As mentioned during the demo sessions we tend not to move keys but delete and create new ones. Moving keys can give problems with missing references to the old keys.

2023-08-21 11:12 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/layout/logic/use-sidebar.tsx
> +  infection_radar: 'infectionRadar',
I think its value can and should be Dutch, based on the other key/value pairs I see in this object.

2023-08-21 11:17 UTC, VWSCoronaDashboard28 commented on packages/app/src/domain/infection_radar/infection-radar-per-age-group.tsx
> +          isPercentage: true,
Good to know. I do like the idea of abstracting this component from `pages/infectie-radar` as it has a decent amount of logic associated with it. However, I don't really see a reason to do that if we have the same kind of component floating around elsewhere.

I would suggest refactoring this, but for the sake of time I'll leave it be.

2023-08-21 11:20 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +  const [confirmedCasesCovidSymptomsPerAgeTimeFrame, setConfirmedCasesCovidSymptomsPerAgeTimeFrame] = useState<TimeframeOption>(TimeframeOption.ALL);
The ticket states the timeframe option should be last three months.

2023-08-21 11:23 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +            timeframeInitialValue={TimeframeOption.THREE_MONTHS}
I see you use the Three-month option here. But you can use the initial value if set correctly.

2023-08-21 11:25 UTC, VWSCoronaDashboard18 commented on packages/cms/src/studio/data/data-structure.ts
This file also contains data from other PRs. Please keep the files separate when creating a PR.

2023-08-21 11:27 UTC, VWSCoronaDashboard18 commented on packages/common/src/data/reverse-router.ts
> +      infectionRadar: () => '/landelijk/infectieradar',
Good one. In English, it consists of two words and in dutch only one! Nice!

2023-08-21 11:29 UTC, VWSCoronaDashboard18 commented on packages/common/src/theme/colors.ts
> +  magenta5: '#6200AF',
Where is this new color coming from? Are the others not sufficient enough? I don't see any conversation about this in the ticket or in the design. And the other colors still have four colors. Do they need an update as well?

2023-08-21 11:31 UTC, VWSCoronaDashboard18 requested changes
See the comments

2023-08-22 14:26 UTC, VWSCoronaDashboard18 commented on packages/app/schema/nl/__index.json
> +    "infectionradar_symptoms_trend_per_age_group_weekly": {
Infection Radar are two words. So the R needs to be capitalized

2023-08-22 14:28 UTC, VWSCoronaDashboard28 commented on packages/app/schema/nl/__index.json
> +    "infectionradar_symptoms_trend_per_age_group_weekly": {
Well, it should be snake case, right? So `infection_radar_***`

2023-08-22 14:28 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +  selectNlData('self_test_overall', 'infectionradar_symptoms_trend_per_age_group_weekly'),
Infection Rader are two words. So the R needs to be capitalized

2023-08-22 14:29 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +  selectNlData('self_test_overall', 'infectionradar_symptoms_trend_per_age_group_weekly'),
Well, it should be snake case, right? So infection_radar_***

2023-08-22 14:31 UTC, VWSCoronaDashboard18 commented on packages/common/src/data/reverse-router.ts
> +      infectieRadar: () => '/landelijk/infectieradar',
infectieradar is one word so the r should be lowercase.

2023-08-22 14:31 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +              values={data.infectionradar_symptoms_trend_per_age_group_weekly.values}
Infection Rader are two words. So the R needs to be capitalized

2023-08-22 14:32 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +  selectNlData('self_test_overall', 'infectionradar_symptoms_trend_per_age_group_weekly'),
You are correct!

2023-08-22 14:32 UTC, VWSCoronaDashboard18 commented on packages/app/schema/nl/__index.json
> +    "infectionradar_symptoms_trend_per_age_group_weekly": {
You are correct!

2023-08-22 14:33 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +            title={textNl.chart_infectie_radar_age_groups.title}
infectieradar is one word so the _ needs to go.

2023-08-22 14:33 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +              values={data.infectionradar_symptoms_trend_per_age_group_weekly.values}
infectieradar is one word so the _ needs to go.

2023-08-22 14:56 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +const InfectionRadar = (props: StaticProps<typeof getStaticProps>) => {
Infectionradar is a single word

2023-08-22 14:57 UTC, VWSCoronaDashboard18 requested changes
See all the comments about camelCase and snake_case

2023-08-23 07:25 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +              values={data.infectionradar_symptoms_trend_per_age_group_weekly.values}
You need some test data in order to be able to run this feature locally.

2023-08-23 10:15 UTC, VWSCoronaDashboard30 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +  selectNlData('self_test_overall', 'infectionradar_symptoms_trend_per_age_group_weekly'),
Unfortunately, this won't be fixed...

2023-08-23 10:16 UTC, VWSCoronaDashboard30 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +const InfectionRadar = (props: StaticProps<typeof getStaticProps>) => {
Corrected!

2023-08-23 10:17 UTC, VWSCoronaDashboard30 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +              values={data.infectionradar_symptoms_trend_per_age_group_weekly.values}
The dataset is present in the ticket!

2023-08-23 10:28 UTC, VWSCoronaDashboard30 commented on packages/cms/src/lokalize/key-mutations.csv
This is cleaned up now!

2023-08-23 10:29 UTC, VWSCoronaDashboard30 commented on packages/common/src/data/reverse-router.ts
> +      infectieRadar: () => '/landelijk/infectieradar',
Corrected!

2023-08-23 11:03 UTC, VWSCoronaDashboard18 commented on packages/app/schema/nl/__index.json
> +    "infectionradar_symptoms_trend_per_age_group_weekly": {
You are merging to develop right? So I don't get why it is already in production. Since you are adding it here there is no possibility this name already works in production right now.

2023-08-23 11:05 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +  selectNlData('self_test_overall', 'infectionradar_symptoms_trend_per_age_group_weekly'),
Can you elaborate on why? You mentioned in another comment that it already is in production. But that cannot be, since you are merging to develop. Any validation would fail on the pipelines.

2023-08-23 11:08 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
>          "elements": ${getElementsQuery('nl', ['self_test_overall'], locale)}
Will there be no elements for the new graph? (Timelines, warnings). Having the feature to add those elements is part of the implementation

2023-08-23 11:09 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +const Infectionradar = (props: StaticProps<typeof getStaticProps>) => {
This should be two words. InfectionRadar.

2023-08-23 11:09 UTC, VWSCoronaDashboard18 requested changes
I'm still seeing Infaction Radar as a single word and Infectie Radar as two words...

* (And I'm not only talking about the metric)

2023-08-23 13:08 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +const InfectionRadar = (props: StaticProps<typeof getStaticProps>) => {
In English its two words though?

2023-08-23 14:03 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +const Infectionradar = (props: StaticProps<typeof getStaticProps>) => {
+1

2023-08-24 10:20 UTC, VWSCoronaDashboard30 commented on packages/app/schema/nl/__index.json
> +    "infectionradar_symptoms_trend_per_age_group_weekly": {
As I mentioned before, BE released this last sprint and it's not enabled yet

2023-08-24 10:20 UTC, VWSCoronaDashboard30 commented on packages/app/src/pages/landelijk/infectieradar.tsx
> +  selectNlData('self_test_overall', 'infectionradar_symptoms_trend_per_age_group_weekly'),
This was released last sprint by BE, but it's not being delivered to us at the moment

2023-08-24 10:59 UTC, VWSCoronaDashboard30 commented on packages/app/src/pages/landelijk/infectieradar.tsx
>          "elements": ${getElementsQuery('nl', ['self_test_overall'], locale)}
The timeline was added. I believe the warning can be manually added by COM

2023-08-24 11:59 UTC, VWSCoronaDashboard28 submitted a review, later dismissed

2023-08-24 13:56 UTC, VWSCoronaDashboard18 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-08-23T10:23:05.336Z,delete,common.sidebar.metrics.infectie_radar.title,jnRBBkraje744C8PaLeYPd,__
Infectie_radar is one word. And shoudl be infectieradar_age....

2023-08-24 13:56 UTC, VWSCoronaDashboard18 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-08-16T11:00:47.292Z,add,common.sidebar.metrics.infectie_radar.title,jnRBBkraje744C8PaLeYPd,__
Infectie_radar is one word. And shoudl be infectieradar_age....

2023-08-24 13:58 UTC, VWSCoronaDashboard18 requested changes
See my last comments...

2023-08-25 07:31 UTC, VWSCoronaDashboard18 commented on packages/app/src/pages/landelijk/infectieradar.tsx
>          "elements": ${getElementsQuery('nl', ['self_test_overall'], locale)}
@VWSCoronaDashboard28 the getElementsQuery is part of any creation of any new time-series graph. So the ticket mentions this by mentioning the creation of a new graph...

2023-08-25 07:34 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/infectieradar.tsx
>          "elements": ${getElementsQuery('nl', ['self_test_overall'], locale)}
I would expect that to be specified in the ticket because, but alright.

2023-08-25 07:34 UTC, VWSCoronaDashboard28 commented on packages/app/src/pages/landelijk/infectieradar.tsx
>          "elements": ${getElementsQuery('nl', ['self_test_overall'], locale)}
This can be resolved now though?

2023-08-25 09:23 UTC, VWSCoronaDashboard30 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-08-16T11:00:47.292Z,add,common.sidebar.metrics.infectie_radar.title,jnRBBkraje744C8PaLeYPd,__
this key was deleted on line `62` and the key `common.sidebar.metrics.infection_radar.title` was added on line `61`

2023-08-25 09:26 UTC, VWSCoronaDashboard30 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-08-23T10:12:09.105Z,add,pages.infection_radar_page.nl.chart_infectie_radar_age_groups.title,3wzwGuQ73UdAvQOvNcO5FR,__
I've update the keys to be consistent to the upper level. It is now `chart_infection_radar_age_groups`. Please check line `118-127`

2023-08-25 09:27 UTC, VWSCoronaDashboard30 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-08-23T10:23:05.336Z,delete,common.sidebar.metrics.infectie_radar.title,jnRBBkraje744C8PaLeYPd,__
This key was deleted. This is the key from line `2`

2023-08-25 09:35 UTC, VWSCoronaDashboard28 approved these changes

2023-08-25 10:20 UTC, VWSCoronaDashboard30 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-08-16T11:00:47.292Z,add,common.sidebar.metrics.infectie_radar.title,jnRBBkraje744C8PaLeYPd,__
Update: The deletion is now on line `29`  and the insertion is on line `28`

2023-08-25 10:21 UTC, VWSCoronaDashboard30 commented on packages/cms/src/lokalize/key-mutations.csv
> +2023-08-25T09:47:47.719Z,add,pages.infection_radar_page.nl.chart_self_tests.title,uHFfJYJkKtXC1Rsty3FUMv,__
@VWSCoronaDashboard18 This block was added due to the fact that the previously added block was not showing up in NL_export or the CMS. The previous block was deleted. Please resolve the conversation if it's ok from your side.

2023-08-25 14:02 UTC, VWSCoronaDashboard18 commented on packages/cms/src/lokalize/key-mutations.csv
I have no idea what is happening in this file. There are items being deleted that do not have the 'add' action in the CSV or are present in the sanity set. 
For example this one: xT2YXVOH9b7Mo5ggz8BErS

Nonetheless I don't see any type errors. So I will approve this PR.

2023-08-25 14:03 UTC, VWSCoronaDashboard18 approved these changes
Awesome!

2023-08-25 14:03 UTC, VWSCoronaDashboard18 commented on packages/cms/src/lokalize/key-mutations.csv
Therefore feel free to resolve without notifying

2023-08-25 14:09 UTC, VWSCoronaDashboard30 commented on packages/cms/src/lokalize/key-mutations.csv
That ID comes from the develop branch. It was merged with this branch because of the merge-conflicts

2023-08-25 14:10 UTC, merged