feat(COR-1674): Added the new lokalize key
minvws/nl-covid19-data-dashboard pull request #4845
Opened 2023-08-21 09:10 UTC by VWSCoronaDashboard30

- Added the new lokalize key _population_count_connected_to_rwzis_

2023-08-21 09:30 UTC, VWSCoronaDashboard18 commented on packages/cms/src/studio/data/data-structure.ts
This file should not be part of this PR, I think...

2023-08-21 09:30 UTC, VWSCoronaDashboard18 requested changes
See my comment, the other two files are great!

2023-08-21 12:35 UTC, VWSCoronaDashboard28 approved these changes

2023-08-22 12:58 UTC, VWSCoronaDashboard18 requested changes
test for realtime github updates

2023-08-22 12:59 UTC, VWSCoronaDashboard18 approved these changes
Now it's OK to merge. Because the other PR's (where the data structure changes) are on the way.
When the data structure is deleted in this PR, a new commit needs to happen, and two new approvals are needed. So for time/effort constraints we do it already in this PR

2023-08-22 13:00 UTC, merged