task(key-mutations): Fix issue with cluttered keys
minvws/nl-covid19-data-dashboard pull request #4847
Opened 2023-08-22 10:04 UTC by VWSCoronaDashboard30

- Removed the 3 batches of keys that need to be replaced with the back up

2023-08-22 10:06 UTC, VWSCoronaDashboard28 submitted a review, later dismissed

2023-08-22 10:54 UTC, VWSCoronaDashboard18 requested changes
I think we need to remove the tested items from here and put them in the branch for COR-1705. Now the validation fails, and emerging this would break the dev environment.

2023-08-22 13:38 UTC, VWSCoronaDashboard28 approved these changes

2023-08-23 07:30 UTC, VWSCoronaDashboard18 submitted a review, later dismissed
Good fixing!

*Normally the files have an empty line at the end of the file. But the file is still valid, so there is no issue to merge. But even with priority stuff and fixing try to stay constant and keep these things in mind.

2023-08-23 09:12 UTC, VWSCoronaDashboard28 approved these changes

2023-08-23 09:13 UTC, merged