Feature/cor 1705 correct timeseries agegroups
minvws/nl-covid19-data-dashboard pull request #4854
Opened 2023-09-01 15:31 UTC by VWSCoronaDashboard29

Remove underreported annotation from agegroups timeseries

2023-09-01 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4854) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4854) before we can accept your contribution.<br/>**6** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: VWSCoronaDashboard18<br/>:white_check_mark: VWSCoronaDashboard27<br/>:white_check_mark: VWSCoronaDashboard25<br/>:white_check_mark: VWSCoronaDashboard26<br/>:white_check_mark: VWSCoronaDashboard28<br/>:white_check_mark: VWSCoronaDashboard30<br/>:x: VWSCoronaDashboard29<br/><hr/>**VWSCoronaDashboard29** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=4854) it.</sub>

2023-09-04 07:29 UTC, VWSCoronaDashboard28 reviewed
Something seems off in this PR. I'm seeing over 250 commits. What's going on?

2023-09-04 07:35 UTC, VWSCoronaDashboard30 commented on packages/cms-v2/src/schemas/topical/theme-tile.ts
@VWSCoronaDashboard29 Why are we changing changing stuff to V2?

2023-09-04 07:36 UTC, VWSCoronaDashboard30 reviewed
Why are there 500 commits to the branch?

2023-09-04 08:08 UTC, VWSCoronaDashboard28 requested changes
Something is off given the number of commits, please recreate this PR with only the changes you have introduced.

2023-09-04 08:15 UTC, closed without merging