feature/COR-1784_COR-1801_vaccinations-modifications
minvws/nl-covid19-data-dashboard pull request #4887
Opened 2023-09-29 14:26 UTC by VWSCoronaDashboard30

2023-09-29 14:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4887) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=4887) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: VWSCoronaDashboard29<br/>:white_check_mark: VWSCoronaDashboard30<br/>:white_check_mark: VWSCoronaDashboard18<br/>:x: beek<br/><hr/>**beek** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=4887) it.</sub>

2023-09-29 14:37 UTC, VWSCoronaDashboard29 requested changes

2023-09-29 14:37 UTC, VWSCoronaDashboard29 commented on packages/app/src/components/kpi/components/kpi-content.tsx
> +      <Metadata {...metadata} isTileFooter marginBottom={space[2]} />
This should be optional

2023-10-02 08:46 UTC, VWSCoronaDashboard30 commented on packages/app/schema/archived_nl/vaccine_campaigns_archived_20231004.json
> +{
@VWSCoronaDashboard29 We need to change the naming for this one. It should not contain the archived date in the title nor name of the file.

2023-10-02 08:47 UTC, VWSCoronaDashboard30 commented on packages/app/schema/archived_nl/vaccine_coverage_per_age_group_archived_20231012.json
same here @VWSCoronaDashboard29

2023-10-02 08:47 UTC, VWSCoronaDashboard30 commented on packages/app/schema/archived_nl/vaccine_coverage_per_age_group_estimated_autumn_2022.json
same here @VWSCoronaDashboard29

2023-10-02 08:49 UTC, VWSCoronaDashboard30 commented on packages/common/src/feature-flags/features.ts
>    {
This one is not fixed yet @VWSCoronaDashboard29

2023-10-02 08:50 UTC, VWSCoronaDashboard30 commented on packages/cli/src/schema/schema-info.ts
> +        createChoroplethValidation(path.join(defaultJsonDirectory, 'archived', 'GM_COLLECTION.json'), 'gmcode', ['vaccine_coverage_per_age_group_archived_202310xx']),
@VWSCoronaDashboard29 Can you fix this one as well or should i take care of it?

2023-10-02 12:44 UTC, VWSCoronaDashboard29 commented on packages/app/schema/archived_nl/vaccine_campaigns_archived_20231004.json
> +{
What do you want to change the filename to?

2023-10-02 12:44 UTC, VWSCoronaDashboard29 commented on packages/app/schema/archived_nl/vaccine_coverage_per_age_group_archived_20231012.json
Same question as in previous comment https://github.com/minvws/nl-covid19-data-dashboard/pull/4887#discussion_r1342639055

2023-10-02 12:54 UTC, VWSCoronaDashboard29 commented on packages/cli/src/schema/schema-info.ts
> +        createChoroplethValidation(path.join(defaultJsonDirectory, 'archived', 'GM_COLLECTION.json'), 'gmcode', ['vaccine_coverage_per_age_group_archived_202310xx']),
See https://github.com/minvws/nl-covid19-data-dashboard/pull/4887#discussion_r1342651681

2023-10-02 12:58 UTC, VWSCoronaDashboard29 commented on packages/common/src/feature-flags/features.ts
>    {
Should be fixed now

2023-10-02 14:14 UTC, VWSCoronaDashboard29 approved these changes

2023-10-02 14:14 UTC, merged