feat: new tooltip design
minvws/nl-covid19-data-dashboard pull request #490
Opened 2020-09-29 16:00 UTC by VWSCoronaDashboard5

## Summary

This PR adds a new tooltip design for the choropleth maps on pages. The updated design shows the name and value of the node in the map and allows for using the tooltip as a link (using an `onClick`) to the node's page (i.e. `/gemeente/GM0627/positief-geteste-mensen` on a node in a municipality choropleth).

The UX of this feature is rather implicit still, but it uses the same implementation as used in the Escalation (Risico) map, which is when the visitor is on mobile, the tooltip is showed on a tap (mobile `:hover`) and then allows the user to use the tooltip as a link to navigate.

### Governance

- [x] Documentation is added
- [ ] Test cases are added or updated
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-09-29 16:21 UTC, VWSCoronaDashboard1 requested changes

2020-09-29 16:21 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/municipal/positiveTestedPeopleTooltip.tsx
> +export const positiveTestedPeopleMunicipalTooltip = (router: NextRouter) => (
since this has now become a factory method as well, I suggest you rename it to 'createPositiveTestedPeopleMunicipalTooltip'

2020-09-29 16:21 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/municipal/positiveTestedPeopleTooltip.tsx
> +    );
Instead of duplicating this code, you can also import the createSelectMunicipalHandler factory here:
`const handler = createSelectMunicipalHandler(router);
handler(context);
`

2020-09-29 16:21 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/region/positiveTestedPeopleTooltip.tsx
> +export const positiveTestedPeopleRegionalTooltip = (router: NextRouter) => (
same naming suggestion as above

2020-09-29 16:21 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/region/positiveTestedPeopleTooltip.tsx
> +  };
Same duplication suggestion as above

2020-09-30 09:45 UTC, VWSCoronaDashboard1 requested changes

2020-09-30 09:45 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/municipal/positiveTestedPeopleTooltip.tsx
> +    const handler = createSelectMunicipalHandler(router);
You can actually move the creation of this handler outside of the onSelectRegion instance, that way it won't have to be created every time onSelectRegion is invoked

2020-09-30 09:45 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/region/positiveTestedPeopleTooltip.tsx
> +    const handler = createSelectRegionHandler(router);
same as the comment above

2020-09-30 09:50 UTC, VWSCoronaDashboard1 approved these changes

2020-09-30 09:58 UTC, VWSCoronaDashboard4 approved these changes

2020-09-30 10:04 UTC, VWSCoronaDashboard8 requested changes

2020-09-30 10:04 UTC, VWSCoronaDashboard8 commented on src/components/chloropleth/tooltips/region/positiveTestedPeopleTooltip.tsx
> +      <div className={styles.escalationTooltip} onClick={onSelectRegion}>
The use of CSS modules here goes against the idea of modules to separate components. It is maybe not the fault of this PR because the CSS file already existed, but you are importing from a module that seems to be shared amongst multiple different tooltip components. So it becomes a sort of "global" CSS again, only now global to all tooltips. This is not a good separation of concerns IMO. 

If a tooltip is so different that it can not be implemented by extending an existing tooltip component via props, it should be a component by itself with its own css module.

That way you can also simplify class names in generic ones like root, header, info...

2020-09-30 10:05 UTC, VWSCoronaDashboard8 commented on src/components/chloropleth/tooltips/region/positiveTestedPeopleTooltip.tsx
> +      <div className={styles.escalationTooltip} onClick={onSelectRegion}>
I will approve the PR since this might be something better fixed when refactoring to styled components.

2020-09-30 10:05 UTC, VWSCoronaDashboard8 approved these changes

2020-09-30 10:06 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/region/positiveTestedPeopleTooltip.tsx
> +      <div className={styles.escalationTooltip} onClick={onSelectRegion}>
Let's chalk this up to technical debt and add a ticket to the tech debt column?

2020-09-30 10:46 UTC, merged