feature/COR-1758_shorten-sidebar-with-hooks
minvws/nl-covid19-data-dashboard pull request #4937
Opened 2023-11-22 13:05 UTC by VWSCoronaDashboard30

Refactored the sidebar to make use of hooks

2023-11-23 15:28 UTC, VWSCoronaDashboard29 commented on packages/common/src/data/reverse-router.ts
> +  const archivedPaths = {
I think this is an OK way to solve the issue of archived paths for now. I'd suggest that in the future we can look into a way of splitting the NL paths block on line 17 into archived and non-archived paths and work from there.

2023-11-23 15:36 UTC, VWSCoronaDashboard29 requested changes
Looks quite allright to me but what about the cijferverantwoording?

2023-11-23 15:38 UTC, VWSCoronaDashboard29 commented on packages/app/src/components/aside/menu.tsx
> +function isCategoryMenuOpen(router: NextRouter, archivedPaths: ArchivedPath) {
I would suggest the following name.

```suggestion
function isCurrentRouteArchivedPage(router: NextRouter, archivedPaths: ArchivedPath) {
```

2023-11-24 09:02 UTC, VWSCoronaDashboard29 submitted a review, later dismissed

2023-11-24 11:13 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/menu.tsx
> +function isCategoryMenuOpen(router: NextRouter, archivedPaths: ArchivedPath) {
The function name was changed!

2023-11-24 11:13 UTC, VWSCoronaDashboard30 commented on packages/common/src/data/reverse-router.ts
> +  const archivedPaths = {
True, we should look into this, as we also have the third sidebar

2023-11-27 12:34 UTC, VWSCoronaDashboard29 approved these changes

2023-11-27 12:39 UTC, merged