bugfix/COR-1865-no-auto-resolve-1970
minvws/nl-covid19-data-dashboard pull request #4955
Opened 2023-12-18 16:04 UTC by VWSCoronaDashboard29

Throw error if pageMetric not found in data

2023-12-19 12:30 UTC, yorickdevries requested changes
Please consider the comments in the review and take a look at the tests when resolved. Perhaps you can even add a test which checks for the behavior when Pagemetrics is missing.

2023-12-19 12:30 UTC, yorickdevries commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  return Array.isArray(metric?.values) && typeof metric?.values[metric.values.length - 1]?.date_of_insertion_unix !== 'undefined';
Nothing is changed except whitespace, consider removing the change

2023-12-19 12:30 UTC, yorickdevries commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  return Array.isArray(metric?.values) && typeof metric?.values[0]?.last_value?.date_of_insertion_unix !== 'undefined';
Nothing is changed except whitespace, consider removing the change

2023-12-19 12:30 UTC, yorickdevries commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  return metric?.values.reduce((lastDate: number, innerValue: any) => {
Nothing is changed except whitespace, consider removing the change

2023-12-19 12:30 UTC, yorickdevries commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  const foundMetrics: string[] = pageMetrics.filter((metricProperty) => {
Naming foundMetrics is not really clear; consider renaming to definedMetrics or merticsWithValues

2023-12-19 12:30 UTC, yorickdevries commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +    if (get(data, metricProperty) !== undefined) {
The filter method should return a boolean. And there is no else case.
Consider: ```return typeof get(data, metricProperty) === 'number';```

2023-12-19 12:30 UTC, yorickdevries commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  if (foundMetrics?.length === 0) {
why the ```?``` in ```foundMetrics?```. Seems redundant and even error prone.

2023-12-19 12:30 UTC, yorickdevries commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +
why is this new line added?

2023-12-19 12:30 UTC, yorickdevries commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +}
why is the semi-colon removed?

2023-12-20 08:27 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  return Array.isArray(metric?.values) && typeof metric?.values[metric.values.length - 1]?.date_of_insertion_unix !== 'undefined';
Reformat done automatically by Husky commit hook. Forceably undone now.

2023-12-20 08:27 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  return Array.isArray(metric?.values) && typeof metric?.values[0]?.last_value?.date_of_insertion_unix !== 'undefined';
Reformat done automatically by Husky commit hook. Forceably undone now.

2023-12-20 08:27 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  return metric?.values.reduce((lastDate: number, innerValue: any) => {
Reformat done automatically by Husky commit hook. Forceably undone now.

2023-12-20 08:27 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +
Reformat done automatically by Husky commit hook. Forceably undone now.

2023-12-20 08:27 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +}
Reformat done automatically by Husky commit hook. Forceably undone now.

2023-12-20 08:28 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  const foundMetrics: string[] = pageMetrics.filter((metricProperty) => {
Renamed to metricsAvailableInData

2023-12-20 08:28 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +    if (get(data, metricProperty) !== undefined) {
Implemented suggestion.

2023-12-20 08:28 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +  if (foundMetrics?.length === 0) {
Removed optional

2023-12-20 09:53 UTC, yorickdevries commented
Thanks for the changes. The PR looks much cleaner now. If Husky changes so much formatting, perhaps we should straighten th whole codebase so everything is linted correctly. Furthermore, a test is still failing. Can you look into that?

2023-12-20 12:58 UTC, VWSCoronaDashboard29 commented on packages/app/src/utils/get-last-insertion-date-of-page.ts
> +}
Newline added

2023-12-20 17:40 UTC, yorickdevries approved these changes
approved

2023-12-22 09:45 UTC, merged