feature/COR-1899-archived-pages-accordion
minvws/nl-covid19-data-dashboard pull request #4974
Opened 2024-01-30 08:21 UTC by ben-van-eekelen

## Summary

Brief explanation of the feature, and describe how other developers can test and see your implementation.

## Motivation

Why are we doing this? What use cases does it support? What is the expected
outcome?

Please focus on explaining the motivation so that if this PR is not accepted,
the motivation could be used to develop alternative solutions. In other words,
enumerate the constraints you are trying to solve without coupling them too
closely to the solution you have in mind.

## Detailed design

This is the bulk of the PR. Explain the design in enough detail for somebody
familiar with the project to understand, and for somebody familiar with the
front-end to implement. This should get into specifics and corner-cases,
and include examples of how the feature is used. Any new terminology should be
defined here.

## Drawbacks

Why should we _not_ do this? Please consider:

- implementation cost, both in terms of code size and complexity
- maintenance cost, how complex is the solution and how prone to change is it?
- integration of this feature with other existing and planned features

There are tradeoffs to choosing any path. Attempt to identify them here.

## Alternatives

What other designs have been considered? What is the impact of not doing this?

## Unresolved questions

Optional, but suggested for bigger features. What parts of the design are still
TBD or not implemented? How will you deal with that in the future?

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2024-01-30 08:32 UTC, yorickdevries requested changes

2024-01-30 08:32 UTC, yorickdevries commented on packages/app/src/components/aside/menu.tsx
> +export function CollapsibleCategoryMenu({ title, children, icon }: { children: React.ReactNode; title?: string; icon: ReactNode; key: string }) {
why is this change here?

2024-01-30 09:33 UTC, ben-van-eekelen commented on packages/app/src/components/aside/menu.tsx
> +export function CollapsibleCategoryMenu({ title, children, icon }: { children: React.ReactNode; title?: string; icon: ReactNode; key: string }) {
Removed

2024-01-30 10:37 UTC, yorickdevries submitted a review, later dismissed

2024-02-01 15:34 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +  min-height: 36px;
I propose to round it down to 32px, thus making use of the theme.

2024-02-01 15:34 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +  margin: 0 8px;
8px is a magic number, we have a space[x] item for 8px

2024-02-01 15:35 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    border-radius: 5px 5px 0 0;
you can make use of the `radii` element from the theme

2024-02-01 15:36 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +  border-radius: 5px;
you can make use of the `radii` element from the theme

2024-02-01 15:39 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    background: ${colors.gray1};
The component still appears as blue for me. Please let me know if otherwise

2024-02-01 15:39 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    border-radius: 0 0 5px 5px;
make use of `radii` component

2024-02-01 15:40 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +      padding: ${space[2]} ${space[2]} ${space[2]} 3rem;
why the 3 rem?

2024-02-05 12:45 UTC, ben-van-eekelen commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +  min-height: 36px;
Changing this doesn't break anything. I'll apply the suggestion.

2024-02-05 12:46 UTC, ben-van-eekelen commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +  margin: 0 8px;
Applied suggestion.

2024-02-05 12:48 UTC, ben-van-eekelen commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    border-radius: 5px 5px 0 0;
Applied suggestion

2024-02-05 13:14 UTC, ben-van-eekelen commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    color: ${colors.blue8};
Nope it doesn't. The design states the design states the border-color should change from light-grey to light-blue.

2024-02-05 13:26 UTC, ben-van-eekelen commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    background: ${colors.gray1};
Fixed by adjusting order of css statements.

2024-02-05 13:43 UTC, ben-van-eekelen commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    border-radius: 0 0 5px 5px;
Applied suggestion

2024-02-05 13:44 UTC, ben-van-eekelen commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +      padding: ${space[2]} ${space[2]} ${space[2]} 3rem;
To outline properly on mobile vs desktop.

2024-02-06 14:39 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    color: ${colors.blue8};
But now you're chaging the text color as well. `color` is responsible for text and `border-color` is what you need. Please correct me if i am wrong.

2024-02-06 14:42 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +    color: ${colors.blue8};
based on design, i don't think you need `color` for hovering. The color should stay `black`

2024-02-06 14:44 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +  &[aria-expanded=true] {
Perhaps it's good to add some indentation for this kind of styling. It becomes more readable

2024-02-06 14:45 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/aside/components/CategoryDropdown.tsx
> +  ${CategoryDropdown}[aria-expanded=true] + & {
Same here for line breaks

2024-02-06 14:45 UTC, VWSCoronaDashboard30 requested changes
Please see new comments

2024-02-06 14:58 UTC, VWSCoronaDashboard30 approved these changes

2024-02-06 14:58 UTC, merged