feature/COR-1953_non-archived-graphs-adjustments
minvws/nl-covid19-data-dashboard pull request #5005
Opened 2024-03-12 14:43 UTC by VWSCoronaDashboard30

## Summary

- Added the metadata corrections for Rioolwater NL and Infectieradar pages

2024-03-12 15:27 UTC, ben-van-eekelen requested changes

2024-03-12 15:27 UTC, ben-van-eekelen commented on packages/app/src/components/metadata.tsx
> +
Remove rendundant comment

2024-03-12 15:27 UTC, ben-van-eekelen commented on packages/app/src/components/metadata.tsx
> +                {/* This can go */}
Why is it still here then? Now it causes the source label to be displayed doubly:
![image](https://github.com/minvws/nl-covid19-data-dashboard/assets/137172332/5531d5bf-0132-4e59-9f99-0e48e5982825)

2024-03-12 15:49 UTC, VWSCoronaDashboard30 commented on packages/app/src/components/metadata.tsx
> +                {/* This can go */}
It's there since it should go as part of the merge of those two metadata components we currently have.

2024-03-13 09:57 UTC, ben-van-eekelen approved these changes

2024-03-13 09:57 UTC, ben-van-eekelen commented on packages/app/src/components/time-series-chart/time-series-chart.tsx
> +  onHandleTimeIntervalChange?: (value: DateRange) => void;
Very solid work on figuring this out!

2024-03-13 10:00 UTC, merged