apply redesign tooltip on hospital admissions
minvws/nl-covid19-data-dashboard pull request #511
Opened 2020-10-01 13:38 UTC by VWSCoronaDashboard5

## Summary

This PR adds a `createMunicipalHospitalAdmissionsTooltip` and `createRegionHospitalAdmissionsTooltip` factory method for the tooltips used on chloropleths showing Hospital Admissions on `/veiligheidsregio` and `/gemeente`. This PR is related to [the earlier PR regarding the redesign of the tooltip](https://github.com/minvws/nl-covid19-data-dashboard/pull/490).

### Governance

- [x] Documentation is added
- [ ] Test cases are added or updated
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-10-01 13:59 UTC, VWSCoronaDashboard8 requested changes

2020-10-01 13:59 UTC, VWSCoronaDashboard8 commented on src/components/chloropleth/tooltips/municipal/hospitalAdmissionsTooltip.tsx
> +export const createMunicipalHospitalAdmissionsTooltip = (
Looking at this name, and then the used css classes below, I get the impression that something is wrong. Why is this about hospital admissions and classes are used called "positiveTestedPeopleInfo" and "escalationX" ?

It looks like a CSS module is being reused amounts several components, which defeats the point of module files.

And do we really need such a specific factory method? Can it maybe be a generic factory method that gets its specificity via arguments and data?

2020-10-01 13:59 UTC, VWSCoronaDashboard8 commented on src/components/chloropleth/tooltips/region/hospitalAdmissionsTooltip.tsx
> +export const createRegionHospitalAdmissionsTooltip = (router: NextRouter) => (
Same comment here.

2020-10-05 07:21 UTC, VWSCoronaDashboard1 approved these changes

2020-10-05 07:21 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/municipal/hospitalAdmissionsTooltip.tsx
> +                  ? `${context.value} / 100.000`
hospital admissions are not indicated per 100.000, here just the value needs to be displayed, AFAIK. Double check with the UX to be sure.

2020-10-05 07:21 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/region/hospitalAdmissionsTooltip.tsx
> +                  ? `${context.value} / 100.000`
same here, not per 100k, I think. Double check please.

2020-10-05 09:36 UTC, VWSCoronaDashboard1 requested changes

2020-10-05 09:36 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/tooltipContent.tsx
> +export function Tooltip(props: IProps) {
the file is called tooltipContent, yet the component is called Tooltip? Better call the component TooltipContent ;)

2020-10-05 09:36 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/tooltipContent.tsx
> +            <strong>{children}</strong>
I would remove the `<strong/>` component and add that to the place where you use this component. In theory its possible that a future tooltip will not want its contents in bold, and/or the content will be more complex than just some text. (The escalation tooltip comes to mind)

2020-10-05 09:36 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/tooltipContent.tsx
> +            <strong>{children}</strong>
Speaking of the escalation tooltip, that is still implemented as an exception, with the current changes that can be implemented using the new TooltipContent component

2020-10-05 11:53 UTC, VWSCoronaDashboard1 requested changes

2020-10-05 11:53 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/tooltipContent.tsx
>    const { title, onSelectRegion, children } = props;
onSelectRegion is probably the wrong name for this prop, since this is a generic tooltip. Better call it onSelect, or simply onClick.

2020-10-05 12:53 UTC, VWSCoronaDashboard1 approved these changes

2020-10-05 12:53 UTC, VWSCoronaDashboard1 commented on src/components/chloropleth/tooltips/tooltipContent.tsx
> +      {<div className={styles.tooltipInfo}>{children}</div>}
```suggestion
      <div className={styles.tooltipInfo}>{children}</div>
```
I think the outer parentheses are no longer necessary

2020-10-05 12:57 UTC, merged