Validator and code generator port to typescript
minvws/nl-covid19-data-dashboard pull request #521
Opened 2020-10-02 12:33 UTC by VWSCoronaDashboard1

## Summary

As the title suggests

## Motivation

Tech debt

## Detailed design

The validation and code generation code was moved from the schema directory into the src/tools directory.
The javascript sources were ported to typescript and the yarn commands updated accordingly.

## Drawbacks

n/a

## Alternatives

n/a

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-10-02 14:30 UTC, VWSCoronaDashboard8 requested changes

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/tsconfig.json
> +{
Was there a need to create a separate tsconfig? I suspect you could have re-used the existing one in the project root.

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/code-generation/generate-typescript.ts
> +function saveFile(typescriptSources: string) {
Nitpick; maybe call it typeDefinitions or something.

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/validator/getSchemaNames.ts
> +  });
```suggestion
  return contents.filter((item) => fs
      .lstatSync(path.join(schemaDirectoryPath, item))
      .isDirectory());
```

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/validator/schemaValidator.ts
> +import Ajv, { ValidateFunction } from 'ajv';
What a shitty name for a library. How are we supposed to know what ajv does? 😅

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/validator/schemaValidator.ts
> +  init(): Promise<ValidateFunction> {
Is the return type annotation necessary here? What does it think you will return?

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/validator/schemaValidator.ts
> +    }) as Promise<ValidateFunction>;
I suspect this already tell the function everything

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/validator/schemaValidator.ts
> +export class SchemaValidator {
The fact that this is class is a bit confusing. The class reads and does things on init() / construction, but doesn't actually have any members that are being called after instantiation it seems. It could have simply been a function that gets passed the correct data and performs its task. It would make the code simpler and easier to understand.

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/validator/validate-json.ts
The reduce makes it way more complicated than needed. And I personally like to prefix promised results with "promised". I suggest doing this:

```
const promisedValidationResults = Object.keys(schemaToJsonLookup).map(schemaName => validate(schemaName, schemaToJsonLookup[schemaName]))
```

2020-10-02 14:30 UTC, VWSCoronaDashboard8 commented on src/tools/validator/validate-single.ts
> +if (cliArgs.length !== 2) {
There are some nice libraries to help with this type of thing, like [meow](https://www.npmjs.com/package/meow)

2020-10-02 14:34 UTC, VWSCoronaDashboard1 commented on src/tools/tsconfig.json
> +{
well, you suspect wrong ;)

2020-10-02 14:34 UTC, VWSCoronaDashboard1 commented on src/tools/code-generation/generate-typescript.ts
> +function saveFile(typescriptSources: string) {
fair enough

2020-10-02 14:36 UTC, VWSCoronaDashboard1 commented on src/tools/validator/schemaValidator.ts
> +  init(): Promise<ValidateFunction> {
it might not be, but I don't see this as a carnal sin in this instance, it doesn't clutter the sources or anything. But I can remove it.

2020-10-02 14:38 UTC, VWSCoronaDashboard1 commented on src/tools/validator/schemaValidator.ts
> +    }) as Promise<ValidateFunction>;
Indeed. The extra cast is necessary because the Ajv definitions are wrong. The definitions claim it returns PromiseLike, but instead we get an actual Promise. PromiseLike doesn't contain a definition for the catch() method, which I use downstream so I had to hack the cast in here.

2020-10-02 17:07 UTC, VWSCoronaDashboard1 commented on src/tools/validator/schemaValidator.ts
> +import Ajv, { ValidateFunction } from 'ajv';
Its an acronym for 'Another JSON Validator', which is arguably the least inventive name possible. Its the most widely used one though, so we'll have to make due.

2020-10-02 17:09 UTC, VWSCoronaDashboard1 commented on src/tools/validator/schemaValidator.ts
> +export class SchemaValidator {
Init was a poorly named class method, reality is that the init was invoked multiple times so it needed a rename. I've refactored the class into an async factory method called createValidateFunction

2020-10-02 17:13 UTC, VWSCoronaDashboard1 commented on src/tools/validator/validate-single.ts
> +if (cliArgs.length !== 2) {
I've added meow because it does some nice boilerplate stuff. Unfortunately, it only performs flag validation and not parameter validation (or at least not according to the docs) so it didn't really clean up a lot IMHO.

As a general comment to the above comments: I took the time to beautify stuff because today is my day off. These tools were written in a hurry and are also not really subjected to an elaborate future of modification, so I won't spend much more time fixing nitpicks on it after this ;)

2020-10-05 07:25 UTC, VWSCoronaDashboard8 approved these changes
👍

2020-10-05 07:25 UTC, VWSCoronaDashboard8 commented on src/tools/validator/getSchemaNames.ts
> +  const contents = fs.readdirSync(schemaDirectory);
nitpick; not really a need to store the intermediate results.

2020-10-05 07:25 UTC, VWSCoronaDashboard8 commented on src/tools/validator/validate-json.ts
> +  const validateFunction = await createValidateFunction(
Nitpick; If you only ever call the validator once in a script pass, there was not really a need for a factory function I think. You could have just passed the data together with the other arguments in a single function call.

2020-10-05 07:25 UTC, VWSCoronaDashboard8 commented on src/tools/validator/validate-json.ts
> +    if (!valid) {
```suggestion
    const isValid = validateFunction(data);
    if (!isValid) {
```

or 

```suggestion
    if (!validateFunction(data)) {
```

2020-10-05 07:27 UTC, VWSCoronaDashboard4 requested changes
Looking good :100: Some methods miss a typescript return where they would be handy. The docblocks do not add much value and are sometimes not aligned with the params/returns types.

2020-10-05 07:27 UTC, VWSCoronaDashboard4 commented on src/tools/code-generation/generate-typescript.ts
> + * @param schemaName the given schema name
I'd remove these @param and @returns, and add the Typescript return type the TS way

2020-10-05 07:27 UTC, VWSCoronaDashboard4 commented on src/tools/validator/createValidateFunction.ts
> +function loadSchema(basePath: string, uri: string): Promise<any> {
Same for the @params and @returns in this file

2020-10-05 07:31 UTC, merged