chore: add properties to schema (for absolute nr positively tested people in tooltip)
minvws/nl-covid19-data-dashboard pull request #529
Opened 2020-10-05 15:05 UTC by VWSCoronaDashboard5

## Summary

This PR adds the properties required to the schemas in order to show the absolute number of positive tested people to the tooltips in the chloropleths of regional and municipality. This data is not yet in place, so in order to complete this feature request, the schema must first be updated.

### Governance

- [ ] Documentation is added
- [] Test cases are added or updated
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-10-05 15:44 UTC, VWSCoronaDashboard4 commented
Can you run `yarn generate-typescript` and commit the generated type definitions?

2020-10-06 13:25 UTC, VWSCoronaDashboard8 requested changes

2020-10-06 13:25 UTC, VWSCoronaDashboard8 commented on src/types/data.d.ts
> +  total_positive_tested_people?: number;
Why is this value optional? I suspect it should be added to the required field in the schema.

2020-10-06 13:25 UTC, VWSCoronaDashboard8 commented on src/types/data.d.ts
> +  total_positive_tested_people?: number;
Same here.

2020-10-06 13:25 UTC, VWSCoronaDashboard8 commented on schema/municipalities/positive_tested_people.json
> +      "type": "number"
number is a floating point. Unless this is an average I think it should be integer

2020-10-06 15:13 UTC, VWSCoronaDashboard5 commented on src/types/data.d.ts
> +  total_positive_tested_people?: number;
my assumption is that the generated `data.d.ts` file made this value optional because the `"total_positive_tested_people"` was not included in the `required` array in `schema/x/positive_tested_people.json`. The reason why I left it out for now is because if this PR gets merged before we receive the data from the backend, the schema's will cause errors (for missing values).

2020-10-06 16:49 UTC, VWSCoronaDashboard8 commented on src/types/data.d.ts
> +  total_positive_tested_people?: number;
Yes that's what I meant with the required field. I don't think it will generate errors, only for the validate script but that is not being run anywhere automatically. 

I think it's odd to code on types that are not correct, because you are likely to forget to change them afterwards. I have been working also with JSONs today that did not match the schema yet. It was no issue for me. @VWSCoronaDashboard1 Can you confirm?

2020-10-06 19:44 UTC, VWSCoronaDashboard1 commented on src/types/data.d.ts
> +  total_positive_tested_people?: number;
The schema validations are only run automatically in the production build pipe, so yes, we don't have to make stuff optional anymore to prevent the develop build from breaking

2020-10-07 09:00 UTC, VWSCoronaDashboard8 approved these changes
Change the PR title before merging because it is not very informative or correct. I would suggest something like this:

"Add municipalities total_positive_tested_people to required properties list"

2020-10-07 09:07 UTC, merged