remove blue bars and implement metric components (sidebar and pages)
minvws/nl-covid19-data-dashboard pull request #631
Opened 2020-10-14 15:48 UTC by VWSCoronaDashboard5

## Summary

Brief explanation of the feature, and describe how other developers can test and see your implementation.

## Motivation

Why are we doing this? What use cases does it support? What is the expected
outcome?

Please focus on explaining the motivation so that if this PR is not accepted,
the motivation could be used to develop alternative solutions. In other words,
enumerate the constraints you are trying to solve without coupling them too
closely to the solution you have in mind.

## Detailed design

This is the bulk of the PR. Explain the design in enough detail for somebody
familiar with Opus to understand, and for somebody familiar with the
front-end to implement. This should get into specifics and corner-cases,
and include examples of how the feature is used. Any new terminology should be
defined here.

## Drawbacks

Why should we _not_ do this? Please consider:

- implementation cost, both in term of code size and complexity
- maintenance cost, how complex is the solution and how prone to change is it?
- integration of this feature with other existing and planned features

There are tradeoffs to choosing any path. Attempt to identify them here.

## Alternatives

What other designs have been considered? What is the impact of not doing this?

## Unresolved questions

Optional, but suggested for bigger features. What parts of the design are still
TBD or not implemented? How will you deal with that in the future?

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-10-15 16:00 UTC, VWSCoronaDashboard8 reviewed
There's a lot of ? and undefined checks on data that I think should just be there, but maybe it's a result of wrong types generated on json schemes that didn't set properties as required.

I suspect a lot of them can be cleared out though.

2020-10-15 16:00 UTC, VWSCoronaDashboard8 commented on src/components/layout/MunicipalityLayout.tsx
> +                            data={getSewerWaterBarScaleData(data) ?? undefined}
What is `?? undefined ` for? If the getData function returns data or undefined you can just pass it like that.

2020-10-15 16:00 UTC, VWSCoronaDashboard8 commented on src/components/metricKPI/index.tsx
> +  label?: string;
I think title is a better name, looking at how you used it in the other components

2020-10-15 16:00 UTC, VWSCoronaDashboard8 commented on src/components/metricKPI/index.tsx
> +  format: any | false;
Why false and not just define it as an optional property?

2020-10-19 07:00 UTC, VWSCoronaDashboard8 commented on src/components/metricKPI/index.tsx
> +  format: any | false;
Also the function signature for "format" should be clear, instead of using any. for example `(number | string) => string`

2020-10-19 11:41 UTC, VWSCoronaDashboard5 commented on src/pages/veiligheidsregio/[code]/rioolwater.tsx
> +              {formatNumber(barScaleData?.value)}
passing it its data through the memoized `barScaleData` (from `getSewerWaterBarScaleData`) does not make sense, i'll change this right away.

2020-10-19 12:12 UTC, VWSCoronaDashboard5 commented on src/pages/veiligheidsregio/[code]/rioolwater.tsx
> +              {formatNumber(barScaleData?.value)}
however, i think it is better to change this in a separate PR to avoid mixing concerns

2020-10-20 09:27 UTC, VWSCoronaDashboard8 requested changes

2020-10-20 09:27 UTC, VWSCoronaDashboard8 commented on src/components/common/nursing-home-infected-locations-metric.tsx
> +  if (!data) return null;
nitpick; it would make more sense to do this check first, before you start using the data. That applies to all metric components below as well.

Then I think you should be able to assume that data.date_of_insertion_unix is always available, if the type definitions are correct, so you don't need the ternary `? :`

2020-10-20 09:27 UTC, VWSCoronaDashboard8 commented on src/components/metricKPI/index.tsx
> +  value: number | undefined;
```suggestion
  value?: number;
```

2020-10-20 09:27 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/verpleeghuis-positief-geteste-personen.tsx
> +          <h3>
I don't think semantically this should be a h3 element. There is already one above it.

2020-10-20 09:27 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/verpleeghuis-sterfte.tsx
> +          <h3>
Same comment about h3

2020-10-20 09:27 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +          <h3>
etc

2020-10-20 09:27 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/rioolwater.tsx
> +              {formatNumber(barScaleData?.value)}
h3 again

2020-10-20 09:27 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/verpleeghuis-besmette-locaties.tsx
> +          <h3>
I think you get my point ;)

2020-10-20 09:41 UTC, VWSCoronaDashboard commented on src/components/metricKPI/index.tsx
> +      <p className={styles.title}>{title}</p>
Semantically this might need to be a smaller heading.

2020-10-20 09:42 UTC, VWSCoronaDashboard commented on src/components/metricKPI/styles.module.scss
> +  margin-left: 1em !important;
This is why you should not do `.wrapper > p` and always target classnames. It prevents specificity issues.

2020-10-20 10:49 UTC, merged