GGD progress over time charts on country and region pages
minvws/nl-covid19-data-dashboard pull request #714
Opened 2020-10-23 12:33 UTC by VWSCoronaDashboard1

## Summary

This adds two charts to the country and region 'positive tested people' pages. A percentage over time and total numbers over time. The total numbers chart shows the total tests and total positive tests in one chart.

## Motivation

Feature request

## Detailed design

For the 'total numbers' chart a new linechart component was added called MultineChart.
Both positive tested pages (region + country) have been refactored to use the new styled system components, therefore this PR is slightly bigger than absolutely necessary.
A few new styled components were added for the choropleth layout. Plus a generic KpiSection that spans the entire column. And an Anchor component for, surprise, anchor links.

## Drawbacks

n/a

## Alternatives

n/a

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-10-23 12:57 UTC, VWSCoronaDashboard4 commented on src/components/lineChart/hooks/useRegionalSewerWaterChartOptions.ts
> +      getFilteredValues(averageValues, timeframe, (value) => value.date * 1000),
milliseconds / seconds deja vu here ...

2020-10-23 12:57 UTC, VWSCoronaDashboard4 commented on src/components/lineChart/multipleLineChart.tsx
> +        rangeDescription: 'Range: 2010 to 2017',
What is this description?

2020-10-23 12:57 UTC, VWSCoronaDashboard4 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            <Heading level={4} fontSize={'1.2em'} mt={'1.5em'} mb={0}>
I'm not so sure about moving the values for fontsizes to the templates, that is a guaranteed way to get inconsistencies in the typography

2020-10-23 12:57 UTC, VWSCoronaDashboard4 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            <Heading level={4} fontSize={'1.2em'} mt={'1.5em'} mb={0}>
Use the `as` prop of heading to specify a different size

2020-10-23 13:19 UTC, VWSCoronaDashboard1 commented on src/components/lineChart/hooks/useRegionalSewerWaterChartOptions.ts
> +      getFilteredValues(averageValues, timeframe, (value) => value.date * 1000),
is exactly the same as in the other linechart

2020-10-23 13:20 UTC, VWSCoronaDashboard1 commented on src/components/lineChart/multipleLineChart.tsx
> +        rangeDescription: 'Range: 2010 to 2017',
good catch, something hardcoded that is also still in the other linechart as well. This is accessibility related, so not rendered on screen so I guess that is why it flew under the radar

2020-10-23 13:21 UTC, VWSCoronaDashboard1 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            <Heading level={4} fontSize={'1.2em'} mt={'1.5em'} mb={0}>
These values are outliers, they're not in the theme. I think there first needs to be some kind of consensus over the spacings. Right now I kept them in to keep this page exactly the same as it looked in the first HTML/CSS incarnation.

2020-10-23 13:26 UTC, VWSCoronaDashboard8 requested changes

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +        <KpiTile title={text.barscale_titel} data-cy="infected_daily_increase">
If this is that the ...props "any" thing was for maybe we can add it to props explicitly. There will not be a huge amount of component for which we need cypress handles I hope.

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
>            {delta && (
If there is no delta, and it shows no bar scale, do we still want to show the tile with title and description and all? I would think it makes sense to then hide the whole thing.

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +          <Text>{text.kpi_toelichting}</Text>
kpi-tile has a prop for description, so please use that. If this one needs to look different we need to update the abstraction somehow.

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +          <Box>
I'm not sure what this box with anchor link is but I feel it can be its own component abstraction. I don't mind if you leave this for later though.

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +      <KpiSection>
I think you can use the LineChartTile component here.

So far the KPI components have been about numbers and bar scales, so all data except the charts. We can discuss if the naming is correct, but I think it would make sense to make the KpiSection so that it can handle the two column layout with title, description and then something in the right column as children.

Basically what is happening below with the flex 50% 👇 

I don't know about the naming. TwoColumnKpiTile or something? 😅

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +          <Text>{ggdText.totaal_getest_week_uitleg}</Text>
Use description prop instead

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +          <Text>{ggdText.positief_getest_week_uitleg}</Text>
Same

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +          <Text>
For this one we could have an extra optional prop if this is a common addition to the normal description.

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +      <KpiSection>
```suggestion
      <LineChartTile>
```

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +      <KpiSection>
```suggestion
      <LineChartTile>
```

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +          <Text>{text.barscale_toelichting}</Text>
Description prop

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +          <Text>{text.kpi_toelichting}</Text>
Same

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +              <Anchor anchorName="ggd" text={ggdText.summary_link_cta} />
I've seen this pattern before :) Might be worth capturing this in a component like I mentioned earlier

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +      <KpiSection>
```suggestion
      <LineChartTile>
```

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +          <Text>{ggdText.totaal_getest_week_uitleg}</Text>
description prop

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +          <Text>{ggdText.positief_getest_week_uitleg}</Text>
same

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +          <KpiValue absolute={ggdData.infected_percentage_daily} />
Looks like you want to use the percentage prop for this

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +      <KpiSection>
```suggestion
      <LineChartTile>
```

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +      <KpiSection>
Same

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/style/theme.ts
> +type TMediaQueries = typeof mediaQueries;
I prefer not to prefix types and interface names. If you do, we need to make that choice and stick with it.

2020-10-23 13:26 UTC, VWSCoronaDashboard8 commented on src/style/theme.ts
> +type TDashboardTheme = ScaleThemeProperties &
What's all this typing for anyway? I don't remember seeing how this is used. Styled-system theme values are not typed AFAIK

2020-10-23 13:29 UTC, VWSCoronaDashboard1 commented on src/components-styled/kpi-value.tsx
> +export function KpiValue({ absolute, percentage, ...props }: KpiValueProps) {
I've added these generic props so that its easy to stick data-* attributes on the HTML elements. These are necessary for the Cypress tests.

2020-10-23 13:30 UTC, VWSCoronaDashboard1 commented on src/components-styled/two-kpi-section.tsx
> +export function TwoKpiSection({ children, ...props }: TwoKpiSectionProps) {
See my previous comment. If you know of a generic way to add data- attributes then I these can be removed.

2020-10-23 13:30 UTC, VWSCoronaDashboard1 commented on src/pages/veiligheidsregio/[code]/positief-geteste-mensen.tsx
> +          <KpiValue absolute={ggdData.infected_percentage_daily} />
Oops, good catch

2020-10-23 13:33 UTC, VWSCoronaDashboard1 commented on src/style/theme.ts
> +type TDashboardTheme = ScaleThemeProperties &
These types come from the styled system definitions. I'm only typing them to guard against future changes. You might know by heart exactly how to name things, but another developer might not. This at least guards against simple typos.

2020-10-23 13:44 UTC, VWSCoronaDashboard1 commented on src/components-styled/choropleth/choropleth-legend.tsx
> +export const ChoroplethLegend = styled(Box)(
These components are used on multiple pages, so they're definitely not local. I'm ok with putting them all in one file under layout.

2020-10-23 15:00 UTC, VWSCoronaDashboard1 commented on src/components-styled/kpi-section.tsx
> +    {...(props as any)}
Me too, but we've had the same issue in the Heading component. I haven't figured out why the compiler refuses to accept this. But for now I had to get thing working.

2020-10-24 07:20 UTC, VWSCoronaDashboard8 commented on src/style/theme.ts
> +type TDashboardTheme = ScaleThemeProperties &
I'm all for typing, but I was under the impression that everywhere you use theme variables in styled system (in the css({}) objects and directly on the props) are in no way type checked. So my question was really where are these types used? I don't see how they would prevent typos

2020-10-24 07:24 UTC, VWSCoronaDashboard8 commented on src/style/theme.ts
> +type TDashboardTheme = ScaleThemeProperties &
Ah ok I see your point in how it might be useful to import the types from styled system so that the theme definition is compatible, but afaik the theme definition is quite flexible in that you can add aliases and variants and other things. So I still doubt you can make it strict. 

My point was more about the "typeof" interfaces that are generated here. I don't think they can be applied within ss

2020-10-24 07:25 UTC, VWSCoronaDashboard8 commented on src/components-styled/choropleth/choropleth-legend.tsx
> +export const ChoroplethLegend = styled(Box)(
👍 When I made the comment I didn't yet see how you constructed the layout.

2020-10-26 09:27 UTC, merged