align header metadata icons on flex-start
minvws/nl-covid19-data-dashboard pull request #755
Opened 2020-10-27 09:05 UTC by VWSCoronaDashboard5

## Summary

This PR aligns the icons (clock-icon and source-icon both places in `<span>` elements), to the start of their flex-containers. Since the `svg` elements of the icons are rather small, the icons would be aligned slightly above the text. This is why the `margin-top` is added. Conventionally you would address this with a `classname` to avoid specificity issues, but since the `css` is imported and its styles apply locally, assigning the styles to `span` wouldn't cause any effects on other elements.

### Governance

- [x] Documentation is added
- [x] Test cases are added or updated
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-10-27 09:39 UTC, VWSCoronaDashboard commented on src/components/contentHeader/metadata.module.scss
> +    margin-top: 4px;
This is why we need to look into https://seek-oss.github.io/capsize/

2020-10-27 09:39 UTC, VWSCoronaDashboard approved these changes

2020-10-27 10:36 UTC, VWSCoronaDashboard1 approved these changes

2020-10-27 12:07 UTC, VWSCoronaDashboard8 requested changes
There are 2 other contentHeader components which are hacks based on this one (right next to it in the components folder). I suspect you need to apply these changes there too.

2020-10-29 10:56 UTC, VWSCoronaDashboard8 approved these changes

2020-10-29 12:37 UTC, merged