Generate sitemap on build w/ generate-sitemap.ts
minvws/nl-covid19-data-dashboard pull request #757
Opened 2020-10-27 09:43 UTC by VWSCoronaDashboard9

## Summary

Brief explanation of the feature, and describe how other developers can test and see your implementation.

## Motivation

Why are we doing this? What use cases does it support? What is the expected
outcome?

Please focus on explaining the motivation so that if this PR is not accepted,
the motivation could be used to develop alternative solutions. In other words,
enumerate the constraints you are trying to solve without coupling them too
closely to the solution you have in mind.

## Detailed design

This is the bulk of the PR. Explain the design in enough detail for somebody
familiar with Opus to understand, and for somebody familiar with the
front-end to implement. This should get into specifics and corner-cases,
and include examples of how the feature is used. Any new terminology should be
defined here.

## Drawbacks

Why should we _not_ do this? Please consider:

- implementation cost, both in term of code size and complexity
- maintenance cost, how complex is the solution and how prone to change is it?
- integration of this feature with other existing and planned features

There are tradeoffs to choosing any path. Attempt to identify them here.

## Alternatives

What other designs have been considered? What is the impact of not doing this?

## Unresolved questions

Optional, but suggested for bigger features. What parts of the design are still
TBD or not implemented? How will you deal with that in the future?

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-10-27 09:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=757) it.</sub>

2020-10-27 12:36 UTC, VWSCoronaDashboard4 commented on src/tools/sitemap/generate-sitemap.js
> +        <loc>https://coronadashboard.rijksoverheid.nl/</loc>
The domain variable can also be applied here.

2020-10-27 12:36 UTC, VWSCoronaDashboard4 commented on src/tools/sitemap/generate-sitemap.js
> +  n + 1 < 10 ? `VR0${n + 1}` : `VR${n + 1}`
Nitpick: you can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart for this, since you don't have to worry about old browsers/polyfills for this.

2020-10-27 12:36 UTC, VWSCoronaDashboard4 commented on src/tools/sitemap/generate-sitemap.js
> +  const formatted = prettier.format(sitemap, {
Neat!

2020-10-27 13:31 UTC, VWSCoronaDashboard4 approved these changes

2020-10-27 15:03 UTC, VWSCoronaDashboard requested changes
Maybe the sitemap should not be part of the git history. We're building a different one for each language? I'd say remove it and add it to gitignore?

2020-10-27 15:29 UTC, VWSCoronaDashboard8 approved these changes
Very nice! 💯

2020-10-27 15:29 UTC, VWSCoronaDashboard8 commented on src/tools/sitemap/generate-sitemap.js
> +      priority: priority != undefined ? priority.value : 0.6,
nitpick; !==

Or maybe better
```suggestion
      priority: priority?.value ?? 0.6
```
But now I doubt if ?? is available outside of TS

2020-10-27 15:29 UTC, VWSCoronaDashboard8 commented on src/tools/sitemap/generate-sitemap.js
> +  const allPaths = pathsWithPriorities.filter(
I find it a little odd that "all paths" are a filtered version of "paths with priorities". Going by the names I would expect the opposite :)

2020-10-28 09:55 UTC, VWSCoronaDashboard commented on src/tools/sitemap/generate-sitemap.js
> +      priority: priority != undefined ? priority.value : 0.6,
TS is not the issue, it's that NodeJS needs to support this, but that's easy to try out. These files and the webpack config file are not transpiled.

2020-10-28 14:16 UTC, VWSCoronaDashboard8 commented on src/tools/sitemap/generate-sitemap.js
> +      priority: priority != undefined ? priority.value : 0.6,
Yes, that's what I mean. The current version of javascript (supported by Node.js) is likely not recognizing this. You'll have to stick with the node version used in the build pipeline I guess.

2020-10-28 14:53 UTC, VWSCoronaDashboard approved these changes

2020-10-29 11:09 UTC, VWSCoronaDashboard7 submitted a review, later dismissed
Since we're introducing a new environmental, we should update the Dockerfile in this PR as well to make sure the sitemap is correctly generated at build time.

2020-10-29 11:12 UTC, VWSCoronaDashboard7 commented on src/tools/sitemap/generate-sitemap.js
> +      priority: priority != undefined ? priority.value : 0.6,
> Yes, that's what I mean. The current version of javascript (supported by Node.js) is likely not recognizing this. You'll have to stick with the node version used in the build pipeline I guess.

If this is correct, the node version in use would be the one as defined in the Dockerfile from this repository. So there's a degree of control there.

2020-10-29 11:14 UTC, VWSCoronaDashboard commented
> Since we're introducing a new environmental, we should update the Dockerfile in this PR as well to make sure the sitemap is correctly generated at build time.

`NEXT_PUBLIC_LOCALE` has been in the codebase for a while now, but we should double-check if everything works as expected when merged to develop.

2020-10-29 11:18 UTC, merged