Update sewer schemas to use corrected values and unify naming of things
minvws/nl-covid19-data-dashboard pull request #760
Opened 2020-10-27 11:38 UTC by VWSCoronaDashboard8

* Update sewer schemas replacing `rna_per_ml` with `rna_corrected`
* Rename sewer schema metric keys and to be consistent
* Rename schema types to be consistent

This is still missing the choropleth schema definition for regions.

2020-10-27 12:23 UTC, VWSCoronaDashboard4 commented on schema/municipal/sewer_per_installation.json
> +        "rna_corrected",
for other places where an adjustment has been made, the term "normalized" is in use:

"In the simplest cases, normalization of ratings means adjusting values measured on different scales to a notionally common scale, often prior to averaging." `</wikipedia>`

2020-10-27 13:51 UTC, VWSCoronaDashboard8 commented on schema/municipal/sewer_per_installation.json
> +        "rna_corrected",
I considered it, but I wasn't sure if normalized maybe also means scaling the values to a prefixed range. I will use that term then 👍

2020-10-27 14:58 UTC, VWSCoronaDashboard4 approved these changes

2020-10-27 17:11 UTC, VWSCoronaDashboard1 approved these changes

2020-10-28 17:47 UTC, VWSCoronaDashboard1 approved these changes

2020-10-28 17:47 UTC, VWSCoronaDashboard1 commented on schema/municipal/__index.json
> +  "additionalProperties": true,
is this temporary? if not, why do we allow additional properties?

2020-10-28 18:20 UTC, VWSCoronaDashboard8 commented on schema/municipal/__index.json
> +  "additionalProperties": true,
I figured on the root level it can't hurt. For example then I can merge the PR about behavior, without breaking the build pipeline until we have data for behavior.

It makes the transition to new data a little easier I think, and I can not think of a scenario where this causes issues.

2020-10-29 07:58 UTC, VWSCoronaDashboard1 commented on schema/municipal/__index.json
> +  "additionalProperties": true,
Aha, ok, so its temporary, no problem then

2020-10-29 08:07 UTC, VWSCoronaDashboard8 commented on schema/municipal/__index.json
> +  "additionalProperties": true,
Well not necessarily temporary. I don't see a problem enabling this always. Can you think of a scenario where this is problematic? Your app needs to know what all required data is available at root level. Any additional things won't hurt. It's different for properties in nested levels because that would bloat the data.

2020-10-29 08:19 UTC, VWSCoronaDashboard1 commented on schema/municipal/__index.json
> +  "additionalProperties": true,
It won't break anything true. It might just feel weird that on production there could be data in there that's unused, but since we pull out only the parts that we need it shouldn't be a problem.

2020-10-30 12:28 UTC, VWSCoronaDashboard4 approved these changes

2020-10-30 12:28 UTC, VWSCoronaDashboard4 commented on src/utils/sewer-water/municipality-sewer-water.util.ts
> + */
This refactor clears up a lot of things! :100:

2020-10-30 12:28 UTC, VWSCoronaDashboard4 commented on schema/municipal/__index.json
> +    "sewer": {
Have you considered naming this eg `sewer_averages` ? Now it could read like `sewer` contains all sewer related data, which that is not the case.

2020-10-30 13:10 UTC, VWSCoronaDashboard1 requested changes

2020-10-30 13:10 UTC, VWSCoronaDashboard1 commented on schema/regions/sewer.json
> +      "pattern": "^VR[0-9]+$"
```suggestion
      "equalsRootProperty": "code"
```
This checks if the vrcode is the same as the 'code' property in the root file.

2020-10-30 13:10 UTC, VWSCoronaDashboard1 commented on src/components/landelijk/sewer-water-barscale.tsx
> +import { NationalSewer } from '~/types/data.d';
A national sewer, how bad do you reckon would smell that? ;)

2020-10-30 13:21 UTC, VWSCoronaDashboard8 commented on schema/municipal/__index.json
> +    "sewer": {
Yes, that would have been a good name, but the value property inside sewer is already named "average". This way we could add more values than just averages. For example it also has the installation count, but I guess that is also linked to the average kind of. In any case I don't think the name is wrong or that confusing at the moment.

2020-11-03 11:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=760) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=760) before we can accept your contribution.<br/>**1** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: VWSCoronaDashboard1<br/>:x: VWSCoronaDashboard<br/>:x: VWSCoronaDashboard4<br/>:x: VWSCoronaDashboard8<br/>:x: VWSCoronaDashboard5<br/>:x: VWSCoronaDashboard10<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=760) it.</sub>

2020-11-03 13:00 UTC, VWSCoronaDashboard4 commented on src/pages/gemeente/[code]/rioolwater.tsx
> +        {barScaleData && barScaleData.value && (
What if `barScaleData.value === 0` ?

2020-11-03 13:03 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/rioolwater.tsx
> +        {barScaleData && barScaleData.value && (
yup good catch :)

2020-11-03 13:03 UTC, VWSCoronaDashboard1 approved these changes

2020-11-03 13:05 UTC, merged