Feature/collapsable styled system
minvws/nl-covid19-data-dashboard pull request #778
Opened 2020-10-28 16:29 UTC by VWSCoronaDashboard4

## Summary

Use styled-system for the collapsable component.

Also fixes clipping bug on-resize.

## Detailed design

* This enhances the third party components from Reach with styled components, to supply our styles.
* The logic for animating is adjusted. Fully opened panels do not have the max-height any more, and a isAnimating property controls the max-height during the animation. Some other code became unnesscary by using that approach, so overall it clears up some things too.

## Unresolved questions

For the previous version I wrote the hook `useWindowResizeDebounce`, which is not used any more. Shall I remove that?

2020-10-28 16:56 UTC, VWSCoronaDashboard1 requested changes

2020-10-28 16:56 UTC, VWSCoronaDashboard1 commented on src/components-styled/collapsable.tsx
> +      Array.from(links).forEach((link) => {
Array.from, is that supported by IE11 or polyfilled?
https://caniuse.com/?search=Array.from

2020-10-28 17:46 UTC, VWSCoronaDashboard8 commented on src/components-styled/collapsable.tsx
> +      Array.from(links).forEach((link) => {
I think TS transpiles to the set target in config, which is I believe es5

2020-10-28 18:01 UTC, VWSCoronaDashboard8 requested changes

2020-10-29 09:34 UTC, VWSCoronaDashboard1 commented on src/components-styled/collapsable.tsx
> +      Array.from(links).forEach((link) => {
We've had issues with things like this before, so I'm not entirely clear what typescript transpiles and what not. So, I guess we'll just have to test it.

2020-10-29 10:06 UTC, VWSCoronaDashboard10 requested changes
Spotted at least one bug :-)

2020-10-29 10:06 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +  }, []); // should not use dependencies in array: use effect mimics mount / unmount
This is buggy: your component will now always trigger the `checkLocationHash` which is initially defined using the initial value of `id`. The moment the `id` variable mutates, you will not be checking the location hash against the new value of `id`.

It's perfectly fine to remove/attach the event listener when the callback changes:


```suggestion
  useEffect(() => {
    window.addEventListener('hashchange', checkLocationHash, false);
    return () => {
      window.removeEventListener('hashchange', checkLocationHash, false);
    };
  }, [checkLocationHash]);
```

2020-10-29 10:06 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +          }}
Do we need to pass a `style` prop? I think this translates to inline styles, doesn't styled-system has something like a `cx` or `css` prop so styles will be applied with classnames?

2020-10-29 10:21 UTC, VWSCoronaDashboard8 commented on src/components-styled/collapsable.tsx
> +  let panelReference: HTMLDivElement | undefined = undefined;
Do you need to pass null? I'm trying to get everyone to avoid null as much as possible :)

2020-10-29 10:24 UTC, VWSCoronaDashboard8 commented on src/components-styled/collapsable.tsx
> +          }}
Good catch

2020-10-29 11:05 UTC, VWSCoronaDashboard4 commented on src/components-styled/collapsable.tsx
> +  let panelReference: HTMLDivElement | undefined = undefined;
I'll add a comment about why I did this in the code; `panelReference` is used as a dependency for the useCallback hook, and React errors that it is used before it is defined if I remove initial setting to undefined.

2020-10-29 11:32 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +  let panelReference: HTMLDivElement | undefined = undefined;
> Do you need to pass null? I'm trying to get everyone to avoid null as much as possible :)

I'm afraid we need to pass `null`, TS will complain when going for `undefined`.

2020-10-29 11:37 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +  let panelReference: HTMLDivElement | undefined = undefined;
I think the `setLinkTabability` can be a regular function/callback instead of having it wrapped in a useCallback hook

2020-10-29 13:21 UTC, VWSCoronaDashboard4 commented on src/components-styled/collapsable.tsx
> +    panelReference = element;
It's what I used in the previous implementation (see deleted collapsable/index); while working on the bug, the reference seemed to get lost from time to time, hence why I converted it to this structure. Since I've also adjusted other things, I'll check if I can use the `useRef` again.

2020-10-29 13:28 UTC, VWSCoronaDashboard4 commented
@VWSCoronaDashboard10 `NodeList.prototype.forEach()` does not work in IE11, and we have not set up anything for it to be transpiled or polyfilled.

2020-10-29 13:48 UTC, VWSCoronaDashboard8 requested changes

2020-10-29 13:48 UTC, VWSCoronaDashboard8 commented on src/components-styled/collapsable.tsx
> +  // };
Comments can be removed I guess

2020-10-29 13:48 UTC, VWSCoronaDashboard8 commented on src/components-styled/collapsable.tsx
> +      Array.from(links).forEach((link) => {
@VWSCoronaDashboard4 Did you forget about this one?

2020-10-29 13:48 UTC, VWSCoronaDashboard8 commented on src/components-styled/collapsable.tsx
> +    color: colors.blue,
You should not have to import colors. Just write "blue" and it should map to the theme, just like paddings etc

2020-10-29 13:48 UTC, VWSCoronaDashboard8 commented on src/components-styled/collapsable.tsx
> +      outline: `1px dashed ${colors.blue}`,
Same here

2020-10-29 13:48 UTC, VWSCoronaDashboard8 commented on src/components-styled/collapsable.tsx
> +      bg: colors.shadow,
etc

2020-10-29 13:52 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +  // let panelReference: HTMLDivElement | undefined = undefined;
comments can be removed

2020-10-29 13:52 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +  // };
same here

2020-10-29 13:52 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +      outline: `1px dashed ${colors.blue}`,
Are you sure that will work here, wrapped inside a string with multiple configuration?

2020-10-29 13:52 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +      Array.from(links).forEach((link) => {
Het mentioned that IE11 doesn't support that method

2020-10-29 13:54 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +      outline: `1px dashed ${colors.blue}`,
I'd assume that it should work using `outline-color: blue` though

2020-10-29 13:55 UTC, VWSCoronaDashboard4 commented
@VWSCoronaDashboard10 Array.from works fine in IE11 with our setup of transpiling

2020-10-29 14:01 UTC, VWSCoronaDashboard8 commented
@VWSCoronaDashboard4 Ah right, I missed your comment about forEach not being supported by IE11 because it was not inline with the subject thread.

2020-10-29 14:47 UTC, VWSCoronaDashboard8 approved these changes

2020-10-29 16:31 UTC, VWSCoronaDashboard10 commented on src/components-styled/collapsable.tsx
> +    <Box as="section" borderTop={`1px solid lightGray`} id={id}>
Can you confirm (with inspect element) that `lightGray` maps to `#dfdfdf` instead of actually being `lightGray`?

2020-10-29 16:46 UTC, VWSCoronaDashboard5 approved these changes

2020-10-29 16:46 UTC, VWSCoronaDashboard5 commented on src/style/theme.ts
> +  lightGray: '#dfdfdf',
we're using both 'grey' and 'gray' throughout the codebase. If we are going to continue using several different grey-tones and both spellings ('grey' and 'gray'), we could write it like:

```
const colors = {
blue: '#01689b',
greys: ['#dfdfdf', '#anotherGreyTone']
}

// followed by:
colors.grays = colors.greys
```

this would allow for a greytone scale that's more easy to read and use, and it would accept both spellings.

2020-10-30 07:29 UTC, merged