Feature/dates everywhere
minvws/nl-covid19-data-dashboard pull request #844
Opened 2020-11-03 15:32 UTC by VWSCoronaDashboard4

## Summary

Add dates, everywhere.

## Detailed design

* Adds new date format (weekday + medium date)
* Adds Metadata component to display date and source in tiles: kpi tiles, linechart tiles etc or used individually.
* Adds KpiTiles to a lot of places
* Adds MultipleLineChartTile
* Adjusts date formatting for content header

To be done next (in a different PR):
* "One column KPI" as proper component
* "KPI with explanation" (as used on Reproduction rate page) as proper component

2020-11-03 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=844) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=844) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=844) it.</sub>

2020-11-03 15:56 UTC, VWSCoronaDashboard8 requested changes

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/components-styled/metadata.tsx
> +  date?: number;
I think we also need to deal with week ranges. Maybe allow dates to be `number | [number, number]` would work for that.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/components/contentHeader/metadata.tsx
> +  if (!dateUnix) return null;
dateUnix is not optional anymore. I changed it recently because we always want to render a date in content header and it prevents not rendering the metadata by accident.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +            date: positivelyTestedPeople?.last_value?.date_of_report_unix,
Redundant ?. here

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +          date={positivelyTestedPeople?.last_value?.date_of_report_unix}
Here too

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +            date: positivelyTestedPeople?.last_value?.date_of_report_unix,
Redundant ?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +            date: positivelyTestedPeople?.last_value?.date_of_report_unix,
Redundant ?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/ziekenhuis-opnames.tsx
> +          date={hospitalAdmissions?.last_value?.date_of_report_unix}
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/ziekenhuis-opnames.tsx
> +            date={hospitalAdmissions?.last_value?.date_of_report_unix}
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/gemeente/[code]/ziekenhuis-opnames.tsx
> +          date={hospitalAdmissions?.last_value?.date_of_report_unix}
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/besmettelijke-mensen.tsx
> +            date={count?.last_value?.date_of_report_unix}
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            date: delta?.last_value?.date_of_report_unix,
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            date: delta?.last_value?.date_of_report_unix,
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/positief-geteste-mensen.tsx
> +            date: delta?.last_value?.date_of_report_unix,
and the rest in this file

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/landelijk/verpleeghuis-besmette-locaties.tsx
> +          <KpiValue absolute={data?.last_value.newly_infected_locations} />
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/verpleeghuis-besmette-locaties.tsx
> +            date: state?.nursing_home.last_value?.date_of_report_unix,
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/verpleeghuis-besmette-locaties.tsx
> +            date: state?.nursing_home.last_value?.date_of_report_unix,
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/verpleeghuis-besmette-locaties.tsx
> +          values={state?.nursing_home.values.map((value) => ({
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/verpleeghuis-besmette-locaties.tsx
> +          values={state?.nursing_home.values.map((value) => ({
Also please rename state to data or something, since it's not state. I've done that in other files where I encountered it.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/verpleeghuis-sterfte.tsx
> +            date={data?.last_value?.date_of_report_unix}
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/verpleeghuis-sterfte.tsx
> +            date={data?.last_value?.date_of_report_unix}
?.

2020-11-03 15:56 UTC, VWSCoronaDashboard8 commented on src/pages/veiligheidsregio/[code]/ziekenhuis-opnames.tsx
> +          date={resultsPerRegion?.last_value?.date_of_report_unix}
?. and the others in this file

2020-11-03 16:36 UTC, VWSCoronaDashboard1 approved these changes

2020-11-03 16:36 UTC, VWSCoronaDashboard1 commented on src/components-styled/metadata.tsx
> +  date?: number;
or create a specific Week type with a start and end property? The usage might be a little clearer in that case. That type is already used in some of the linecharts, so it could be moved into a more general place.

2020-11-03 16:37 UTC, VWSCoronaDashboard1 commented on src/components-styled/metadata.tsx
> +  date?: number;
or create a specific Week type with a start and end property? The usage might be a little clearer in that case. That type is already used in some of the linecharts, so it could be moved into a more general place.

2020-11-03 16:53 UTC, VWSCoronaDashboard8 commented on src/components-styled/metadata.tsx
> +  date?: number;
A specific week type would also be fine with me. There is nothing really weekly about a week type though. It could just be any time range, so we might as well start making it generic. But a middle ground could be to still create a type with explicit start / end timestamps.

2020-11-03 17:02 UTC, VWSCoronaDashboard1 commented on src/components-styled/metadata.tsx
> +  date?: number;
Yea, you're right, simply a TimeRange type with a start and end would make it more flexible

2020-11-04 07:40 UTC, VWSCoronaDashboard4 commented on src/pages/gemeente/[code]/positief-geteste-mensen.tsx
> +            date: positivelyTestedPeople?.last_value?.date_of_report_unix,
The `?.` should be a separate PR, these occur everywhere in these files, for a reason. Removing them would give type errors that the values could be undefined (perhaps not for all of them, but for plenty).

2020-11-04 07:51 UTC, VWSCoronaDashboard4 commented on src/components-styled/metadata.tsx
> +  date?: number;
I'd propose to include this in the next PR (together with what is already listed under "To be done next (in a different PR):"), since this would need some input from the designers/PO.

2020-11-04 08:03 UTC, 0x80 approved these changes

2020-11-04 08:15 UTC, VWSCoronaDashboard10 reviewed
I think I spotted one mistake with an incorrect source, besides that looking good overall  👍

2020-11-04 08:15 UTC, VWSCoronaDashboard10 commented on src/pages/landelijk/ziekenhuis-opnames.tsx
> +          source: text.bronnen.rivm,
sourcedFrom previously had `text.bronnen.lnaz` as source?

2020-11-04 08:21 UTC, VWSCoronaDashboard4 commented on src/pages/landelijk/ziekenhuis-opnames.tsx
> +          source: text.bronnen.rivm,
Good catch!

2020-11-04 08:27 UTC, merged