New schema for infected age groups
minvws/nl-covid19-data-dashboard pull request #916
Opened 2020-11-12 14:50 UTC by VWSCoronaDashboard4

## Summary

Schema for new infected age group.

Compared to the previous version:
* different main key: `infected_age_groups`;
* division of `values` and `last_value` was not properly used in the previous version; adjusted to `age_groups`;
* adjustment of the keys inside `age_groups` objects.

### Example of new structure

NL.json

```json
{
   ...
  "infected_age_groups": {
      "age_groups": [
         {
            "age_group": "0-9",
            "infected_percentage": 1,
            "national_percentage": 7,
            "date_of_insertion": 1605192514,
            "date_of_report_unix": 1605192514
         },
         {
            "age_group": "10-19",
            "infected_percentage": 20,
            "national_percentage": 17,
            "date_of_insertion": 1605192514,
            "date_of_report_unix": 1605192514
         },
        ....
      ]
   }
   ...
}
```

2020-11-12 14:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=916) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=916) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=916) it.</sub>

2020-11-12 15:03 UTC, VWSCoronaDashboard1 requested changes

2020-11-12 15:03 UTC, VWSCoronaDashboard1 commented on schema/national/infected_age_groups.json
> +    "age_groups": {
I think in all of the other schema's these properties are called 'values', even when there's no last_value property. So I'd opt for keeping things consistent and simply calling this one 'values' as well.

2020-11-16 10:42 UTC, VWSCoronaDashboard8 requested changes

2020-11-16 10:42 UTC, VWSCoronaDashboard8 commented on schema/national/infected_age_groups.json
> +  "$id": "infected_age_groups.json",
$id is not being used so you can remove it.

2020-11-16 10:42 UTC, VWSCoronaDashboard8 commented on schema/national/infected_age_groups.json
> +  "title": "infected_age_groups",
The newer schemas use a prefix in the title to make it unique, since the typescript types are generated from it. I would suggest `national_infected_age_groups` to keep it consistent.

2020-11-16 10:42 UTC, VWSCoronaDashboard8 commented on schema/national/infected_age_groups.json
> +    "age_groups": {
Yes, we are not free to choose top-level properties like this. Everything uses values and/or last_value. With the exception being the difference keys.

2020-11-16 10:42 UTC, VWSCoronaDashboard8 commented on schema/national/infected_age_groups.json
>      "item": {
In the newer schemas this definition is called "value".  Don't forget to change `"$ref": "#/definitions/item"` then above.

2020-11-16 10:42 UTC, VWSCoronaDashboard8 commented on schema/national/infected_age_groups.json
> +      "title": "infected_age_group",
To make this unique and keep it consistent with newer schemas I suggest `national_infected_age_groups_value`

2020-11-16 10:42 UTC, VWSCoronaDashboard8 commented on schema/national/infected_age_groups.json
> +        "national_percentage",
This name is a little vague. Mabe `national_age_group_percentage` or `national_total_percentage`?

2020-11-17 13:26 UTC, VWSCoronaDashboard1 approved these changes

2020-11-17 13:44 UTC, VWSCoronaDashboard8 requested changes

2020-11-17 13:44 UTC, VWSCoronaDashboard8 commented on schema/national/infected_age_groups.json
> +        "national_age_group_percentage": {
I don't see a reason to prefix properties like this. We do not do that anywhere else. Properties are already scoped in their respective data context. This doesn't help to avoid naming collisions, it just makes the property name longer.

2020-11-17 13:44 UTC, VWSCoronaDashboard8 commented on schema/national/infected_age_groups.json
> +        "national_age_group_percentage",
See comment below.

2020-11-17 13:44 UTC, VWSCoronaDashboard8 commented on src/types/data.d.ts
> +export interface InfectedAgeGroups {
Seems like you forgot to re-generate the types

2020-11-17 15:29 UTC, VWSCoronaDashboard8 approved these changes

2020-12-02 11:11 UTC, VWSCoronaDashboard8 commented on src/domain/infected-people/age-demographic/age-demographic.tsx
> +const Wrapper = styled.div(
I think Box also has position properties, so you can just reuse that.

2020-12-02 14:44 UTC, merged