Add maatregelen page to landelijk and regional
minvws/nl-covid19-data-dashboard pull request #928
Opened 2020-11-16 13:29 UTC by VWSCoronaDashboard1

## Summary

This adds the restrictions pages to the national and regional sections.
A new menu item is added to both national and regional sidebars that link to the respective pages.
During development, a few inconsistencies were found by design in the SVG icon files which were fixed but led to some changes in the sidebar and content headers to maintain the correct sizes.

## Motivation

Feature request

## Detailed design

The bulk of the logic to shape the data for the restrictions table is in the hook `useRestrictionsTable`. The result of this hook is passed on as a prop to the RestrictionsTable component.
Changes were made to the `ContentHeader` component to allow for the given designs.
The `TitleWithIcon` now has an extra prop for extra icon attributes so that, for example, a custom color can be passed in. 

## Drawbacks

n/a

## Alternatives

Perhaps, instead of passing in an Icon class and separate attributes, it would be cleaner to just pass in an Icon component instance with all of the custom props already configured on it.
So instead of this:
`
        Icon={Ziekenhuis}
        iconAttrs={{
          style: {
            transform: 'scale(1.5)',
          },
        }}
`
it would be more like this:
` Icon={<Ziekenhuis style={transform: 'scale(1.5)'}/>}`

## Unresolved questions

n/a

### Governance

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License
      https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
      and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

2020-11-16 13:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=928) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=928) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=928) it.</sub>

2020-11-16 15:46 UTC, VWSCoronaDashboard4 requested changes

2020-11-16 15:46 UTC, VWSCoronaDashboard4 commented on src/assets/restrictions/Verzorgingstehuis.svg
> +<svg width="32px" height="32px" viewBox="0 0 64 64">
A lot of these icons contain things that are not needed or not handy. Eg: comments, empty (background?) rectangles, width/height attributes on <svg> (don't work well with resizing when embedded in HTML).

We could add a task to the package to clean up icon svgs (nice one for the tech debt backlog)

2020-11-16 15:46 UTC, VWSCoronaDashboard4 commented on src/pages/landelijk/ziekenhuis-opnames.tsx
> +            transform: 'scale(1.5)',
Why is there need to apply this transform everywhere? Is there something wrong/different about the icons? Can this be fixed somewhere else, in the styling of this component?

It would be clearer and cleaner if we can avoid using these.

2020-11-16 15:46 UTC, VWSCoronaDashboard4 commented on src/locale/en.json
> +    "VR15": "Haaglanden",
This is not a URL.

2020-11-16 15:46 UTC, VWSCoronaDashboard4 commented on src/utils/useRestrictionsTable.ts
> +function createRows(
Can you add a few comments for these methods?

2020-11-16 15:46 UTC, VWSCoronaDashboard4 commented on src/pages/veiligheidsregio/[code]/maatregelen.tsx
> +        <Box borderRight={{ lg: '1px solid lightgrey' }} pr={[0, 2]}>
This is not re-using the lightGray variable as defined in the styled system variables.

2020-11-16 15:46 UTC, VWSCoronaDashboard4 commented on src/components/contentHeader/index.tsx
> +export function GenericContentHeader(props: ISmallContentHeaderProps) {
Instead of creating a styled system component next to an old component, you can create a styled system component in the `components-styled` folder with the same (or similar) name: `components-styled/content-header`. Then for the use new uses, just import that one. Then this file can be reverted.

2020-11-16 15:56 UTC, VWSCoronaDashboard1 commented on src/assets/restrictions/Verzorgingstehuis.svg
> +<svg width="32px" height="32px" viewBox="0 0 64 64">
svgo/webpack is installed, so the optimizer get rid of all the garbage in the files.

2020-11-16 16:17 UTC, VWSCoronaDashboard1 commented on src/locale/en.json
> +    "VR15": "Haaglanden",
fixed

2020-11-16 16:29 UTC, VWSCoronaDashboard1 commented on src/utils/useRestrictionsTable.ts
> +function createRows(
done

2020-11-16 16:31 UTC, VWSCoronaDashboard1 commented on src/pages/veiligheidsregio/[code]/maatregelen.tsx
> +        <Box borderRight={{ lg: '1px solid lightgrey' }} pr={[0, 2]}>
Yes, for some reason I couldn't get the separate border attributes to work responsively unless I stuck them in a combined attr like here.

2020-11-16 16:33 UTC, VWSCoronaDashboard1 commented on src/components/contentHeader/index.tsx
> +export function GenericContentHeader(props: ISmallContentHeaderProps) {
I'm not sure I understand what you mean. I split up the ContentHeader component into two smaller components because on the restrictions page I needed only to show part of the ContentHeader component.

2020-11-16 16:34 UTC, VWSCoronaDashboard1 commented on src/pages/landelijk/ziekenhuis-opnames.tsx
> +            transform: 'scale(1.5)',
The icons were cleaned up by one of the designers. Resulting in the icons not rendering in consistent sizes. I've been battling viewboxes and widths and heights for about a day, in the end this was the only way of getting everything to render in the same size.

2020-11-17 09:15 UTC, VWSCoronaDashboard4 commented on src/components/contentHeader/index.tsx
> +export function GenericContentHeader(props: ISmallContentHeaderProps) {
This is now a mixed component, while for the styled system components there is a separate folder.

If we implement a new component in the styled system folder, we can leave the old one untouched.

2020-11-17 09:20 UTC, VWSCoronaDashboard8 requested changes

2020-11-17 09:20 UTC, VWSCoronaDashboard8 commented on src/scss/layout.scss
> +  .restrictions {
Do we really need to add global CSS classes for newly built features? I suspect you can place this in a styled component.

2020-11-17 09:20 UTC, VWSCoronaDashboard8 commented on src/types/data.d.ts
> +  escalation_level: 0 | 1 | 2 | 3 | 4 | 41 | 401 | 402;
Probably too late to change now, but strings would have been a better choice I think if we're going to use sub-levels. So we can write "4a" "4b" etc

2020-11-17 09:20 UTC, VWSCoronaDashboard8 commented on src/utils/useEscalationColor.ts
> +export function useEscalationColor(level: number | undefined) {
```suggestion
export function useEscalationColor(level?: number) {
```

2020-11-17 09:20 UTC, VWSCoronaDashboard8 commented on src/utils/useEscalationColor.ts
> +    if (level === undefined) {
Might be worth doing an assert instead to fail hard. I think you might want to break the app if the data is not compatible with the escalation levels you can handle in the code.

2020-11-17 09:20 UTC, VWSCoronaDashboard8 commented on src/utils/useRestrictionsTable.ts
> +import { useMemo } from 'react';
IMO utils are generic simple functions that are used commonly in different features. This is very specific to the restrictions feature, so there's nothing utilitarian about it. Do we already have that domain folder? I would suggest to move it there.

2020-11-17 09:20 UTC, VWSCoronaDashboard8 commented on src/utils/useRestrictionsTable.ts
> +    .sort((left, right) => rowOrder.indexOf(left) - rowOrder.indexOf(right));
This code is a bit cryptic. Creating a unique array with the filter especially.

It should be possible to greatly simplify this code by combining it with the map logic below, using a single reduce function. But it's up to you if want to take this challenge ;)

2020-11-17 09:25 UTC, VWSCoronaDashboard1 commented on src/types/data.d.ts
> +  escalation_level: 0 | 1 | 2 | 3 | 4 | 41 | 401 | 402;
not my choice, this has been a decision made somewhere by someone in the data analysis process

2020-11-17 09:55 UTC, VWSCoronaDashboard1 commented on src/utils/useRestrictionsTable.ts
> +    .sort((left, right) => rowOrder.indexOf(left) - rowOrder.indexOf(right));
I've created named functions, I think it's pretty straightforward now what is happening. Have a look.

2020-11-17 10:25 UTC, VWSCoronaDashboard10 commented on src/pages/veiligheidsregio/[code]/maatregelen.tsx
> +        <Box borderRight={{ lg: '1px solid lightgrey' }} pr={[0, 2]}>
But then still that color won't match the theme's `lightGray`

2020-11-17 10:30 UTC, VWSCoronaDashboard8 commented on src/types/data.d.ts
> +  escalation_level: 0 | 1 | 2 | 3 | 4 | 41 | 401 | 402;
But we aren't always a slave to their internal design choices I think :) If we define a schema for it won't they have to map their values to it?

2020-11-17 10:36 UTC, VWSCoronaDashboard1 commented on src/pages/veiligheidsregio/[code]/maatregelen.tsx
> +        <Box borderRight={{ lg: '1px solid lightgrey' }} pr={[0, 2]}>
haha, yes, fair point, I'll change it

2020-11-17 10:40 UTC, VWSCoronaDashboard8 commented on src/utils/useRestrictionsTable.ts
> +    .sort((left, right) => rowOrder.indexOf(left) - rowOrder.indexOf(right));
To be honest I prefer the first version since this adds a lot more lines of code. I meant to suggest that a reduce could simplify and shrink the code.  But this is nitpicking so I'm fine if you leave it like that 👍

2020-11-17 11:17 UTC, VWSCoronaDashboard10 commented on src/pages/landelijk/maatregelen.tsx
> +          data={restrictionsTable}
Why didn't you pass `data.restrictions` to this component and run the `useRestrictionsX`-hooks in there?

2020-11-17 11:17 UTC, VWSCoronaDashboard10 commented on src/utils/useRestrictionLevel.ts
> +    }, 0);
nitpick; Sometimes a reduce is a bit overkill:
```tsx
const top = Math.max(
 ...values.map((item) => codes.indexOf(item.escalation_level))
)
```

2020-11-17 11:54 UTC, VWSCoronaDashboard8 commented on src/components/contentHeader/index.tsx
> +      {!children && <Box mb={4} />}
I don't see a problem with this if contentHeader is providing the logic for the layout it makes sense that margins are set in this context. I only see problems with components settings margins themselves without knowing for sure how and where they are used.

Could you elaborate on this @VWSCoronaDashboard10 ?

2020-11-17 11:58 UTC, VWSCoronaDashboard8 commented on src/components/contentHeader/index.tsx
> +      {!children && <Box mb={4} />}
Yeah I see why it's a bit dodgy. If the header needs an inside margin always it should not depend on whether it is rendering children / metadata.

2020-11-17 12:12 UTC, VWSCoronaDashboard10 commented on src/components/contentHeader/index.tsx
> +      {!children && <Box mb={4} />}
Applying a padding would be better, simply add a bottom margin on the last component might result in collapsing margins with sibling components which in turn can result in unexpected and hard to fix layout quirks.

2020-11-17 12:15 UTC, VWSCoronaDashboard10 commented on src/components/restrictions/hooks/useRestrictionsTable.ts
> +}
Haha, now I see [an older comment](https://github.com/minvws/nl-covid19-data-dashboard/pull/928#discussion_r524998562) of @VWSCoronaDashboard8 which resulted in this verbose function 🤷  I guess its a nitpick thing so do with it whatever feels best :-)

2020-11-23 14:10 UTC, VWSCoronaDashboard8 requested changes
Looks to me that regional/sewer_per_installation got removed by accident.

2020-11-23 14:10 UTC, VWSCoronaDashboard8 commented on schema/regional/__index.json
> -    "sewer_per_installation",
Sewer per installation got tossed out? Did you also remove that json file then or is this a mistake?

2020-11-23 14:10 UTC, VWSCoronaDashboard8 commented on src/domain/behavior/behavior-metric.tsx
> +  if (!data?.last_value) {
What's the use-case for not having a last_value? Can it happen according to the data source?

2020-12-14 13:34 UTC, VWSCoronaDashboard8 commented on src/utils/useRestrictionLevel.ts
> +export function useEscalationLevel(
The file is called useRestrictionLevel.

The filename should also be kebab-cased.

2020-12-14 13:35 UTC, VWSCoronaDashboard8 commented on src/components/restrictions/restrictionsTable.tsx
>  import { Fragment } from 'react';
filename ☝️

2020-12-14 13:35 UTC, VWSCoronaDashboard8 commented on src/components/restrictions/hooks/useRestrictionsTable.ts
>   * is rendered in the table.
filename ☝️

2020-12-14 22:45 UTC, VWSCoronaDashboard8 approved these changes

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/static-props/data-sorting.ts
> +    (propertyName) => propertyName !== 'restrictions'
do we need to add a comment on why we filter `restrictions` out?

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/scss/layout.scss
> +  .restrictions {
this ☝️

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/pages/veiligheidsregio/[code]/maatregelen.tsx
> +    escalationLevel > 4 ? 4 : (escalationLevel as 1 | 2 | 3 | 4);
it feels like when `escalationLevel > 4 ` happens there should be something wrong in the delivered data no?

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/pages/landelijk/maatregelen.tsx
> +          data={restrictionsTable}
I still believe it makes sense to call the `useRestrictionsTable` hook from within the RestrictionsTable component. These two are tightly coupled and the data is not used outside of that table.

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/components-styled/escalation-level.tsx
> +      <Text as="span" marginLeft="0 !important" marginRight=".5em !important">
Are the `!important` really necessary? It's code smell..

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/components-styled/content-header/index.tsx
> +  reference?: {
Maybe @VWSCoronaDashboard4 can shine his light on this too, but he corrected me previously that this reference prop should never be optional.

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/components-styled/base/box.tsx
> +  BackgroundImageProps &
It also doesn't look like the background props are used in this PR, so I suggest to remove them again from the box component.. (and for future reference: there's also the combination of all separate styles, called `backgroundProps`)

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/assets/restrictions/Vinkje.svg
> +<?xml version="1.0" encoding="utf-8"?>
filename lowercase

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/assets/restrictions/Winkelwagen.svg
> +<?xml version="1.0" encoding="utf-8"?>
filename lowercase

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/assets/restrictions/Verzorgingstehuis.svg
> +<?xml version="1.0" encoding="utf-8"?>
filename lowercase

2020-12-15 07:45 UTC, VWSCoronaDashboard10 commented on src/assets/restrictions/Rugzak.svg
> +<?xml version="1.0" encoding="utf-8"?>
filename lowercase, etc :-)

2020-12-15 08:26 UTC, VWSCoronaDashboard1 commented on src/types/data.d.ts
> +  escalation_level: 0 | 1 | 2 | 3 | 4 | 41 | 401 | 402;
Yes, but it's a little late for that now I'm afraid...

2020-12-15 08:38 UTC, VWSCoronaDashboard1 commented on schema/regional/__index.json
> -    "sewer_per_installation",
This is very probably a merge mistake, I'll take a look

2020-12-15 08:45 UTC, VWSCoronaDashboard1 commented on schema/regional/__index.json
> -    "sewer_per_installation",
I just checked my local file and "sewer_per_installation" is still in there. I think github is showing the changes a little wonky...

2020-12-15 08:53 UTC, VWSCoronaDashboard1 commented on src/pages/veiligheidsregio/[code]/maatregelen.tsx
> +    escalationLevel > 4 ? 4 : (escalationLevel as 1 | 2 | 3 | 4);
No, there'is the escalation level which can be 1,2,3,4,401,402 or 41, on that level the list of restrictions is based. Then there's the effective level which is a simpler one: 1,2,3,4, which is communicated to the user.

2020-12-15 09:08 UTC, VWSCoronaDashboard1 commented on src/pages/veiligheidsregio/[code]/maatregelen.tsx
> +    escalationLevel > 4 ? 4 : (escalationLevel as 1 | 2 | 3 | 4);
I've added a code comment that explains this

2020-12-15 09:52 UTC, VWSCoronaDashboard1 commented on src/utils/useEscalationColor.ts
> +    if (level === undefined) {
I've added another assert as well, in case a color could not be found for the given level

2020-12-15 15:12 UTC, merged