Styling adjustments for 1 KPI tile on a row
minvws/nl-covid19-data-dashboard pull request #929
Opened 2020-11-16 15:06 UTC by VWSCoronaDashboard4

## Summary

Adjust TwoKpiSection/Tile components to display 1 Tile with the new design.

## Detailed design

* Use Tiles on all leftover pages that were previously blocked.
* Apply new layout when 1 Tile is used in TwoKpiSection: full width, description with a max width of 1 column (400px).
* Fix padding issue with reproduction number tile along the way.
* Add (temporary) `dataWarning` attribute to the Tile so we can use the new design on the Ziekenhuis-tiles as well.

## Unresolved questions

* Should we rename _TwoKpiSection_ to something different, now that it is optimized for 1 or 2 Kpi Tiles?

2020-11-16 15:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=929) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=929) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=929) it.</sub>

2020-11-16 15:24 UTC, VWSCoronaDashboard1 approved these changes

2020-11-17 10:21 UTC, VWSCoronaDashboard10 approved these changes
Approved, only couple of questions.

2020-11-17 10:21 UTC, VWSCoronaDashboard10 commented on src/components-styled/kpi-tile.tsx
> +        <Box
Did you change this component on purpose? Looks like the Text component has some default styling applied (e.g. fontSize=2) which is now lost by going for a Box.

2020-11-17 10:25 UTC, VWSCoronaDashboard8 requested changes

2020-11-17 10:25 UTC, VWSCoronaDashboard8 commented on src/components-styled/kpi-tile.tsx
> +  dataWarning?: boolean /* TODO: remove this temporary attribute when it is not used anymore */;
This doesn't read like a boolean.
```suggestion
  showDataWarning?: boolean /* TODO: remove this temporary attribute when it is not used anymore */;
```

2020-11-17 10:25 UTC, VWSCoronaDashboard8 commented on src/components-styled/kpi-tile.tsx
> +          mt="3"
I think this should be a number? Maybe styled system casts strings to numbers internally, but still a number would be correct I think.

2020-11-17 10:25 UTC, VWSCoronaDashboard8 commented on src/components-styled/two-kpi-section.tsx
> +      {childrenArray[1] && (
I would prefer to use childrenCount here too, since that was extracted from the array and the intention is clearer then IMO

```suggestion
      {childrenCount == 2 && (
```

Might be worth creating a `hasTwo` boolean even, so you can use that in these two places.

2020-11-17 11:50 UTC, VWSCoronaDashboard8 approved these changes

2020-11-17 12:30 UTC, merged