Link to explanation from all metric pages
minvws/nl-covid19-data-dashboard pull request #962
Opened 2020-11-18 14:42 UTC by VWSCoronaDashboard4

## Summary

Adds links to explanation from all content headers.

## Detailed design

* Extend content header component and co with `reference`, that should contain a `href` and `text` for the link.
* The link will only be shown if the href and text are non-zero-length strings.
* Extend `Collapsable` component to have a link to the anchor, this link is only visible when the collapsable is openend.

2020-11-18 14:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=962) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=962) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=962) it.</sub>

2020-11-18 15:52 UTC, VWSCoronaDashboard10 approved these changes

2020-11-18 16:08 UTC, VWSCoronaDashboard8 commented on src/components/contentHeader/index.tsx
> +          {reference.text && reference.href && (
nit; I have a feeling that reference could enforce the existence of text and href together. Or are there reference texts that do not have a link associated with them?

2020-11-18 16:09 UTC, VWSCoronaDashboard8 commented on src/components/contentHeader/index.tsx
> +    text: string;
Looks like they are non-optional? Why the checks above then?

2020-11-18 16:10 UTC, VWSCoronaDashboard8 commented on src/components/contentHeader_sourcesHack/index.tsx
> +          {reference.text && reference.href && (
Same comment as before

2020-11-18 16:13 UTC, VWSCoronaDashboard8 requested changes

2020-11-18 16:13 UTC, VWSCoronaDashboard8 commented on src/components/contentHeader_weekRangeHack/index.tsx
> +          {reference.text && reference.href && (
etc

2020-11-18 16:13 UTC, VWSCoronaDashboard8 commented on src/locale/en.json
> +    },
OK, I'm guessing the checks are there because the strings can be empty. 

I don't think it's worth guarding for in code. I would vote to clean up the code and assume these things are filled correctly. If a string or link is missing it can be caught in QA

2020-11-18 16:15 UTC, VWSCoronaDashboard8 approved these changes
I'm approving it because the behavior of links is according to the description, but I don't think I agree on hiding the links if strings are empty

2020-11-19 08:44 UTC, VWSCoronaDashboard4 commented on src/components/contentHeader/index.tsx
> +          {reference.text && reference.href && (
This check is merely to avoid empty strings for these values.

2020-11-19 10:17 UTC, VWSCoronaDashboard1 approved these changes

2020-11-20 13:06 UTC, VWSCoronaDashboard8 approved these changes
💯

2020-11-20 14:17 UTC, merged