chore: Remove unused keys from homepage props
minvws/nl-covid19-data-dashboard pull request #965
Opened 2020-11-18 20:53 UTC by VWSCoronaDashboard

## Summary

To reduce payload of the homepages HTML file, we need to strip away all of the `values` except the `latest_values` from `NL.json`.

`NL.json` is a huge file and this saves an intense amount of bytes.

## Motivation

Shipping smaller websites leads to better performance and less battery usage. 

## Detailed design

I'm doing a naive but perfectly efficient loop over `NL.json` and remove the `values` key. Feel free to improve on this method directly when doing a pull review if you can think of a cleaner way to do this.

```ts
  const data = JSON.parse(fileContents);

  // Strip away unused data (values) from staticProps
  // keep last_values because we use them!
  for (const [key, value] of Object.entries(data)) {
    if (typeof value === 'object') {
      for (const [key2] of Object.entries(data[key])) {
        if (key2 === 'values') {
          delete data[key].values;
        }
      }
    }
  }
```

## Drawbacks

In the case of the homepage, I don't think there's a drawback. It adds a few lines of maintenance, but it's acceptable. As soon as these structured become difficult to maintain we should think twice about how we solve this.

## Alternatives

### Using react-query and removing getStaticProps
Not a viable alternative. We purposefully ship static pages for fast loading speeds, good SEO and accessibility reasons. We don't want to ship a blank page while the JS is still loading.

## Unresolved questions

No unresolved questions, but it would be good to think about which data sources have the biggest impact in the rest of the application and see how we can reduce file sizes some more.

### Governance

- [X] Documentation is added

2020-11-18 20:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=965) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/minvws/nl-covid19-data-dashboard?pullRequest=965) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/nl-covid19-data-dashboard?pullRequest=965) it.</sub>

2020-11-19 08:03 UTC, VWSCoronaDashboard4 commented on src/pages/index.tsx
> +  const data = JSON.parse(fileContents);
I like the approach, and it can be scaled/adapted to different pages as well.

`data` will, after this procedure, have a different type than `National`; do we want to have an adjusted type as well, to guarantee type safety in the dynamic part of the page?

2020-11-19 08:06 UTC, VWSCoronaDashboard1 requested changes

2020-11-19 08:06 UTC, VWSCoronaDashboard1 commented on src/pages/index.tsx
> +  }
While I obviously agree with the bundle size-reduction, this change does potentially introduce runtime errors since you're changing the data shape at runtime. That is why you had to remove the `as National` cast.
So, to keep this type-safe you would either have to create an interface based on National, but with all of the 'values' properties taken out, or, instead of removing the values key altogether, setting it to an empty array.

2020-11-19 08:12 UTC, VWSCoronaDashboard10 requested changes
I think we also need to define the data type without the `values`-properties, otherwise it could result in runtime errors not caught with the TS compiler.

2020-11-19 08:12 UTC, VWSCoronaDashboard10 commented on src/pages/index.tsx
> +    if (typeof value === 'object') {
```suggestion
    if (typeof value === 'object' && value !== null) {
```

2020-11-19 08:41 UTC, VWSCoronaDashboard commented on src/pages/index.tsx
> +  }
Aha! The first solution sounds like it's safest. I'll cook something up for this.

2020-11-19 08:41 UTC, VWSCoronaDashboard commented on src/pages/index.tsx
> +  const data = JSON.parse(fileContents);
Seems the new approach is to make a new type for this to ensure type safety.

2020-11-19 10:04 UTC, VWSCoronaDashboard8 approved these changes

2020-11-19 10:04 UTC, VWSCoronaDashboard8 commented on src/pages/index.tsx
> +  }
I prefer to use named variables that give you a sense of what you're dealing with. Key and value do not tell you much and key2 even less. Maybe something like this :
```suggestion
  for (const [metricName, metric] of Object.entries(data)) {
    if (typeof metric === 'object' && metric !== null) {
      for (const [metricProperty] of Object.entries(data[metricName])) {
        if (metricProperty === 'values') {
          delete data[metricName].values;
        }
      }
    }
  }
```

2020-11-19 11:22 UTC, VWSCoronaDashboard8 commented on src/pages/index.tsx
> +
Small tweaks to make it more correct

```suggestion
  for (const metric of Object.values(data)) {
    if (typeof metric === 'object' && metric !== null) {
      for (const [metricProperty, metricValue] of Object.entries(metric)) {
        if (metricProperty === 'values') {
          (metricValue as {
            values: Array<unknown>;
          }).values = [];
        }
      }
    }
  }

```

2020-11-19 12:28 UTC, VWSCoronaDashboard10 approved these changes

2020-11-19 16:08 UTC, merged